### ISSUE TITLE
'My Projects' view is not showing submissions made via 'My Submissions' page

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/dcp-ingest-central#101]
I tested updates to the Project view in ingest staging and everything looks as expected as indicated here in @aaclan-ebi 's test file:

https://docs.google.com/spreadsheets/d/1sf_PnPRufEPUeqkADhewJGJsYsb00CBwymKKPFB_VHI/edit#gid=2047502474

However, when a new submission is created in the "My Submissions" tab, it doesn't actually show up in the "My Projects" page even when validated/exporting. As we are moving in the direction of keeping only the 'My Projects' view to add and edit submissions, I am not sure how important it is to work on fixing this particular issue so long as we (wranglers) are aware of it.

@clairerye fyi please see above!

**Comment by clairerye** [comment]
Thanks for testing!

**Comment by clairerye** [comment]
So I may have misunderstood @ami-day so maybe you could show me on Monday? 
When I have created a submission for one of my projects, I can link to that submission from the 'my projects' tab by clicking on the 'view project' and then to the 'upload' tab and on the 'submission UUID'. Is this what you were meaning, or something else?

**Comment by ami-day** [comment]
This is no longer relevant.
