### ISSUE TITLE
Register marine samples

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#1014]
For MICROBE, we want to register the marine samples generated for Roscoff. For that:

- [x] Review the [metadata spreadsheet](https://docs.google.com/spreadsheets/d/1I1cEyVNqCjwZwPKNTdvvipLh2_ogkigr/edit?usp=drive_link&ouid=105945877951113459382&rtpof=true&sd=true)
- [x] Curate metadata according to [GSC MIxS water](https://www.ebi.ac.uk/ena/browser/view/ERC000024)
- [ ] Submit to BioSamples and set it to private
- [x] Send to Charles for review (If Charles does not answer, try another Roscoff team member - He may have left the team)
- [ ] Make public!

**Comment by ESapenaVentura** [comment]
Cryopreservant translations:
- GB: Glycine betaine
- SUC: Sucrose
- MET: Metformin
- TRI: Tricine

We should probably ask for concentrations - Just having the name of the compound feels like we're missing metadata

**Comment by ESapenaVentura** [comment]
I've got a spreadsheet ready - however, it's a bit confusing in terms of samples and how they were cryopreserved. Currently preparing an email to send charles

**Comment by Jeena-Rajan** [comment]
Waiting on Charles to review the spreadsheet before submission to BioSamples
