### ISSUE TITLE
Project fields not showing in staging UI

### ISSUE THREAD

**Issue by arschat** [ebi-ait/dcp-ingest-central#1019]
### Describe the bug
In [ingest staging](https://staging.contribute.data.humancellatlas.org/projects/all), in some projects, ingest is not showing the tabs in the Project section (Project Information, Contributors, Publications, Funders, Admin Area), but only `Project title` and `Project description`. This has been observed in projects that have a project_schema <= 17.1.1

This happens in **staging** ingest, and not in **prod**. Could not reproduce in **dev** since I don't have access to old projects with < 17.1.1 project schema.

### To Reproduce
Steps to reproduce the behaviour:
1. Go to [https://staging.contribute.data.humancellatlas.org/projects/all](https://staging.contribute.data.humancellatlas.org/projects/all)
2. Click on any project (i.e. [project](https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=217c28b7-bf26-4e11-a46e-7daaa52160aa))
3. See project tabs, are missing
4. Observe the project schema using the [api findbyUUID call](https://api.ingest.staging.archive.data.humancellatlas.org/projects/search/findByUuid?uuid=217c28b7-bf26-4e11-a46e-7daaa52160aa)
5. Projects with the most recent project_schema (i.e. [api](https://api.ingest.staging.archive.data.humancellatlas.org/projects/search/findByUuid?uuid=b41fb844-4630-47c4-b921-6a22ec53e282) [project](https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=b41fb844-4630-47c4-b921-6a22ec53e282)) do not have this behaviour. 

### Expected behaviour 
All projects on ingest right now are open access, therefore we would like have access to all the other fields from the UI as well.

### Screenshots / Logs
[Project](https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=217c28b7-bf26-4e11-a46e-7daaa52160aa) with Bug and project_schema < 17.1.1:
<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWNXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac0641c87f9688ca2b7ec46698a1784bf22891e0/image.png" alt="image.png" />

[Project](https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=b41fb844-4630-47c4-b921-6a22ec53e282) without the Bug and project_schema = 19.0.0:
<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWtXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a525afab9f9dab2aa7409cfdb55b47351c333e04/image.png" alt="image.png" />

### Environment
- [ ] prod
- [X] staging
- [ ] dev

### Browser
- [X] Chrome
- [ ] Safari
- [ ] IE
- [ ] Other (please specify)

**Comment by arschat** [comment]
[Here](https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=67e05285-418d-4e14-a172-6de3864b6b1f) is a project with schema version 18.0.0 ([api](https://api.ingest.staging.archive.data.humancellatlas.org/projects/search/findByUuid?uuid=67e05285-418d-4e14-a172-6de3864b6b1f)) that also has this bug.

[Project schema v18](https://schema.humancellatlas.org/type/project/18.0.0/project) introduced the `data_use_restriction` field
[Project schema v19](https://schema.humancellatlas.org/type/project/19.0.0/project) introduced the `duos_id` field with the conditional requirement

**Comment by KociOrges** [comment]
A new version of the ingest-ui has been deployed to the `staging` area to address the issue mentioned above. Have now refactored the code to handle missing schema fields and included relevant test cases.

**Comment by idazucchi** [comment]
@arschat @KociOrges can we close this ticket? it sounds like this bug has been resolved with the update

**Comment by KociOrges** [comment]
This is resolved, in my opinion. @arschat can also confirm :)

**Comment by arschat** [comment]
yes, it's resolved!
