### ISSUE TITLE
Testing user story #75

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#102]
related to https://github.com/ebi-ait/dcp-ingest-central/issues/75#issuecomment-735724883

### First submission

Tried to upload a super broken spreadsheet. Didn’t work. It pointed to errors, although they are pretty well pointed out.

Trying with another sheet with the error “UnexpectedUuidEntity” solved.

Fatal errors make the spreadsheet **unloadable** and you have to look at the json response. In this case, it was a boolean error (NOO instead of yes/no, which I guess ingest can’t convert), and integer conversion errors (96O6 instead of 9606).

Fixing those ones for the next iteration to see if it loads the spreadsheet.

Adding a non-existing link also breaks the import with the error:
```
A link from a biomaterial with id specimen_ID_1 to a biomaterial with id, "not_a_real_donor_id", is not found in the spreadsheet.
```
Only showing that 1 error. Going to fix it and then see if it can load the spreadsheet

### Last submission

https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=5b0f1d6d-6d45-4c18-9273-e023b5f93d30

Now it’s showing the errors as intended. Immediately, the first thing I noticed is that project and submission errors are in a different format, which is not ideal. Screenshot attached.

![Error_v4.png](https://images.zenhubusercontent.com/5ca5f897027e3e7234ac788c/d18a9f3f-bd65-421e-8ba0-5017b82d2ecb)

Going type by type:

**Biomaterials:**

Clicked to show biomaterials. Shows only the donor, even though the specimen also should have biomaterial errors.

For now, looking at the metadata errors:

![Biomaterials_v4.png](https://images.zenhubusercontent.com/5ca5f897027e3e7234ac788c/787e0eae-5c1b-4a5a-976c-35bcc84890ff)

Can we get the user friendly name in the errors?

Also, about the linking, it shows unlinked, but there is no intuitive way to know how to fix the linking. My first thought would be to go to edit the biomaterial and link it there, but we have to go to processes.

Why is body mass index a boolean?

About the biomaterial_core error: Can we state which additional properties are they trying to add?

Other than that, the other errors are easy to spot.

**File errors:**

Metadata errors are easy to spot, kind of the same comments as the previous one.

I like the metadata errors being different from the “file missing” and stating both, but there is a bug in the file metadata/data validation: When the metadata is invalid, it won’t list the missing data file. In the specific example, I would have expected “1 metadata error, 2 files missing” but it’s stating only 1 file missing.

I uploaded an invalid file for the file with the invalid metadata. No changes. 

Corrected the metadata in the UI and it is validating now. After correcting the metadata and uploading an incorrect file, no error shows up, but the file is invalid. It just goes to invalid without specifying “invalid data file”. I think this is another bug!

So far I have come up with this. Happy to test further if needed?

**Comment by gabsie** [comment]
Hi, Enrique!!!
These look awesome.
cc @aaclan-ebi and @jacobwindsor so that we can maybe break these down and see what to do about them.
I think I need to think of more options of visualising errors.

Gabs
