### ISSUE TITLE
api calls from ui should be authenticated

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#1020]
As part of the managed access implementation (see #967) some of the calls to ingest api now require authentication.
Some of this requirement has been fulfilled by changing the `SECURED_ENDPOINTS` list of regular expressions in the `environment*.ts` files. This list contains the patterns of the api calls for which the `Authorization` header will be added.

The related fix was successfully tested with a locally running frontend using the dev ingest api. Despite that, when pushed to the dev environment, there are still `401 UNAUTHORIZED` responses for the `/submissionEnvelopes/<id>/relatedProjects` resource.

Checking whether a url requires authorisation is done in [OidcInterceptor.intercept()](https://github.com/ebi-ait/ingest-ui/blob/feb8fecdbe519d1b94e78256d126f0b9f516347a/src/app/aai/oidc-interceptor.ts#L36).

The problem only happens to some of the `/relatedProjects` calls, so it could be related to some api requests that are not intercepted by `OidcInterceptor`. Not sure how it would be possible.

**Comment by KociOrges** [comment]
Resolved `401 UNAUTHORIZED` issue for `SECURED_ENDPOINTS` by updating Helm YAML files for consistency in the deployed environment. Updated README documentation to detail the setup and changes. Changes for Ingest-UI and `ingest-kube-deployment` are currently on the `dev` branches.
