### ISSUE TITLE
MS6: Write milestones document about validation tools

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#1023]
**Description of the issue**

As part of the reporting for MICROBE WP3, we need to write a milestone progress report document for MS6: `Validation tools for assessing compliance with standards for microbiome biobanking implemented`.

We had a brief chat on 13th June where we divided and briefly discussed the sections on [this document](https://docs.google.com/document/d/1XJi16AyYfrjrsPw56qi7nrbEO5OJuWQ-VjMR9cKhTZ0/edit)

- Check up deadline: 27th June 2022 -> moved to 2nd July
- Hard deadline: EO July (Prob Last week)

**Comment by Wkt8** [comment]
Meeting on 27th June
