### ISSUE TITLE
rotate GCP keys

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#1030]
This is relevant for hca components such as the exporter.

The GCP identities that will receive new keys are:

- `ebi-staging-writer@mystical-slate-284720.iam.gserviceaccount.com`
- `lattice-prod-writer@mystical-slate-284720.iam.gserviceaccount.com`

Current keys will be disabled on Wednesday 31 July.
See:
- [slack message](https://embl-ebi-ait.slack.com/archives/C01360XN04S/p1721661949319509) from Barbara Hill
- [sop](sop in onboarding: https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/update-exporter-gcp-creds.html)
- similar ticket: ebi-ait/hca-ebi-dev-team#478

this happens every 90 days as part of Broad's information security policy.

**Comment by amnonkhen** [comment]
Key in [ebi_mystical-slate-284720-b286547028c1.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0Q2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--494d665036575683392b20cf2dfc4aa17737451d/ebi_mystical-slate-284720-b286547028c1.zip)
Talk to me for the password.

**Comment by ESapenaVentura** [comment]
New keys have been deployed and an integration test (https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/jobs/1755839) has been run successfully
