### ISSUE TITLE
file metadata/data validation

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#105]
When the metadata is invalid, it won’t list the missing data file. In the specific example, I would have expected “1 metadata error, 2 files missing” but it’s stating only 1 file missing.

I uploaded an invalid file for the file with the invalid metadata. No changes.

Corrected the metadata in the UI and it is validating now. After correcting the metadata and uploading an incorrect file, no error shows up, but the file is invalid. It just goes to invalid without specifying “invalid data file”. I think this is another bug!

As described more fully in the testing ticket #102 or check with @ESapenaVentura who did the testing

**Comment by clairerye** [comment]
@aaclan-ebi or @jacobwindsor did we fix this? I meant to ask today and forgot!

**Comment by aaclan-ebi** [comment]
Yes, this is already fixed and already promoted to prod last 4th Jan prod [release](https://github.com/ebi-ait/ingest-kube-deployment/blob/master/production/changelog.md#04-january-2021).

<img width="1155" alt="Screenshot 2021-01-14 at 10 39 07" src="https://user-images.githubusercontent.com/31281398/104580138-c490d600-5654-11eb-81ff-f241bed3712f.png">
