### ISSUE TITLE
Suggested designs for Search - within a project

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#106]
hi everyone
I at least have found a place for this search, within project view.

I still have to work on the results maybe, but let me know what you think about this idea on searching

I don't want it to be too much in the way. Search - though it might beimportant in some occasions, has secondary priority to everything else a user or a wrangler would be doing.!

![9.1 Project Search - keywords position.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/c23e8562-e638-4ad0-af1f-74c040d991cc)
[9.1 Project Search - keywords clicked.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/ba5a8a43-f2bc-4796-9b32-b4e7590d2e4e)

Comments are welcome, and I will try to place some ideas for results!
I have uploaded these here as well: https://chanzuckerberg.invisionapp.com/share/4RZLFPTXDA2 

Gabs

**Comment by gabsie** [comment]
This one is just a suggestion from somewhere else, but I think I need more information from Enrique here to understand what is better for results..

Gabs![9.1 Project Search - keywords suggestions.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/f0e093c8-5e7c-47a1-8256-098c794df89c)

**Comment by amnonkhen** [comment]
closing, not needed now.
