### ISSUE TITLE
[Core] Restrict the PATCH updates to the metadata document 

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#109]
Any updates to document:
1. should set it back to Draft
2. should update contentLastModified field - this is a new field which will track the timestamp when the content was last modified
3. should re-trigger validation

**Comment by aaclan-ebi** [comment]
The following fields are allowed in PATCH endpoints:

project
- content
- releaseDate
- primaryWrangler
- accessionDate
- technology
- dataAccess
- identifyingOrganisms
- validationErrors

biomaterial
- content
- validationErrors

file
- content
- validationErrors
- validationJob

protocol
- content
- validationErrors

process
- content
- validationErrors


The validator is using the same patch endpoint for setting the validationJob and validationErrors, would need changes in the validator before we restrict that field. Project contains additional fields on top of the metadata. Not sure if we need to restrict these fields as well.

**Comment by clairerye** [comment]
@aaclan-ebi is this in prod now?

**Comment by aaclan-ebi** [comment]
Yup i believe this one's in prod now.

**Comment by aaclan-ebi** [comment]
It seems that there are issues with the newly added fields:

1. contentLastModified gets updated for every GET requests.
@mshadbolt reported this issue on [slack](https://embl-ebi-ait.slack.com/archives/C016R78CDV1/p1612548033159400) 

Example metadata from @jacobwindsor 
https://api.ingest.dev.archive.data.humancellatlas.org/biomaterials/5cd588a9d96dad00085634a5
https://api.ingest.dev.archive.data.humancellatlas.org/biomaterials/601bd9d80b033d68b6a87720

It seems that this issue is happening for those documents whose contentLastModified is inexistent.

2. _For the second biomaterial, the update date is PRIOR to the firstdcpversion_
@ESapenaVentura noticed this.

```
"firstDcpVersion": "2021-02-04T11:26:16.710Z",
"dcpVersion": "2021-02-04T11:26:16.710Z",
"contentLastModified": "2021-02-04T11:26:16.700Z"
```


For issue 1, we need to do migration for the newly added fields in prod:
1. contentLastModified - if null, should get the dcpVersion 
2. firstDcpVersion - if null, should get the dcpVersion

For issue 2, we need to correct the way the dcpVersion is being set. It should always source its value from the contentLastModified.
