### ISSUE TITLE
Share a user friendly summary of the project with a contributor so they can easily check metadata is correct

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/dcp-ingest-central#11]
Summary of entity types donors, cell suspensions, files.
Same info as ticket #6 but doesn't need linking info. 
Needs additional info about how to use this and in a format that can be shared with a contributor

This should wait until the wrangler need is fulfilled here first.

**Comment by clairerye** [comment]
Closing as we are not going to get to this now or within this milestone of work
