### ISSUE TITLE
[Core + State tracker] Implement changes to state transition

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#111]
Support the flow from Exported -> Draft-> Valid -> Exported, track different export entities

When a metadata is updated, the submission will go back to draft
- ~Core to send metadata content updates to state tracker: https://github.com/ebi-ait/ingest-core/compare/master...ebi-ait:task/resubmit ~ not needed
- Update State tracker configuration to support Exported -> Draft transition : https://github.com/ebi-ait/ingest-state-tracking/pull/3/files

**Comment by clairerye** [comment]
@aaclan-ebi This is in prod, right?

**Comment by aaclan-ebi** [comment]
This is in staging and part of the updates user story.

**Comment by aaclan-ebi** [comment]
We did initially promoted this in prod but we reverted it. The changes now are still in staging and being tested as part of the updates user story.
