### ISSUE TITLE
Same project shows up multiple times in 'All Projects' view

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/dcp-ingest-central#112]
**Issue**
When in the 'All projects' view, a project with the same uuid shows up multiple times when it should show up once.

**How to recreate**
1. Login to contribute.data.humancellatlas.org
2. go to 'all projects' page
3. search 'kidneysingle'
4. Note that all these projects link to the same project uuid page `abe1a013-af7a-45ed-8c26-f3793c24a1f4`

![Screenshot 2020-12-23 at 09.39.25.png](https://images.zenhubusercontent.com/5d078c35851df4191d4ecc7a/24f0b3b7-5a94-4490-b5ce-2e004691a0f0)

**Expected behaviour**
Only one row should be displayed per project uuid.

**Comment by mshadbolt** [comment]
this is also an issue with the project `Reprogrammed_Dendritic_Cells` -  `116965f3-f094-4769-9d28-ae675c1b569c`
https://contribute.data.humancellatlas.org/projects/detail?uuid=116965f3-f094-4769-9d28-ae675c1b569c

I am guessing it has something to do with projects that have been updated and/or have multiple submission envelopes

**Comment by amnonkhen** [comment]
The mentioned projects appear a single time in the list. I did not notice other repetitions.
