### ISSUE TITLE
Improve reliability of the graph validator

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#113]
## User Story

As a wrangler I want a reliable instance of the graph validator that I can use every time I need to check the experimental graph of a dataset I am wrangling.

The graph validator is currently run locally on wranglers' machines. There seems to be a lot of reliability issues, differences in operating systems and other examples where it stops working, blocking progress and causing much frustration.

There has been a suggestion that there could be a central version deployed on the EC2 and this would be accessible by all the wranglers (including UCSC?) and the hydration could happen directly by pulling from mongo DB. 

- [x] Readme updated
- [x] Testing of the graph validator
- [x] SOP updated in wrangler docs

**Comment by ami-day** [comment]
We don't have an SOP for the graph validator, but the graph validator has it's own repo and the README file in this repo is very clear, so I don't think we need to duplicate the instructions in an SOP.

**Comment by clairerye** [comment]
No further issues reported since March 9th, so counting this as successful
