### ISSUE TITLE
Allow wranglers to export projects from HCA ingest prod. immediately after completing them

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/dcp-ingest-central#121]
At the moment, we cannot export projects once complete in HCA ingest prod. We don't yet know when and how often we will export projects in bulk to pipelines. We want to be able to export projects immediately and have them wait in the 'background' so that when ready, the pipelines team can access them for processing without our input. 1 of the advantages is that there will be no confusion and no need to go through all the projects determining if they have been exported already or not when the next data release is planned.

**Comment by amnonkhen** [comment]
I think this is covered by the data releases and import form.
