### ISSUE TITLE
slowness of GEO-> HCA script

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#124]
The GEO to HCA script has become slow when converting large datasets (anything over 100 samples). This needs to be investigated and optimised so that it can convert larger datasets.

**Comment by ami-day** [comment]
The running time is now under 8 mins when the large dataset with >2000 samples & >5500 file names is requested :) Standardly though it runs in <20 secs for most datasets (stats below). There are a couple more updates I want to make (add some more technology specifics) but then I'll create a pull request. It would be great @yusra-haider if you could review to see if further improvements might be good. We could meet sometime Monday if you're free!

`

GEO   accession | number of samples | number of experiments | number of fastq files | number of   multiprocessing threads | time taken | manual intervention by   user?
-- | -- | -- | -- | -- | -- | --
GSE140231 | 12 | 12 | 56 | 1 | 0m14.464s |  
GSE140231 | 12 | 12 | 56 | 5 | 0m14.266s |  
GSE101207 | 13 | 13 | 22 | 1 | 0m13.189s |  
GSE101207 | 13 | 13 | 22 | 5 | 0m13.129s |  
GSE150132 | 5 | 5 | files   not in ENA | 1 | 0m19.098s | yes   (script asks the user to indicate if a publication title is correct or not)
GSE150132 | 5 | 5 | files not in ENA | 5 | 0m17.204s | yes (script asks the user to indicate if a   publication title is correct or not)
GSE116222 | 9 | 9 | files   not in ENA | 1 | 0m14.394s |  
GSE116222 | 9 | 9 | files not in ENA | 5 | 0m13.960s |  
GSE96769 | 2779 | 2779 | 5557 | 1 | 8m15.466s |  
GSE96769 | 2779 | 2779 | 5557 | 5 | 7m35.361s |  

`

**Comment by ami-day** [comment]
Linking to new tickets for improvements:
https://github.com/ebi-ait/dcp-ingest-central/issues/133

**Comment by ami-day** [comment]
Everything is ready now for review @yusra-haider, I'll do a pull request to the improve_speed branch now.

**Comment by ami-day** [comment]
I have refactored the script based on Yusra's review/discussion and merged the pull request for that branch so the latest version is now ready for others to use. I created a new refactoring branch today to improve the readability and maintainability of the code, including splitting into separate scripts and documenting functions.

**Comment by ami-day** [comment]
Finished refactoring so moving to done.
