### ISSUE TITLE
HCA-> SCEA script not working

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#125]
When this was last attempted to be used it didn't work at all. There is also some confusion about how suited it is for SS2 datasets

**Comment by ami-day** [comment]
The HCA -> SCEA script is working for Yusra. It is not working for me locally, so I will try to get mine version working.

We will also update the script with new functions and link the tickets for these updates to this ticket.

**Comment by ami-day** [comment]
It is working now once I re-cloned it so I am closing this ticket.
