### ISSUE TITLE
Layout of About page

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#126]
**User story:**
As a single cell researcher interested in HCA relevant data, I want to understand the source and selection of the projects on this page, so that I know how they differ to other similar resources or if there's an overlap.

**Comment by gabsie** [comment]
Hi, @jacobwindsor and @mshadbolt 

![Project-catalogue-Publication separate.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/e16eaea6-2919-4ef1-b107-3d70c89e02fc)

Attaching here one idea to show:
1. the top nav pages (for which we will need layouts as well)
2. Logos  (which will need some confirmation/thoughts from stakeholders)
3. How we can filter by data location (e.g. HCA DCP)

I will also upload two more ideas.. 

Gabs

**Comment by mshadbolt** [comment]
Wanted to note down currently where publications have come from:
1. Anything in the official HCA publications list https://www.humancellatlas.org/publications/
2. Anything that has been wrangled, awaiting export but project info can be public
3. Anything that has been wrangled and is currently in the HCA Portal/Browser (DCP)
4. Any primary data publications that were used in any of the integrative analysis papers in HCA publications
5. Any datasets identified as suitable by wranglers and in the backlog of datasets to wrangle, potential sources being:
- Valentine single cell database - https://www.nxn.se/single-cell-studies
- GEO
- ArrayExpress
- Single Cell Expression Atlas
- incidental discovery of a paper with suitable data by any other means
6. Any datasets with a funding connection to the HCA
- WSSS
- MRC Developmental Cell Atlas
- Organoid H2020 project
- CZI seed networks
- CZI biological networks
- covidcellatlas papers https://www.covid19cellatlas.org/

**Comment by jacobwindsor** [comment]
@gabsie just confirming that there's nothing I can work on right now right? 

Also, about the pagination, there's none at the moment. Would you rather have some rather than one long table?

**Comment by gabsie** [comment]
@jacobwindsor 

I wonder if today we can at least, from this screenshot, work on:
1. getting the right logo at the top, and show at least sort of a top navigation which shows About and Contact us there (even if they don't go anywhere for now)
2. fix the title and the sentence below
3. get the page footer from here: https://contribute.data.humancellatlas.org/
4. introduce pagination like the one here: https://www.covid19dataportal.org/sequences?db=embl-covid19 
5. let's get the font size down to the one in tables in the covid portal.. which I think is 16
6. the colour for links to also be from the https://contribute.data.humancellatlas.org/ 

I will think what else? and let me know if questions!!!
Gabs

**Comment by mshadbolt** [comment]
I think I am a bit confused, wouldn't adding the footer from the ingest ui not be compliant with what the footer needs to look like for ebi resources?

I am also not sure on pagination...

**Comment by jacobwindsor** [comment]
I'm also not sure it's a good idea to link to pages that don't exist. It's looking like this will go into production very soon and I can't see those three pages content getting made this week

**Comment by gabsie** [comment]
@mshadbolt  - maybe we can catch up with Tony on the footer. Are we presenting this Catalogue as within the EMBL-EBI resources? In which case it will have to have the usual EBI footer..?

@jacobwindsor - OK on the top pages... but maybe we need to create tickets for content on the About page.. @mshadbolt

**Comment by mshadbolt** [comment]
@gabsie i assume so, given it is at an ebi address...

**Comment by lauraclarke** [comment]
@gabsie as this is being presented under ebi.ac.uk it has to have the EBI footer and follow EBI style/visual framework

**Comment by gabsie** [comment]
@lauraclarke @tburdett 
So an important question here: 

1. is this Project Catalogue being presented as part of EMBL-EBI? (where you imagine the EMBL-EBI top nav and footer, like on Arrayexpress and eqTL catalogue: https://www.ebi.ac.uk/arrayexpress/browse.html )
2. is this Project Catalogue being presented as part of EMBL-EBI, but more remote and still more linked to the HCA DCP, in which case the GWAS catalogue is a good example, where it still features the EMBL-EBI logo, but has its own kind of pages and a different footer.. 

I will get in touch with VF to see what is the current way to feature header and footer meanwhile.

**Comment by gabsie** [comment]
Actually, it would be a good idea for @mshadbolt  @tburdett and @lauraclarke  to list here comments on the design above.. Any feedback is welcome.

Gabs

**Comment by lauraclarke** [comment]
I think the GWAS catalog is a special case. I don't think there are many or any other examples where if you are under ebi.ac.uk and you don't have to had the standard header/footer

This is meant to be an EBI resource so making it look like all other EBI resources makes sense

**Comment by gabsie** [comment]
@jacobwindsor 
Hey, @jacobwindsor - seems the current and most up-to-date way to include EMBL-EBI header and footer is here:
 https://stable.visual-framework.dev/components/ebi-header-footer/
And a sample page: https://stable.visual-framework.dev/patterns/boilerplate-generic-embl-ebi/

Let's try this out, and I can meanwhile see how to integrate the table of projects inside. Please let me know if comments or questions!

Gabby.

**Comment by jacobwindsor** [comment]
@gabsie the index already includes one of the EBI footers but I will update to your preferred one. Your design does not include the header, do you want that?

**Comment by gabsie** [comment]
Hey @jacobwindsor - yes let's go ahead with the header (meaning only the top strip with the EMBL-EBI navigation etc) and see how everything looks. I will try update the inside of all this at some point as well :)

**Comment by tburdett** [comment]
On the specific question for me:

> is this Project Catalogue being presented as part of EMBL-EBI? (where you imagine the EMBL-EBI top nav and footer, like on Arrayexpress and eqTL catalogue: https://www.ebi.ac.uk/arrayexpress/browse.html )

**Yes** to this position. This is an EMBL-EBI service that is a complementary resource to the DCP. This means it is a requirement to use EMBL-EBI styling on the pages for consistency with other EBI web content.

**Comment by gabsie** [comment]
Hey, @jacobwindsor and @mshadbolt 

Attaching the updated design here as well. Now that we have the EMBL-EBI header and footer, we don't need to repeat the EMBL logo (it's part of the Header)

I am here for questions/discussion right after 1pm.

![Current variant - Project Catalogue.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/5d5b3a34-7cd3-41b9-a200-e70f77e3a67c) 

Gabs

**Comment by mshadbolt** [comment]
@gabsie is there anything I can do to help with coming up with the explanatory text for this or are you on it?

**Comment by mshadbolt** [comment]
I have updated the ticket name, I think since we decided that we will now have 'about' information as a separate page, we need a design about what that page should look like.
The existing designs in this thread show what the link to this page will look like from the catalogue page, i.e. a link from the top right corner. I think we decided we don't yet need a 'Contribute a project' or 'Contact' page

**Comment by gabsie** [comment]
HI, @mshadbolt AND @jacobwindsor 

I actually reviewed the new visual framework for boilerplates and I think we can use that for our About page.
see here:
https://chanzuckerberg.invisionapp.com/console/share/F7ZY8J9TEZ4/516301155

and... , I think we can maybe also use the same boilerplate for our homepage eventually, because the current thing is not very well organised (done as an MVP and quickly... as always)

And you can view a similar boilerplate here:
https://stable.visual-framework.dev/patterns/boilerplate-generic-embl-ebi/
but this one as well is a good example:

http://wwwdev.ebi.ac.uk/training-beta/about

Please let me know any concerns.. :) I am free for a chat till 1. I might need to find a background image that fits the HCA, if we go this way. 

Gabs

**Comment by lauraclarke** [comment]
thanks  @gabsie 

Just reviewing
https://chanzuckerberg.invisionapp.com/console/share/F7ZY8J9TEZ4/516301155

I am slightly concerned about the use of the word All in this sentence

All datasets identified as suitable for the HCA by the HCA Data Coordination Platform wranglers

Could we lose All, I worry that that word might make people think if their dataset which has to existed for a while isn't on the list it is because it was assessed as non-suitable rather than because we either didn't know about it or haven't got round to adding it yet

**Comment by tburdett** [comment]
@lauraclarke I understand your concern here but rather than softening the aims by removing the "all" (creating ambiguity around what we aim to include), it would be better to use this as an opportunity to encourage people to reach out if they think something is omitted (indeed the bottom line does just this, but could maybe be more prominent)

**Comment by gabsie** [comment]
Hi, @jacobwindsor and @mshadbolt 

So I have attached a simple version of the About, without using the boilerplate, and a version with using the boilerplate from VF. Both are with breadcrumb at the top, which hopefully will give people a way back to catalogue (a link at the bottom as well)

Maybe at this stage go with the one without. 

@tburdett and @lauraclarke  - I have commented on the separate issue about the content,

Gabs


![About catalogue- no boilerplate.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/8adea1a3-b89f-4cf9-8cf1-97ba8700b39c)
![About catalogue- boilerplate.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/6978c3d2-10d8-4e61-83f6-6d2fdebebd19)
