### ISSUE TITLE
[BUG] Error when editing a project and moving too quickly between tabs

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/dcp-ingest-central#128]
When editing a project, if you move between tabs using the Next button too quickly, an error appears as shown below. Then if you wait a bit and click the 'Next' or 'Finish' button, you are able to complete the action.
I was able to reproduce this in Staging and Production.

![Screenshot 2021-01-13 at 17.45.41.png](https://images.zenhubusercontent.com/5d078c35851df4191d4ecc7a/7330b85d-13ea-4cff-bae1-7665eb2656a1)

**Comment by amnonkhen** [comment]
does not reproduce. closing
