### ISSUE TITLE
About page - content

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#138]
Prepare content for the About page for the Project Catalogue.

(finish up the user story)

**Comment by gabsie** [comment]
I am pasting here the list @mshadbolt made about the source of the information for the Catalogue, as this will probably be a source for the content on this page.

======
Wanted to note down currently where publications have come from:
1. Anything in the official HCA publications list https://www.humancellatlas.org/publications/
2. Anything that has been wrangled, awaiting export but project info can be public
3. Anything that has been wrangled and is currently in the HCA Portal/Browser (DCP)
4. Any primary data publications that were used in any of the integrative analysis papers in HCA publications
5. Any datasets identified as suitable by wranglers and in the backlog of datasets to wrangle, potential sources being:

Valentine single cell database - https://www.nxn.se/single-cell-studies
GEO
ArrayExpress
Single Cell Expression Atlas
incidental discovery of a paper with suitable data by any other means
Any datasets with a funding connection to the HCA
WSSS
MRC Developmental Cell Atlas
Organoid H2020 project
CZI seed networks
CZI biological networks
covidcellatlas papers https://www.covid19cellatlas.org/

**Comment by gabsie** [comment]
HI, @mshadbolt, @lauraclarke, @tburdett 

I am pasting here my first idea about the copy on this page, it's in the layout, but the copy is here, and is open for feedback.
I have made a point of the different things we might want to say to potential contributors... 

https://docs.google.com/document/d/1ih-nf4zPnyreugr7K6bbLwEX4vKAEn5iqrqq7FsdUGE/edit?usp=sharing 

![About catalogue- no boilerplate.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/24812f74-dd12-407c-a7cf-4464bf78e503)

Gabs

**Comment by amnonkhen** [comment]
@gabsie is this ticket being Open means the content of the **_About_** page still requires work?

**Comment by gabsie** [comment]
hi, @amnonkhen and @jacobwindsor 

For now, there's just a short block on the Criteria section. What I suggest is that we remove for now the Criteria paragraph (I am asking my participants anyway on their opinions on that), and we publish this on prod.

I expect to go back and just add that paragraph shortly..

Gabs

**Comment by jacobwindsor** [comment]
@gabsie sounds good. Is that something that can be done today?

**Comment by gabsie** [comment]
I think please go ahead and publish on prod, yeah!
