### ISSUE TITLE
Add google analytics

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#140]
As a wrangler I want to know what users of the project catalogue are using the service for.

As a product owner, I want to understand whether users are using the product, and if it is useful

**Tasks**

- Decide on whether to use just GA or HotJar too
- Decide what we will monitor (page clicks, "hot" areas, search terms, search results etc.)
- Decide on some "goals" for tracking
- Implement
- Continually monitor

**Comment by mshadbolt** [comment]
Does ebi have access to use hotjar?

from @tburdett 'I'd like to be able to see how many people start using the project catalog and what sort of searches they're doing'

**Comment by tburdett** [comment]
Re: hotjar - I have never used it and I don't know off the top of my head if we have an EBI license. I would expect not (we could check with TSC) but we're within our rights to sign up for a license ourselves. We can probably pay for a license if we need to and if it makes financial sense.

**Comment by mshadbolt** [comment]
@gabsie to provide account details for ingest and give @jacobwindsor access

**Comment by mshadbolt** [comment]
partially blocked until we get the page hosted on ebi url

**Comment by mshadbolt** [comment]
putting this here from the epic from tony so we think about it when we work on this:
> We should be able to demonstrate this by checking what people search for and detecting when they click through on an archive link. We will be doing a good job if users a) get results corresponding to the thing they searched for and b) follow links to archives for a high number of search results returned.

**Comment by gabsie** [comment]
Hi, everyone, @jacobwindsor in particular
I just set up a new property in GA, for the HCA Project Catalogue.
As a first step, it will count visits, and referrals, for extra stuff like search terms we will need events maybe?
I can put Jacob in touch with Sandeep from my team who has a very good view on how the searches are tracked in Covid portal.
Gabs

**Comment by jacobwindsor** [comment]
Hi all (@mshadbolt @gabsie),
This has now been done. It's implemented using [GTM](https://tagmanager.google.com/) which you should have admin access to via your EBI emails.

Basic GA4 analytics (traffic, scrolls, etc.) will only be done in the production environment but that can be changed via the GTM UI. GA events are now fired whenever a user searches (also only in production environment). This might need some tweaking in code or in the GA UI but let's wait for data to come through before we do that

**Comment by mshadbolt** [comment]
woohoo awesome!
