### ISSUE TITLE
Ability to directly edit metadata in ingest production

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/dcp-ingest-central#141]
It would be really useful if we were able to directly make edits to the different metadata entity types in ingest production. This would not replace making edits to the spreadsheet and then re-uploading, it would be an alternative option so we can choose and do which is easier. This would save time going back and forth editing fields in the spreadsheet if we could make small edits directly in the sample/experiment/file rows where the status is invalid.

**Comment by ESapenaVentura** [comment]
I don't understand this ticket, aren't we allowed to modify pre-submission metadata?

**Comment by ami-day** [comment]
@ESapenaVentura I mean, if we get metadata errors for example, I want to be able to amend the errors directly in ingest, as opposed to deleting the submission, correcting the spreadsheet and re-uploading. Does that make sense? or still not?!

**Comment by ESapenaVentura** [comment]
This is already mentioned in this user story ticket https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/148

**Comment by amnonkhen** [comment]
This has been implemented in more recent tickets.
