### ISSUE TITLE
Multiple updates to hca-to-scea tools script to improve usability of the tool and efficiency of metadata conversion

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/dcp-ingest-central#143]
**User story**
Currently the method to convert hca to datasets involves a semi-automated script (hca-to-scea tools) and multiple manual steps. It can be difficult to get all the details correct if a wrangler has little experience working on the single-cell mage tab format according to their guidelines. The goal is to enable a wrangler to get the required metadata in the required format much more easily, quickly and accurately. It is specifically to update the hca-to-scea tools script itself.

Tickets containing details of the update tasks are in the hca-to-scea tools repo.

**Comment by ami-day** [comment]
We are part way through this epic, but have more tasks to complete.

**Comment by clairerye** [comment]
@ami-day is going to bring in @amnonkhen and @gabsie about next steps

**Comment by ami-day** [comment]
The pull request has now been merged.
