### ISSUE TITLE
Agree to privacy notice banner

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#144]
Hi, @jacobwindsor @mshadbolt 

We forgot to mention this today.. I think all EMBL-EBI sites need to have the agreement to Privacy notice.
Can you find the agreement banner in the visual framework?

@tburdett - which privacy notice should people agree to?

Gabs

**Comment by tburdett** [comment]
As this falls under the main public EMBL-EBI website, it is covered by the main privacy policy https://www.ebi.ac.uk/data-protection/privacy-notice/embl-ebi-public-website. It's good to link to this somewhere on the about page (see e.g. https://www.ebi.ac.uk/biosamples/about)

**Comment by gabsie** [comment]
Hey @jacobwindsor 

I think there a version for this banner which has the I agree as a visible button. That's the only thing to check before closing this issue.

Gabs

**Comment by jacobwindsor** [comment]
@gabsie Is this done? The banner is there but is it the wrong one?

**Comment by gabsie** [comment]
hi, @jacobwindsor 

I only wanted to check whether you're using the latest for this one.
(I thought it had a button, not just a link for I agree)

shall I also check with Ken?
Gabs

**Comment by mshadbolt** [comment]
the one on the main ebi website is exactly like the one we have so I think this is fine.
