### ISSUE TITLE
UI for organs

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#152]
**user story**
As a user of the project catalogue, I want to see what organs are used in each project and be able to search/filter by them.

@gabsie I'll need some design to go off here, I think you already have one right?

@mshadbolt how do we want to search? By ontology label and term or just one of those?

Related to https://github.com/ebi-ait/ingest-core/pull/57 and https://github.com/ebi-ait/ingest-ui/pull/77

**Comment by mshadbolt** [comment]
just the label I think. thanks!

**Comment by tburdett** [comment]
Capturing this here although it can be second phase, it is not necessarily an initial requirement: A wrinkle to this feature would be to search by organ, organ parts, and system. This can be enabled using the ontology annotations and I am happy to make connections to places this has been implemented elsewhere (e.g. biosamples, GWAS Catalog) if it is useful.

**Comment by gabsie** [comment]
Hey, Jacob

I think for now this can be an extra dropdown next to the search one. 

![Current variant - Project Catalogue.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/86e708ea-b7f6-4a66-b280-460d0b512ce2)

Let me know if any more questions.. And the values inside should be the values we have data for..

All the best, 
Gabs

**Comment by mshadbolt** [comment]
do we also want the organs to be displayed in the table itself?

**Comment by gabsie** [comment]
yes, I was thinking that from the beginning, and have a design somewhere.. Now that we are doing it, we can reintroduce. I will think how to present publications and contributors so that we have space for this info..

**Comment by mshadbolt** [comment]
I guess one option could be like you illustrate above to have the publication link just after the project title, and replace the publication column with the organ column?

**Comment by gabsie** [comment]
Hi, @jacobwindsor and @mshadbolt 

Attached just showing the **organ** dropdown, I also introduced technology but know this is not for now. I also explored ideas about how to situate several other bits on this page (which are not for now - top nav, visualising publications and contributors, etc
Happy to discuss them later today. 

![Project catalogue- organ and technology Copy.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/f0d9f068-0666-4fc7-a4ad-6b066df9cc47)

Gabs
