### ISSUE TITLE
write script to populate project organs field

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/dcp-ingest-central#155]
We are currently adding a field to the project that can be populated with organs, this needs to be backfilled for all existing project in ingest. The two ways this will be done are:

For projects with submissions:
* traverse the metadata graph and get a unique list of organs and organ parts

For projects without submissions:
* query the dataset tracking sheet, get the free text organs and ontologise

Make an update submission to each project with the list of organs

**Comment by clairerye** [comment]
@mshadbolt are you still working on this? Or is it done?

**Comment by mshadbolt** [comment]
still working on it, I hope I should finalise it this week

**Comment by clairerye** [comment]
perfect, thank you

**Comment by mshadbolt** [comment]
The script and info are here: https://github.com/ebi-ait/hca-ebi-dev-team/tree/master/scripts/set-project-tech-organs

I will fill out the documentation properly in the next couple of days.
