### ISSUE TITLE
Provide ability for wranglers to see the report of what's in the Terra staging area

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#156]
Wranglers currently don't have access to the Terra staging area unless they use the ingest exporter GCP credentials.

Would be nice to be able to generate a nice report to help with testing:
1. list of files in a project's directory 
2. list of all files in the whole Terra staging area 

This could be just a script that a dev can run and give the output report to the wranglers. Something similar may have already been done before to test the DCP MVP2 exporting. @mshadbolt @ESapenaVentura do you know what was done before to test the DCP2 MVP?

**Comment by mshadbolt** [comment]
@aaclan-ebi this is the little report doc I generated when we were trying to understand what was in the staging area https://rpubs.com/mshadbolt_ebi/653495

the way I generated it was that rolando would give me a text file dump of all the files in the staging bucket and I wrote code to summarise into various tables. Though I think the file structure of the staging bucket as now changed so I guess this wouldn't work anymore

Anyways happy to help with trying to decide what summary statistics might be useful when checking things are exported to the staging area

**Comment by aaclan-ebi** [comment]
Cool! Thanks @mshadbolt , I believe this will be helpful! I think this just needs a small tweak to make it work with the new project subdirectory structure.

**Comment by aaclan-ebi** [comment]
From meeting with @prabh-t and @rays22 yesterday, we agreed on giving wranglers access to the ingest exporter service account for testing.

https://ebi-ait.github.io/hca-ebi-dev-team/admin_setup/Setting-up-access-to-Terra-staging-area.html

It's up to them if they'll create a script to get a summary of files to help with testing. Could reuse and tweak Marion's tool or use python script to do this. @rays22 please let us know if you need any help on this! Very willing to help if needed!

**Comment by aaclan-ebi** [comment]
This ticket is no longer needed as wranglers should now have access to the Terra staging area.

**Comment by aaclan-ebi** [comment]
Just to clarify, we gave access to HCAWrangler user to retrieve the exporter's dev GCP credential for testing exporting in dev or staging. Afaik, it should have access to Terra dev bucket (dev and staging data are in same bucket atm).
