### ISSUE TITLE
File validation is not working

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#159]
**Description of the issue**:

When uploading the data to the ingest upload areas with the hca-util for a submission, the file metadata is not getting validated.

The `cloudUrl` field is not being set up

**How to replicate the issue**:
Get this spreadsheet [https://app.zenhub.com/files/299258791/ee19c909-e6e4-44a6-bef7-c2b5bf488dbf/download](https://app.zenhub.com/files/299258791/ee19c909-e6e4-44a6-bef7-c2b5bf488dbf/download), upload it to the UI, then select hca-util area with name `eventura-GSE131256` and upload the files. 

Once the upload is finished, the 30 files are still missing.

**Examples**:

- https://contribute.data.humancellatlas.org/submissions/detail?id=601970b2ac1792031eee0b88&project=6c040a93-8cf8-4fd5-98de-2297eb07e9f6

**Comment by ESapenaVentura** [comment]
In my case, the issue was that I was using an older version of the `hca-util` package. Updating to latest solved this issue

**Comment by clairerye** [comment]
closing for now, we believe it was the version of the util being used
