### ISSUE TITLE
provide test data to DCP components

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#167]
## User story

**As a** downstream operator of the DCP 
**I want to** test my systems with data on the latest version of the schema 
**so that** I know if changes will need to be made before using this version of the schema on production systems.

## Requirements

test datasets are available for all schema versions
test datasets are available in a GH repo - we want to confirm if this is true
versions.json to accompany test datasets

**Comment by clairerye** [comment]
Do we need history? how do we indicate the latest?

**Comment by clairerye** [comment]
@ESapenaVentura has a doc here looking at pros and cons
https://docs.google.com/spreadsheets/d/1YnWnGot4HFYtQV40sLONPGEpdThJWi0vm97BraBDMVs/edit#gid=0

**Comment by ESapenaVentura** [comment]
We decided to go for a GH repo

Ideally ingest would push data directly to the repo but as a first iteration we will pull data from the repository with a small script and create a PR

**Comment by ESapenaVentura** [comment]
https://github.com/HumanCellAtlas/schema-test-data test dataset has been set up

**Comment by ESapenaVentura** [comment]
Added a couple of changes to the repository:

- Added script to automatically update versions.json on new releases (Pulls from metadata schema repo and processes to desired format)
- Added versions.json from integration
- Added .gitignore to ignore pycharm .idea folder
