### ISSUE TITLE
End to end testing of Updates

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#169]
Updates work as far as exporting to the staging bucket. We need to check they propagate downstream.

- [x] get an actual DCP2 dataset (that needs file additions) into the staging staging bucket (either re-export or copy from prod to staging bucket or ? which is easiest?)
- [x] Make additions to the project and export
- [x] notify downstream components - slack (Raaid and Jeff) that this has been done, could they test import please 
- [x] Wait for confirmation import was successful

------

- [x] get an actual DCP2 dataset (that needs updating into the staging staging bucket (either re-export or copy from prod to staging bucket or ? which is easiest?)
- [x] make updates to the project
- [x] notify downstream components - slack (Raaid and Jeff) that this has been done, could they test import please, and check if we need to complete the snapshot request form so that it can be passed downstream further
- [x] Wait for confirmation import was successful
- [ ] Review with Raaid and Jeff how this process went to inform on how we can improve this sort of multi-component testing in the future

**Comment by Wkt8** [comment]
There are two datasets that are good for these two separate things to test (additions and updates). 

https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=3959a67a-9080-4030-a292-2ba153a43a2b 
I exported this dataset, then made another submission that added additional data files, and exported that. Am about to notify downstream components (Raaid and Jeff) on Slack. 

On testing updates to metadata, a conversation with ray showed that the functionality for actually CHANGING metadata might not be available yet. Checking with a dev to see if this functionality is available.

**Comment by Wkt8** [comment]
Both projects have been successfully imported: 

https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1613736665028000
https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1613731990026900

Awaiting confirmation from browser team that they are reflected in browser, and also need to set up a review with Raaid and Jeff to improve this testing.

**Comment by Wkt8** [comment]
This has now been effectively completed, albeit with some miscommunications and confusion on multiple parts. This grew into a large slack channel conversation thread, as shown here (https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1613736665028000). 

In summary: 
There was disagreement about the method of testing, which will be clarified by the [Exporting SOP ](https://docs.google.com/document/d/1nxqG-WBnjz-bpZafwfupAeIDzUmnPr7W5bbNnOn2Yz4/edit). We do not need to repeat this test, but there was difficult communicating steps between different components. We are reasonably confident updates is now tested. 

For the future/takeaway: 
Utilize specific SOPs with specific steps when communicating with other components.
