### ISSUE TITLE
Create terraform scripts for schema environment

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#172]

**Comment by aaclan-ebi** [comment]
Changing estimate to 3 as we want to look into making terraform scripts for this

**Comment by aaclan-ebi** [comment]
As we no longer need an integration env for the metadata changes testing flow, I'll remove the linking to the "Testing schema changes in ingest" user story. 

Renaming and linking to the Technical Debts epic.
