### ISSUE TITLE
hca-util upload not working

### ISSUE THREAD

**Issue by yusra-haider** [ebi-ait/dcp-ingest-central#185]
duplicate of https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/139#issuecomment-778602403

from Ray's comments:

```
1. I have downloaded the fastq data files from the `hca-util` s3 bucket.
2. I have created a new `hca-util` upload area.
3. I have tried to upload the files in bulk to the new `hca-util` upload area in bulk (using command: `hca-util upload .`), but the upload failed after uploading about ~100 files in 10 hours. I tried that again with the same result.
4. I have successfully uploaded the remaining fastq files to the new `hca-util` upload area one-by-one (using `hca-util upload <filename>` commands).
5. I used `hca-util sync` to re-upload from the new `hca-util` upload area the fastq files that were falsely reported by Ingest to be missing from the Ingest upload area for the submission. This process was successful and triggered validation in Ingest. One file was found to be invalid by Ingest:

>: ERROR: Error in file /data/a489cab8-2e35-456f-8b28-3d571a1bf213/1782163192_C36_F9__N345Barcode_726-508_S129_R2_001.fastq.gz: line 4813284: file truncated

I have downloaded the original data file from the `hca-util` upload area for manual checks. I can confirm that the original data file is corrupted and not a valid gz compressed fastq file. I am omitting it and its paired read as well the corresponding cell suspension (GSM3047806, which is one Fludigm cell) from the dataset, because or their limited usefulness due the loss of sequence data integrity. I can update the dataset once the authors update the corrupted file in the NCBI archives.

6. All the 4345 sequence data files and the metadata in the set passed validation by Ingest.

```

**Comment by jacobwindsor** [comment]
This ticket is actually about upload command. From Ray:

To reproduce the *slow upload issue*, you can download a dataset with a large number of files (>4000) from the hca-util upload area and try to re-uploading them to a new temporary hca-util upload area.

I have downloaded the large file set that caused the issue to me to the wrangler EC2 here:
/data/rstefancsik/GSE111976-endometrium_MC-issue139/

I have had problems when I tried to upload the fastq files like below:
cd /data/rstefancsik/GSE111976-endometrium_MC-issue139/

`hca-util upload .`

The issue seems to be with getting files when using "." and the number of files in the current directory is large. Seems to be caused by the use of recursion and appending files to a list in https://github.com/ebi-ait/hca-util/blob/master/ait/commons/util/command/upload.py. A better approach would be to use lazy evaluation. However, https://github.com/ebi-ait/hca-util/blob/master/ait/commons/util/file_transfer.py#L46 will also need to be changed as calling `len` on a lazy list will evaluate that list causing slowness again

**Comment by yusra-haider** [comment]
The previous implementation of `hca-util upload` would fail due the number of threads being created.

**Testing out the old upload implementation on EC2 and on my local machine for both Ray's dataset and various dummy datasets gave the following results:**

```
EC2, Ray's dataset:
- run against full dataset(4346 files)
    only 103 files got uploaded
    got a lot of different errors

- run against 1000 files from the dataset
    RUN 1:
      took ~ 2 hours.
      63 files uploaded

    RUN 2:
      took ~ 2 hours
      65 files uploaded

    RUN 3:
      took ~100 mins
      65 files uploaded

- run against 500 files from the dataset:

  RUN 1:
    57 files got uploaded

  RUN 2:
    got this error twice when I tried
    `libgcc_s.so.1 must be installed for pthread_cancel to work
     Aborted (core dumped)`

  RUN 3:
      only 39 files got uploaded

  RUN 4:
      got this error:
      `libgcc_s.so.1 must be installed for pthread_cancel to work
       Aborted (core dumped)`

 
- run against 250 files from the dataset:

  RUN 1:
    error:
    `libgcc_s.so.1 must be installed for pthread_cancel to work
    Aborted (core dumped)`

  RUN 2:
    42 items got uploaded 

Against dummy generated datasets:

on my mac:

100 files, 5KB each: all uploaded

200 files, 5KB each: all uploaded

250 files, 5KB each: run 1: 244 uploaded, run 2: all uploaded

500 files, 5KB each: run 1: 261 uploaded, run 2: 253 uploaded

500 files, 73 MB each: run 1: 5 files uploaded

250 files, 73 MB each: run 1: 7 files uploaded

200 files, 73 MB each: run 1: 8 files uploaded

100 files, 73 MB each: run 1: 11 files uploaded

on EC2:
500 files, 5KB each: successful

1000 files, 5KB: 825 got uploaded
```

**errors encountered were with the old version of upload**

```
Errno 24] Too many open files
Could not connect to the endpoint URL
SSL validation failed -> only on EC2
`libgcc_s.so.1 must be installed for pthread_cancel to work
    Aborted (core dumped)`
```

**Comment by yusra-haider** [comment]
Details of testing out the new implementation of upload with `ThreadPoolExecutor` are as follows:

datasets with files of these sizes were used:

- 5KB, that's the minimum acceptable upload size for aws s3
- 73MB, the median size of the files in Ray's dataset
- 170MB, the average size of the files in Ray's dataset
- 500MB
- 2GB
- 5GB
- 10GB

the last four sizes were chosen based on these statistics here: [https://app.zenhub.com/files/299258791/33fe2de1-b927-4bea-a168-2041d16856b9/download](https://app.zenhub.com/files/299258791/33fe2de1-b927-4bea-a168-2041d16856b9/download)

I was unable to generate dummy files with sizes more than 10GB due to memory errors on `EC2` (the RAM is 15GB)

The runs were timed using the `time` command. 

**dataset with each file size as 5KB** 

- 100 files, 5 KB each: successful run, timed at 0m10.437s

- 200 files, 5 KB each: successful run, timed at 0m20.471s

- 500 files, 5 KB each: successful run, timed at 0m50.366s

- 1000 files, 5 KB each: successful run, timed at 1m40.141s

- 2000 files, 5 KB each: successful run, timed at 3m21.663s

- 3000 files, 5 KB each: successful run, timed at 5m3.600s

- 4000 files, 5 KB each: successful run, timed at 6m46.120s

**dataset with each file size as 73MB**

- 100 files, 73 MB each: successful run, timed at 1m10.743s

- 500 files, 73 MB each: successful run, timed at 5m31.245s

- 500 files, 73 MB each: successful run, timed at 5m31.245s

- 1000 files, 73 MB each: successful run, timed at 12m50.795s

- 2000 files, 73 MB each: successful run, timed at 21m57.961s

- 3000 files, 73 MB each: successful run, timed at 32m28.745s

**dataset with each file size as 170MB**

- 100 files, 170 MB each: successful run, timed at 2m21.674s
 
- 200 files, 170 MB each: successful run, timed at 4m39.729s

- 500 files, 170 MB each: successful run, timed at 11m24.384s

- 1000 files, 170 MB each: successful run, timed at 22m50.250s

- 2000 files, 170 MB each: successful run, timed at 45m21.767s

- 3000 files, 170 MB each: successful run, timed at 46m48.672s

**dataset with each file size as 500MB**

- 100 files, 500 MB each: successful run, timed at 6m24.805s

- 200 files, 500 MB each: successful run, timed at 12m42.456s

- 500 files, 500 MB each: successful run, timed at 31m47.480s

- 1000 files, 500 MB each: successful run, timed at 63m58.891s

- 2000 files, 500 MB each: successful run, timed at 128m47.870s


**dataset with each file size as 2GB**

- 100 files, 2 GB each: successful run, timed at 25m31.529s

- 200 files, 2 GB each: successful run, timed at 50m51.057s

- 500 files, 2 GB each: successful run, timed at 127m54.874s

**dataset with each file size as 5GB**

- 100 files, 5 GB each: successful run, timed at 63m59.075s

- 200 files, 5 GB each: successful run, timed at 127m38.572s

**dataset with each file size as 10GB**

- 40 files, 10 GB each: successful run, timed at 47m54.188s

**Run of Ray's dataset, against which the issue was originally reported**
- 4347 files, where the max file size is 55 GB, average file size is 170 MB, median file size is 73 MB and minimum file size is 5 KB, successful run, timed at 84m3.852s

It seems that upload time roughly doubles when the data file size or number of data files are doubled. This isn't an accurate estimate as we would need to do multiple runs against the same dataset for that but it gives a rough idea of what to expect. We can tweak around the performance by changing the max number of threads used.

**Comment by yusra-haider** [comment]
PR raised here: https://github.com/ebi-ait/hca-util/pull/17
