### ISSUE TITLE
Easy to find project UUID

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#197]
# User Story
As a wrangler I want to retrieve the project UUID and pass it to the ops developer in order to get them to check the project I just submitted for export has been exported successfully

**Acceptance Criteria / Definition of Done**

* Given our team and downstream teams need to be aware of the status of exported projects
* When a wrangler submits a project for export
* Then the project UUID should be easy to capture and pass on to downstream team members (and not be confused with the submission UUID)

**Comment by clairerye** [comment]
@gabsie has some ideas/designs of how this could be shown

**Comment by gabsie** [comment]
Hello

My suggestion is here:![Sprint 11 - UUID.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/d2faa6fa-b8da-40fa-98f8-16957cf0a46c)

We can show that if you guys are OK with this

Gabs

**Comment by clairerye** [comment]
This is not for "new projects" this is to be shown wherever possible, nice to have would be the copy to clipboard

**Comment by gabsie** [comment]
Hi, Jacob

This can be uploaded, with this small addition - on hover, and before clicking - can you show 'Click to copy', and once a person has clicked, show a message ' 'Copied to clipboard'

Thanks, 
Gabby

**Comment by jacobwindsor** [comment]
@gabsie Sorry, I missed this comment. How exactly do you want that to look like? We do not have a standard "on hover notification" that we have used before, as far as I'm aware.

**Comment by clairerye** [comment]
This is in prod so moving to evaluating impact

**Comment by gabsie** [comment]
Hey @jacobwindsor 

Like this? Both for hover on the icon  (text to be - Click to copy) and for after clicking on it (like the below)

![Screenshot 2021-05-06 at 04.11.17.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/d4a01176-29ea-443e-bde6-bdc276f6f615)

let me know!
Gabs
