### ISSUE TITLE
Script to push metadata files from staging area to github

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#200]

**Comment by clairerye** [comment]
@ESapenaVentura where are we up to with this? Is it ready for testing?

**Comment by ESapenaVentura** [comment]
I thought I commented on this ticket! the script is here https://github.com/HumanCellAtlas/schema-test-data/blob/master/src/pull_test_data.sh

It currently doesn't really create the branch-push to branch properly. It needs a couple of adjustments on that front

other than that, given a valid project UUID, it downloads the data fine
