### ISSUE TITLE
Time out when registering project leads to data loss

### ISSUE THREAD

**Issue by rays22** [ebi-ait/dcp-ingest-central#206]
**Describe the bug**
It took me longer than 1 hour form me to manually enter project metadata for a study with 27 authors at different institutions in Ingest UI prod. When I clicked `Register`, I got an error (I think it was `404 Not Found`). Tried to log in again in another window, but when I went back to the original window with the data I had entered, it still failed to register and showed the same `404` error. When I clicked to `Show all projects` button, the new project was not listed. I tried to go back to the project registration page, but I was asked to log in again and then I got to a new and empty registration page. All the data I entered disappeared.
**To Reproduce**
Steps to reproduce the behaviour:
1. Enter some project related metadata via Ingest UI.
2. Wait an hour or more until you click `Register`.
3. See what happens.

**Expected behaviour**
Any user entered data should be retained in some form so they do not need to re-enter them.

**Comment by clairerye** [comment]
Introduce autosave to get around this

**Comment by yusra-haider** [comment]
PR raised here: https://github.com/ebi-ait/ingest-ui/pull/89

The current implementation / flow is as follows:

While registering a new project, the project will get autosaved to the client browser storage, 10 seconds after every user change to the form. The project stays saved in the browser till a successful save to the ingest db occurs, after which the project is removed from the client browser storage.

There's now an option to `restore your unsaved project` on the UI:

![image.png](https://images.zenhubusercontent.com/5fa15836bb6093b67034928a/a835cada-c8f6-4721-a231-156ddb78d8e8)

**Comment by yusra-haider** [comment]
@clairerye this is in dev now -- is this going to be tested by a wrangler? There isn't any wrangler assigned to it yet

**Comment by yusra-haider** [comment]
wrangler testing assigned to @ESapenaVentura 

cc: @clairerye

**Comment by ESapenaVentura** [comment]
I have tried it with a project and I have a couple of notes:

Autogenerate label does not work after being logged out (I guess it's not in the scope of this but just wanted to point it out)

If there was required information not filled, it doesn’t let you click save (It will always tell you there are errors and to go back to fix them, even though there aren't any)

It was actually saved but it is not super apparent, I have to click on "register my project" again and look at the tiny text below. Can there be a pop-up in the main page saying that you got an unsaved project? And have something like “continue” “dismiss”? I think a frustated, logged out contributor would be very glad to read that 

On the bright side, I inputted information AFTER I was logged out and it was saved. That is very nice!

**Comment by yusra-haider** [comment]
Thank you for the feedback @ESapenaVentura 

Would it be possible for you to post a screenshot of autogenerate label not working after being logged out, for tracking / record keeping purposes?

And yes, we need to do more work on better showing the project being autosaved from the UX / UI perspective

**Comment by yusra-haider** [comment]
@clairerye I've moved this into the `In Production` pipeline, is that okay or do we need it in the `Evaluating Impact` pipeline?

**Comment by clairerye** [comment]
I will move it into the evaluating impact now we are at the end of the sprint, thank you!

**Comment by clairerye** [comment]
Next steps, @MightyAx, @ESapenaVentura  and @clairerye to confirm what we need from the above, what it may cost and what the priority is.
