### ISSUE TITLE
Ingest UI: Project Catalogue Flag

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#208]
As a contributor, I need to indicate that I agree to the project level metadata being made public in the project catalogue prior to data release in the archives/DCP.

Tasks:

- [ ] Show this in the UI

using this mockup as a reference:
![image.png](https://images.zenhubusercontent.com/5e4d068a4ff78267228d27b4/6679bb20-bb23-4ac7-bef5-4425145ac71b)

**Comment by clairerye** [comment]
@gabsie do we have a logical point where we would put this? At the save point on the project metadata?

**Comment by gabsie** [comment]
Hi, Claire - yes, just today was thinking about this, I would put it on the final screen at this point for project info

**Comment by clairerye** [comment]
something like - 

![image.png](https://images.zenhubusercontent.com/5e4d068a4ff78267228d27b4/6679bb20-bb23-4ac7-bef5-4425145ac71b)

**Comment by lauraclarke** [comment]
Is there a plan to make this default yes? a default no will be frequently missed

**Comment by clairerye** [comment]
good plan

**Comment by clairerye** [comment]
set default flag as yes if spreadsheet is uploaded

**Comment by clairerye** [comment]
closing as this is a duplicate of 284
