### ISSUE TITLE
Analysis files should be exported to Terra staging area

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#210]
As a data wrangler
I want to submit datasets with sequencing to analysis files linking
so that i can submit contributor generated matrices data

**Acceptance criteria:**

Given 
- a valid submission 
- with a sequencing file linked to a process 
- and an analysis file 
- and analysis protocol linked to it,

When
- the project is exported

Then
- the analysis protocol, analysis file will also be exported to the Terra staging area

**Comment by clairerye** [comment]
with sequencing file to analysis file linking

**Comment by aaclan-ebi** [comment]
Hi @rays22 

The changes are deployed in dev and should be ready for testing.

Added a test case for testing submissions with sequencing file to analysis file linking: https://docs.google.com/spreadsheets/d/1sf_PnPRufEPUeqkADhewJGJsYsb00CBwymKKPFB_VHI/edit#gid=2012648405&range=12:13

Here's a very basic spreadsheet which I modified to include that linking that you could follow:
[test_analysis_files.xlsx](https://github.com/ebi-ait/dcp-ingest-central/files/6243828/test_analysis_files.xlsx)

Many thanks
Alegria

**Comment by rays22** [comment]
@aaclan-ebi
Please, coordinate the tests for this ticket with the wranglers on the dev rota for the current sprint.

**Comment by mshadbolt** [comment]
I will run through the test plan for this

**Comment by mshadbolt** [comment]
@aaclan-ebi just to confirm the task for this, you want me to manually look at the list of files and the links.json provided above to make sure all the expected files and links are present?

**Comment by mshadbolt** [comment]
number of files in each sub folder:
|directory   |  n|passing|
|:-----------|--|---:|
|data        |  3| Y|
|descriptors |  3|Y|
|links       |  1|Y|
|metadata    | 17|Y|

Number of json files for each entity type
|type                         |  n|passing|
|:----------------------------|--:|
|analysis_file                |  1|Y|
|analysis_protocol            |  1|Y|
|cell_suspension              |  1|Y|
|collection_protocol          |  1|Y|
|dissociation_protocol        |  1|Y|
|donor_organism               |  1|Y|
|enrichment_protocol          |  1|Y|
|library_preparation_protocol |  1|Y|
|process                      |  4|Y|
|project                      |  1|Y|
|sequence_file                |  2|Y|
|sequencing_protocol          |  1|Y|
|specimen_from_organism       |  1|Y|

Checked links have correct inputs and outputs in the provided `links.json`

marked as passing in the test plan

**Comment by aaclan-ebi** [comment]
Thanks @mshadbolt ! I'm so sorry for my delayed response. 
I was wondering if you could try this using a real dataset spreadsheet if there is one. If none, I believe this test should be good enough.

**Comment by aaclan-ebi** [comment]
I've deployed the changes in staging today. Will promote to prod by tomorrow.

**Comment by mshadbolt** [comment]
I did a test by adding analysis files and analysis protocols to a project I am wrangling. 

spreadsheet: [GSE130708_ontologies_matrices.xlsx](https://github.com/ebi-ait/dcp-ingest-central/files/6301794/GSE130708_ontologies_matrices.xlsx)

I used dummy fastq and analysis files to minimise size of files.

I uploaded the spreadsheet to staging here: https://staging.contribute.data.humancellatlas.org/submissions/detail?id=6075028fed34714563010525&project=e9df5a71-6b94-42c4-b62d-19eaf891ee2e

I then exported to staging folder of staging bucket and did the same testing as above by looking at the folder in the staging bucket (`gs://broad-dsp-monster-hca-dev-ebi-staging/staging/e9df5a71-6b94-42c4-b62d-19eaf891ee2e`).

|directory   |  n|passing|
|:-----------|---|---:|
|data        | 47| Y|
|descriptors | 47| Y|
|links       |  4| Y|
|metadata    | 72| Y|

within the metadata folder:
|type                         |  n| passing|
|:----------------------------|--|--:|
|analysis_file                |  3| Y| 
|analysis_protocol            |  5| Y|
|cell_suspension              |  1| Y|
|collection_protocol          |  1| Y|
|dissociation_protocol        |  1| Y|
|donor_organism               |  1| Y|
|enrichment_protocol          |  1| Y|
|library_preparation_protocol |  2| Y|
|process                      |  9| Y|
|project                      |  1| Y|
|sequence_file                | 44| Y|
|sequencing_protocol          |  2| Y|
|specimen_from_organism       |  1| Y|

I then looked at the `links.json` files to check the sequence files were linked to the analysis files as expected. Each links.json did have linking from sequence files to each of the 3 analysis files

One thing I noticed while using the ui to help me check the links.json files was that the ui doesn't display the input files in the process when a file is both the input and output when viewing the graph. I don't think this should stop the feature being promoted but it would be good to ensure we fix this at some point as it is really handy for wranglers to be able to view these processes in this way.
![Screenshot 2021-04-13 at 17 07 06](https://user-images.githubusercontent.com/13007987/114511019-b6b21780-9c7a-11eb-8e0e-f9fa24acb214.png)

**Comment by aaclan-ebi** [comment]
Thanks for testing this Marion! Yes, the UI isn't displaying the input files yet. When the UI which displays the linking info was implemented, there was an assumption that there are no analysis files that will be submitted thru Ingest. I have very rough UI changes that I still need to properly code and finalise to support the display of input files. I'll create a separate ticket for that.

I'll proceed with deploying this to production. I believe the acceptance criteria have been met to export all the analysis files which weren't happening before.

Let's discuss the thread further later https://embl-ebi-ait.slack.com/archives/C016R78CDV1/p1618299105131000 to clarify how we want to construct the links.json files and represent the subgraphs better. I'll create a new ticket for any changes that we'll agree on.

**Comment by mshadbolt** [comment]
sounds good to me!

**Comment by clairerye** [comment]
Using for release 6, will close when this has been used successfully.

**Comment by aaclan-ebi** [comment]
Hannes confirmed that our implementation which creates 1 links.json for both assay and analysis subgraph is fine. 
https://embl-ebi-ait.slack.com/archives/C01360XN04S/p1621333630000700

**Comment by clairerye** [comment]
using this in release 7 and 8
