### ISSUE TITLE
Migration to new AWS cloud account

### ISSUE THREAD

**Issue by prabh-t** [ebi-ait/dcp-ingest-central#231]
Provisional checklist of todos
- [ ] migrate ingest service to new aws account
  - [ ] dev
  - [ ] staging
  - [ ] prod
- [ ] migration upload service to new aws account
- [ ] s3 buckets transfer
- [ ] clean up resources in existing aws account

**Comment by amnonkhen** [comment]
closing this ticket, as it would be tracked by others. See epic.
