### ISSUE TITLE
Error messaging for a form field - VF UI

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#237]
As a data submitter I want to see the erroneous entry for a form field in context - which field of what I am entering, so that I know I need to correct my entry.

**Acceptance Criteria / Definition of Done**

* Given the error messaging appears on the level of the form field
* When I type in an unaccepted value for a field
* Then I should see which field doesn't accept that and why, so that I can make amends.

**Comment by gabsie** [comment]
As a start, can we please show the errors for the DOI in this way? I think this is part of the Visual framework?
Let me know if any questions.

Gabs![Sprint 11 - Project start-1.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/a7925f84-f787-401a-8ee5-b8970a7d614b)

**Comment by ofanobilbao** [comment]
@gabsie I feel like this is also part of the error reporting. But it could be more on the Contributor persona. If the latter I would move to Icebox

**Comment by amnonkhen** [comment]
This is implemented as Gabby requested.
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/c60228b6-6634-421c-b877-66d37946a6fc)
