### ISSUE TITLE
Implement post processing script

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#241]
As a HCA user
I want to be confident schema changes I need can be supported by all HCA components
so that my experiment can be reflected accurately in HCA

test data push to git:
https://github.com/HumanCellAtlas/schema-test-data

post processing design:
https://docs.google.com/document/d/1wcHuSQXwNXyAyzYvXj9lv9QKbcABQ0-64Gr1oQ-gItQ/edit#

**Acceptance Criteria**

- Given a project with test data that has been ingested and exported
- When
  - a schema change is introduced 
  - and ingested and exported
- Then the exported project file differences reflect the modified schema elements

**Comment by Wkt8** [comment]
This is a test project that was exported **before** the schema changes adding dbGAP and EGA accessions.
https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=81cea047-fbba-4c1e-a97c-cba17086cd6a 

This is the same test project that was exported **after** the schema changes adding dbGAP and EGA accessions.
https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=81cea047-fbba-4c1e-a97c-cba17086cd6a

The schema change is here:
https://github.com/HumanCellAtlas/metadata-schema/pull/1366/files

The changes to the spreadsheet are: 
Added the two new optional fields 'project.ega_accessions' and 'project.dbgap_accessions' to the project tab. 
Added values for the two fields.
project.ega_accessions: EGAS00000000001||EGAD00000000002
project.dbgap_accessions: phs001997.v1.p1||phs001836
