### ISSUE TITLE
Error page when deleting a submission

### ISSUE THREAD

**Issue by mshadbolt** [ebi-ait/dcp-ingest-central#244]
**Describe the bug**
> When you delete a submission from the page where you are viewing the submission, after the submission is deleted you get shown a 'Service unavailable' Error screen which is confusing/annoying. I would expect to get directed back to the 'Upload' tab of the project as the most likely action after deleting a submission, is to upload a corrected spreadsheet

**To Reproduce**
1. Go to the ingest ui to a project with a submission and view the submission by doing to 'Upload' then click the uuid of the submission
2. While viewing the submission, Click on the trash can icon to delete the submission
3. After deletion you are shown a 'Service Unavailable' screen that advises reloading, but no amount of reloading will fix it because the submission doesn't exist

![Screenshot 2021-03-23 at 14.23.38.png](https://images.zenhubusercontent.com/5d078c35851df4191d4ecc7a/3a7a9f61-bce7-4602-ad65-de4c276c2a30)

**Expected behavior**
> I would expect to be directed back to either the project summary page or specifically to the 'Upload' tab of the Project

**Comment by jacobwindsor** [comment]
Closing as no longer a bug
