### ISSUE TITLE
updates on previously exported projects

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#246]
As wrangler I want to update projects that were exported prior to 12 March 2021 (when updates feature was deployed to dev) so that I can update projects as required

**Acceptance Criteria / Definition of Done**

* Given I have an update to make to any project exported prior to 12 March 2021
* When I make that update in the UI
* Then it will be exported correctly to the terra staging area

This is the follow on work for #77

**Comment by clairerye** [comment]
either create a script to rename all the data files and execute the script.
Or delete the data files.

**Comment by rays22** [comment]
@aaclan-ebi
Please, coordinate the tests for this ticket with the wranglers on the dev rota.

**Comment by aaclan-ebi** [comment]
This is blocking ebi-ait/hca-ebi-wrangler-central#280

**Comment by aaclan-ebi** [comment]
I ran the migration script against the prod Terra staging area. The script is in the PR linked to this ticket. The log files were too big to paste here. It ran against the descriptors listed [here](https://github.com/ebi-ait/hca-ebi-dev-team/blob/master/scripts/fix_iss_ebi-ait_dcp-ingest-central_246/descriptors.txt).

**Comment by ami-day** [comment]
Submitted export form for the updated project.
