### ISSUE TITLE
Ensure `file_core.format` field is correctly filled

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/dcp-ingest-central#266]
As a wrangler I want to ensure `format_file` field correctly reflects the file format of the file it references 

Consequences of this being incorrectly filled:
File validation is based on the `format_file` field if it is incorrect files, specifically fastq files skip file validation. 
`format_file` field is used by downstream components, incorrect values in this field are displayed in the browser and cause issues with pipelines.

Possible solutions - are there others?

Have `format_file` filled by the system to ensure no human error
Additional graph validator check to check cross field - `sequence_file.file_name` matches `format_file`
restrict values/ validate `format_file` field to catch errors

Slack thread where the validation issue occured: https://embl-ebi-ait.slack.com/archives/C01360XN04S/p1616522022057700?thread_ts=1616512556.056600&cid=C01360XN04S

**Comment by gabsie** [comment]
From the chat in the sprint meeting, to be continued here now we understand the problem:
"From an error prevention principle POV, a file format should be automatically detected and checked by the system. why we keep a field in the db to say manually what the file format is, I don't get.. "

Gabs +1 from everyone else

**Comment by lauraclarke** [comment]
Might be worth checking if any downstream component expects this field, it is the sort of thing that might have been added as a convenience for some other component or because at the time we did it, it was easier than automatic detection!

**Comment by ESapenaVentura** [comment]
https://github.com/HumanCellAtlas/metadata-schema/issues/1383 

I created a schema ticket about a possible update on this

@lauraclarke yes, we discussed a little bit in the meeting, and afaik there's at least one downstream component that uses (browser displays file format)

**Comment by aaclan-ebi** [comment]
After a discussion with @ESapenaVentura and @amnonkhen, we've thought of the possible options:
1. Update metadata schema to validate correct file format, e.g. will match regex without dot in the beginning
- will take time before the schema changes can be released given the current process
- won't guarantee misspelt file formats
2. Flagging to the user if a file is set as valid if it has no validator
- this might not be useful to the user
**3. Update validator to automatically determine the file format for a given file/metadata and compare it with the format given by the user
- use the file name extension for now
- this is the approach we're implementing for this sprint

**Initial test cases:**

Given:
1. file metadata filename file extension
2. file metadata `file_core.format` 

When: If both formats from 1 & 2 have the same format validator
Then: proceed with validation

When: If both formats from 1 & 2 have no format validator
Then: set valid

When: If the format from 1 is not determined & 2 has a format validator
Then: proceed with validation

When: the format from 1 & 2 differs
Then: mark the file invalid and return the validation error, user can decide on what to do

@amnonkhen @ESapenaVentura, do these test cases reflect what we agreed on?

**Comment by clairerye** [comment]
Out of curiosity if we can:
> Update validator to automatically determine the file format for a given file/metadata and compare it with the format given by the user

Can we auto fill the field from the file format rather than just doing the comparison?

**Comment by ESapenaVentura** [comment]
> Can we auto fill the field from the file format rather than just doing the comparison?

I worked in a detailed spreadsheet with the possible use cases https://docs.google.com/spreadsheets/d/1J0oNWFDLmoLh_a26itZQCu8eH9eAZ0Ts1ZcEQXKRPX4/edit#gid=0

One of the possible outcomes for a couple of scenarios is to either fill automatically (When it wasn't filled in the spreadsheet) or throw a warning and ask if ingest can fill it automatically.

I like the idea of automatic filling tbh, but at the same time I am concerned about deleting contributor-filled metadata without asking first

**Comment by aaclan-ebi** [comment]
@clairerye, sorry for my late reply to your question. @ESapenaVentura made a good point as well on overwriting the file format specified by the contributor. 

@amnonkhen and @jacobwindsor discussed this and we think that auto-filling could be implemented if the user hasn't specified any file format. We could do it but we decided to scope it out for now as it'll have to be implemented during importing/uploading.  We'll prioritise the file format validation which would check if the file format matches the file format the system has detected from the filename vs the file format specified by the user. This should already avoid the problem of the fastq file not being validated from happening again. Is this okay with you @clairerye ?

**Comment by clairerye** [comment]
Yes, absolutely. I was just checking. I like the idea of not including this field in the spreadsheet and autofilling it in the future.
I see @ESapenaVentura concern on 
> I am concerned about deleting contributor-filled metadata without asking first
But I think this is metadata the contributor should never be asked to fill in in the first place.

Your plan @aaclan-ebi is sound and maybe we can consider autofill in the future

**Comment by aaclan-ebi** [comment]
Thanks @clairerye ! I created a ticket here ebi-ait/dcp-ingest-central#281

> But I think this is metadata the contributor should never be asked to fill in in the first place.
Yeah, but won't the user have to confirm/verify if the type detected by the system is correct? So we were thinking it's a bigger scope and still needs a bit more thinking. The validation should be simple enough to be put in place for this sprint.

**Comment by clairerye** [comment]
> The validation should be simple enough to be put in place for this sprint.

Great, thank you.

> Yeah, but won't the user have to confirm/verify if the type detected by the system is correct?

I would argue no, but am possibly missing things. Is there a scenario when the system would be wrong? And if so would the contributor be right? I agree a bit more thinking about this is sensible, but not for this sprint.

**Comment by aaclan-ebi** [comment]
Hi @Wkt8 

The changes are now in staging. You could do the testing there. Here are the test cases based on @ESapenaVentura 's [test plan](https://docs.google.com/spreadsheets/d/1J0oNWFDLmoLh_a26itZQCu8eH9eAZ0Ts1ZcEQXKRPX4/edit#gid=0)
https://github.com/ebi-ait/ingest-validator/blob/master/features/validator.feature

**Comment by Wkt8** [comment]
I have gone through the test plan and also added a couple more involving changes in the UI. (https://staging.contribute.data.humancellatlas.org/submissions/detail?id=60818a665ba51701d5bb4978) There are two points: 
1. We are able to edit the file_name in the UI after syncing the files from the hca-util upload area to the s3 bucket. This means the file_name in the metadata could be changed whilst the file_names of the actual files remain unchanged. It would be great if we could restrict this somehow. 

2. The 'file_format' field is a required field, and there were several test cases that assumed it is not a required field. I can't see any reason it must be amade an optional field. A required field should work fine. 

UI Test cases: Changing information in the UI so that the 'file_name' and 'file_format' fields are in sync causes the invalid file to cycle from invalid -> draft -> validating -> valid. This is great as we can fix any invalid errors within the UI.

**Comment by aaclan-ebi** [comment]
Thanks @Wkt8 for the feedback.

For 1, I've filed a different user story ticket for disallowing users to update the filename in the file metadata ebi-ait/dcp-ingest-central/290.

For 2, I will update the test cases in the ingest validator cucumber tests.

**Comment by clairerye** [comment]
In staging, needs staging integration tests to pass then can be promoted

**Comment by aaclan-ebi** [comment]
Promoted to prod https://gitlab.ebi.ac.uk/hca/ingest-validator/-/pipelines/153303

**Comment by clairerye** [comment]
Closing this ticket, assumption is that this ticket will mean less helpdesk tickets/ pipelines questions about data files, so will keep an eye on this.

**Comment by clairerye** [comment]
First bug ticket - https://github.com/ebi-ait/dcp-ingest-central/issues/324
