### ISSUE TITLE
Consumer metadata spreadsheet

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#267]
As data consumer I want to understand the metadata associated with a project so that I can re-use the data in a scientifically valuable way for my own research.

** Acceptance Criteria / Definition of Done **

* Given the HCA metadata that accompanies a project 
* When a consumer downloads that metadata from the project catalogue (or elsewhere)
* Then the metadata is useable to a data consumer 

** Open Questions: **
 - Is there "best practice" for this?
 - how do we measure/define useable? 
 - who do we know who is an HCA data consumer?
- should we align with SCEA and use MAGE-TAB or ISA tab format?

**Comment by mshadbolt** [comment]
Had a quick chat with Claire and we decided that a good first step would be to come up with my best guess of what I think a consumer might want in terms of a table of our metadata.

We discussed a little bit about a potential 'summary graph shape' of projects too.

**Comment by amnonkhen** [comment]
work maintained on #854. Closing this
