### ISSUE TITLE
cucumber testing pilot

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#270]

**Comment by amnonkhen** [comment]
@jacobwindsor @aaclan-ebi I pushed the skeleton test to [cucumber-test-pilot] remote branch (https://github.com/ebi-ait/ingest-validator/tree/task/cucumber-test-pilot)

**Comment by clairerye** [comment]
waiting on file format ticket

**Comment by aaclan-ebi** [comment]
Promoted to prod: https://gitlab.ebi.ac.uk/hca/ingest-validator/-/pipelines/153303

**Comment by amnonkhen** [comment]
Closing. We will use cucumber in future testing.
