### ISSUE TITLE
flexible DOI input, rigid output

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#275]
As a user I want to be able enter "whatever I consider as a DOI" and use it to pre-fill project metadata.

the doi field should be able to take both doi urls and plain doi strings as input.
the doi should always be stored as the doi string in ingest/mongo.

Additionally it would be nice to have have all doi validations on the page where the user inputs the doi. 

Right now the validation checks are:

the input doi isn't being used by any other project in ingest
the input doi actually exists in europe pmc, and is a valid doi
The latter validation is currently on the project form page. The feedback is to have this on the page where the user inputs the doi.

Tasks:

- [ ] Have relevant error messages to describe the errors correctly

- [ ] UI error message handling should be according to the provided VF error message design.

- [ ] dev work around also taking URLS

**Comment by mshadbolt** [comment]
I found a couple of small bugs to fix up when using the doi input project registration flow
* The authors in the `project.publications.authors` have a leading white space from the second author onwards e.g. `"publications" : [ {
      "authors" : [ "Sim CB", " Phipson B", " Ziemann M", " Rafehi H",...` [in ingest](https://api.ingest.archive.data.humancellatlas.org/projects/6076ceb2dd9aab1232d26848)
* The contributor names get commas in the wrong spot when there is a middle initial
    * e.g. `"name" : "David A,,Elliott",` should be `"David,A,Elliot"` (I do not know why we format it like this)

I also noticed a weird thing where on the[ paper](https://www.ahajournals.org/doi/10.1161/CIRCULATIONAHA.120.051921?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed) there are bunch of authors that have ORCIDs but then in europmc only 2 have orcids listed, and they aren't the same as those that are listed on the article. But anyways, that isn't a bug with our code, but maybe something weird with where europmc are getting them from.

**Comment by mshadbolt** [comment]
I was curious so I looked into it a bit more, i think either the journal or crossref guesses ORCIDs by author names (https://api.crossref.org/v1/works/10.1161/circulationaha.120.051921)

**Comment by mshadbolt** [comment]
In the registration form it now asks for 'Existing project accession ID' from any of geo/arrayexpress but in the next step it puts it into the 'ArrayExpress' field. It might be possible to use regex matching to put the accessions into the appropriate fields, e.g. starts with 'E-MTAB', put in arrayexpress, starts with 'GSE', put it in GEO, matches with any of the INSDC study/project pattern

**Comment by clairerye** [comment]
Changing my mind and moving @mshadbolt suggestions to a different user story so this doesn't become a "grab all" list of improvements. This will be tracked in #283

**Comment by amnonkhen** [comment]
Implemented with "import DOI" feature.
