### ISSUE TITLE
Fix broken ingest-archiver tests

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#280]
Many of the tests for ingest-archiver are failing. A large part of the tests are also integration tests so can be removed

**Comment by jacobwindsor** [comment]
Looks like @aaclan-ebi did this #266

**Comment by aaclan-ebi** [comment]
@jacobwindsor you can remove all integration tests in the archiver repository, they were all moved to the ingest-integration-tests. Please retain the unit tests if there are.
