### ISSUE TITLE
Evaluation of DSP and decision on HCA archiving

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#282]
Evaluation of DSP and HCA's current archiving infrastructure architecture to determine next steps.

Considering the following options:

- Re-using DSP’s services and move them into HCA’s infrastructure. 
- Build a brand new application and reuse some libraries that we created when we implemented a supporting app for the Covid-19 Drag & Drop Portal in the last couple of months.

Both of the options has pros and cons.

**Comment by ke4** [comment]
This is the document that is containing the plans for archiving:

https://docs.google.com/document/d/10m4IDxtFw68ZiTzTHGH3EKJvmHd9Bl3zb-mGbK9glJg/edit#

**Comment by ke4** [comment]
This is a document that lists the known issues and missing features of DSP regarding to HCA submissions:

https://docs.google.com/document/d/1UixAKWBrYqgvjzXZwEclcG4xptyKSpsLd3ngoRM1CDg

**Comment by clairerye** [comment]
Decision to retire DSP and replace it using the covid-utils work.
