### ISSUE TITLE
DOI autofill improvements

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#283]
As a wrangler/contributor I want the auto-filled fields to be as correct as possible so I don't need to manually fix them.

Two areas:

The authors in the project.publications.authors have a leading white space from the second author onwards e.g. "publications" : [ { "authors" : [ "Sim CB", " Phipson B", " Ziemann M", " Rafehi H",... in ingest
The contributor names get commas in the wrong spot when there is a middle initial
e.g. "name" : "David A,,Elliott", should be "David,A,Elliot" (I do not know why we format it like this)

In the registration form it now asks for 'Existing project accession ID' from any of geo/arrayexpress but in the next step it puts it into the 'ArrayExpress' field. It might be possible to use regex matching to put the accessions into the appropriate fields, e.g. starts with 'E-MTAB', put in arrayexpress, starts with 'GSE', put it in GEO, matches with any of the INSDC study/project pattern

** Acceptance Criteria **
When the form is autofilled from a DOI the:
commas appear in the correct position when the author has a middle initial
Auto fill the correct accession field rather than simply putting any accession in the ArrayExpress field.

**Comment by amnonkhen** [comment]
implemented in DOI feature.
