### ISSUE TITLE
ingest -> BioSamples using Excel Covid

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#288]
Diagram: https://drive.google.com/file/d/1NHpkIK-irfD7Eq2A8jyqi4xSJ9CX8R2Z/view?usp=sharing
In-progress Branch: [biosamples-direct](https://github.com/ebi-ait/ingest-archiver/tree/biosamples-direct)

Subtasks (Not exhaustive or prescriptive)
- [x] Import submission module
- [x] Create an ~~ingest~~ loader package
    - [x] Create Cached ingest class
    - [x] Loads an ingest project / submission into a Submission / Entity model
        - [Document describing how to load all a project's entities and links](https://docs.google.com/document/d/1DoRKM2zmtBvZg3duD884TeqdRMUl9E29B7KuI6Vgvfc/edit#)
    - [x] Unit Test HcaSubmission (cache)!
    - ~~Unit Test HcaLoader~~
- [x] Import BioSamples module
- [x] Create a converter package
    - [x] with a BioSamples class that takes a Submission / Sample and creates BioSamples payloads
    - [x] Fix datetime conversion issue
    - [x] Unit Tests!
- [x] BioSampleSubmitter class
    - [x] Input is a Submission / Entity
    - [x] Uses converter to make payloads
    - [x] Sends payloads to BioSamples Module
    - [x] Saves accessions/errors in entity
    - [x] Unit Tests
- [x] Save accessions back to ingest
    - ~~Create converter~~
    - [x] Generate new biomaterial entity attributes using BioSamples accession
    - [x] Unit tests edited biomaterial
    - [x] Save to ingest (current archiver code does this)
    - [x] unit test save to ingest

**Comment by MightyAx** [comment]
One last thing for Tuesday is to save the Accessions from Biosamples into Ingest.
The rest of the work is here: https://github.com/ebi-ait/ingest-archiver/pull/33

**Comment by MightyAx** [comment]
# Notes from Sprint Review Demo:

## Missing Features:
 - Fix datatime conversion bug
 - Unit tests of the: Loader / BiosamplesSubmitter classes
 - Save Accessions back to ingest
 - Switch over to stop sending BioSamples to DSP
    - Default to new functionality with param for DSP mode?

## Possible future improvements:
 - Send BioSample Attributes for any value in the HCA schema rather than specific ones:
    - either using the schema friendly name
    - or by using a common conversion from the programatic name

## Either as a one off test or as a regular Integrations test:
 - Use this list of submitted HCA BioSamples: `https://www.ebi.ac.uk/biosamples/samples?filter=attr%3AHCA+Biomaterial+UUID`
 - Given each sample:
    - Download BioSamples Version
    - Get HCA sample using `https://api.ingest.archive.data.humancellatlas.org/biomaterials/search/findByUuid?uuid=`
    - Regenerate BioSamples Payload
    - Check that they match (within tolerance for Date Added / Date Modified)
        - If they don't match:
            - Either the BioSample Should be updated to the latest HCA version
            - or the HCA conversion to BioSample code should be updated to include the change.

**Comment by MightyAx** [comment]
Ticket updated with latests todos:
1. HcaLoader Unit Tests
2. BioSamplesSubmitter Unit Tests
3. fix datetime conversion bug
4. Save to ingest
5. unit test save to ingest

**Comment by MightyAx** [comment]
I've finally decided that there's no reasonable Unit Test for the HCA Loader passed on the architecture of the Ingest API that it is calling.
I added in #299 since I needed to test the output.
Ready for Review

**Comment by MightyAx** [comment]
Integration Test Failure:
https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/jobs/439151#L416

Pod Logs:
```
Traceback (most recent call last):
  File "app.py", line 18, in <module>
    from archiver.direct import direct_archiver_from_config
  File "/app/archiver/direct.py", line 2, in <module>
    from hca.loader import HcaLoader, IngestApi
ModuleNotFoundError: No module named 'hca.loader'
```

Fix:
https://github.com/ebi-ait/ingest-archiver/commit/99ff6c04fd0a038e1c1fbb25ad0632b6d3fc6649
