### ISSUE TITLE
Create Switch to Archiving Direct Mode.

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/dcp-ingest-central#299]
# Acceptance Criteria
Archive Production Projects biomaterial to BioSamples using "direct-mode" rather than through DSP.

**Comment by clairerye** [comment]
Need to make a decision about when we do the switch between DSP and the new archiving method.

**Comment by ke4** [comment]
I am not sure this action worth to do.
My points:
- This could be a bit complex to do and won't add any value to the user. They won't see any difference at the result.
- It has never be tested how DSP would work without a BioSamples submission. It might work or not.
- **DSP is linking together BioStudies (project is DSP) entity and the BioSamples that belongs to them. Without BioSamples submission from DSP that functionality would be broken!!!!**
- We would have to repeat this activity when the new BioStudies submission route would be ready. IMO that would be another waste of time

**Comment by MightyAx** [comment]
we can probably close this ticket because the work is done in #288
