### ISSUE TITLE
Incorporate the VF-hero component into the HCA Project Catalogue

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#307]
As a visitor to the HCA Project Catalogue, I wish to see it appear consistent with other sites of EBI, so I know it's their product and I can trust it.

** Acceptance Criteria / Definition of Done **

* Given we implement the header component
* When a visitor goes to the homepage
* Then they recognise it as the usual for EBI services

Tasks:

- [x] implement the vf-hero component from the Visual Framework, similar to the way it's implemented here: https://www.ebi.ac.uk/training/
- [x] implement the breadcrumb navigation for an inner page, like About
- [x] Gabs to supply the header image which fits with the HCA brand

**Comment by gabsie** [comment]
Here are the top header area suggestions, if I find alternative visuals, I will upload different ones, let's have these as placeholders

Gabs
![nobreadcrumb.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/b9a8be67-0ad0-4118-ae10-41f2e852c854)![with breadcrumb.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/02503f39-653b-47cf-8c08-0e1750f24e4d)

**Comment by clairerye** [comment]
will be deployed with 173
