### ISSUE TITLE
Filter projects by assigned wranglers and status

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#313]
As a wrangler/stakeholder I want to go and find just the projects I am assigned to so that I can quickly review them and work on them.

**Acceptance Criteria / Definition of Done**

* Given the list of all projects
* When I select a wrangler to view their projects
* Then I am presented with a smaller list with just the relevant projects.

Tasks:
- [x] UI design

To avoid doing this work twice we **could** do this intended with the Solr work (currently waiting until alter sprint)

#### Core: 
- [x] Project query that accepts wrangler & wrangling status filters

#### UI:
- [x] Implementation of UI Designs

**Comment by gabsie** [comment]
Here is an initial suggestion for discussion.![Projects - Wrangler list.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/b8916b3b-9ad2-4353-9f12-4d8d215a0979)
Thoughts, @clairerye @mshadbolt

**Comment by gabsie** [comment]
Also include a filter by wrangler and status for this.

**Comment by aaclan-ebi** [comment]
Updates:

The primary wrangler and wrangling status are added in the project list table
https://staging.contribute.data.humancellatlas.org/projects/all

![Screenshot 2021-06-02 at 10.04.03.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/6d0deb29-243e-48ce-b2a8-c32d97f02710)

Waiting for designs for the badges and the filters.

**Comment by clairerye** [comment]
super super excited about this!!

**Comment by gabsie** [comment]
So I have updated things here:

You can use the badges for the statuses
The Search component for the top
the dropdowns components for the filters

Gabs


![Projects - Filter Wrangler list.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/3b59f7d0-bb05-4943-a16e-b07035a4dec8)
