### ISSUE TITLE
Set Project Wrangling Status on Admin Screen

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#317]
#### Ingest Core:
- [x] Add Wrangling Status field as set by the Wrangler to Project Metadata (not schema)

#### Ingest UI:
 - [ ] Add Wrangler Status Dropdown to Project Admin Screen

This is a continuation of [ticket 279](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/279)

**Comment by clairerye** [comment]
Designs as per the assign a wrangler admin screen
https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/fdd1ed13-a1c4-4f41-91ef-92871ee31600

**Comment by gabsie** [comment]
Hi, @aaclan-ebi and @clairerye 

As per our chat on Friday, here is the list of Wrangling statuses that we decided on:

New
Eligible - 1,2,3
Not eligible
In progress
Stalled
Submitted
Published in DCP
Deleted

Let me know if anything else needs discussing, @aaclan-ebi 
Gabs

**Comment by aaclan-ebi** [comment]
Here are the current changes, will push the PR to play around in dev env. 
![Screenshot 2021-05-24 at 15 59 29](https://user-images.githubusercontent.com/31281398/119366665-1bfd1d80-bca9-11eb-9182-66b97d56b4e1.png)

We still need a plan for populating the existing projects. Currently, they will be set as empty.

**Comment by aaclan-ebi** [comment]
Hi @gabsie @ESapenaVentura The changes are now in dev, please let me know what you think. Thanks!

**Comment by aaclan-ebi** [comment]
https://dev.contribute.data.humancellatlas.org/projects/new

**Comment by ESapenaVentura** [comment]
Hi @aaclan-ebi LGTM! Excited to see this feature

As @clairerye mentioned, having the possibility of negative numbers looks weird, but I don't think that should be a problem (Also tried to break it by adding a super high number but it just gave a validation error and reset to 0, so great!)

About the statuses, just 3 minor things:
- Can they have a more user-friendly name? Even if internally they are represented like that, it doesn't look great all in caps and with no spaces
- What does exactly "Deleted" mean? I am guessing if the project should be deleted we shouldn't even see that page? or are we assuming that the wrangler/user will delete most of the metadata and just input that status?
- Will these statuses be completely manual? I can see examples of that being useful but also would be great to see some statuses being applied automatically (e.g. hitting "submit" in the submission makes the status to be "submitted")

**Comment by gabsie** [comment]
Hi, everyone

Just to repeat the things from @ESapenaVentura and Claire, let's, if possible, have the statuses read like we had them in the task:
New
Eligible
Not eligible
In progress
Stalled
Submitted
Published in DCP
Deleted

2. @ESapenaVentura - We thought that Deleted would be for anything that for example needed removing from the DCP etc. Yes, supposedly all data and metadata and data for the submission would not be there, but at least we keep a record of the project name, DOI etc, so that we can avoid somebody entering it again or something?

3. @ESapenaVentura - I think for both 'Submitted' and 'Published to DCP' - it would be great to automate that in the future, but we can make new tickets for that?

Gabs

**Comment by gabsie** [comment]
And one more thing... 
I suggest that before somebody has put a priority, we just have N/A and then only 1,2,3 afterwards

One thing I don't know actually, @ESapenaVentura - when you guys keep the triaging info in the data tracker, do you have priority placed alongside eligibility?

Thanks!
Gabby

**Comment by ESapenaVentura** [comment]
@gabsie agree on tickets for that in the future - I was just thinking ahead, don't expect it to be in this iteration!

Also I like the changes a lot! But if I can be very picky, I'd like for the wrangling status and priority to have the same blank state; either you can specify N/A for both or just leave both blank, but not both
