### ISSUE TITLE
File validator assumes anything after a '.' is the extension

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/dcp-ingest-central#324]
**Describe the bug**
> The file validator in ingest assumes anything after a '.' is the extension

**To Reproduce**
1. Go to https://staging.contribute.data.humancellatlas.org/
2. Create a submission which has a metadata file entity, whose name has a '.' in it, e.g. a sequencing file with the name 24905_6#205.cram-1.fastq.gz
3. Sync the files from the hca-util upload area
4. Wait for the files to validate
5. See error

**Expected behavior**
We should be able to upload files with 
> .
 in the names. Instead, the validator is recognizing everything after the first 
>. 
as the file format

**Screenshots / Logs**
![Screenshot 2021-05-20 at 12.42.59.png](https://images.zenhubusercontent.com/5fd74f67b86eb46030b3f4e3/e1627683-be8a-478d-87b2-46f7bfe101e8)

** Links **
https://embl-ebi-ait.slack.com/archives/C016R78CDV1/p1621478679034000

**Comment by Wkt8** [comment]
This affects the submission of this dataset: https://contribute.data.humancellatlas.org/projects/detail?uuid=dc1a41f6-9e09-42a6-959e-3be23db6da56

**Comment by aaclan-ebi** [comment]
![Screenshot 2021-06-21 at 13 14 15](https://user-images.githubusercontent.com/31281398/122763976-dd9e5280-d296-11eb-97e0-29adb8a20ba5.png)
