### ISSUE TITLE
stress test the catalog - 1000 projects in dev db

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#326]

**Comment by amnonkhen** [comment]
The purpose here is to get a feel on the UI's performance when the catalogue is in its full expected load of 800 projects.
We should check:
- [x] ui load time
- [x] search time
- [x] sort time

**Comment by clairerye** [comment]
Include payload size testing with the number of projects

**Comment by jacobwindsor** [comment]
# With 1000 projects

## UI Load Time
- Time to contentful paint: 3.3s (lighthouse reported)
- Catalogue endpoint load time (no throttling): 1.17s
- Catalogue endpoint load time (throttled slow 3g): 21.68s
- Catalogue endpoint load time (throttled fast 3g): 6.73s

## Search Time
- On desktop (no cpu throttling):
  - Responsive when searching and faceting
  - Noticeable lag when going from few projects to manyhttps://images.zenhubusercontent.com/299258791/e8c47159-72ab-46df-9b60-72738e249aab/lag_1.mp4
- On desktop (4x CPU throttling)
  - Very unresponsive, even annoying
  https://images.zenhubusercontent.com/299258791/5316981a-4ab9-4af3-abfa-dfbe42e453ae/lag_2.mp4
- On desktop (6x CPU throttling)
  - As expected, even more unresponsive. Particularly when going from few to many projects
https://images.zenhubusercontent.com/299258791/d2165769-2879-4349-ad12-59eb1558ffbc/lag_3.mp4
- On low budget phone (redmi 9)
  - Similar results to 4x CPU throttling but still usable
  - Bit annoying to search as high CPU load impedes being able to type


## Sort times
Sort times follow a similar pattern to search times. There is very little noticable lag when not throttling is enabled but with 4x, and 6x throttling sorting takes ~1.1s and ~1.9s, respectively.

## JS Performance Profiling
Profiling has been done on the extreme case of filtering to 1 project and then removing the filter to get to 1000 projects. This seems to be where the render blocking JS is most noticeable. Profiling was done with 4x CPU throttling to make results more noticeable although they are still apparent with no throttling.

### 1000 -> 1 project
More than 90% of the execution time for the render blocking task was taken up by actually performing the search (scripting time).

![image.png](https://images.zenhubusercontent.com/5f8d5ed6657f5d56f6792bec/5886608d-49c8-4a31-86d9-c04e8a6a4c4c)

### 1 -> 1000 projects
Both the scripting time and the rendering time increased dramatically. However, close to half of the execution time was taken up from the rendering task.
![image.png](https://images.zenhubusercontent.com/5f8d5ed6657f5d56f6792bec/bfa69a10-e754-482e-a452-52cc016d4194)

# With 500 projects
## UI Load Time
- Time to contentful paint: 1.1 (lighthouse reported)
- Catalogue endpoint load time (no throttling): 0.84s
- Catalogue endpoint load time (throttled slow 3g): 12.03s
- Catalogue endpoint load time (throttled fast 3g): 3.36s

## Search Time
Similar results to 1000 projects but times approximately halved.

## JS Performance Profiling

### 500 -> 1 project
![image.png](https://images.zenhubusercontent.com/5f8d5ed6657f5d56f6792bec/39d49f07-1947-4cd1-8e12-6cb6fc33c9b6)

### 1 -> 500 projects
![image.png](https://images.zenhubusercontent.com/5f8d5ed6657f5d56f6792bec/d8262cb2-8039-4933-bdcd-c084bd2cf38d)

# Verdict
The time to load the catalogue endpoint is poor but satisfactory and can be rectified by using server side pagination and querying. The large performance bottle neck at the moment is the JS execution and rendering times when searching/faceting. The rendering times can be improved by introducing client side pagination. Search times can be improved by moving querying to the server. UX improvements, without moving search to the server, could be done by moving the search into a promise, making it into a microtask, and adding a loading indicator to the table. Alternatively, [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) could be used for a similar but enhanced effect.

**Comment by amnonkhen** [comment]
Thanks.How do the numbers look with 500 projects? On Jun 7, 2021 22:26, Jacob Windsor ***@***.***> wrote:
Testing done with 1000 projects
UI Load time
Time to contentful paint: 3.3s (lighthouse reported)Catalogue endpoint load time (throttled slow 3g): 21.68sCatalogue endpoint load time (throttled fast 3g): 6.73s
Search time

**Comment by jacobwindsor** [comment]
@amnonkhen See updated comment above

**Comment by clairerye** [comment]
@amnonkhen and I agreed this was not a problem. It would be nice to have a loading whirly to help communicate its loading, which I will make a separate ticket for.
