### ISSUE TITLE
Ingest UI stuck in Loading state when submission does not exist

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#330]
**Ingest UI stuck in Loading state when submission does not exist**
> Ingest UI stuck at the loading message and not telling the user that the required submission could not be found.

**Steps to reproduce the behaviour**:
1. Log in to Ingest UI
2. Type a non existent submission URL to the browser like this: https://contribute.data.humancellatlas.org/submissions/detail?uuid=12345678-6938-4f73-b7e7-3eb5e016f80b&project=7b947aa2-43a7-4082-afff-222a3e3a4635

**Expected behavior**
> A message stating that the required/specified submission is not found/exists.

**Screenshots / Logs**
![Screenshot 2021-05-27 at 11.32.54.png](https://images.zenhubusercontent.com/5f2957fd448645a503a32777/5c2baeb1-3b6f-467c-9a64-b1625ec14acc)

**Comment by amnonkhen** [comment]
closing, has not resurfaced since creation
