### ISSUE TITLE
Investigate sporadic docker dind issues in GitLab

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#331]
Occasionally, docker fails in the gitlab runner (see https://gitlab.ebi.ac.uk/hca/ingest-core/-/jobs/455800). 

Error: 
```
Pulling docker image docker:stable ...
ERROR: Preparation failed: Error: No such image: docker:stable (executor_docker.go:195:0s)
```

**Comment by amnonkhen** [comment]
@jacobwindsor Has this happened recently? Is there a reason to keep this open?

**Comment by jacobwindsor** [comment]
Closing this as doesnt happen since we moved to our own gitlab runners
