### ISSUE TITLE
Add google analytics to Project Catalogue

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#335]
put the google analytics into the project catalogue

**Comment by ke4** [comment]
Instructions from @jacobwindsor (Thanks):

1. Go to an older version of the project in github, like this: https://github.com/ebi-ait/projects-index/tree/331f1e727cfcf38e1a65e9242877853e35cbadbb
2. Copy the `scripts` tags for Google Tag manager from `index.html` to the latest `index.html`
`
    <script>
      dataLayer = [];
    </script>
    
    <script>
      (function (w, d, s, l, i) {
        w[l] = w[l] || [];
        w[l].push({ "gtm.start": new Date().getTime(), event: "gtm.js" });
        var f = d.getElementsByTagName(s)[0],
          j = d.createElement(s),
          dl = l != "dataLayer" ? "&l=" + l : "";
        j.async = true;
        j.src = "https://www.googletagmanager.com/gtm.js?id=" + i + dl;
        f.parentNode.insertBefore(j, f);
      })(window, document, "script", "dataLayer", "GTM-P72BXLR");
    </script>
    


3. Copy push event for `dataLayer` from the `js/component/project-list.riot` file

``
window.dataLayer.push({
                    event: "search_projects",
                    search_term: val,
                    search_projects_term_and_uuids: `term: ${val}, results: ${this.state.data.slice(0, LIMIT).map(dataPoint => dataPoint.uuid).join(",")}`,
                    search_projects_term_and_titles: `term: ${val}, results: ${this.state.data.slice(0, LIMIT).map(dataPoint => dataPoint.project_core.project_title).join(",")}`,
                });
``
We might have to refactor this bit of code according to the new context.

**Comment by ke4** [comment]
Step 2 is already exists in the current code ;-)
