### ISSUE TITLE
Cannot view project in Safari, console logs has errors

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#336]
**Describe the bug**
Cannot view project in Safari, console logs has errors

**To Reproduce**
1. Go to All projects
2. Click on 1 project to view the project details
3. The project details is not loaded
4.  Open the developer console, there are errors logged.

**Expected behavior**
The project details should be loaded and viewable by the user.

**Screenshots / Logs**
Console error logs:
TypeError: undefined is not an object ( evaluating 'this.config.layout') 

**Environments**
Prod
Safari browser

See screen recording from @MightyAx who reported the issue on slack:
https://embl-ebi-ait.slack.com/archives/C01Q3RMJZ6K/p1622627277036800

**Comment by ke4** [comment]
This project could have the same issue: https://contribute.data.humancellatlas.org/projects/detail?uuid=fc55bd4a-8694-4a28-9a35-59a685bda323

**Comment by yusra-haider** [comment]
this project may have the same issue: https://contribute.data.humancellatlas.org/projects/detail?uuid=a9c022b4-c771-4468-b769-cabcf9738de3 The page fails to load properly and it isn't possible to open the console

**Comment by aaclan-ebi** [comment]
I believe the issue with those 2 projects is different from the issue with Safari browser that Alexie detected. Created a different ticket: https://github.com/ebi-ait/dcp-ingest-central/issues/342
