### ISSUE TITLE
Browser becomes unresponsive when viewing some projects in the Ingest UI

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#342]
**Describe the bug**
Browser becomes unresponsive when viewing some projects in the Ingest UI

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://contribute.data.humancellatlas.org/projects/detail?uuid=fc55bd4a-8694-4a28-9a35-59a685bda323
2. OR to https://contribute.data.humancellatlas.org/projects/detail?uuid=a9c022b4-c771-4468-b769-cabcf9738de3
3. The project details are not loaded and the browser becomes unresponsive

**Expected behaviour**
> The project details should be loaded and viewable by the user.

**Screenshots / Logs**
The developer console can't be opened. 
![Screenshot 2021-06-08 at 10 16 10](https://user-images.githubusercontent.com/31281398/121158908-a1083b00-c842-11eb-887e-3e5c28cfb303.png)

**Comment by aaclan-ebi** [comment]
This seems to happen both in Chrome and Safari.

**Comment by aaclan-ebi** [comment]
Findings so far:

Commenting out this part in the project.component.html will fix the unresponsive browser.
```
 <mat-tab [label]="tabConfig[4].label">
        <div class="vf-u-margin__top--xxl">
          <app-data-table [dataSource]="filesDataSource" [flatten]="true"></app-data-table>
        </div>
      </mat-tab>
```

The file's metadata for some projects might not be being handled well in the data table component. Needs to further investigate.

Assigning to @ke4 as I'll prioritise another ticket. Thanks @ke4 !

**Comment by rays22** [comment]
An additional example of an Ingest project page that is crashing my browser:
* [027c51c6-0719-469f-a7f5-640fe57cbece](https://contribute.data.humancellatlas.org/projects/detail?uuid=027c51c6-0719-469f-a7f5-640fe57cbece)

**Comment by ami-day** [comment]
An additional example:
https://contribute.data.humancellatlas.org/projects/detail?uuid=08b794a0-519c-4516-b184-c583746254c5

**Comment by clairerye** [comment]
and this one [091cf39b-01bc-42e5-9437-f419a66c8a45](https://contribute.data.humancellatlas.org/projects/detail?uuid=091cf39b-01bc-42e5-9437-f419a66c8a45)

**Comment by ami-day** [comment]
Same with this submission: I am able to get to the project page ok and it loads fine, but then when I click the submission to be able to make updates to the metadata, the metadata page won't load properly: https://contribute.data.humancellatlas.org/submissions/detail?uuid=d35d9af6-c532-4944-b520-3ec5ca369dc9&project=2d846095-8a33-4f3c-97d4-585bafac13b4

**Comment by rays22** [comment]
An additional example: [88ec040b-8705-4f77-8f41-f81e57632f7d](https://contribute.data.humancellatlas.org/projects/detail?uuid=88ec040b-8705-4f77-8f41-f81e57632f7d)
