### ISSUE TITLE
Include Cell Count & Extra Fields in the Project Catalogue

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#344]
- [x] Add cell count to project (core)
- [ ] Migration for populating cell count (or Python post-processing script)
- [ ] UI designs for including cell count in the catalogue
- [x] Add cell count to the catalogue 
- [ ] Add filters/facets for cell count
- [ ] Any more fields we would like to visualize in the catalogue?

**Comment by gabsie** [comment]
Hi, Jacob

I will update the designs tonight with showing this in the table.
I will also study the numbers in data tracker, so that I know what the different levels might be for filtering on

Gabs

**Comment by gabsie** [comment]
Jacob, actually for Cell count you only need an extra column in the table for project catalogue, I suggest just before Organ and Technology. Thoughts, @clairerye @ESapenaVentura @rays22 

Gabs

**Comment by clairerye** [comment]
From the meeting we decided it should be an extra column after organ and technology

**Comment by aaclan-ebi** [comment]
How will filtering look like?

**Comment by aaclan-ebi** [comment]
@clairerye @gabsie How big can cell counts be?

**Comment by gabsie** [comment]
Hi, @aaclan-ebi 

Here you can see what those might be:
https://docs.google.com/spreadsheets/d/15imB5HErtY-wWaelnT_gxHRjWXyOQP6iagfPm0hU8sU/edit#gid=1934812232&range=N:N

Gabs

**Comment by aaclan-ebi** [comment]
you could add a project in https://staging.contribute.data.humancellatlas.org/projects/adcb86a4-f685-440e-8c9a-b24ef4171012/project update cell count and that should be reflected in https://wwwdev.ebi.ac.uk/humancellatlas/project-catalogue/

Assigning to @rays22 to do some testing in staging, Thanks @rays22!

**Comment by rays22** [comment]
* I have updated the **cell count** for some of the projects on staging.
* The new cell count values **did show up** in the dev **project catalogue**.

**Comment by aaclan-ebi** [comment]
Thanks for testing @rays22 . The changes were promoted to prod last 12th June. Moving this to Production pipeline.
