### ISSUE TITLE
Introduce the Main nav from VF, for three items - Home / About and Add a Project

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#347]
I think it's a good idea to actually introduce a nav just below the header area, because that way a user doesn't just depend on the links on home for accessing About and Add a project.

The component is in the VF and maybe easy to introduce? We can also remove this sentence already, if we have the navigation. 

Sorry for jumping things on the  sprint, let me know if makes sense! (and certainly this is for after we have the projects in)

Gabs

**Comment by gabsie** [comment]
For a glimpse on how this looks, a nav like this (for us it will be Home  About  Add a Project): ![Screenshot 2021-06-09 at 10.25.57.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/98f35c31-52e7-4216-9913-ac44075de703)

**Comment by jacobwindsor** [comment]
Work for #360 can be combined with this work on the `add-nav` branch @MightyAx
