### ISSUE TITLE
Publication citation and author list in project catalogue

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#348]
- [x] Replace the Author list expandable link with a down arrow -  in Project Catalogue
At the moment, we have an arrow which we put temporarily, but is more like navigating externally, instead of allowing to collapse the info on authors
Can we use a drop arrow like these in the Visual Framework?
https://stable.visual-framework.dev/components/vf-link-list/#vf-link-list--easyist/ 

- [x] Ensure no wranglers are listed as authors

- [x] If no publication is available, there should be a "pre-publication or citation missing" in place of the publication link

- [x] If no publication available then use the contributor list to populate the author list

**Comment by jacobwindsor** [comment]
Removing wranglers from contributors is related to [this PR](https://github.com/ebi-ait/hca-ebi-dev-team/pull/418). We can just use that script (after editing it) to update contributors. However, we need to fix the issue discussed there.

**Comment by jacobwindsor** [comment]
@gabsie I'm not really sure what you mean with the link list. You mean just to change the arrow to the same one there or something more?

**Comment by jacobwindsor** [comment]
We already use contributors to populate the list of authors not the authors of the publication

**Comment by gabsie** [comment]
hi, @jacobwindsor 


in this covid portal page, in the cross references tab, you can see how they use that down arrow. 
for the Publication link, can we also use the external link icon they use, please?
let me know if questions..

https://www.covid19dataportal.org/sequences?crossReferencesOption=all
thanks!

Gabs
