### ISSUE TITLE
Updating metadata JSON via spreadsheet

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#349]

**Comment by amnonkhen** [comment]
# Acceptance Criteria 

## Scenario 1: Changing Accessions*
* Given a spreadsheet 
  * with uuids 
  * and a list of files with no accessions
* when the accessions is added to the spreadsheet
* then the spreadsheet can be uploaded keeping uuids consistent


## Scenario 2: ????
* Given ... 
* when ...
* then ...

**Comment by clairerye** [comment]
Target use case - https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/ebi-ait/hca-ebi-wrangler-central/18


Latest spreadsheet: https://drive.google.com/open?id=1vk5e2yPk6plMnoor1JvcLxzxwUbTmTrs

and
https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/ebi-ait/hca-ebi-wrangler-central/20

**Comment by aaclan-ebi** [comment]
Please note that I'm trying to work on implementation to support the general case. 

* Given a spreadsheet that accurately represents the project in ingest
   * with UUIDs
   * and updated values
* when the spreadsheet is uploaded to Ingest
* update the entities with the relevant changes in the metadata JSON

The use case for updating accessions should be supported with the general case implementation. Reusing the importer logic on how to construct the JSON should be able to support the general case for metadata JSON updates.

**Comment by aaclan-ebi** [comment]
previous title: Simple Bulk Update Scenario - usecase 2 adding accessions to files

I replaced the title with the more generic one.

@clairerye @amnonkhen, FYI.

**Comment by aaclan-ebi** [comment]
All necessary changes for this user story are here:
https://github.com/ebi-ait/ingest-client/pull/19/files
https://github.com/ebi-ait/ingest-broker/pull/15/files
https://github.com/ebi-ait/ingest-ui/pull/102

**Comment by ESapenaVentura** [comment]
I have found a small issue with this feature - Whenever you upload a spreadsheet to update the submission, if there is an error in the spreadsheet (e.g. missing required field `official_hca_publication`), it throws that error but doesn't update and doesn't say anything about any error updating

**Comment by ESapenaVentura** [comment]
I have tested the feature:
- Addition of fields and modification of existing metadata works as intended *
   - *Aside from adding a list object, which adds it as a string instead of as an array
- Deletion of metadata does not work, if I delete the field completely (3 types of fields) ingest does not detect it on upload

All details here: https://docs.google.com/spreadsheets/d/1hf6k7EUw5_l3mZEHVMi-iRZTRtCFyTDS1rOcIXNHBpo/edit#gid=0
