### ISSUE TITLE
Ontology related values are converted into a wrong URL

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#353]

**Comment by rays22** [comment]
I think showing the original field value of the abbreviated IRI (for example, `NCBITaxon:9606`) in Ingest is good enough and it is better than expanding the abbreviated IRI into an incorrect URL.
I am not sure if there was an intended feature in Ingest to expand the IRI to [http://purl.obolibrary.org/obo/NCBITaxon_9606](http://purl.obolibrary.org/obo/NCBITaxon_9606) or not.
