### ISSUE TITLE
export search results to tsv

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#356]
As a user of the catalogue 
I would like to export project search results in a csv format so that I can keep/modify/ add relevant additional info etc 

check out - https://stackoverflow.com/questions/51487689/angular-5-how-to-export-data-to-csv-file

**Comment by amnonkhen** [comment]
As a user of the catalogue 
I would like to export project search results in a textual format (csv, json)

check out - https://stackoverflow.com/questions/51487689/angular-5-how-to-export-data-to-csv-file

**Comment by clairerye** [comment]
What should be included in the download. All fields from the project catalogue and the UUID as a first pass
.

**Comment by gabsie** [comment]
hey people, @MightyAx @jacobwindsor 

I have this as a link above the table for now.
Clicking should automatically download the file to one's computer. Let me know if questions and ignore the old contents within the table

gabs
![export](https://user-images.githubusercontent.com/19713125/122899315-a174fb80-d343-11eb-95ff-ca5f23a435f7.png)

**Comment by MightyAx** [comment]
There's an open question whether the "Unique Key" (aka UUID) column should be moved to the last column. Currently it is the first column so get chosen in the numbers app as a header.

We can actually change the column ordering very easily if a decision is made on this at a later date.
