### ISSUE TITLE
Visual summary of project catalogue contents

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#366]
As HCA stakeholder I want to quickly understand the contents of the HCA project catalogue so that identify trends, patterns, and outliers within HCA data. 

** Acceptance Criteria / Definition of Done **

- [x] total number of projects, cell counts, organs
- [x] representation of organs by project and by cell count
- [x] representation of technology by project and by cell count
- [ ] number of publications over time and cell count over time

I think this should be enough to then ask for feedback at the HCA poster session, but @gabsie did you have any other thoughts?

Thinking this would be a separate tab on the nav menu - say "summary statistics" 

see [PR 67](https://github.com/ebi-ait/projects-index/pull/67)

**Comment by amnonkhen** [comment]
@gabsie please review/suggest/beautify
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/a54e1c7a-6fc7-4b7e-8ac2-5ca6a5fd431a)

**Comment by gabsie** [comment]
Hi, @amnonkhen!

Looks good. Can we please get rid of the heading at the top of the visualisations? We already have 3 instances where we have which page the user is on, and the rest of the pages just display the content on the pages. 

What I can suggest is probably a sentence at the top. Will come up with suggestions :)
Gabs

**Comment by clairerye** [comment]
This is great! - It loads rather strangely though - bits at a time that then move on the page as other bits load, can we changes this? Also is it possible to have the border extend so that the organs/technology fit rather than them being chopped as it makes it hard to read.

![image.png](https://images.zenhubusercontent.com/5e4d068a4ff78267228d27b4/cc66fc71-c926-44e2-8626-ebcd76d9ddc1)
