### ISSUE TITLE
Use JSON mapper in project catalogue

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#367]
Use something like [JSON Object Mapper](https://www.npmjs.com/package/json-object-mapper) in the projects-service of the project catalogue so that we lose some of the duplications and make this slightly more readable

**Comment by amnonkhen** [comment]
@jacobwindsor can you elaborate the need and user value here? (or close, if no longer relevant)

**Comment by jacobwindsor** [comment]
I think we don't need this anymore
