### ISSUE TITLE
Fix exporter "broken pipe" error

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#368]
This is another intermittent issue in the exporter which causes a submission to get stuck at Exporting state.

Please see error details in this ticket.
https://github.com/ebi-ait/hca-ebi-dev-team/issues/429

**Comment by amnonkhen** [comment]
@aaclan-ebi Has this happened recently? When was the last time? How often does this happen?

**Comment by aaclan-ebi** [comment]
Duplicate of #532
