### ISSUE TITLE
Header of About page - changed + text changes

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#372]
hey

can we please get the header text on the About to be as it is on prod
I notice it is now changed on dev.
![Screenshot 2021-06-25 at 17.01.15.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/2f5de458-00e9-4722-a5a4-ef04ae03077c)

Gabs

**Comment by gabsie** [comment]
I will also place some text changes for the page on this ticket here.

**Comment by jacobwindsor** [comment]
Done the about page heading change. Leaving this open for more incoming changes

**Comment by gabsie** [comment]
I have made the changes I think are relevant for now. @jacobwindsor @clairerye 
https://docs.google.com/document/d/1rCRJB5AdOIT1UnLHOJWRXtR6Y2HOisms7WMoF8Di09g/edit?usp=sharing

(I will make this page shorter in the future, but for now this is good!)

**Comment by clairerye** [comment]
LGTM
