### ISSUE TITLE
DCP1 project updates to terra

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#376]
DCP1 projects were not exported/imported through ingest and the GCP staging area to terra, they were exported from the DSS via another GCP staging area to terra.
This means the data files for DCP1 projects do not exist in the staging area used for export/import to DCP2 and so updates for DCP1 projects do not currently make it to terra.

Options to solve this
- ~improve importer to not require data files~
- change exporter to not export file descriptors/file metadata if files are not being exported
- ~copy the files from one GCP staging area to the other and rearrange file structure to match new structure~
- ~change exporter to export to the other GCP staging areas for DCP1 projects - need file rearrangement in that bucket too~
- ~download files from browser, upload and then re-export all data files alongside the metadata~
- implement full DCP2 updates doc

**Comment by clairerye** [comment]
Discussed with Jeff and Drew from the Broad.
**Decision**
**Short term plan** - change the exporter to not export file descriptors/file metadata, test in dev before production
**Long term plan** - implement DCP2 updates spec but scope out some aspects, such as deletions. Timeframe on this tbd

**note:** for testing in dev - we need to export a project get import, delete the project from the staging area, export update (metadata json only) and ask for import

@aaclan-ebi did I miss anything?

**Comment by aaclan-ebi** [comment]
Also noting here the issue on provenance fields that may be affecting other DCP1 datasets https://github.com/ebi-ait/hca-ebi-dev-team/issues/433#issuecomment-877187803

**Comment by ofanobilbao** [comment]
PR needs approval

**Comment by aaclan-ebi** [comment]
This change needed for the exporter not to add schema major and minor version fields for metadata using older schema is deployed in prod. 
https://gitlab.ebi.ac.uk/hca/ingest-exporter/-/pipelines/199822
![Screenshot 2021-10-04 at 18.59.50.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/6124801d-4967-4fdc-9a89-4e3fd4bcf28e)

**Comment by aaclan-ebi** [comment]
When updating a DCP1 dataset, the workaround steps are:
1. Force set a submission from Complete to Valid by sending a PUT request to the `commitValid` link of the submission
2. Delete state tracker pod so K8 will create a new pod, this will trigger state tracker's initialisation which will sync its state from Ingest database will allow transition from Valid -> Submitted -> Exporting. If this is not done state tracker will think that the submission is in `Complete` state and wouldn't set the submission state to the next state.
3. Click submit button again from the UI and check the "Export only metadata" checkbox
or via API by sending a PUT request to submit link with payload ["Export_Metadata"]
4. After the submission is set to Exported. Remove the descriptors and file metadata from the Terra staging area. There is a known issue/limitation in importing projects without data files and any file metadata cannot be updated yet. Hopefully, this will be resolved when we implement the DCP2 specs for updates in collaboration with the Terra Data Import team.

**Comment by aaclan-ebi** [comment]
Trying to do a test run for Tabula Muri's dataset in dev first. There might be other exporter issues and changes needed.
