### ISSUE TITLE
Setup CI/CD for ingest-client

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#385]
GH repo: https://github.com/ebi-ait/ingest-client

**Comment by amnonkhen** [comment]
next time we work on ingest-client we will add the CI/CD

**Comment by MightyAx** [comment]
this has been working since: ebi-ait/ingest-client#48
https://gitlab.ebi.ac.uk/hca/ingest-client/-/pipelines

Although it doesn't run the pipeline automatically (I haven't figured out how to fix that yet)
