### ISSUE TITLE
Show the 'project.ega_accessions' metadata field in Ingest UI.

### ISSUE THREAD

**Issue by rays22** [ebi-ait/dcp-ingest-central#387]

**Comment by clairerye** [comment]
This should be added to the project tab below the other accessions and before the supplementary links, can we please add the dbGaP accession field at the same time too please.

**Comment by rays22** [comment]
@jacobwindsor 
* I have tested the new feature on dev. I can confirm that I can add [EGA accessions](https://data.humancellatlas.org/metadata/dictionary/project/project/#ega_accessions) to projects in Ingest UI.
    * I have noticed that I get a JSON validation error after adding EGA accessions:

> JSON Validation Error
should NOT have additional properties at root of document

* I could not find a new [`project.dbgap_accessions`](https://data.humancellatlas.org/metadata/dictionary/project/project/#dbgap_accessions) field, but that is not a blocker for my current project.

**Comment by clairerye** [comment]
Used as part of release 8
