### ISSUE TITLE
"service unavailable" during dcp demo ( stale token )

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#396]
during the spreadsheet export/import demo on 20/7 there were "service unavailable" messages in the ui. Let's investigate and see how this can be avoided in the future.

<details>
  <summary>Click to see the log</summary>

<pre>
ingest-broker-77d5c97464-qlx5s ingest-broker [app.py:1455 -        log_exception() ] 2021-07-20 15:20:02,763 - broker_app - ERROR - Exception on /submissions/60ec310d-5f5c-4f09-996b-7555e1bb7d12/spreadsheet [GET]
ingest-broker-77d5c97464-qlx5s ingest-broker Traceback (most recent call last):
ingest-broker-77d5c97464-qlx5s ingest-broker   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
ingest-broker-77d5c97464-qlx5s ingest-broker     response = self.full_dispatch_request()
ingest-broker-77d5c97464-qlx5s ingest-broker   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
ingest-broker-77d5c97464-qlx5s ingest-broker     rv = self.handle_user_exception(e)
ingest-broker-77d5c97464-qlx5s ingest-broker   File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
ingest-broker-77d5c97464-qlx5s ingest-broker     return cors_after_request(app.make_response(f(*args, **kwargs)))
ingest-broker-77d5c97464-qlx5s ingest-broker   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
ingest-broker-77d5c97464-qlx5s ingest-broker     rv = self.dispatch_request()
ingest-broker-77d5c97464-qlx5s ingest-broker   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
ingest-broker-77d5c97464-qlx5s ingest-broker     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
ingest-broker-77d5c97464-qlx5s ingest-broker   File "/app/broker/submissions/routes.py", line 18, in export_to_spreadsheet
ingest-broker-77d5c97464-qlx5s ingest-broker     workbook = ExportToSpreadsheetService(app.ingest_api).export(submission_uuid)
ingest-broker-77d5c97464-qlx5s ingest-broker   File "/app/broker/submissions/export_to_spreadsheet_service.py", line 14, in export
ingest-broker-77d5c97464-qlx5s ingest-broker     entity_list = self.data_collector.collect_data_by_submission_uuid(submission_uuid)
ingest-broker-77d5c97464-qlx5s ingest-broker   File "/app/src/hca-ingest/ingest/downloader/data_collector.py", line 10, in collect_data_by_submission_uuid
ingest-broker-77d5c97464-qlx5s ingest-broker     submission = self.api.get_submission_by_uuid(submission_uuid)
ingest-broker-77d5c97464-qlx5s ingest-broker   File "/app/src/hca-ingest/ingest/api/ingestapi.py", line 183, in get_submission_by_uuid
ingest-broker-77d5c97464-qlx5s ingest-broker     search_link = self.get_link_from_resource_url(self.url + '/submissionEnvelopes/search', 'findByUuid')
ingest-broker-77d5c97464-qlx5s ingest-broker   File "/app/src/hca-ingest/ingest/api/ingestapi.py", line 74, in get_link_from_resource_url
ingest-broker-77d5c97464-qlx5s ingest-broker     r.raise_for_status()
ingest-broker-77d5c97464-qlx5s ingest-broker   File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
ingest-broker-77d5c97464-qlx5s ingest-broker     raise HTTPError(http_error_msg, response=self)
ingest-broker-77d5c97464-qlx5s ingest-broker requests.exceptions.HTTPError: 401 Client Error:  for url: http://172.20.37.89:80/submissionEnvelopes/search
ingest-broker-77d5c97464-qlx5s ingest-broker [_internal.py:225 -                 _log() ] 2021-07-20 15:20:02,765 - werkzeug - INFO
</pre>
</summary>
</details>

**Comment by ke4** [comment]
There is another bug.
Here is the log:
<details>
  <summary>Click to see the log</summary>

<pre>
[_internal.py:225 -                 _log() ] 2021-07-22 17:41:21,166 - werkzeug - INFO - 10.40.1.113 - - [22/Jul/2021 17:41:21] "^[[35m^[[1mGET /submissions/60ec310d-5f5c-4f09-996b-7555e1bb7d12/spreadsheet HTTP/1.1^[[0m" 500 -
[app.py:1455 -        log_exception() ] 2021-07-22 17:41:21,312 - broker_app - ERROR - Exception on /submissions/60ec310d-5f5c-4f09-996b-7555e1bb7d12/spreadsheet [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/broker/submissions/routes.py", line 18, in export_to_spreadsheet
    workbook = ExportToSpreadsheetService(app.ingest_api).export(submission_uuid)
  File "/app/broker/submissions/export_to_spreadsheet_service.py", line 14, in export
    entity_list = self.data_collector.collect_data_by_submission_uuid(submission_uuid)
  File "/app/src/hca-ingest/ingest/downloader/data_collector.py", line 19, in collect_data_by_submission_uuid
    raise Exception('There should be a project')
Exception: There should be a project
</pre>
</details>

**Comment by jacobwindsor** [comment]
Tested locally on recently restored DB from prod. UUIDs are submission UUIDs. All were test by changing the project short name and one of the biomaterial names

- ee32b5da-696f-4f65-bf0e-83be66e88122
  - [x] Downloads with updates from UI
  - [x] Updates with updates from spreadsheet
  - No errors in broker
- db5fa8f5-5069-4aa0-a5f9-edc61f9120fd
  - [x] Downloads
  -  **Uploads but does not update**. Changed title but no update. This could be because there is only project info for this submission
- 593e76a2-7809-4e1d-91bc-5312b0f2c96b
  - [x] Downloads
  - **Uploads but causes core to crash**. 
    - Too many requests to the queue/state tracker? Error in core: `MessageSender$AmqpHttpMixinBufferSender ... I/O error on POST request for "http://localhost:8999/state-updates/metadata-documents": Connection refused (Connection refused);`
    - Error in rabbit `caused a channel exception not_found: no exchange 'provide notifications send exchange' in vhost '/'`
    - Restarted ingest core, tried uploading again, and the problem goes away
- 9d34d9f4-ee04-4a18-9765-02c8e9a70e79
  - [x] Downloads
  - [x] Updates
- 13a43a95-5cf4-43a0-abf7-bb1a8e1a3bef
  - [x] Downloads
  - [x] Updates
- 4b822e5a-0889-4afd-ba3b-7250fee29e06
  - **Download fails** Same error as before with upload in core seen in logs. Restarting fixes it

**Comment by jacobwindsor** [comment]
I found another bug! This one I think is to do with the UI

If you upload a change the spreadsheet, and reupload you get an error with console message ERR_UPLOAD_FILE_CHANGED.
