### ISSUE TITLE
 Search projects by uuid by UUID

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#398]

**Comment by amnonkhen** [comment]
Pasting the project uuid in the search box shows the relevant project.

![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/81e60587-78d5-43b8-b4de-262c3894d09e)

**Comment by amnonkhen** [comment]
@ami-day would you please validate that this works as expected?

**Comment by ami-day** [comment]
Yep it works as expected @amnonkhen
