### ISSUE TITLE
metadata schema estimated_cell_count PR

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#400]
[estimated_cell_count PR
](https://github.com/HumanCellAtlas/metadata-schema/pull/1388)
- [x] merge PR to staging
- [x] point ingest staging at the new schema
- [ ] link the UI cell count field to the new schema field
- [x] create a test dataset that has the estimated_cell_count
- [x] Make a PR in the dataset test repo with the test dataset 
- [x] Notify 6 reviewers on slack that test data is available
- [x] promote schema (we can do this without review, see Hannes' comment - I don't think a PR against master is necessary. In the unlikely case that we find issues with the schema changes when we review the test metadata changes, we would do another staging PR with adjustments.) and UI changes to production 
- [ ] migrate projects that have no cell suspension cell count to the new schema
- [ ] migrate existing "cell counts" on the project level to the new estimated_cell_count field in the schema
- [ ] export projects with project level estimated_cell_count fields
 - [ ] identify dcp1 datasets that cannot yet be updated

**Comment by clairerye** [comment]
@ESapenaVentura I think quite a lot of this is now done. Are we waiting on acknowledgement of test data?

**Comment by ESapenaVentura** [comment]
Yep - I have ticked the proper boxes, thanks for tagging me

The schema test PR is here: https://github.com/HumanCellAtlas/schema-test-data/pull/13

It's missing a couple of approvals, should we ping people on slack?

**Comment by clairerye** [comment]
thank you, yes, I reckon we should

**Comment by ESapenaVentura** [comment]
Project schema v 14.3.0 is officially in master - What should be the next steps?

@aaclan-ebi mentioned we need to update the form in the UI

Tagging @clairerye @gabsie @amnonkhen

**Comment by aaclan-ebi** [comment]
The work to update the UI is captured here: https://github.com/ebi-ait/dcp-ingest-central/issues/425
