### ISSUE TITLE
Metadata schema - official_hca_publication

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#401]
[official_hca_publication](https://github.com/HumanCellAtlas/metadata-schema/pull/1396/files) PR

- [x] Decide on whether we want the ? given there are no other ? in the schema (unless I am missing things) Hannes is ok either way, I think we decide, I wanted to wait for @ESapenaVentura 
- [x] Get missing approvals
- [x] merge PR to staging
- [ ] point ingest staging at the new schema
- [ ] link the UI hca publication field to the new schema field
- [x] create a test dataset that has the official_hca_publication
- [x] Make a PR in the dataset test repo with the test dataset
- [x] Notify 6 reviewers on slack that test data is available
- [x] promote schema (we can do this without review, see Hannes' comment - I don't think a PR against master is necessary. In the unlikely case that we find issues with the schema changes when we review the test metadata changes, we would do another staging PR with adjustments.) and UI changes to production
 migrate projects that have no cell suspension cell count to the new schema
- [ ] migrate existing "hca publications" on the project level to the new official_hca_publication field in the schema
- [ ] export projects with project level official_hca_publication field
- [ ] identify dcp1 datasets that cannot yet be updated

**Comment by aaclan-ebi** [comment]
Closing this as the project metadata's new version has been released to prod. But, there are unchecked tasks in the task checklist. I believe these will be captured in the operations/wrangling tasks as we submit new datasets or update existing datasets to use the new project schema version.
