### ISSUE TITLE
Metadata/Data Validation error links in View Submission page bug

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#404]
Reported by Will Sullivan https://embl-ebi-ait.slack.com/archives/C014HMTV0FN/p1627329034020700

> @Claire Rye @Enrique As I’m unsure where else to put this I wanted to bring up an issue with the ingest UI. Currently the red error links at the top of the metadata submission page no longer work. Not sure if this is a known issue but its that way for both Rachel and I.

**Steps:**
1. Go to an invalid submission's page
2. In the metadata/data validation report found next to the Project title
![Screenshot 2021-07-27 at 09.58.47.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/8476d096-493f-4517-be28-3a217d1017d1)
3. Click `1 file missing` link

**Expected Behavior:**
It should activate the `Data` tab and filter to only display invalid files.

**Actual Behavior:**
Nothing happens when you click the link

**Comment by jacobwindsor** [comment]
@ami-day to test in staging

**Comment by Wkt8** [comment]
Tested with errors on biomaterial, protocol and data tabs. Works as expected.
