### ISSUE TITLE
Make it possible to add a dbGAP accession for a project in the project registration form

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#409]
As a data submitter (wrangler or contributor) I want to add a dbGAP accession for a project, so that people can find the data for my project in the correct resource (Project Catalogue or DCP) by its accession.

** Acceptance Criteria / Definition of Done **

* Given there is an option to accept dbGAP accessions when registering a project
* When I enter a dbGap accession
* Then the interface accepts it in a field, and I can see that accession in the HCA project Catalogue and the DCP portal.

Constraint: to be discussed when we review this whether to include a task to add this field to the metadata schema and DCP respectively, and how this will impact the time frames.

**Comment by clairerye** [comment]
hang on, we do have this as part of the schema, it just needs to be added in Ingest UI I believe.
See - https://github.com/HumanCellAtlas/metadata-schema/pull/1366#pullrequestreview-613159160

**Comment by ESapenaVentura** [comment]
Yep, you're right

I don't know how I missed this, my bad

**Comment by clairerye** [comment]
its not you, we missed this dev work at the time

**Comment by jacobwindsor** [comment]
https://github.com/ebi-ait/ingest-ui/pull/117

**Comment by Wkt8** [comment]
Have tested and spoken to Jacob - when registering a new project / editing an existing project - there are options to enter dbGAP accessions. This gets carried through to the Project Catalogue. 

Have also tested that adding the accession in the UI carries over to the metadata schema and spreadsheet. Looks good!

**Comment by gabsie** [comment]
Great stuff
