### ISSUE TITLE
Fix ERR_UPLOAD_FILE_CHANGED

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#413]
When uploading a spreadsheet via the UI for a submission, if you upload a spreadsheet, change it quickly, and re-upload, before getting a response from broker, you will receive an error. This is a bug in the UI and not the broker.

Relates to #396

**Comment by gabsie** [comment]
maybe @gabsie or a wrangler can try this as well on prod and see if possible to reproduce. @gabsie to try first and get in touch with wrangler.
