### ISSUE TITLE
Do bulk updates on the Peng dataset

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#414]
As a wrangler I want to update my dataset so that it has the right accessions.

Make sure that we can update the Peng dataset with the new accessions for runs.
This is also part of the [test plan](https://docs.google.com/spreadsheets/d/1hf6k7EUw5_l3mZEHVMi-iRZTRtCFyTDS1rOcIXNHBpo/edit?usp=sharing).

**Comment by gabsie** [comment]
Make sure that we can update the Peng dataset with the new accessions for runs.
This is also part of the [test plan](https://docs.google.com/spreadsheets/d/1hf6k7EUw5_l3mZEHVMi-iRZTRtCFyTDS1rOcIXNHBpo/edit?usp=sharing).

**Comment by Wkt8** [comment]
This is now complete. See https://contribute.data.humancellatlas.org/submissions/detail?uuid=8f44d9bb-527c-4d1d-b259-ee9ac62e11b6&project=b176d756-62d8-4933-83a4-8b026380262f

There were two submissions made to Peng's dataset. The first was exported. The second is in the 'archived' state. This is the one which has been updated with the new run accessions. 

We are currently waiting for Peng to give us the go ahead for the project to go public before exporting. However, the dataset has been updated with new accessions, so I think we can close this ticket! @gabsie
