### ISSUE TITLE
Could not flatten metadata whose ontology property only requires text

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#415]
**Actual Behavior:**

UI displays the error page because the broker api is returning HTTP 500
![Screenshot 2021-08-11 at 21.33.16.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/aff43c77-8ef4-49dc-a2c2-f5caecee8573)

Broker has error in logs:
```
  File "/Users/aaclan/dev/ait/repos/ingest-client/ingest/downloader/flattener.py", line 16, in flatten
    self._flatten_entity(entity, object_key)
  File "/Users/aaclan/dev/ait/repos/ingest-client/ingest/downloader/flattener.py", line 32, in _flatten_entity
    self._flatten_object(content, row, parent_key=worksheet_name)
  File "/Users/aaclan/dev/ait/repos/ingest-client/ingest/downloader/flattener.py", line 66, in _flatten_object
    self._flatten_object(value, flattened_object, parent_key=full_key)
  File "/Users/aaclan/dev/ait/repos/ingest-client/ingest/downloader/flattener.py", line 70, in _flatten_object
    self._flatten_list(flattened_object, object, parent_key)
  File "/Users/aaclan/dev/ait/repos/ingest-client/ingest/downloader/flattener.py", line 74, in _flatten_list
    self._flatten_object_list(flattened_object, object, parent_key)
  File "/Users/aaclan/dev/ait/repos/ingest-client/ingest/downloader/flattener.py", line 84, in _flatten_object_list
    self._flatten_to_include_object_list_to_main_entity_worksheet(object, flattened_object, parent_key)
  File "/Users/aaclan/dev/ait/repos/ingest-client/ingest/downloader/flattener.py", line 93, in _flatten_to_include_object_list_to_main_entity_worksheet
    flattened_object[f'{parent_key}.{key}'] = SCALAR_LIST_DELIMETER.join([elem[key] for elem in object])
  File "/Users/aaclan/dev/ait/repos/ingest-client/ingest/downloader/flattener.py", line 93, in <listcomp>
    flattened_object[f'{parent_key}.{key}'] = SCALAR_LIST_DELIMETER.join([elem[key] for elem in object])
KeyError: 'ontology'
```

**Steps to replicate:**
1. Restore prod db in the local database
2. Download spreadsheet of the Heart dataset in the production 
http://localhost:4200/submissions/detail?uuid=20a871b4-5684-4630-96bd-146f94debf1c&project=ad98d3cd-26fb-4ee3-99c9-8a2ab085e737

**Expected Behavior**
The spreadsheet is downloaded. Only the text column has 2 values delimited by a pipe.

![Screenshot 2021-08-11 at 21.37.02.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/adea9179-1082-4c92-a412-323340545433)

Notes:
The flattened needs to handle metadata json which has the ontology property value like:

```
"diseases": [
    {
        "text": "hypertension",
        "ontology": "MONDO:0005015",
        "ontology_label": "diabetes mellitus (disease)"
    },
    {
        "text": "Diabetes"
    }
],
```

sample prod metadata: https://api.ingest.dev.archive.data.humancellatlas.org/biomaterials/5f1b0ea3fe9c934c8b835c86

The diseases ontology schema is not requiring only the text and not the other ontology attributes :
https://schema.humancellatlas.org/module/ontology/5.3.8/disease_ontology

**Comment by ke4** [comment]
I tested the fix in dev and we don't have `Service unavailable` error anymore, but we still need to do a small fix as the `||` are still added into the cell's value if there is no value after them.
I attached a screenshoot from the spreadsheet.

![Screenshot 2021-09-02 at 11.26.59.png](https://images.zenhubusercontent.com/5f2957fd448645a503a32777/73eb0067-aeff-4305-933e-c1bacf122ee2)

**Comment by ke4** [comment]
Fixes:
- https://github.com/ebi-ait/ingest-client/commit/6249cbc52c18ceae91f0649d2fa7297a8ef60970
- https://github.com/ebi-ait/ingest-client/commit/c95e0794ae08e3d394229216cc8e0d6946531ba6

Tested it by the above mentioned project in production and I was able to download a spreadsheet without the service unavailable error and the spreadsheet looked fine.
