### ISSUE TITLE
EGA/dbGaP accessions to show correctly in the project catalogue

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#418]
As wrangler I want to the EGA accessions to show up correctly in the project catalogue so that we can link to the data

Since updating the schema to support EGA and dbGaP accessions we no longer use the supplementary links field to capture these.
We need to change the catalogue to use the correct accession field and also migrate the current projects (or support both?) 
> * story should be vertical, i.e. bring value to a user, rather than a dev task
> * break story by role, persona, cardinality, so it is small enough to be completed in a sprint

** Acceptance Criteria / Definition of Done **

* Given a project with data in EGA or dbGaP
* When I enter that project into the catalogue via Ingest
* Then the EGA/dbGaP accessions will show correctly in the catalogue
Also
* Given a project with data in EGA or dbGaP 
* That is already in the project catalogue
* Then the EGA/dbGaP accessions will show correctly in the catalogue

**Comment by jacobwindsor** [comment]
https://github.com/ebi-ait/projects-index/pull/74
