### ISSUE TITLE
Wrangling from backlog in backoffice - ability to filter by priority 

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#423]
As a data wrangler who wishes to take another project to wrangle, I want to be able to filter by priority, and select a project with priority number 1.

Acceptance Criteria / Definition of Done

- Given I am in backoffice logged as a wrangler, I can see a filter for priority
- When I filter by priority 1
- Then I get relevant results and can choose a project to wrangle next.

Tasks:

- [ ]  UI design
- [ ]  Backend implementatons
- [ ]  Frontend implementation

**Comment by amnonkhen** [comment]
@gabsie,  few quesstions:

- [ ] do you mean that the sorting be only on the displayed page? or do you want it to reset the paging?
- [ ] Do you want a new "priority column" in the table? or just a priority filter field in the filter row?
- [ ] Do you want to change the default sort from descending update date to sort by wrangling priority?

**Comment by Wkt8** [comment]
Jacob and Amnon to work together on this ticket

**Comment by ofanobilbao** [comment]
This ticket is nearly done. Jacob worked in a related bug and will work on another bug today.

The UI part is done. The visual framework does not support some of the requirements. We can check with Ken

**Comment by ofanobilbao** [comment]
@jacobwindsor and @gabsie to have a chat on this

**Comment by jacobwindsor** [comment]
Closing as being done as part of #426
