### ISSUE TITLE
Triaging from backoffice - ability to filter by different criteria and get relevant results and perform triaging

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#426]
As a data wrangler, I want to be able to filter by criteria such as the below, so that I can get results of eligible projects for the HCA, which I can further triage and assign priority to, and they're ready for wrangling. 

** Acceptance Criteria / Definition of Done **

* Given I am in backoffice logged as a wrangler, I can see filters which are relevant to eligibility criteria and contrubute to the triaging phase 

* When I filter by criteria like:

- [x] HCA publication - when this gets done in ticket 424
- [x] organ
- [x] by access type
- [x] and species
- [x] cell count
- [ ] #474

* Then I get relevant results and can perform triaging.

- [x] UI design

- [x] Backend implementatons

- [x] Frontend implemenatation

**Comment by gabsie** [comment]
Examples of the different kinds of filters we wish to introduce in backoffice, and how this can work:
![Screenshot 2021-08-25 at 15.35.37.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/5eb5ae2f-9e63-451a-8fb2-30c9527846ef)![Screenshot 2021-08-25 at 15.34.12.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/ce89d2c7-96dd-46f2-a9aa-c2fe043b8357)

**Comment by Wkt8** [comment]
Amnon is starting work on this. Gabsie planning to do some design work on this today (which will not stop work).

**Comment by amnonkhen** [comment]
@jacobwindsor created a draft PR for the ui, core to follow today

**Comment by ofanobilbao** [comment]
Jacob is working on this.

**Comment by amnonkhen** [comment]
@jacobwindsor unit testing the server side impl.
@gabs to approve the UX

**Comment by jacobwindsor** [comment]
Waiting for input from @gabsie

**Comment by jacobwindsor** [comment]
https://images.zenhubusercontent.com/299258791/585c8967-3359-45a9-b282-8e5b597e1934/filters.mp4

Video of the functionality for @gabsie @ESapenaVentura @Wkt8 for input if you have it :)

Note the logarithmic scale of cell count: the "step" of the scale increases as you drag. I hope this works well to select cell counts of small numbers up to large numbers with the "approximation" increasing as you increase the scale. Note that you need the checkbox for whether to filter by cell count since many projects do not have cell count specified.

**Comment by ESapenaVentura** [comment]
Looks awesome @jacobwindsor !! I can't wait to see this in production!

About the cell count, I think this is great, and if we find any issues in the future, we can always iterate on this. Having this as a starting point is already an improvement!

**Comment by jacobwindsor** [comment]
This is now on staging and I can move into prod if no more changes need to be made

**Comment by amnonkhen** [comment]
@gabsie to approve

**Comment by gabsie** [comment]
As discussed with @jacobwindsor, let's get this to prod, and we can improve the visual framework elements afterwards.
We can also evaluate its impact, by having Oihane and the wranglers use it
Thanks!
Gabby
