### ISSUE TITLE
Create new processes + update linkings for submission 96e500d8-11e9-4d25-a2e5-817e0628199f

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#429]
Context + some info here https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/416

- [x] Create 10 processes to link specimens with cell suspensions
- [x] Update linking between specimens and cell suspensions
- [x] Have a wrangler (Preferrably Will) look at the linkings
- [x] Export the submission

**Comment by theathorn** [comment]
[Project details](https://data.humancellatlas.org/explore/projects/d3446f0c-30f3-4a12-b7c3-6af877c7bb2d?catalog=dcp9).

**Comment by amnonkhen** [comment]
@ESapenaVentura Is this ticket still needed?

**Comment by ESapenaVentura** [comment]
@amnonkhen I forgot to add the "operations" label so this ticket flew completely under my radar

This is not needed anymore, the issues with that dataset were solved for this past release.

Thanks for the reminder!
