### ISSUE TITLE
JSON Validation Error message on Projects added to Ingest on 27th August 2021

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/dcp-ingest-central#430]
When you click on "View Project" for a Project where "Last Updated" is 27th August 2021, when the project opens, you get an error message that says "JSON Validation Error. Should NOT have additional properties at root of document".

![Screenshot 2021-08-31 at 10.59.17.png](https://images.zenhubusercontent.com/5b6c1d07134f1f42006dc89f/4de0da55-85a8-4bc0-a5ff-f3713b596710)

This does not happen when you try to view a Project that was Updated before that date.

**Comment by ofanobilbao** [comment]
I have linked this ticket that Gabs created, as after conversation with Enrique, it looks like this issue should be resolved once that other issues is dealt with.

**Comment by jacobwindsor** [comment]
https://github.com/ebi-ait/ingest-ui/pull/118

**Comment by amnonkhen** [comment]
@ami-day to verify
