### ISSUE TITLE
Requesting Ingest API's root with a valid token results 401

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#431]
When we send an API request to Ingest API root with a valid JWT token we get an Authentication error response (401).
Example URL: https://api.ingest.dev.archive.data.humancellatlas.org

Expected results:

1. With no auth header -> get response from the root endpoint with JSON payload
2. With valid JWT token in the request header -> get response from the root endpoint with JSON payload
3. With invalid (for example expired) JWT token in the request header -> 401 Authentication error

**Comment by amnonkhen** [comment]
Seems ok to me.
