### ISSUE TITLE
Integration test for archiving from Ingest to BioSamples archive

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#447]
Implement an integration test to archive samples from Ingest to BioSamples archive.
- It needs to use the BioSamples test environment (wwwdev)
- It needs to test the direct archiving approach from Ingest to BioSamples and not via DSP

Test cases:
- [ ] Test a successful sample(s) submission from Ingest to BSD
- [ ] Test when BSD archive's service is down (mock a 500 response from BSD)

**Comment by ke4** [comment]
After some investigation I decided to implement this test in the ingest-integrations-test repository instead of the ingest-archiver.

**Comment by amnonkhen** [comment]
@ke4 to merge to staging/prod

**Comment by ofanobilbao** [comment]
There is a problem with the BioStudies Dev environment. BioStudies team suggested using the Test environment instead. @ke4 will change some config and use the Test environment
