### ISSUE TITLE
Integration test for archiving from Ingest to BioStudies archive

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#448]
Implement an integration test to archive samples from Ingest to BioStudies archive.

It needs to use the BioStudies test environment (wwwdev)
It needs to test the direct archiving approach from Ingest to BioStudies and not via DSP
Test cases:

- [ ] Test a successful sample(s) submission from Ingest to BioStudies
- [ ] Test when BioStudies archive's service is down (mock a 500 response from BioStudies)

**Comment by Wkt8** [comment]
There is a PR for sending data to BioStudies (not integration test), but needs a bit more work (due to merge conflicts) - amnon interested in reviewing

**Comment by amnonkhen** [comment]
@ke4 finished cleanup and merge of previous PR. actual work will start today.

**Comment by ke4** [comment]
BioStudies Test (they call it Beta) environment is not expose to outside the EBI VPN. That means we can't reach it from our ingest-archiver service that is running on AWS. We are going to investigate this issue further with the help of BioStudies team.

**Comment by amnonkhen** [comment]
@ke4 to schedule a discussion about our testing strategy for this project

Also - discussions with BioSturdies team about test env access - in progress

**Comment by ke4** [comment]
BioStudies REST API documentation: https://biostudies.gitbook.io/biostudies-api/

**Comment by amnonkhen** [comment]
meeting with BST about exposing the test env scheduled for today.
Alternative - use a mock server

**Comment by ofanobilbao** [comment]
Karoly tested it on the VPN and got an accession. He did not have any errors but there were some issues with the UI. He entered a 4h loop. Karoly has reached out to them with the issues.

**Comment by Wkt8** [comment]
Karoly to pick up when he is back on development. @amnonkhen and @gabsie to discuss delegating work

**Comment by idazucchi** [comment]
@ke4 started to work on integration tests

**Comment by ESapenaVentura** [comment]
similar outcome to #523, integration test in staging failing

**Comment by ESapenaVentura** [comment]
@ke4 to deploy into production
