### ISSUE TITLE
Add metadata prior to hitting submit

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#45]
## User Story
As a wrangler I would like to add metadata to a submission prior to submitting it when I missed something, currently I have to delete the submission and start again, which is very slow.

## Acceptance Criteria
Provide a way to add a metadata in a submission and revalidate it

**Comment by rays22** [comment]
* As part of the test plan of [Impact 1 - Update metadata and data for a project](https://docs.google.com/spreadsheets/d/1sf_PnPRufEPUeqkADhewJGJsYsb00CBwymKKPFB_VHI/) I did  functional tests:
    - [x] Update Metadata content <https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/45>
        - [x] Update a valid metadata: PASS
        - [x] Update a invalid metadata: PASS

The test `xlsx` and `fastq.gz` sequence files I used for testing can be found in gdrive folder [impact1 test files (xlsx spreadsheets)](https://drive.google.com/drive/folders/1d1YTB2PKXbL9C4CY83e8LZBq72i6Hxv0)

**Comment by clairerye** [comment]
@aaclan-ebi is this now done or do we still need the changes that are blocking this ticket? Sorry, I seem to have got a bit lost here!

**Comment by clairerye** [comment]
closing as complete
