### ISSUE TITLE
Bulk updates should preserve metadata schema versions

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#455]
**Steps to replicate:**
1. Create a project via API with an older version of the project schema. The current latest version of the project metadata schema is 15.0.0. Pick a version older than that. Upload a submission for that project.

or

Pick an existing submission linked to a project with an older version.

2. Download spreadsheet of a submission.
3. Update the project metadata in the spreadsheet. Update any field.
4. Upload the updated spreadsheet.
5. Wait until the project is updated.
6.  Check the version of the project metadata in the `describedBy` field.

**Actual Behavior:**
The project metadata is updated to the latest version 15.0.0.

**Expected Behavior:**
The project metadata version should **NOT** update the project to use the latest version/ `describedBy` field.

**Note:**
Migration of schema versions will be a different update process. It can be a part of the metadata release process or something a user will have to explicitly do. Updating to the latest version can be tricky and can make the metadata invalid esp. if there is a required field and information is not available.

**Bulk updates user story**: ebi-ait/dcp-ingest-central/issues#455

**Comment by aaclan-ebi** [comment]
This is now deployed in dev and staging.  
(staging pipeline)https://gitlab.ebi.ac.uk/hca/ingest-broker/-/pipelines/195322
(dev pipeline) https://gitlab.ebi.ac.uk/hca/ingest-broker/-/pipelines/195317

![Screenshot 2021-09-20 at 15.55.47.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/f74664b7-8ef7-4e3f-8e0d-3ae7e64dd59b)

**Comment by aaclan-ebi** [comment]
Hi @Wkt8, would you be able to verify in `staging` if the issue is fixed? Thanks!

**Comment by Wkt8** [comment]
Will do!

**Comment by Wkt8** [comment]
Testing to make sure that updating via bulk updates does not change the schemas 

Have done the following: 
- [x] Pick an existing submission linked to a project with an older version. (https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=955dfc2c-a8c6-4d04-aa4d-907610545d11&tab=upload)


- [x] Download spreadsheet of a submission.
- [x] Update the project metadata in the spreadsheet. Update any field.
- [x] Upload the updated spreadsheet.
- [x] Wait until the project is updated.
- [x] Check the version of the project metadata in the describedBy field. (Still 14.1.0)

**Comment by aaclan-ebi** [comment]
Thanks @Wkt8 , promoting this to prod now.

**Comment by aaclan-ebi** [comment]
This is deployed in prod and the ingest integration test is passing.

https://gitlab.ebi.ac.uk/hca/ingest-broker/-/pipelines/195322

![Screenshot 2021-09-21 at 12.08.25.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/c1a274ba-6b3a-4a77-aae3-cc4a4cd757dd)

*note: The integration test in staging was already fixed. The staging pipeline triggered yesterday became stale and new pipeline should be run. A new pipeline passed in staging this morning. https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/pipelines/195512
