### ISSUE TITLE
Publications being added to cell lines

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#458]
Due to the new `official_hca_publication` field and the fact that it is always required AND the fact that cell line has publications, any cell lines are invalid because they have a publication with only the `official_hca_publication` field.

**Comment by ami-day** [comment]
assigning myself to test fixes

**Comment by Wkt8** [comment]
![Screenshot 2021-09-20 at 14.36.05.png](https://images.zenhubusercontent.com/5fd74f67b86eb46030b3f4e3/4435f4e1-5927-471d-97c6-82cc6750a864)

Looks good! @jacobwindsor has created a separate ticket #460 for adding the functionality to be able to remove publications from a cell line, but for now, we are able to submit cell lines through ingest once more. 

@ami-day if you want to have a look at a test: https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=8e7dad3d-4ba4-4dec-8af1-67dcc376b96e

**Comment by ami-day** [comment]
It's ok I am testing it on a dataset I am trying to get submitted :) thanks @Wkt8 for testing

**Comment by jacobwindsor** [comment]
https://github.com/ebi-ait/ingest-ui/pull/121 

See conversation in https://github.com/ebi-ait/ingest-ui/pull/121#issuecomment-921911059

**Comment by jacobwindsor** [comment]
#460 opened to fix issues found
