### ISSUE TITLE
[ Broker ] Endpoint to update a submission spreadsheet

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#46]

**Comment by aaclan-ebi** [comment]
This is a temporary solution if we want to keep the spreadsheet up to date with changes done thru UI. Wranglers can manually update the spreadsheet based on the changes they did in the UI form and upload it to where spreadsheets are being stored. (This is a very manual process and not ideal)

We're storing spreadsheets at the moment in case we need to use them when we do bulk updates in the project/dataset post submission. But we're still about to work on the design of how we'll allow users to this.

Ideally, spreadsheets will be generated from the project data. And updates can be done thru those. We can also support bulk updates via the UI.

I'm gonna treat this task with very low priority for now among the sprint tasks.

**Comment by ofanobilbao** [comment]
@aaclan-ebi if I understand correctly when we implemented the bulk updates spreadsheet download/recreation etc made this task no longer needed right? I'll close this issue. Please, re-open if I am missing something and this ticket is still required.

**Comment by aaclan-ebi** [comment]
@ofanobilbao you are right! :D i believe this is no longer needed.
