### ISSUE TITLE
Updating DCP1 datasets submitted to ingest

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/dcp-ingest-central#461]
We have come across a DCP1 dataset wrangled by our team which needs an update as it is missing lane indices to distinguish multiple fastq files per input cell suspension. 
However, currently we are not able to make updates to DCP1 datasets in ingest. We need a way to be able to update DCP1 datasets in ingest.

**Comment by ofanobilbao** [comment]
@ami-day, ticket #376 is trying to cover exactly that. Deleting this ticket as it is a duplication.
