### ISSUE TITLE
Add BioStudies related secrets to HCA's secret manager

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#463]
Add BioStudies username and password to HCA's Secret Manager on AWS.

**Comment by ofanobilbao** [comment]
We need to decide on email address or create a new one.

We need to make sure that the data ownership is assigned correctly to the contributors.

**Comment by ofanobilbao** [comment]
@ke4 to schedule a brief meeting to discuss this

**Comment by amnonkhen** [comment]
@ke4 - started writing SOP. Link: ???

**Comment by ke4** [comment]
PR for SOP: https://github.com/ebi-ait/hca-ebi-dev-team/pull/446

**Comment by ke4** [comment]
The actual secret creation is blocked by #468

**Comment by Wkt8** [comment]
Still blocked by #468

**Comment by ke4** [comment]
We only have the credentials for the dev account.
I asked Amnon to request credentials for `prod`, too.
We don't need it for `staging` as we are already using BioStudies test env with our dev and staging env.

**Comment by ke4** [comment]
I registered our hca-archiving-broker-prod@ebi.ac.uk with BioStudies test environment and they sent an email to that address to activate our new account. I am probably not subscribed to that email list, so I need @amnonkhen to help me to access that email list and activate our new account.

**Comment by ke4** [comment]
Yesterday BioStudies flowed my account with 400 emails :-( regarding all the submissions I made in their submission portal.
Amongst them there was the email response for our registration with the HCA DEV user, but the activation link in their email was only a plain text instead of a link, so I could not activate our user.
I notified them about this issue and I am waiting for their response.

**Comment by ipediez** [comment]
still waiting for biostudies response

**Comment by ke4** [comment]
I sent a message them today to notify them we are still waiting for their reply.

**Comment by ke4** [comment]
I am also waiting for @amnonkhen to get the account/email for production usage.

**Comment by idazucchi** [comment]
there is already a prod user

**Comment by amnonkhen** [comment]
mailbox: hca-archiving-broker-prod@ebi.ac.uk
[view all messages on RT](https://helpdesk.ebi.ac.uk/Search/Results.html?Query=Queue%20%3D%20%27hca-archiving-broker-prod%27%20AND%20Status%20%3D%20%27__Active__%27)

**Comment by Wkt8** [comment]
No longer in waiting, will be picked up when Karoly is back on dev

**Comment by prabh-t** [comment]
Karel added and deployed new secrets and restarted the apps.
