### ISSUE TITLE
Create an email account for HCA's BioStudies user for each environment

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#468]
We need to create a user for the BioStudies REST API for their TEST and PRODUCTION environment.
These user need the following parameters:
- username
- email address

**Comment by ke4** [comment]
from https://intranet.ebi.ac.uk/article/mailing-lists:
How do I request a new email alias?

If you require an email alias list contact ITSupport@ebi.ac.uk including the following information: 

- Approval by a GTL or their trustees.

- What you would like to call your email alias (e.g. alias@ebi.ac.uk)

- The names of internal staff members who will receive emails to this alias

When to use an email alias:

For internal team/group, project, monitoring/service alerts*.

For temporary email addresses e.g. dc-migration@ebi.ac.uk

When an email should be forwarded to a group of internal people only

*There is another solution called shared mailboxes (beta) where only 1 copy of the email is sent to an internally accessible shared mailbox.  benefit is doesn’t fill up your inbox Please contact itsupport@ebi.ac.uk for more information.

Examples of EMBL-EBI aliases:

comms@ebi.ac.uk

doffice@ebi.ac.uk

associate_directors@ebi.ac.uk

Email aliases are an easy way to have an email sent to a group of internal people and can be quick to set up with no self administration. The same email is forwarded to each member of the alias and there is no moderation.

**Comment by ke4** [comment]
Still waiting for the response from IT

**Comment by amnonkhen** [comment]
I created [ghca-archiving-dev oogle group ](https://groups.google.com/a/ebi.ac.uk/g/hca-archiving-dev) but it is not yet accessible by email. 
Waiting for [itsupport's help](http://helpdesk.ebi.ac.uk/Ticket/Display.html?id=536540)

**Comment by amnonkhen** [comment]
@amnonkhen to poke itsupport for help again.

**Comment by ofanobilbao** [comment]
@amnonkhen had a conversation yesterday with ITsupport. Probably today he will make the request

**Comment by ESapenaVentura** [comment]
@amnonkhen delegated to @tburdett about user creation

**Comment by prabh-t** [comment]
@amnonkhen - no update yet.

**Comment by amnonkhen** [comment]
See [IT ticket](http://helpdesk.ebi.ac.uk/Ticket/Display.html?id=543998)

**Comment by ofanobilbao** [comment]
Amnon sent some details to IT support on Friday. Hopefully will be resolved today

**Comment by idazucchi** [comment]
Still waiting for IT support

**Comment by amnonkhen** [comment]
mailbox details: hca-archiving-broker-dev@ebi.ac.uk
all messages: https://helpdesk.ebi.ac.uk/Search/Results.html?Query=Queue%20%3D%20%27hca-archiving-broker-dev%27%20AND%20Status%20%3D%20%27__Active__%27

**Comment by amnonkhen** [comment]
prod queue name: **hca-archiving-broker-prod**

https://helpdesk.ebi.ac.uk/Search/Results.html?Query=Queue%20%3D%20%27hca-archiving-broker-prod%27%20AND%20Status%20%3D%20%27__Active__%27
