### ISSUE TITLE
A metadata spreadsheet example friendly for a data consumer

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#469]
As a data consumer I want to download a friendly version of the metadata for a project, containing the full amount of the metadata for a project. The assumption we have is that file looks like a metadata csv in one tab, which links the files with the full metadata of the biological entity (cell). 

* Given [assumption]
* When [action]
* Then [outcome]

**Comment by amnonkhen** [comment]
work maintained on #854. Closing this
