### ISSUE TITLE
hca_to_scea script "missing argument"

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/dcp-ingest-central#472]
**Describe the bug**
Running the hca_to_scea script produces the following error: 
`script.py: error: the following arguments are required: -study`
even though the -study argument is included. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the hca-to-scea-tools directory and activate the environment.
```
cd /data/tools/hca-to-scea-tools/hca2scea-backend
source venv/bin/activate
```

2. Run the command
`python3 script.py -s /home/wteh/SCEA/SCEAImmuneRenalCarcinoma.xlsx -id 955dfc2c-a8c6-4d04-aa4d-907610545d11 -c wkt -ac 44 -tt '10Xv2_5' -et differential -f disease -pd 2021-01-27 -hd 2021-05-10 -study SRP166375 -name cs_name --facs `

3. It should output the following error: 
`usage: script.py [-h] -s SPREADSHEET -id PROJECT_UUID -study STUDY
                 [-name {cs_name,cs_id,sp_name,sp_id,other}] -ac
                 ACCESSION_NUMBER -c CURATORS [CURATORS ...] -tt
                 {10Xv1_3,10Xv2_3,10Xv2_5,10Xv3_3,drop-seq,smart-seq,seq-well,smart-like}
                 -et {baseline,differential} [--facs] -f EXPERIMENTAL_FACTORS
                 [EXPERIMENTAL_FACTORS ...] -pd PUBLIC_RELEASE_DATE -hd
                 HCA_UPDATE_DATE
                 [-r RELATED_SCEA_ACCESSION [RELATED_SCEA_ACCESSION ...]]
                 [-o OUTPUT_DIR]
script.py: error: the following arguments are required: -study`

**Expected behaviour**
The script runs successfully and creates a .sdrf and .idf file. 

**Screenshots / Logs**
![Screenshot 2021-10-04 at 16.06.23.png](https://images.zenhubusercontent.com/5fd74f67b86eb46030b3f4e3/b6e02694-9654-428d-8dc6-a910c0a423e8)

**Links**
https://github.com/ebi-ait/hca-to-scea-tools#setting-the-environment-on-ec2

**Environment**
- [x] prod
- [ ] staging
- [ ] dev

**Browser**
- [ ] Chrome
- [ ] Safari
- [ ] IE
- [ ] Other (please specify)

**Comment by Wkt8** [comment]
[https://app.zenhub.com/files/299258791/5f4969ad-38d6-4ce9-ba63-a83509004ba0/download](https://app.zenhub.com/files/299258791/5f4969ad-38d6-4ce9-ba63-a83509004ba0/download)

Attaching spreadsheet for @ami-day to test!

**Comment by ami-day** [comment]
Hi @Wkt8 , this command works for me (generates the idf and sdrf file):

`python3 script.py -s /home/aday/5f4969ad-38d6-4ce9-ba63-a83509004ba0.xlsx -o weis_dataset -id 955dfc2c-a8c6-4d04-aa4d-907610545d11 -ac 46 -c wkt -tt 10Xv2_5 -et differential -f disease -pd 2021-01-27 -hd 2021-05-10 -study SRP166375 --facs`

Does this work for you?

**Comment by Wkt8** [comment]
Yep! Clearly something else fixed the error that we're unaware of!

**Comment by ami-day** [comment]
We have worked out that it is copying and pasting the command-line arguments that causes an error on Wei's laptop. Not specific to this script. Sometimes dashes require writing manually at the cmd-line rather than copy paste.
