### ISSUE TITLE
Ability to find the projects imported through the literature search

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#475]
This is linked to the import from literature search ticket

As [role/persona] I want to [goal] so that [value]

> * story should be vertical, i.e. bring value to a user, rather than a dev task
> * break story by role, persona, cardinality, so it is small enough to be completed in a sprint

** Acceptance Criteria / Definition of Done **

* Given [assumption]
* When [action]
* Then [outcome]

**Comment by yusra-haider** [comment]
As per the sprint kickoff meeting

1. we can add wrangling. notes to the search index
2. we can add a new filter that filers via source

option 1 is the simplest, fastest

currently the script that populates ingest from valentine's db sets wranglingNotes as:

 `Auto imported from nxn db (date the script was run)`

do we want to change the content of wranglingNotes?

which solution do we want to go for?

cc: @gabsie @amnonkhen

**Comment by gabsie** [comment]
Hello!
So, today we had a useful meeting, in which we discussed a few things.
However, as an action point, I had forgotten that we had a status **New!** (which is also not used at the moment). 
The initial idea for New - was that it's for new datasets which are discovered, so this fits perfectly with our scenario. (Thanks Oihane for reminding me)
In this case, let's 
1. Get all the new projects imported with the script with a status **New**, and keep 'New suggestion' for the ones suggested by humans.
2. Additionally, let's set the Project Catalogue showing to OFF or NO etc, 
The idea is to NOT having those projects show up in Catalogue until a wrangler has taken a look at them

cc @yusra-haider @ofanobilbao @ESapenaVentura @amnonkhen @tburdett 

Gabs

**Comment by yusra-haider** [comment]
addressed / added both changes in the PR for https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/382 and tested the changes on my local setup

Moving this ticket to Final Checks

cc: @gabsie @amnonkhen 
@ESapenaVentura  would we need further wrangler testing?

**Comment by yusra-haider** [comment]
merged the PR for https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/382, moving this ticket into in production

**Comment by gabsie** [comment]
This needs testing from @ESapenaVentura , @gabsie 
Gabs

**Comment by Wkt8** [comment]
@gabsie to check
