### ISSUE TITLE
Project metadata form is stuck in loading

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#482]
**Steps to replicate:**
1. Click the create new project button and it'll redirect you to page https://dev.contribute.data.humancellatlas.org/projects/register/autofill
2. Click the link, no DOI yet

**Actual Behavior:**
The user is redirected to the New Project form page but is never loaded successfully.

**Expected Behavior:**
Empty project is loaded.

Browser: Chrome

Env: Happening in dev and prod. 

Workaround: hard refresh the page (cmd + shift + r in mac chrome browser) https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache

Reported by @Wkt8 and @ESapenaVentura  https://embl-ebi-ait.slack.com/archives/C016R78CDV1/p1633686659152800

This issue seems to also happen when loading form with DOI, it may be a different issue but I couldn't replicate it atm. It might be closely related to this loading issue.

**Comment by aaclan-ebi** [comment]
The fix is deployed in staging. Hi @Wkt8 could you verify the fix in staging?

**Comment by Wkt8** [comment]
Tested this in staging by: 
- attempting to create a new project on the staging environment 10 times in a row, each time resulted in no error (expected positive result) 
- attempted to create a new project on the prod environment, immediately resulted in an error (expected negative result)

Seems like it works!

**Comment by jacobwindsor** [comment]
Waiting for #506 to go to prod to promote ths

**Comment by amnonkhen** [comment]
no change
