### ISSUE TITLE
Improve the geo_to_hca script 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/dcp-ingest-central#488]
As a wrangler I want to increase the rate at which I want to wrangle datasets with GEO accessions 

The geo_to_hca script extracts information from a GEO accession and automatically populates a copy of the current hca_template located in https://github.com/ebi-ait/geo_to_hca/tree/master/docs. 

This gives wranglers a head-start by automatically extracting a lot of the useful and laborious information (fastq names, information from SRA accessions, etc.) although there is still some manual curation necessary for ensuring that the information is accurate. 

Task is broadly split into: 
- a list of potential improvements / additional fields we could extract further metadata from in GEO (wrangler work?)
- prioritising and developing those improvements (wrangler and dev) 

**Acceptance Criteria / Definition of Done**

* Given a GEO accession
* When the geo_to_hca script is run 
* Then: 
- I obtain additional fields of information in the generated hca spreadsheet OR 
- I require less manual curation of information in the generated hca spreadsheet

**Comment by amnonkhen** [comment]
See [PR 26](https://github.com/ebi-ait/geo_to_hca/pull/26) from @ami-day

**Comment by gabsie** [comment]
Closing because duplicated in 496
