### ISSUE TITLE
Fix organisation in BioStudies payload

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#500]
Currently we are not populating the organisations part the payload in a way that compatible for the BioStudies UI to process.
See current example: https://wwwdev.ebi.ac.uk/biostudies/studies/S-BSST843
We only have numbers as sup-scripts as the organisations.

Here is an example how it should look like: https://wwwdev.ebi.ac.uk/biostudies/studies/S-EPMC1489022?query=S-EPMC1489022

How to fix it:
Compare the 2 JSON and implement the fix based on the difference.

**Comment by ke4** [comment]
PR created for review: https://github.com/ebi-ait/ingest-archiver/pull/48

**Comment by ESapenaVentura** [comment]
@amnonkhen
