### ISSUE TITLE
Ingest UI stuck in Loading state when trying to Edit a Project from the Project Information page in Safari

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/dcp-ingest-central#501]
**Describe the bug**
> When I try to Edit a Project from the Project Information page in Safari, the UI gets stuck in the Loading state.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'All Projects'
2. Select one project and Click on 'View Project'
3. In the Project Information tab, scroll down to 'Edit'
4. Click 'Edit'

**Expected behaviour**
> The page loads in Edit mode and you can start editing the Project Information.

**Screenshots / Logs**
> ![Screenshot 2021-10-21 at 14.27.20.png](https://images.zenhubusercontent.com/5b6c1d07134f1f42006dc89f/da911d3d-45f4-40bd-a5ff-74c432bb31a5)

**Environment**
- [ ] prod

**Browser**
- [ ] Safari

**Comment by aaclan-ebi** [comment]
This has the same fix as ebi-ait/dcp-ingest-central#482 and that fix is deployed in staging. Hi @Wkt8, could you verify the edit view as well? Thanks!

**Comment by ipediez** [comment]
@Wkt8 to take a look

**Comment by Wkt8** [comment]
Tested in staging: 
- tested by opening up 8 different projects in safari and trying to 'Edit Project' with no errors (expected positive result)
- tested in prod by attempting to 'Edit project', on the second project, encountered the error (expected negative result)

**Comment by jacobwindsor** [comment]
Waiting for #506 to go to prod to promote this

**Comment by ESapenaVentura** [comment]
In prod now!
