### ISSUE TITLE
Creating a Roadmap for direct archiving

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#502]
A document that describe the roadmap to implement the direct archiving to EBI archives would help to see how much work this specific job is involved. 

[see doc](https://docs.google.com/document/d/1rPCsRuC-mDRLffQd_LyoAFftil6wYu8Hif4yBQMvJ0g/edit#)

We can break this job down to a number of phases.
- Phase 1 - replicate what we have now by using DSP

- Phase 2 - Improve brokering to BioStudies by the following features:
  - able to send supplementary files
  - able to distinguish projects (bio studies) by the actual submitter

It also helps to add deadline to specific tasks inside a phase and add a deadline for the end of this job.

**Comment by ke4** [comment]
The roadmap document can be found here: https://docs.google.com/document/d/1rPCsRuC-mDRLffQd_LyoAFftil6wYu8Hif4yBQMvJ0g/edit#
You can go edit/comment it there.

**Comment by aaclan-ebi** [comment]
The roadmap doc is waiting for feedback from wranglers. @gabsie will review it, @ke4 could set up a meeting if needed.

**Comment by ESapenaVentura** [comment]
LGTM

**Comment by gabsie** [comment]
@gabsie still to read this

**Comment by ke4** [comment]
@prabh-t I created this roadmap document for archiving. When you come back from your vacation we could go over and discuss it. After that we can finalise it.

**Comment by ESapenaVentura** [comment]
@ke4 met with @prabh-t yesterday, to meet today again to finish document.

**Comment by ke4** [comment]
@MightyAx This is the ticket for the roadmap document. It is still in Draft as we still have to create tickets for the tasks and discuss them with Prabhat.

**Comment by gabsie** [comment]
This roadmap has been broken down into tasks already.

**Comment by prabh-t** [comment]
@ke4 created all tickets and added an estimate. To have a meeting to discuss plan ahead.

**Comment by prabh-t** [comment]
Part 1 of this is done. May need to split part 2 into a new ticket and close this one.
