### ISSUE TITLE
Feedback on graph validator in ingest

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#519]
Prepare a research plan to evaluate the impact of the graph validator, and how it works for wranglers. 
Aim to trace the next 5 data projects ingested, and test with at least one project with over 800 entities.
2 of US wranglers
2 of ours
present insights for improvements

**Comment by ESapenaVentura** [comment]
@gabsie got feedback session from 2 wranglers 

Targetting the UCSC wranglers next for feedback

**Comment by gabsie** [comment]
@gabsie thinks for now we can close this one - and we are addressing the errors issue. we can open a new ticket afterwards for later feedback.
