### ISSUE TITLE
Add links to a project that is already in the DCP

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#52]
As a wrangler I want to be able to add/edit/remove links within a project that is already part of the DCP so that it is correct and up to date.

Any of the 5 entities within the metadata model need to be correctly linked together, this is tricky to check pre-submission, so human error can mean that these are sometimes linked to the wrong entities or not linked at all.

@mshadbolt can you please link or add the relationships that the entities are allowed to have please? Actually @rays22 is this something you can do? I think Marion has a nice diagram that shows this.

Reasons to add to links after submission, as a result of extra information which has been received post my original submission. An example for these can be:
add more samples and data files, these need to be linked and linked to the original project

Acceptance Criteria
Provide a way to add any links between entities associated with a project or submission that is already in the DCP.
A version history is kept with the record of any additions and the time they were made.
Existing UUIDs remain the same

**Comment by rays22** [comment]
> @mshadbolt can you please link or add the relationships that the entities are allowed to have please? Actually @rays22 is this something you can do? I think Marion has a nice diagram that shows this.

Is it this image
<https://github.com/HumanCellAtlas/metadata-schema/blob/master/docs/images/project_scenario.png>
or another diagram that you are looking for?

**Comment by mshadbolt** [comment]
I don't think I understand what is being requested

**Comment by clairerye** [comment]
The diagram is great @rays22. No action needed @mshadbolt - sorry for the confusing message.

**Comment by clairerye** [comment]
Story sliced the wrong way. Closing, and will re-think this.
