### ISSUE TITLE
Convert HCA project/study to ENA study XML

### ISSUE THREAD

**Issue by prabh-t** [ebi-ait/dcp-ingest-central#523]
Before we submit our project metadata to ENA archive we have to convert our data model to an ENA compatible XML format. ENA's REST API only accept XML as the POST request's content type.

Here is the documentation how to register a study programmatically with ENA: https://ena-docs.readthedocs.io/en/latest/submit/study/programmatic.html
Here is the XSD to use for creating ENA compatible study XML: [ftp://ftp.ebi.ac.uk/pub/databases/ena/doc/xsd/sra_1_5/SRA.study.xsd](ftp://ftp.ebi.ac.uk/pub/databases/ena/doc/xsd/sra_1_5/SRA.study.xsd)

**Comment by ofanobilbao** [comment]
Conversion almost ready. @ke4 asked for advice on slack. He needs input from @tburdett and @ESapenaVentura before continuing. Or he can progress and change later

**Comment by ke4** [comment]
We need to decide what value to use for `center_name` and `alias` attribute for the `STUDY` XML element.
Slack conversation about `center_name`: https://embl-ebi-ait.slack.com/archives/C016R78CDV1/p1636640524114100
Slack conversation about `alias`: https://embl-ebi-ait.slack.com/archives/C016R78CDV1/p1636649052120600

**Comment by ESapenaVentura** [comment]
Merged in dev, staging.

Need to be deployed in production.

Staging integration test failed (May be related to #517), fixing that issue before moving on

**Comment by aaclan-ebi** [comment]
Deployed to prod yesterday.
