### ISSUE TITLE
Fix metadata-schema PR Review (due to unpaid Travis CI subscription)

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/dcp-ingest-central#525]
**Describe the bug**
Travis CI failing on PRs

Happening in this PR: https://github.com/HumanCellAtlas/metadata-schema/pull/1427

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://github.com/HumanCellAtlas/metadata-schema/pull/1427 
2. Scroll down to the bottom of the PR 
3. See error pullapprove — Travis CI tests must pass before review starts

If you login to travis with your GitHub account you can see why it has stopped working here:
https://app.travis-ci.com/github/HumanCellAtlas/metadata-schema/requests
 ![Screenshot 2022-06-30 at 10.43.15.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/dc03c3d7-c133-4df4-81ce-199b26a4c4e9)
Because **Owner HumanCellAtlas does not have an active subscription**,

**Expected behaviour**
Automatically run on the PR branch:
- [ ] python schema linting
    - `python ./schema_linter.py`
- [ ] node tests
    ```bash
    cd tests
    npm install
    npm test
    ```
- [ ] Block PR merge on failure
- [ ] Report success/failue to slack

**Comment by ESapenaVentura** [comment]
@jacobwindsor to take a look into this

**Comment by MightyAx** [comment]
Initial idea was to migrate to gitlab but I think that would require moving the [metadata-schema](https://github.com/HumanCellAtlas/metadata-schema) repository from the [HumanCellAtlas](https://github.com/HumanCellAtlas) GitHub organisation to our [ebi-ait](https://github.com/ebi-ait), and is probably overkill.

Considering we just need to run a python script and node npm tests:
**The next step is to investigate wether we can migrate to GitHub Actions.**

**Comment by ofanobilbao** [comment]
@MightyAx to open a new PR. Ida also ok if Alexie adds to her PR

**Comment by gabsie** [comment]
This has been fixed yesterday --
