### ISSUE TITLE
Convert HCA biomaterials to ENA sample XML

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#527]
Before we submit our biomaterial metadata to ENA archive we have to convert our data model to an ENA compatible XML format. ENA's REST API only accept XML as the POST request's content type.

Here is a general documentation on ENA samples: https://ena-docs.readthedocs.io/en/latest/submit/samples.html
Here is the documentation how to register a sample programmatically with ENA: https://ena-docs.readthedocs.io/en/latest/submit/samples/programmatic.html
Here is the XSD to use for creating ENA compatible sample XML: [ftp://ftp.ebi.ac.uk/pub/databases/ena/doc/xsd/sra_1_5/SRA.sample.xsd](ftp://ftp.ebi.ac.uk/pub/databases/ena/doc/xsd/sra_1_5/SRA.sample.xsd)

**Comment by ke4** [comment]
I had a discussion with @ESapenaVentura how to map the biomaterial's attributes to ENA sample's attributes. I am working on a draft model for now and we could improve it later if I accidentally skipped some attributes.

**Comment by Wkt8** [comment]
ENA file structure is more flat than ours. Karoly is working on a draft model including mappings for wranglers to review. 
- will check current archiving to DSP (via ENA) but... that might not be that helpful. As DSP creates the objects.

**Comment by ESapenaVentura** [comment]
Waiting on outcome of #615

**Comment by ke4** [comment]
PR ebi-ait/ingest-archiver#69

**Comment by gabsie** [comment]
Needs another review @amnonkhen
