### ISSUE TITLE
Submit ENA sample(s) XML

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#528]
After we converted the HCA biomaterial to an ENA sample XML we need to send it to ENA to be able to store it in that archive.
To be able to send an ENA sample XML or any other ENA object(s), we also need an accompanying submission XML in a separate file. We need to name this file to `submission.xml`.

Here is the documentation from ENA how to do it: https://ena-docs.readthedocs.io/en/latest/submit/samples/programmatic.html

**Comment by aaclan-ebi** [comment]
@ke4 started this again and will continue work today.

**Comment by ipediez** [comment]
@ke4 to continue working today

**Comment by yusra-haider** [comment]
@ke4 refactoring the code (conversion and submitter flow). @ke4 to discuss with @prabh-t regarding the refactoring and potential side effects.

**Comment by ipediez** [comment]
Amnon and Alegria reviewed it and @ke4 is still working on it. Almost finished.

**Comment by ke4** [comment]
Finished applying all the suggestions from @aaclan-ebi and @amnonkhen in the PR: https://github.com/ebi-ait/ingest-archiver/pull/71 and waiting their approval.

**Comment by Wkt8** [comment]
Need approval from @amnonkhen
