### ISSUE TITLE
Convert HCA experiment data to ENA experiment and run XML

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#529]
Before we submit our experiment metadata to ENA archive we have to convert our data model to an ENA compatible experiment and run XML format. ENA's REST API only accept XML as the POST request's content type.

Here is a general documentation on ENA Raw read submission: https://ena-docs.readthedocs.io/en/latest/submit/reads.html
Here is the documentation how to register an experiment and run programmatically with ENA: https://ena-docs.readthedocs.io/en/latest/submit/reads/programmatic.html
Here is the XSDs to use for creating ENA compatible experiment XML: [ftp://ftp.ebi.ac.uk/pub/databases/ena/doc/xsd/sra_1_5/SRA.experiment.xsd](ftp://ftp.ebi.ac.uk/pub/databases/ena/doc/xsd/sra_1_5/SRA.experiment.xsd) and run XML: [ftp://ftp.ebi.ac.uk/pub/databases/ena/doc/xsd/sra_1_5/SRA.run.xsd](ftp://ftp.ebi.ac.uk/pub/databases/ena/doc/xsd/sra_1_5/SRA.run.xsd)

**Comment by prabh-t** [comment]
Update: Prabhat has started to work on this, and has generated the model classes from the XSDs (for experiment and run XMLs), and now looking at the hca->ena experiment mapping.

**Comment by yusra-haider** [comment]
@prabh-t got some clarification on this from @MightyAx about the historical code context. still in progress.

**Comment by ipediez** [comment]
@ESapenaVentura : this discussion took place before, it might be information available at Google Drive. 
@amnonkhen : this needs a proper discussion with a wrangler. 
@ke4 to organise a meeting

**Comment by Wkt8** [comment]
Meeting organised for today.

**Comment by idazucchi** [comment]
second part of the meeting today

**Comment by aaclan-ebi** [comment]
@prabh-t had a meeting with Karoly and Amnon. @prabh-t to finalise the design/approach.

**Comment by prabh-t** [comment]
PR https://github.com/ebi-ait/ingest-archiver/pull/73

**Comment by jacobwindsor** [comment]
Waiting for @prabh-t to address review comments

**Comment by Wkt8** [comment]
@ke4 and @amnonkhen to review PR again after prabhat makes changes.

**Comment by idazucchi** [comment]
should be able to merge soon

**Comment by prabh-t** [comment]
Reviewed, comments addressed, merged to dev.
