### ISSUE TITLE
Submit ENA run and experiment XMLs

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#530]
After we converted the HCA experiment to an ENA experiment and run XML we need to send it to ENA to be able to store it in that archive.
To be able to send the ENA experiment and run XML or any other ENA object(s), we also need an accompanying submission XML in a separate file. We need to name this file to `submission.xml`.

Here is the documentation from ENA how to do it:
https://ena-docs.readthedocs.io/en/latest/submit/reads/programmatic.html

**Comment by ofanobilbao** [comment]
Prabhat will be looking into this today. But it is dependant on at least a ticket that is in Code Review.

**Comment by gabsie** [comment]
Almost done, requires more written tests and testing.

**Comment by MightyAx** [comment]
Unit tests are done but testing to the actual archives is in progress.

**Comment by ESapenaVentura** [comment]
@prabh-t to test today

**Comment by prabh-t** [comment]
PR https://github.com/ebi-ait/ingest-archiver/pull/79
