### ISSUE TITLE
graph validation errors for dcp1 dataset

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#534]
@aaclan-ebi  please add some details

**Comment by aaclan-ebi** [comment]
From meeting with @ESapenaVentura , we decided to bypass graph validation for now and create separate ops ticket to run validation on existing submissions. I created an epic ticket in the ops-board for that: https://github.com/ebi-ait/hca-ebi-dev-team/issues/455 

Meeting notes: https://docs.google.com/document/d/1Kd-hNFqwTDOT0-ZHlbBMC0g2wXcJx1jx3JGf5e0vIWM/edit
