### ISSUE TITLE
Scale the graph validator

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#535]
**Problem**

Since only one instance of the graph validator is running, graph validation requests can get stuck in "Pending" for a long time if one run is taking a long time. This is poor UX and the user can actually request multiple graph validation runs leading to a backlog for the same submission. The latter is not so much an issue as the messages will be discarded when the graph validator sees that the submission is in "Validating" state, although there is a chance of some repeated runs.

**Solution 1 (to be decided)**
One thing we could do is scale-up the graph validator. However, I think this might be expensive and probably require a neo4j cluster to keep up.

**Solution 2 (done)**
Another simple option is to introduce a new "Requested" graphValidationState. When in this state, the user cannot request another graph validation run. We should alter core so that core sets the graphValidationState to "Requested" and also alter graph validator so that it can only do runs on those that are in the "Requested" state. Graph validator will then request the transition from "Requested" to "Validating". At least a "Requested" state tells the user something is happening and we can give a message like "This could take some time"

We can do both solutions 1 and 2

See https://docs.google.com/document/d/1fsN_2Ugx-ZXgYOgXlqpUYR8n6sHku9pTSVTz3C5-MZg/edit

**Comment by ipediez** [comment]
@ipediez to test today on staging with @gabsie

**Comment by jacobwindsor** [comment]
Solution 2 has been done and is now in prod. We might not need to do solution 1 depending on usage - we will do #539 first to check requirements
