### ISSUE TITLE
Format of downloadable metadata spreadsheet to follow the format of the uploaded spreadsheet

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#544]
Make the format of this spreadsheet contain row 1-5 from the original metadata template, which has got the user-friendly name, the description, examples, system name and separator line

**Comment by MightyAx** [comment]
@gabsie Can we have your comments on whether this ticket includes styling?
Some examples to prompt discussion:
**Top Example**: spreadsheet with metadata and styling, without data
**Bottom Example**: spreadsheet with data and metadata, without styling
![Screenshot 2022-12-20 at 16.05.41.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/603d85fa-0177-44bd-abdb-5e875dc76a8a)

**Comment by MightyAx** [comment]
Development continues well on ebi-ait/ingest-client#63. No blockers

**Comment by gabsie** [comment]
@amnonkhen and @MightyAx to discuss the next steps and if any support is needed.

**Comment by MightyAx** [comment]
[ebi-ait/ingest-client#63](https://github.com/ebi-ait/ingest-client/issues/63)

The ingest client changes are ready, awaiting approval from @amnonkhen .
While waiting for approval I'll investigate if styling the fields is possible.

**Comment by ESapenaVentura** [comment]
Looks like it's working fine now (in staging), @amnonkhen to test today and maybe to push to prod

Looking to re-upload the spreadsheets that are meant for R24

**Comment by MightyAx** [comment]
The push to production was done, and the R24 spreadsheets were regenerated to have the new format, and this format has been confirmed both:

1. on the terra system
2. downloaded from r24 projects
