### ISSUE TITLE
Consolidate graphValidationState and validationState in submission and metadata entities

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#546]
**User Story**
As a wrangler/contributor,I want entity and submission validation states to reflect the graph validation state.

At the moment, the state of an entity (biomaterial/process/file/protocol) will only show "Valid"/"Invalid"/"Draft" etc when the *metadata* is of that state. It does not consider graph validation. It should show Invalid" when graph is invalid too. The same goes for the submission validation state

**Comment by jacobwindsor** [comment]
Can also improve error reporting when this is done to show graph validation success messages alongside the valid entitites. Something like "This entity is not causing an invalid graph".

**Comment by ami-day** [comment]
Hi @jacobwindsor , I'm just wondering if this task is based on the graph validator as it is on EC2, or whether it has been or is in the process of being integrated into ingest?

**Comment by jacobwindsor** [comment]
@ami-day no, this has nothing to do with the graph validator on EC2. Besides, I don't think you need to use that anymore

**Comment by ofanobilbao** [comment]
@jacobwindsor to work on this

**Comment by jacobwindsor** [comment]
Assigning @aaclan-ebi and @amnonkhen as primary code reviewers 

https://github.com/ebi-ait/ingest-state-tracking/pull/9
https://github.com/ebi-ait/ingest-core/pull/102
https://github.com/ebi-ait/ingest-ui/pull/143
https://github.com/ebi-ait/ingest-graph-validator/pull/60
https://github.com/ebi-ait/ingest-integration-tests/pull/20

**Comment by jacobwindsor** [comment]
Testing this will involve the following:

## For a metadata valid & graph valid submission
1. Upload the submission
2. Ensure the state shows "Metadata Valid"
3. Ensure you can navigate to the "Validate" tab
4. Trigger validation and watch the transition go between "Graph Validation Requested", "Graph Validating", "Graph Valid"
6. Ensure you can submit

## Metadata invalid
1. Upload the submission
2. Wait for validation and see "Metadata Invalid"
3. Ensure you cannot navigate to the "Validate" tab

## Metadata valid & graph invalid
1. Upload the submission
2. Wait for validation and "Metadata valid" state
3. Navigate to "Validate" tab and trigger validation
4. Ensure you see transitions between "Graph Validation Requested", "Graph Validating", "Graph Invalid"
5. Ensure you can navigate to the error causing entities and see the detailed messages

## Other checks
- [ ] All submissions page works as it always has
- [ ] My projects page works as it always has
- [ ] You can filter by validation states (e.g. "Invalid") in the submission page

**Comment by jacobwindsor** [comment]
### Deployment order 

- ingest-graph-validator
  - [x] dev
  - [x] staging
  - [x] prod
- ingest-core (wait for migration)
  - [x] dev
  - [x] staging
  - [x] prod
- ingest-state-tracking (check logs for failures after deploying)
  - [x] dev
  - [x] staging
  - [x] prod
- ingest-ui
  - [x] dev
  - [x] staging
  - [x] prod
- integration tests
  - [x] dev
  - [x] staging
  - [x] prod

**Comment by aaclan-ebi** [comment]
Waiting for review.

**Comment by aaclan-ebi** [comment]
Waiting for review. @MightyAx will take a look today.

**Comment by MightyAx** [comment]
Done with review.
@jacobwindsor merge it!

**Comment by ESapenaVentura** [comment]
@jacobwindsor to test after stand-up and fix today. @ESapenaVentura to test afterwards

**Comment by ke4** [comment]
There is a PR for the UI, core, state tracker.
There is a related ticket has been created (#578).

**Comment by jacobwindsor** [comment]
@ESapenaVentura to review alongside #578 and #517 in staging

**Comment by ami-day** [comment]
Still testing this

**Comment by ESapenaVentura** [comment]
Going with the tests (The submission was generated with the data here https://github.com/HumanCellAtlas/schema-test-data, submission here https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=558f1636-0ae9-4747-9238-6276f14aa563&project=218a4231-28a0-46f4-b174-8b9901986e98):

## Metadata valid, graph invalid
- Works as intended!! States transitioned from valid metadata, to graph validation requested, to a couple of other steps until "invalid graph"
- Clicked on the hyperlink and showed me only entities that cause invalid graphs

## Metadata valid, graph valid
- After the last step, I corrected the issue (protocols were not connected to anything)
- Tried to cause graph changes (valid) by deleting 2 files to test #517
   - Submission went back to draft, so #517 is working as intended!

## Metadata invalid, graph valid
- Changed a couple of fields on donor `AP1`, saved and ingest re-validated without any issue, pointing out to the proper biomaterial

## Metadata invalid, graph invalid
- Deleted a link to a file to generate an orphaned entity while metadata was still valid and requested graph validation
- Modified AP1 donor to have invalid metadata
- Metadata status overrides graph validation status (expected) and the errors are shown for both (expected), so great!!




## Discovered bugs/weird things noticed (may not even related to the changes)
- After clicking on the hyperlink to show the graph errors, changing the filter to blank takes a very long time to be effective (I was actually writing this down as a bug until I noticed it fixed) (probably same bug as #582)
- Service unavailable error when trying to search for the protocols to link them back, wasn't working and threw me out of the page (but I was still logged in) (#583)
- Protocols page takes ages to load (#582)
- Throws "service unavailable" error intermittently, I checked and I wasn't logged out so I don't know why this is happening (#583)

### Other comments
- I like the greyed out button, but maybe it could change the text? something like "Validation requested" or something like that?
