### ISSUE TITLE
Remove graph validator PyPi package

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#551]
The graph validator doesn't need to be in PyPi and we can remove setup.py, Makefile and other related files

**Comment by ke4** [comment]
I found the following `pypi` related files in this repository (https://github.com/ebi-ait/ingest-graph-validator):
- Dockerfile
- Makefile
- README.md (version image from pypi)
- README.template (a section related to pypi)
- setup.cfg
- setup.py
- version

**Comment by ke4** [comment]
@jacobwindsor I created a new setup.py for the entry point according to this article: https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/.
I tested it and it worked for me.
I also added the missing steps to the README file.

Here is the PR: https://github.com/ebi-ait/ingest-graph-validator/pull/68

**Comment by idazucchi** [comment]
@ke4 and @jacobwindsor to discuss
