### ISSUE TITLE
Write integration test for Download Spreadsheet with metadata link info

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#552]
This should test that linking columns are also in the spreadsheet.

**Comment by ofanobilbao** [comment]
@aaclan-ebi planning on working on this today

**Comment by aaclan-ebi** [comment]
Assigning @ke4 @jacobwindsor  as primary code reviewers

PR: https://github.com/ebi-ait/ingest-integration-tests/pull/19
