### ISSUE TITLE
Don't send empty values in the archiving payload

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#556]
When we are creating the payload for the various archives some of the properties could be empty. Currently we send them as an empty string value. BioStudies changed their implementation and it is causing an error response from their side. Even if Biostudies handle it correctly we should not send empty values in the payload.

Acceptance criteria:
In the JSON payload every key has a meaningful non-empty value.

**Comment by ofanobilbao** [comment]
@ke4 thinks it is a bigger issue than initially anticipated. We can't even archive through DSP. Karoly having a discussion with the BioStudies people, so that they fix it. DSP code is in freeze, so Karoly can't touch it. To take the discussion Offline with BioStudies team

**Comment by ke4** [comment]
Regarding DSP I had a discussion with Ugis and he promised that his team is going to fix this issue as it is a broken contract between the 2 services.

**Comment by ke4** [comment]
I am going to assign @yusra-haider and @jacobwindsor as my PR reviewers. It was a random selection. Don't worry, I am not ready with my PR, yet. :-)

**Comment by Wkt8** [comment]
@ke4 to do some investigation on integration tests as they are failing (possibly due to graph validation)
