### ISSUE TITLE
We need better error reporting/processing for BioStudies archiving

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#557]
We need to process the error response as well as the success response. Currently we don't do anything with the response that is not a success. That is bad. At least we need to log the error message that came from the archive.

Acceptance criteria:
If we get an error response from the archive we need to report it:
- in our log messages
- report it to the user

**Comment by Wkt8** [comment]
Karoly to continue working on this after integration test investigation.

**Comment by ke4** [comment]
I created a PR that fixes the parsing of the HTTP error response that comes from BioStudies service.
https://github.com/ebi-ait/biostudies-client/pull/4 
After approval I have to incorporate the new version of BioStudies client library to ingest-archiver and do some tiny modification there.

**Comment by aaclan-ebi** [comment]
@ke4 to use the biostudies-client changes in the archiver.

**Comment by ESapenaVentura** [comment]
@ke4 trying to write a test but finding issues with module imports. @amnonkhen will help with this

**Comment by ke4** [comment]
PR: https://github.com/ebi-ait/ingest-archiver/pull/60
