### ISSUE TITLE
Investigate log4j security bug impact on Ingest

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#569]
Check if ingest-core is affected.

**Comment by ke4** [comment]
@amnonkhen has investigated this issue and it looks like we are not effected by this security bug.
@amnonkhen is going to do more investigation today.

**Comment by amnonkhen** [comment]
Investigation scope:
1. research online in [Spring's blog](https://spring.io/blog/2021/12/10/log4j2-vulnerability-and-spring-boot)
According to the blog post, we are not affected as we are using spring boot default logging configuration, that does not use log4j-core, the jar that contains the vulnerable class.

2. search explicitly for log4j-core dependencies in our code 

I used the command:
```bash
./gradlew dependencyInsight --dependency log4j-core
```
to check whether our projects use log4j core.

 I checked:
- ingest-state-tracking
- ingest-core
Both are free from the jar.

3. search generated artefacts for log4j-core jar

*ingest-core*
```
ingest-core git:(dcp-517-debug-link-event) ✗ unzip -l build/libs/ingest-core-0.0.1-SNAPSHOT.jar| grep log
      405  01-28-2021 17:32   BOOT-INF/lib/spring-boot-starter-logging-2.1.6.RELEASE.jar
   290339  01-28-2021 17:32   BOOT-INF/lib/logback-classic-1.2.3.jar
    17522  01-28-2021 17:32   BOOT-INF/lib/log4j-to-slf4j-2.11.2.jar
    66469  01-28-2021 17:33   BOOT-INF/lib/jboss-logging-3.3.2.Final.jar
   471901  01-28-2021 17:33   BOOT-INF/lib/logback-core-1.2.3.jar
   266283  01-28-2021 17:33   BOOT-INF/lib/log4j-api-2.11.2.jar
```

*ingest-state-tracking*
```
  ingest-state-tracking git:(master) ✗ unzip -l build/libs/ingest-state-tracking-0.0.1-SNAPSHOT.jar | grep log
      405  01-28-2021 17:32   BOOT-INF/lib/spring-boot-starter-logging-2.1.6.RELEASE.jar
   290339  01-28-2021 17:32   BOOT-INF/lib/logback-classic-1.2.3.jar
    17522  01-28-2021 17:32   BOOT-INF/lib/log4j-to-slf4j-2.11.2.jar
    66469  01-28-2021 17:33   BOOT-INF/lib/jboss-logging-3.3.2.Final.jar
   471901  01-28-2021 17:33   BOOT-INF/lib/logback-core-1.2.3.jar
   266283  01-28-2021 17:33   BOOT-INF/lib/log4j-api-2.11.2.jar
     5711  12-20-2021 22:14   BOOT-INF/lib/minlog-1.3.0.jar
```

**Comment by ipediez** [comment]
This is done, we are not in risk
