### ISSUE TITLE
Pre-build docker image dependencies for integration tests

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/dcp-ingest-central#571]
Benefits:

- Cleaner logging
- Easier investigation of issues
- *Slightly* quicker integration tests

Get development work to staging quicker.

**Comment by ami-day** [comment]
testing this

**Comment by jacobwindsor** [comment]
This is deployed to the `dev` branch of `ingest-integration-tests` and needs testing

However, the build is failing due an issue with EBIs GitLab runners https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/jobs/672361

**Comment by jacobwindsor** [comment]
Builds are working now but tests are failing now due to bad AWS CLI configuration. I need the correct AWS access keys to move forward

**Comment by jacobwindsor** [comment]
Reverted dcp-571 for now until managed to create a service account in AWS that can be used to run integration tests

**Comment by amnonkhen** [comment]
@jacobwindsor & @amnonkhen to create service account today

**Comment by jacobwindsor** [comment]
We didn't end up creating a service account. @amnonkhen and I gave the service account used by dev cluster the correct permissions. Details are in [this comment](https://github.com/ebi-ait/ingest-kube-deployment/pull/40/files#diff-9ed511e4c6d4bdf9ba5183db443bf0ef23d80e7dd1750a362673bcdc36b97892R37).

Integration tests now run on the previous runner created just for integration tests as well as the new inges-eks-dev runner. You can see the configuration in the Runners section of [this page](https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/settings/ci_cd). The ingest-eks-dev runner is tagged with `ingest-integration-tests` as well as `dind` so the build stage and the testing stages will run on it. The old integration tests runner is only tagged with `ingest-integration-tests` (it doesn't have dind) so will only run the testing stages.

## If something goes wrong while I'm away
@aaclan-ebi @amnonkhen @ke4 @yusra-haider @MightyAx @prabh-t 

You can go back to our previous setup by:

1. revert `4cfdf4b92b396b08eb42e4c785acb49658630e47` on `ingest-integration-tests`
2. Checkout `dcp-260` branch from `ingest-kube-deployment` (or just master if it gets merged)
3. Remove the `ingest-integration-tests` tag from [here](https://github.com/ebi-ait/ingest-kube-deployment/pull/40/files#diff-9ed511e4c6d4bdf9ba5183db443bf0ef23d80e7dd1750a362673bcdc36b97892R41)
4. Re-deploy `gitlab-runner` app

**Comment by aaclan-ebi** [comment]
The integration test changes were merged to staging and prod, I noticed an issue in the changes for prod and fixed it. The environment variable for jwt audience is different in prod. Fixed it here: https://github.com/ebi-ait/ingest-integration-tests/commit/ef032e5d441d37bab2e8669d114f2f276c3fd41c

**Comment by aaclan-ebi** [comment]
I think there's an issue in gitlab config changes, in the build stage. This build job https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/jobs/687810  is pushing an ingest validator image in the integration test pipeline.

**Comment by aaclan-ebi** [comment]
@jacobwindsor posting here the changes I did, https://github.com/ebi-ait/ingest-integration-tests/compare/893aa9b..11d6774 please review once you're back! (don't review now! hope you're enjoying your holidays!)

**Comment by jacobwindsor** [comment]
@aaclan-ebi That looks great thanks for catching that!
