### ISSUE TITLE
"Add/Remove a contributor" buttons showing outside the "Edit" Ingest view

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/dcp-ingest-central#574]
The UI allows adding a contributor in Ingest without first clicking on “Edit project”. This adds a new empty entry that cannot be filled if you are not editing the project. We should we remove this button outside the “Edit” view

Slack: https://embl-ebi-ait.slack.com/archives/C016R78CDV1/p1639413136273200

**Comment by gabsie** [comment]
Linked to 268

**Comment by gabsie** [comment]
Checked - the button is not there :)
