### ISSUE TITLE
Allow filtering by metadata entities that have caused graph validation errors

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#578]
**Story**
As a wrangler, I want to be able to see a summary of metadata entities that have caused graph validation errors and filter by them.

**Background**
After #546, submission states for graph validation have been added. Before #546, the graph validator was setting the validation state of metadata documents to `INVALID`, which, in turn, sets the submission state to `INVALID`. This meant the user could just filter by metadata entities that were invalid because of graph validation errors or metadata validation errors. Now that the graph validation state is included in the overall submission state, setting the overall submission state to `INVALID` after graph validation is not possible due to complications with state transitions. The submission state now transitions to a new `GRAPH_INVALID` state. 

**Technical task**
We don't need a `graphValidationState` on metadata documents as it can only be `VALID` or `INVALID`, hence, the presence of `graphValidationErrors` should suffice. `graphValidationErrors` are removed whenever graph validation is requested.

- [x] Allow filtering by metadata entities that have `graphValidationErrors.length > 0` (core)
- [x] Include a count of entities with `graphValidationErrors` in the submission summary (core)
- [x] Display the new count in the summary (UI)
- [x] Display option to filter by entities with graph validation errors (UI)

**Comment by jacobwindsor** [comment]
PRS:

- https://github.com/ebi-ait/ingest-ui/pull/145
- https://github.com/ebi-ait/ingest-core/pull/103

**Comment by ami-day** [comment]
Testing this

**Comment by ESapenaVentura** [comment]
Tested (see comment on #546), works fine!

I noticed that seems slower than usual to show non-filtered entities, is that normal though?
