### ISSUE TITLE
Creating a temporary script that could trigger direct archiving

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#581]
Creating a temporary script that could trigger direct archiving.
Its parameter would be a submission UUID.
It would be useful for testing the feature.

**Comment by ke4** [comment]
Added 2 PRs to fix some issues with the archiver: 
- https://github.com/ebi-ait/submission-broker/pull/3 - Reviewed and merged
- https://github.com/ebi-ait/ingest-archiver/pull/64 - Under review

When they merged than I can test my script in DEV environment.
If everything is fine with the testing then I can create a PR for the script.

**Comment by ofanobilbao** [comment]
@ke4 needs another reviewer for 64

**Comment by ke4** [comment]
The PR for the archiver triggering script: https://github.com/ebi-ait/ingest-archiver/pull/67 - needs reviews

**Comment by MightyAx** [comment]
@ke4 to give demo today, with readme should be ready for Wrangler Testing.

**Comment by ke4** [comment]
I also organised a meeting for tomorrow (this Thursday afternoon) for the Wranglers to demo it again and help them to understand how to use this script.

**Comment by ke4** [comment]
On the meeting we agreed that @Wkt8 is doing a direct archiving test probably on the staging environment with NOT an SS2 dataset. As I ( @ke4 ) was only tested it with the SS2 dataset.
Thanks a lot for volunteering @Wkt8 !

**Comment by ESapenaVentura** [comment]
@Wkt8 tested and ran into issues. Had a chat with @ke4 and created a bug ticket.

@ke4 to investigate the issue (Possibly related to BioStudies?)
