### ISSUE TITLE
Investigate memory usage spike importing 50k cell suspension dataset

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#590]
Reported by @ipediez on slack:
https://embl-ebi-ait.slack.com/archives/CSDN3M2P5/p1640179375418300

**Steps to replicate:**
1. Create a valid project
2. Create a new submission  by uploading the  spreadsheet. This has 2.8 MB size.
[https://app.zenhub.com/files/299258791/23ff30c1-c77b-4da9-b1b0-621af4a23b05/download](https://app.zenhub.com/files/299258791/23ff30c1-c77b-4da9-b1b0-621af4a23b05/download)

**Actual Behavior:**
1. Ingest UI displays error
2. Ingest Broker pods are being evicted and restarted
3. Grafana shows memory usage spike
![Screenshot 2021-12-22 at 14.02.28.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/5d3be1f8-ad0a-4182-a33b-0fbe293a26a8)

**Expected behaviour:**
Create all entities and linking

**Comment by aaclan-ebi** [comment]
The Tabula Muris dataset which was imported before 2019-07-09 has much more metadata than this dataset: https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/5d24eda088fa640008b02b26/submissionManifest

```
{
"expectedBiomaterials": 53992,
"expectedProcesses": 153822,
"expectedFiles": 199680,
"expectedProtocols": 61,
"expectedProjects": 1,
"actualLinks": 1214782,
"expectedLinks": 1214782,
"totalCount": 407556,
...
}
```

This spreadsheet has the following counts:

```
{
"expectedBiomaterials": 49433,
"expectedProcesses": 49426,
"expectedFiles": 1,
"expectedProtocols": 7,
"expectedProjects": 1,
"actualLinks": 0,
"expectedLinks": 395423,
"totalCount": 98868,
"submissionDate": "2021-12-23T12:58:47.168Z",
...
}
```

**Comment by aaclan-ebi** [comment]
<img width="1423" alt="Screenshot 2021-12-23 at 13 36 03" src="https://user-images.githubusercontent.com/31281398/147248015-703dfaa7-0808-4a97-b733-d9f4388721e5.png">

It seems that memory usage increases as more entities are created. I know we’re storing the whole Ingest API response for every entity created in an entity map object in the importer. We might be able to optimise memory usage by not storing the whole API response.

**Comment by MightyAx** [comment]
@jacobwindsor and @amnonkhen performed an extensive debug session. While it appears that there is a memory leak, we believe the **failure** is a side effect of a denial of service attack.

More investigation required.

**Comment by gabsie** [comment]
Still investigating, but this probably needs wrangler attention when they come back Monday, to understand if the experiment is supposed to be structured this way?
@ESapenaVentura @ipediez @aaclan-ebi

**Comment by aaclan-ebi** [comment]
Even if we optimise the memory usage of importing, the importing may take a long time and the token may expire in the middle. The fix to be able to handle such large spreadsheets isn't trivial but doable and may need more time. 

A workaround that should work in theory is to split the large spreadsheet into multiple spreadsheets/submissions.

**Comment by ipediez** [comment]
@amnonkhen tried to replicate the issue in dev, but it doesn't raise the issue. Needs more investigating. @ipediez to load again the spreadsheet and update @amnonkhen

**Comment by gabsie** [comment]
This doesn't seem like a memory issue, so waiting for the wranglers to decide the scientific decision on these types of datasets.
