### ISSUE TITLE
Pagination when you are on Submission - Biomaterials is not working

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#598]
![Screenshot 2022-01-04 at 17.42.49.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/f81a4a28-b198-4493-89af-cbe5c8ac5cb0)

Please investigate @aaclan-ebi  :P

**Comment by jacobwindsor** [comment]
This has been fixed by #613
