### ISSUE TITLE
Ability to download when the spreadsheet is generated

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#600]
At the moment, when the spreadsheet generation takes a very long time, it encounters a timeout error and the user has no way of getting the spreadsheet. This ticket should provide the ability for the user to download the last generated spreadsheet once it's finished.

This is a pre-requisite of ebi-ait/dcp-ingest-central#555 which will do auto triggering spreadsheet generation so the user won't even have to trigger the download and would allow the user to download the spreadsheet instantly.

This is also related to ebi-ait/dcp-ingest-central#491 which are initial fixes to the UX when downloading the spreadsheet.

**Comment by aaclan-ebi** [comment]
@amnonkhen @gabsie here are the mock-ups https://miro.com/app/board/uXjVOX88PlI=/ 

I'll put the sequence diagram for the implementation design soon.

**Comment by aaclan-ebi** [comment]
```
@startuml
actor User
User -> UI: requests to export submission into spreadsheet download
UI -> Broker: Sends request to generate spreadsheet
Broker -> UI: HTTP 204 Accepted
UI -> User: Gives a message that spreadsheet is being generated
Broker -> Core: get data
Broker -> Core: create a spreadsheet entity which will track the filename/path, timestamp, submission, status
Broker -> Broker: generate the spreadsheet
User -> User: Checks and waits until spreadsheet is available
Broker -> Broker: store spreadsheet in its volume for now, sets spreadsheet entity status as ready for download
UI --> Core: Polls for last generated spreadsheet
User <- UI: Downloads spreadsheet
@enduml
```
![image](http://www.plantuml.com/plantuml/png/RP5DRi9038NtESKx0AXLrHMgAbegjUoGIWvW4fECc9zqx91o-p884bBOZ4Qo_Js_vxaeHMsTpQZG494BnomzcBuYNyuG-QTbKO46y6yJeaBQZJCY9dWOhm7IHAPIQcP56Jfl0vLPlao4znXs76VuPb_AXPLG5NkEf7mzdANkGVbhlLxXwV4PRqN1ZVA5cKiYVfez2mYEHQXYQ4qwsiG8DcnyrKkLL_n5Y3n3bHOcfPj24JdjHYCWUpLwG5UReaPdh8L6AdP7PSRMMFRa-A4XhITGurYKN3Ev2kluLz9M1hK-dZuDhSU99A-3vqNDnKv0laH7HWMjLsF_kwOz6KiRotU4H4FayO178ks3RHrZ6o9yw2OGLhdZ_cm194YbGneOtxpFS1MibLFTakXmXLj_BzFJlJ_E61brpDcNhRD_)

**Comment by ofanobilbao** [comment]
@prabh-t @gabsie @amnonkhen to review

**Comment by ipediez** [comment]
still waiting on the reviews

**Comment by gabsie** [comment]
Hey @aaclan-ebi - Diagram looks great to me!

**Comment by gabsie** [comment]
Alegria can pair up with another dev and talk things a bit more on the design.

**Comment by idazucchi** [comment]
@aaclan-ebi will work on this today

**Comment by aaclan-ebi** [comment]
@aaclan-ebi will continue work today.

**Comment by yusra-haider** [comment]
@aaclan-ebi  had a meeting @gabsie and @amnonkhen to clarify UX flow. This will be carried over for next sprint

**Comment by amnonkhen** [comment]
Alegria to publish PRs for review this morning.

**Comment by aaclan-ebi** [comment]
@gabsie @amnonkhen I updated the miro board of actual screenshots of what I've implemented: https://miro.com/app/board/uXjVOX88PlI=/ 

It changed quite a bit from the original, part of the changes are what we also discussed last Friday and a little more UI touches which I think are helpful. Please let me know if you have comments or anything you want to change.

**Comment by amnonkhen** [comment]
needs PR reviews from devs
needs UI reviews from @gabsie

**Comment by MightyAx** [comment]
Need Review:
https://github.com/ebi-ait/ingest-broker/pull/26
https://github.com/ebi-ait/ingest-client/pull/40
https://github.com/ebi-ait/ingest-core/pull/109

**Comment by ipediez** [comment]
@aaclan-ebi got the reviews and applied the comments, devs to take another look at it

**Comment by aaclan-ebi** [comment]
Hi @ESapenaVentura The changes are all deployed to staging and ready for testing. 
Please check miro board to see the new flow: https://miro.com/app/board/uXjVOX88PlI=/https://miro.com/app/board/uXjVOX88PlI=/

**Comment by ESapenaVentura** [comment]
I have tested the feature:

- With a small dataset, it works great! just as intended
- With a big dataset, I haven't checked yet, but we found a bug ( @aaclan-ebi can give more details on this) related to hitting the button before the submission is fully imported

Just a small comment, I would love to see an option to get an email notification when the spreadsheet generation is finished, but I think that would be part of future improvements!

**Comment by aaclan-ebi** [comment]
Thanks @ESapenaVentura 

Issues:

- [ ] 1 - don't allow user to download while importing/linking - i thought i added this check, i need to verify
- [ ] 2 - exporting causes another user's importing to fail https://github.com/ebi-ait/ingest-broker/pull/32 - awaiting 1 more review
