### ISSUE TITLE
investigate ingest-broker web server hacking attempts

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#601]
Someone is trying to brute force find files with sensitive data using HTTP GET from ingest-broker.

for example:

```
GET /etc/password
```

Analysis of the logs from 24/12 showed that no data had been compromised.

This is a burden on the server and maybe causing temporary service outages like the one described in #590.

See [IT ticket](https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=554302)

We are waiting for IT to suggest possible courses of action.

**Comment by ofanobilbao** [comment]
No data compromised. @amnonkhen involved IT support. It might be related to Irene's insufficient memory issue.

**Comment by amnonkhen** [comment]
IT (Mahmut Ackin) has been running security tests (OWASP top 10) since 10/1. They will continue today. According to the findings we'll decide whether we run them on Prod.

**Comment by prabh-t** [comment]
Amnon - IT still running tests. they haven't found anything yet.

**Comment by Wkt8** [comment]
IT has said no major problems were determined, but minor problems were detected - more information to follow.

**Comment by ESapenaVentura** [comment]
IT sent @amnonkhen a report, there doesn't seem to be anything grave.

@amnonkhen to ask if there is anything we should prioritise

The discussion may be extended to the archiver as @ke4 detected some attacks

**Comment by gabsie** [comment]
Some ideas were sent through by tech services how to protect our server.
