### ISSUE TITLE
Display error properly in the UI when submission is submitted with invalid project

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#607]
**Steps to Replicate** 
1. Create an invalid project
2. Upload integration test spreadsheet - do not update the project
3. Upload the data files
4. Wait for files to be validated
5. Wait for the submission's graph to be valid
6. Submit to HCA

**Actual Behavior**
![Screenshot 2022-01-11 at 11.41.13.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/5913a4d6-4359-413c-ad76-71a3b1b8c9fd)

**Expected Behavior**
Display proper error why submission couldn't be submitted

Related to changes from ebi-ait/dcp-ingest-central#549

**Comment by yusra-haider** [comment]
PR up for review: https://github.com/ebi-ait/ingest-ui/pull/155

**Comment by prabh-t** [comment]
@jacobwindsor to help with testing.

**Comment by Wkt8** [comment]
Jacob to check if in prod.
