### ISSUE TITLE
[ingest-core] 2 submit buttons appearing in the Ingest UI

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#608]
**Steps to replicate:**
1. Upload a spreadsheet with project
2. Upload data files
3. Validate the graph
4. Wait for _Graph Valid_ state
5. Go to Submit tab on the submission's page
6. Tick the _submit to hca_ checkbox

**Actual Behavior**
2 buttons appearing
![Screenshot 2022-01-11 at 11.50.55.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/392f9c4a-67a1-45d1-bfa6-4ebc58bd13e0)

**Expected Behavior**
Only 1 submit button should appear

**Comment by MightyAx** [comment]
It seems the "Submit" button will perform the action for "Submit to HCA" when required (by ticking the HCA box) so we should not need the "Submit to HCA" button anymore.

**Comment by MightyAx** [comment]
Functionality finished in theory, building a test on the dev system.

**Comment by MightyAx** [comment]
Tested:
![dcp-608-submit-button](https://user-images.githubusercontent.com/13031259/150125433-14bb3c80-1b51-421a-be06-b9970bd902de.png)

**Comment by MightyAx** [comment]
Please ignore the above updates to ingest-ui, as this needs to be fixed in Ingest Core:
https://github.com/ebi-ait/ingest-ui/pull/150#pullrequestreview-857128097
> I believe we don't need to change anything in the UI to fix the issue. We need to figure out why the export link is being generated when the state is Graph Valid. By design, the UI will display the link as a button if it's available in '_links'. @aaclan-ebi

**Comment by ipediez** [comment]
Deployed on staging, ready for testing.

**Comment by yusra-haider** [comment]
waiting for wrangler testing @Wkt8

**Comment by Wkt8** [comment]
LGTM!

**Comment by aaclan-ebi** [comment]
Thanks @Wkt8 . This is in prod now.
