### ISSUE TITLE
[Exporter] Write DCP2 exports to project "sub-directories"

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#61]
Raaid has proposed a change to the data-exchange format for new datasets:

Rather than exporting all of our metadata, data, links, and descriptors to /metadata, /data, /links, and /descriptors respectively, we should instead export to a prefix determined by the project being exported.

e.g

Instead of exporting, for example, a donor_organism to gs://staging-bucket/prod/metadata/donor_organism/<uuid>_<version>.json, we should export to gs://staging-bucket/prod/<project-uuid>/metadata/donor_organism/<uuid>_<version>.json

The benefits of this are:

It allows the TDR team to selectively import projects; we just tell them the project UUID and they know where to find all related metadata/data in the staging bucket.
It allows us to straightforwardly wipe all data for a project if needs be
Acceptance criteria:

The staging bucket prefix for exports must be changed from <env> to <env>/<project-uuid>

**Comment by aaclan-ebi** [comment]
Tasks:
[ ] Exporter changes to copy metadata/data to separate project directory
[ ] Move existing exported projects to be in separate directories

**Comment by jacobwindsor** [comment]
https://github.com/ebi-ait/ingest-exporter/pull/10

**Comment by aaclan-ebi** [comment]
Exporter changes are already deployed to staging and is integration tests are passing (Thanks to @jacobwindsor !)
- @ESapenaVentura  could we try doing a test dataset submission in staging and we can verify it? You could also just point us to the spreadsheet and data files, we can do the submission ourselves if ever.

Things in review for the work to move the current staging area files in Terra prod staging area:
1. Steps https://github.com/ebi-ait/hca-ebi-dev-team/tree/task/project-sub-dir/scripts/project-sub-dir
2. PR https://github.com/ebi-ait/hca-ebi-dev-team/pull/351/files 

@ESapenaVentura your go ahead signal for 1 is necessary. Many thanks!!!



Many Thanks!

**Comment by clairerye** [comment]
Great work team! +1 to testing in staging with real data. Thank you!
Also just a thought, does the SOP for exporting need to change at all based on these changes?

**Comment by ESapenaVentura** [comment]
@aaclan-ebi do we need to use a real dataset? or should we use the integration test? it will be easier to check!

Also I just finished reviewing 1!

**Comment by aaclan-ebi** [comment]
We've already tested it for integration test data. :) Maybe a test dataset which is really small, or we could use small dummy data files.

**Comment by aaclan-ebi** [comment]
Thanks for reviewing the steps @ESapenaVentura , I'll apply those and proceed with executing those tomorrow!

**Comment by aaclan-ebi** [comment]
Hi @ESapenaVentura 

I applied the comments you suggested in the steps and ran all those and finished moving the files yesterday. 

(I did run into some issues doing the moving of files because i wasn't very familiar with the `gsutil` commands behaviour but i think it went alright overall, and the file count and file sizes are the same for both directories. I'll put all the execution details in the artifacts shared google drive directory which i'll link later in this ticket)

Here's the bucket locations now. Please review the contents.
  *`gs://broad-dsp-monster-hca-prod-ebi-storage/prod/`  - contains the project subdirectories
  * `gs://broad-dsp-monster-hca-prod-ebi-storage/bk/` - contains the old prod/ data

Many thanks
Alegria

**Comment by ESapenaVentura** [comment]
All the files for each project are now under "prod".

To check, I have generated a <ingest_uuid> : <path_in_staging_area> map and run the following tests:

```
\\ This one checks on every map (per submission) that all files are in the staging area under prod
for i in $( ls | grep staging | grep json);do cat $i | jq -r ' .[] | .[]' | grep  -v "gs://"; done
\\ This one checks that files do belong to their projects
for i in $( ls | grep staging | grep json); do project_uuid=$( jq '.project' $i | jq 'keys[]' | tr -d "\""); cat $i | jq -r ' .[] | .[]' | grep -v $project_uuid;done

**Comment by aaclan-ebi** [comment]
Cool! Thanks @ESapenaVentura ! Requested snapshot from Data Import team 
https://humancellatlas.slack.com/archives/C01360XN04S/p1605272782453000
