### ISSUE TITLE
Submission entities tables are stuck on page 1

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/dcp-ingest-central#613]
**Describe the bug**
In the submission section, for tabs Biomaterials, Processes, Data and possibly Protocols:
The tables displaying the entities do not allow to visualise all entities.
It's impossible to display any page other than the first one: the page counter will change but the table remains frozen on the first 20 entities.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any project with a submission [ex](https://contribute.data.humancellatlas.org/submissions/detail?uuid=3547e529-9963-469e-aaf6-eeaf606530e8&project=2ad191cd-bd7a-409b-9bd1-e72b5e4cce81) 
2. Click on Biomaterials tab
3. At the bottom of the table click to display the next 20 entities
4. See error: the page counter changes but the table is frozen  

**Expected behaviour**
I expect the table's contents to change when I click to display the next 20 entities

**Environment**
- [x] prod
- [ ] staging
- [ ] dev

**Browser**
- [x] Chrome
- [ ] Safari
- [ ] IE
- [ ] Other (please specify)

**Comment by Wkt8** [comment]
This also does not work on the Data and the Processes tab.

**Comment by Wkt8** [comment]
@gabsie this is a bug and the fix needs to be prioritised as it is significant in ingest

**Comment by ESapenaVentura** [comment]
Blocked by #616

**Comment by jacobwindsor** [comment]
PR https://github.com/ebi-ait/ingest-ui/pull/149

**Comment by gabsie** [comment]
Needs reviews and promoting.

**Comment by jacobwindsor** [comment]
This is on staging and ready to test @Wkt8 

- [x] Pagination works as expected on all tabs of submission
- [x] Filtering by validation status works as expected on all tabs of submission

**Comment by Wkt8** [comment]
Pagination and Filtering have been tested on Biomaterials, Processes, and Protocols tab in staging. Works as expected!
