### ISSUE TITLE
Create a document to map HCA biomaterial attributes with ENA sample attributes

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#615]
Biomaterials described by these schemas currently:
- type/biomaterial/3.3.0/imaged_specimen: https://schema.humancellatlas.org/type/biomaterial/3.3.0/imaged_specimen
- type/biomaterial/11.3.0/organoid: https://schema.humancellatlas.org/type/biomaterial/11.3.0/organoid
- type/biomaterial/15.0.0/cell_line: https://schema.humancellatlas.org/type/biomaterial/15.0.0/cell_line
- type/biomaterial/15.5.0/donor_organism: https://schema.humancellatlas.org/type/biomaterial/15.5.0/donor_organism
- type/biomaterial/10.4.0/specimen_from_organism: https://schema.humancellatlas.org/type/biomaterial/10.4.0/specimen_from_organism
- type/biomaterial/13.3.0/cell_suspension: https://schema.humancellatlas.org/type/biomaterial/13.3.0/cell_suspension 

We need to create a document that contains the mapping between a HCA biomaterial attribute and ENA sample attribute.
A mapping entry should contain these values:
- HCA biomaterial attribute's name
- HCA biomaterial attribute's example value
- ENA sample attribute name
- ENA sample attribute's example value
- Submit to ENA (Yes/No)
- Comment
- Approved By

Here is the mapping document: [Mapping HCA biomaterial attributes to ENA sample attributes](https://docs.google.com/spreadsheets/d/18LvAf8wv-yGV552kk0R3SlGf5oEmAyKdKZ2OMk9QMWk/edit#gid=1421951667)

**Comment by ESapenaVentura** [comment]
@ke4 to re-schedule meeting with wranglers to discuss about this

**Comment by ke4** [comment]
Started to create a script to get the attributes, their type and probably other data from the schema and add it to the document. It is quicker than by do it manually.

**Comment by gabsie** [comment]
Script is more or less ready. Wranglers can revise the spreadsheet for next sprint. (Dev ticket?)

**Comment by ke4** [comment]
I updated the document with the biomaterial attribute names and also populated other columns that we send with current archiving to DSP/ direct archiving in phase 1.
https://docs.google.com/spreadsheets/d/18LvAf8wv-yGV552kk0R3SlGf5oEmAyKdKZ2OMk9QMWk/edit#gid=1484105842

**Comment by ke4** [comment]
I also created a PR for the helper script: https://github.com/ebi-ait/ingest-archiver/pull/70

**Comment by ke4** [comment]
ENA XML schema is available to download [here](https://ena-docs.readthedocs.io/en/latest/submit/general-guide/programmatic.html#types-of-xml)

**Comment by idazucchi** [comment]
@ESapenaVentura will write the ticket for the wranglers to review the document
