### ISSUE TITLE
[ingest-ui] Error 137: Gitlab build actions failing

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/dcp-ingest-central#616]
Build actions are [failing for Ingest UI](https://gitlab.ebi.ac.uk/hca/ingest-ui/-/jobs/693102) without reporting a useful error:
I've tried:
- Restarting the job
- Not using the ingest runner so that the task gets picked up by the EBI runners.
    - EBI runners using gitlab runner v13 or above are successful
    - EBI runners using v12 fail or below fail (Opened #617 to investigate later)
    - I have disabled using the EBI gitlab runners for ingest UI for the time being
- Making a change to the [build-release-deploy.yml](https://github.com/ebi-ait/gitlab-ci-templates/commit/32d752957ed28c56cf9b9f68477c08bc3bcb0b8d) to skip the build if a released build already exists for the commit hash (the build worked for the dev deploy, so we should just use that tagged container)
    - [build logs after change](https://gitlab.ebi.ac.uk/hca/ingest-ui/-/jobs/693123)

**Error 137 is associated with Docker Out of Memory errors, this appears to only occur for ingest-ui builds but angular builds do use a lot of memory.**

Initial investigation suggests angular builds using docker may need as much as 4GB of memory

**Comment by jacobwindsor** [comment]
@aaclan-ebi @MightyAx and I seem to have solved this issue by increasing the memory limit of the ingest runners to 4GB.

See [successful pipeline](https://gitlab.ebi.ac.uk/hca/ingest-ui/-/pipelines/232535)

**Comment by gabsie** [comment]
For now this should be sorted.

**Comment by aaclan-ebi** [comment]
It seems that using 4GB limit won't allow us to run tests in parallel, I'm seeing these errors in running the tests:
```
Waiting for pod gitlab-ci/runner-cvkxx73u-project-1900-concurrent-8jtg4s to be running, status is Pending
	Unschedulable: "0/2 nodes are available: 2 Insufficient memory."
Waiting for pod gitlab-ci/runner-cvkxx73u-project-1900-concurrent-8jtg4s to be running, status is Pending
	Unschedulable: "0/2 nodes are available: 2 Insufficient memory."
Waiting for pod gitlab-ci/runner-cvkxx73u-project-1900-concurrent-8jtg4s to be running, status is Pending
	Unschedulable: "0/2 nodes are available: 2 Insufficient memory."
Waiting for pod gitlab-ci/runner-cvkxx73u-project-1900-concurrent-8jtg4s to be running, status is Pending
	Unschedulable: "0/2 nodes are available: 2 Insufficient memory."
Waiting for pod gitlab-ci/runner-cvkxx73u-project-1900-concurrent-8jtg4s to be running, status is Pending
	Unschedulable: "0/2 nodes are available: 2 Insufficient memory."
Waiting for pod gitlab-ci/runner-cvkxx73u-project-1900-concurrent-8jtg4s to be running, status is Pending
	Unschedulable: "0/2 nodes are available: 2 Insufficient memory."
Waiting for pod gitlab-ci/runner-cvkxx73u-project-1900-concurrent-8jtg4s to be running, status is Pending
	Unschedulable: "0/2 nodes are available: 2 Insufficient memory."
```
It seems that it's requesting 4GB for every job and other jobs couldn't run because of it
```
 Namespace                   Name                                              CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                              ------------  ----------  ---------------  -------------  ---
  gitlab-ci                   runner-cvkxx73u-project-1900-concurrent-04k58m    0 (0%)        0 (0%)      4G (59%)         4G (59%)       22s

Allocated resources:
```
