### ISSUE TITLE
EBI Gitlab Runners <v13.0 fail

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/dcp-ingest-central#617]

**Comment by jacobwindsor** [comment]
Contacting Sandeep to see who to talk to

**Comment by jacobwindsor** [comment]
After a brief discussion with Sandeep - the advice from web prod is not to use the EBI shared runners as there are issues with them. In this case, we can see how we go and deploy our k8s implementation to staging cluster as well if needed. 

Alternatively, we can spin up our own "ingest-ops" separate cluster and that won't take resources away from dev or staging.

**Comment by jacobwindsor** [comment]
I have disabled shared runners for all projects
