### ISSUE TITLE
User token expires just about after doing a spreadsheet upload

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#618]
Steps to replicate:
1. Login in the UI
2. After 55 minutes, upload a very big submission

Actual Behavior:
Token will expire and importer will not finish the upload.

Expected Behaviour:
The spreadsheet upload should finish successfully

Notes:
Elixir token only has 1 hr duration
Could be problematic for very huge spreadsheets which will probably not happen since we have a current row limit.

Workaround:
User retries the upload after logging in

**Comment by gabsie** [comment]
needs a design discussion, @aaclan-ebi and @jacobwindsor

**Comment by jacobwindsor** [comment]
This is now ready for testing in staging. Please follow the repro steps in the description

**Comment by ami-day** [comment]
I have tested this, it is working. @jacobwindsor can we close the ticket?
