### ISSUE TITLE
Unable to un-assign primary or secondary wrangler

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/dcp-ingest-central#620]
**Description of the task:**

The project [Multiomics single-cell analysis of human pancreatic islets reveals novel cellular states in health and type 1 diabetes](https://contribute.data.humancellatlas.org/projects/detail?uuid=22eed35e-0062-4c7f-90ed-388e6c29a84f&tab=project) is not wrangleable right now, as it is a pre-print with no data or metadata available at the moment. To avoid this affecting our way of filtering and triaging datasets in Ingest, it would be great to set back the value of the "Primary Wrangler" field to its default. This cannot be done from the UI, where the last value of the field gets automatically assigned when left blank, so a dev action is needed.

**Acceptance criteria for the task:**
- The "Primary Wrangler" field can be set to its "default value"
     - Better put as "Assigned wranglers can be unassigned"?
- The "Secondary Wrangler" field can be set to its "default value"

Other fields that can't currently be un-set, should be resolved by current intended solution:
- Project Information Fields:
    - releaseDate
    - accessionDate
    - dataAccess
    - technology
    - identifyingOrganisms
- Wrangler Admin Fields:
    - primaryWrangler
    - secondaryWrangler
    - wranglingState
    - wranglingNotes
    - dcpReleaseNumber

**Comment by MightyAx** [comment]
Reviewer's: @aaclan-ebi & @yusra-haider

**Comment by MightyAx** [comment]
This issue is 2 fold:
1. there is no interface (clickable) to allow "clearing a wrangler assignment" or "setting the default value" for primary or secondary wranglers.
2. The underlying data for an unassigned project is `primaryWrangler: null`, ingest-ui strips out all null values before sending the data to ingest core.
     - This affects more fields than primary / secondary wrangler and will have to be fixed for those fields too.

**Comment by MightyAx** [comment]
Work in progress solution for problem 1: "there is no interface (clickable) to allow clearing a wrangler assignment":
![Screenshot 2022-01-26 at 17 32 05](https://user-images.githubusercontent.com/13031259/151216312-3161b88a-f7fa-40c3-9864-b07defbf6f5d.png)
![Screenshot 2022-01-26 at 17 32 20](https://user-images.githubusercontent.com/13031259/151216327-17ed67e1-9044-4026-80f0-5038c0b642e0.png)
![Screenshot 2022-01-26 at 17 33 13](https://user-images.githubusercontent.com/13031259/151216337-55b4e2a3-b160-419d-83c7-746b887be063.png)

**Comment by MightyAx** [comment]
Current Sequence Diagram: https://miro.com/app/board/uXjVOSWgtMw=/

**Comment by ipediez** [comment]
@gabsie @ipediez and @ofanobilbao to take a look at the design and the functionality

**Comment by gabsie** [comment]
Hi, @MightyAx - I am good with the designs shown above !

**Comment by MightyAx** [comment]
@ofanobilbao you wanted to know the other fields that can't currently be un-set, that should be resolved by current intended solution:
- Project Information Fields:
    - releaseDate
    - accessionDate
    - dataAccess
    - technology
    - identifyingOrganisms
- Wrangler Admin Fields:
    - primaryWrangler
    - secondaryWrangler
    - wranglingState
    - wranglingNotes
    - dcpReleaseNumber

**Comment by MightyAx** [comment]
Awaiting PR Reviews

**Comment by idazucchi** [comment]
Jacob is reviewing

**Comment by MightyAx** [comment]
Review comments resolved, merged and deployed to dev.
merged to master and deployed to staging.
Will sit with @Wkt8 this afternoon to verify.

**Comment by Wkt8** [comment]
Have sat with @MightyAx and tested it - looks great. Clear, and fulfils what we are trying to do. I think we can put this into production.

**Comment by MightyAx** [comment]
Deployed to Production.
Verified functionality is on production
