### ISSUE TITLE
Provide Visium metadata spreadsheet  in format we are going to get through backoffice

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#623]

**Comment by Wkt8** [comment]
@Wkt8 will do this

**Comment by gabsie** [comment]
Hey, @Wkt8 - let me know when you can put the XLS sheet for the imaging dataset here. I will afterwards let Amnon create the flattened version for it..  :)

**Comment by Wkt8** [comment]
https://docs.google.com/spreadsheets/d/1fBm89rJvvfHODg1u3vtmnRth4VftGqSi/edit?usp=sharing&ouid=114069941208994528669&rtpof=true&sd=true

**Comment by gabsie** [comment]
nice, thanks @Wkt8!

**Comment by amnonkhen** [comment]
@amnonkhen to verify table linking with @Wkt8
