### ISSUE TITLE
Provide spreadsheet in flattened form - to follow from the one for submission

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#624]

**Comment by gabsie** [comment]
Hey @amnonkhen 

@Wkt8 has already supplied a metadata spreadsheet for the first Visium dataset.
Would it be possible to create a flattened version for this file?
https://docs.google.com/spreadsheets/d/1fBm89rJvvfHODg1u3vtmnRth4VftGqSi/edit?usp=sharing&ouid=114069941208994528669&rtpof=true&sd=true
(FYI - this is a real spreadsheet for a real project)

cc @Wkt8 @ipediez if you guys need to advise on how we can show the linking with the new metadata entities (what you consider makes sense)

Let me know if questions. Ideally I would need this by end of today as a first version @amnonkhen  (sorry!)

Gabs

**Comment by gabsie** [comment]
Hey @amnonkhen - spreadsheet is above. Imaging information is in the last 4 tabs. They more or less link the imaged specimens back to a specimen, to a protocol and a file. @Wkt8 can provide more info :) to your other questions.

**Comment by amnonkhen** [comment]
@gabsie @Wkt8 please review
[https://app.zenhub.com/files/299258791/9330eb69-8da3-4883-af08-02ee6921e839/download](https://app.zenhub.com/files/299258791/9330eb69-8da3-4883-af08-02ee6921e839/download)

**Comment by prabh-t** [comment]
Amnon to schedule a mtg with Wei.

**Comment by Wkt8** [comment]
Gave some feedback to amnon (coordinates file not there, some of the analysis_protocol fields are showing information that isn't 100% accurate). Will have another catchup later!

**Comment by Wkt8** [comment]
Amnon to try and find some capacity for this.

**Comment by amnonkhen** [comment]
v0.4 - image files and analysis files, hidden empty columns
(https://app.zenhub.com/files/299258791/07201c29-3d3f-4ddf-bd08-c66177112a72/download)

**Comment by gabsie** [comment]
Hi, @Wkt8 - are you happy with this file as something to be usable by a scientist trying to use Visium metadata?

**Comment by MightyAx** [comment]
@gabs needs to email (people) regarding this.
