### ISSUE TITLE
Release 12 projects missing from Catalogue

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#625]
Projects from release 12 are not in the catalogue and are not set to "Published in DCP"

**Comment by jacobwindsor** [comment]
The below projects are not displaying because they do not have DOIs and hence an empty array in `publicationsInfo`. This could be changed so that they do display and say "pre-publication or citation missing". I think that used to be the case? @gabsie @ofanobilbao to decide

```
005d611a-14d5-4fbf-846e-571a1f874f70
cc95ff89-2e68-4a08-a234-480eca21ce79
9c20a245-f2c0-43ae-82c9-2232ec6b594f
116965f3-f094-4769-9d28-ae675c1b569c
b176d756-62d8-4933-83a4-8b026380262f
910fc0b2-3054-47b2-97f0-549f23e29d72
fc232d87-7b10-47f7-9197-b2c6cf210dea
1ce3b3dc-02f2-44a8-96da-d6d107b27a76
1538d572-bcb7-426b-8d2c-84f3a7f87bb0
60ea42e1-af49-42f5-8164-d641fdb696bc
e9f36305-d857-44a3-93f0-df4e6007dc97
0061c7e8-7b90-4296-be53-ca1de3bd6651
a0b4a252-c768-44df-a82a-399413a75ec1
4c886170-3f73-4661-832f-ab10409e84a9
fde199d2-a841-4ed1-aa65-b9e0af8969b1
2b38025d-a5ea-4c0f-b22e-367824bcaf4c
6768e2c1-38ce-4b07-87d5-552d52f01a30
```

There are also many projects from release 12 that have no been included in the catalogue. For this reason, they have also not been updated to show the "Published in DCP" state by our automatic script. That script only processes projects that are included in the catalogue. It has been expected (until this point?) for all projects in DCP to be in the catalogue. If neccesary, the script can be altered if requirements have changed. @ofanobilbao

**Comment by amnonkhen** [comment]
pending discussion @gabsie @jacobwindsor @ESapenaVentura 
@gabsie to schedule for next week.

**Comment by ipediez** [comment]
A meeting took place, @jacobwindsor to pick some of the tasks described in the previous comments. @gabsie to check if this needs to be converted into an epic.

**Comment by ipediez** [comment]
It looks like it works now, it would need testing from @ofanobilbao

**Comment by jacobwindsor** [comment]
I am going to move this into the "in production" column since I fixed them in production
