### ISSUE TITLE
Automatic project status update to  In Progress

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#627]
As a data wrangler and stakeholder, I want to have a correct view of how many projects have been Submitted over a certain period of time.

This [Miro board](https://miro.com/app/board/uXjVPcuO51U=/) prepared by @ESapenaVentura @Mil-m & @amnonkhen contains the project status transition chart and outlines the required transitions to be automated.

## **Current situation**: 
A data wrangler would forget to change the status of a project to Submitted, and then the number of projects Submitted over a period of time or in a release would not be correct.

## **NB:** 
if a new submission appears per project, change status back to In progress, and then do the above when Complete. 
*Note* - this scneario is removed from the initial scope, because an update to a project that is already in the dcp is, in theory, in both statuses at the same time. It is "in progress" but also "exported". This requires further discussion and refinement.

# Acceptance Criteria
see board

- scenario 1 - set status to In Progress for new submissions
  - [x] test
  - [x] code 
- scenario 2 - set status to Submitted when exporting finishes successfully
  - [x] test
  - [ ] code 
- integration tests
  - [ ] add an integration test

**Comment by gabsie** [comment]
To discuss the options at the design meeting. What happens with new submissions.

**Comment by amnonkhen** [comment]
This sequence diagram shows the sequence of events for creating a new submission, the relevant involved components and the location where the new functionality will be would be implemented.
Note: ZenHub does not render this diagram. View it on github #627.

```mermaid
sequenceDiagram
    actor User

    User ->> UI: create submission <br> (upload spreadsheet)
    UI ->> Broker: REST call:
    note right of UI: POST /api_upload
    Broker ->> Core: REST call create submission envelope 
    note right of Broker: POST '/submissionEnvelopes'
    Core -->> Broker: submission
    Broker ->> Core: associate submission with project (REST)
    note right of Broker: POST /projects/<project-uuid>/submissionEnvelopes <br> body <br> <ingest-api-url>/submissionEnvelopes/<submission-id> <br> headers <br> Content-type: text/uri-list''
    Core ->> ProjectLinkChangeListener : update project status 
    note right of ProjectLinkChangeListener: This is a RepositoryEventHandler
```

**Comment by amnonkhen** [comment]
See draft PR with test: ebi-ait/ingest-core#141

**Comment by ESapenaVentura** [comment]
@Mil-m to check and fix the test for statuses

**Comment by amnonkhen** [comment]
```mermaid
sequenceDiagram
autonumber
   actor Wrangler
   participant Core
   participant Exporter
   participant Queue
   participant StateTracker

   Wrangler ->> Core: export
   Core ->> Queue: export experiments
   Queue -->> Exporter: new Export event
   loop 
     Exporter ->> Exporter: export experiments
   end
   Exporter -) Queue: completed
   Exporter ->> Core: Job Completed
note right of Core: PATCH request to exportJob
   Queue -->> StateTracker: new "submission exported" event
StateTracker ->>Core: submission exported
note right of Core: PUT /submissionEnvelopes/<id>/commitExportedEvent
note right of Core: How is this triggered?
  Core ->> Core: update submission state to exported
  Core ->> Core: update project state to exported
  note right of Core: this is the work to be done
   
   

```

**Comment by idazucchi** [comment]
this was tested
now waiting for #850 to fix a github issue

**Comment by MightyAx** [comment]
Once testing is complete:
This [ingest-core pipeline](https://gitlab.ebi.ac.uk/hca/ingest-core/-/pipelines/322400) and this [ingest-exporter pipeline](https://gitlab.ebi.ac.uk/hca/ingest-exporter/-/pipelines/322398) can be released to production.

**Comment by gabsie** [comment]
There is a bug relevant to this feature, which is still being investigated by @amnonkhen

**Comment by gabsie** [comment]
Let's have this tested/confirmed by a wrangler, and see if this works correctly. @ESapenaVentura
