### ISSUE TITLE
When entering a GEO accession, create a project similar to the DOI flow

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#628]
As a data wrangler, I would like to create a project in ingest backoffice based on a GEO accession, and save with its existing information.  (So that wranglers can know who is working on what)

This is an improvement of the GEO to HCA spreadsheet generation functionality we already have in place.

**Comment by gabsie** [comment]
This would need a design meeting to sort out the flow and make it consistent with the DOI flow.. 
Let's have a meeting with @ESapenaVentura and devs who decide to take on this task

**Comment by gabsie** [comment]
@aaclan-ebi will join the discussion together with Yusra and Amnon.

**Comment by amnonkhen** [comment]
@yusra-haider , @aaclan-ebi @ESapenaVentura & @amnonkhen had a design discussion.

created a branch with the sequence diagram: [feature/dcp-628-new-project-from-geo](https://github.com/ebi-ait/ingest-broker/tree/feature/dcp-628-new-project-from-geo)

**Comment by amnonkhen** [comment]
@aaclan-ebi @yusra-haider to pair up on this.

**Comment by Wkt8** [comment]
Alegria and yusra have divided up the work and are improving the feature.

**Comment by idazucchi** [comment]
@MightyAx and @ke4 to review Alegria's PR

**Comment by aaclan-ebi** [comment]
We've got changes on the UI flow: https://miro.com/app/board/uXjVOQXsRrU=/ 
pls check @gabsie @amnonkhen

**Comment by gabsie** [comment]
needs reviews by devs, and then wrangler checks @ami-day

**Comment by gabsie** [comment]
@yusra-haider is this ready for checking by @ami-day

**Comment by yusra-haider** [comment]
@gabsie not yet. One of the pull requests still needs review compliance and then further reviews. I'll move it to the user testing pipeline once done

**Comment by MightyAx** [comment]
@yusra-haider to address review comments.

**Comment by jacobwindsor** [comment]
Build is failing in PR, to be addressed by @aaclan-ebi and @yusra-haider

**Comment by aaclan-ebi** [comment]
@ami-day this should be ready for testing in staging.

**Comment by ami-day** [comment]
I have tested the following:

**GSE156728**

- Raises error: "Unable to import the project or download spreadsheet. Unable to find HCA metadata against given accession [AttributeError("'NoneType' object has no attribute 'empty'",)]".
- Error is expected: there is no SRA study accession linked to this GEO accession.

**GSE157789** 

- Response: "The project metadata with GEO accession GSE157789 has been successfully created" 
- Spreadsheet downloads
- Downloaded spreadsheet is filled with metadata as expected

**GSE160936**

- Response: "The project metadata with GEO accession GSE160936 has been successfully created" 
- Spreadsheet downloads
- Downloaded spreadsheet is filled with metadata as expected

**GSE185477**

- Response: "The project metadata with GEO accession GSE185477 has been successfully created" 
- Spreadsheet downloads
- Downloaded spreadsheet is filled with metadata as expected

Nice work @aaclan-ebi and @yusra-haider :)

My only feedback is that, the geo-to-hca.py script actually also accepts an SRA study accession or an ENA study accession using the same command-line input argument --accession. Can we extend the regex which searches for the "GSE" prefix to include the prefixes "SRP" and "ERP"?

**Comment by ami-day** [comment]
@gabsie shall I move this to Done?
