### ISSUE TITLE
automate resource cleanup after submission deletion

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#629]
When Wranglers delete a submission, the corresponding s3 bucket needs to be deleted. It is currently a manual "dev on ops" task, but it should be automated.
See ebi-ait/hca-ebi-wrangler-central#615

**Comment by aaclan-ebi** [comment]
PR's for review:
https://github.com/ebi-ait/ingest-core/pull/113/files
https://github.com/ebi-ait/ingest-staging-manager/pull/3

**Comment by jacobwindsor** [comment]
More reviews needed
