### ISSUE TITLE
Create an external available endpoint to trigger data archiving

### ISSUE THREAD

**Issue by prabh-t** [ebi-ait/dcp-ingest-central#631]
It was expected this request would come from another ingest component for e.g. ingest-core/-archiver, but we realised it may be useful to be triggered by end-users as well, thus this endpoint to initiate the process in the background.

This would effectively automate Step 2 (of 3) of the current Archiving SOP.

This can be in ingest-core or ingest-archiver, both with external IP/domain name.

- [x] endpoint in core or archiver to trigger archiver
- [x] update Archiving SOP with new instructions
- [x] update ingest-data-archiver README

Also, if time allows, 
- [ ] endpoint to check progress

**Comment by aaclan-ebi** [comment]
@prabh-t updating the sop re data archiving. There's a PR for review.

**Comment by prabh-t** [comment]
~~https://github.com/ebi-ait/ingest-data-archiver/pull/6~~ **Merged**
~~https://github.com/ebi-ait/ingest-archiver/pull/72~~ **Merged**
https://github.com/ebi-ait/hca-ebi-wrangler-central/pull/633 needs wrangler feedback

**Comment by MightyAx** [comment]
@ami-day please review ebi-ait/hca-ebi-wrangler-central#633

**Comment by ipediez** [comment]
@ami-day to test this

**Comment by ami-day** [comment]
I have added my comments to the pull request here https://github.com/ebi-ait/hca-ebi-wrangler-central/pull/633#pullrequestreview-882996895

**Comment by yusra-haider** [comment]
waiting on @prabh-t

**Comment by prabh-t** [comment]
Steps to test direct data file upload to ENA using the new endpoint:

1. Prepare a test submission in dev or staging.
2. Get the ARCHIVER_API_KEY from Step 2 of the Archiving SOP.
3. Run the following command in terminal, replacing INGEST_ARCHIVER_URL accordingly depending on the environment you are using and the test submission uuid.
```
curl -X POST {INGEST_ARCHIVER_URL}/archiveSubmissions/data -H 'Content-Type: application/json' -H "Api-Key:{ARCHIVER_API_KEY}" -d '{"sub_uuid": "{SUB_UUID}"}'
```
This will trigger the background process to start transferring the submission data files from Ingest S3 to ENA upload area.
To test if the files have been transferred successfully, 
4. Go to the submission Data tab in Ingest UI.
5. Click on the `ingest api url` of some sequence files. This will open the file json documents.
6. If the file has been copied to ENA, the `fileArchiveResult` attribute will not be null.

**Comment by idazucchi** [comment]
@ami-day to test this following the instructions

**Comment by Wkt8** [comment]
Ami has tested and left feedback (?) to be looked at.

**Comment by Wkt8** [comment]
@prabh-t to have a look at the feedback

**Comment by ofanobilbao** [comment]
PR have been reviewed and merged. Ami did comments that will be addressed in a separate improvement ticket. This can be closed

**Comment by prabh-t** [comment]
Checked. PRs affecting code (ingest-archiver, ingest-data-archiver) merged to dev and master, so in prod.
