### ISSUE TITLE
Linking entities from another submission alter submission status from original submission

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#633]
**Describe the bug**
Linking an entity from another submission will kick the original submission back to "metadata valid" status

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a project page with an exported submission
1. Create another submission 
1. Link protocols from exported submission into new submission

**Expected behaviour**
The status from the previous submission is not changed

**Workaround:** Ask a dev to force set the first submission to Exported and redeploy the state tracker after second submission is added.

**Environment**
- [x] prod
- [ ] staging
- [ ] dev

**Browser**
- [x] Chrome
- [ ] Safari
- [ ] IE
- [ ] Other (please specify)

**Comment by aaclan-ebi** [comment]
Happened to ebi-ait/hca-ebi-wrangler-central#723

**Comment by aaclan-ebi** [comment]
Should be fixed by ebi-ait/dcp-ingest-central#736

**Comment by aaclan-ebi** [comment]
@ami-day this fix is now in the staging env and should be ready for testing, you could follow the steps to reproduce above. Thanks!

**Comment by gabsie** [comment]
@Wkt8 to test the above scenario.

**Comment by MightyAx** [comment]
Not specifically @Wkt8 or @ami-day, wranglers to coordinate.

**Comment by aaclan-ebi** [comment]
@idazucchi could cover this in #740 testing.

**Comment by idazucchi** [comment]
I tested this with submission ticket280_test_case2 in staging - the first submission stayed exported after the addition of a second submission, the fix is working correctly
