### ISSUE TITLE
Transform the current View mode for Contributors in a table view

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#635]

**Comment by ke4** [comment]
I would be glad to do some UI work. It would be a change from archiving work, at least for a short amount of time. 😊
So, happy to pair on this with @aaclan-ebi if that is fine with her.

**Comment by jacobwindsor** [comment]
See PR https://github.com/ebi-ait/ingest-ui/compare/dcp-635?expand=1

**Comment by ipediez** [comment]
devs to review

**Comment by jacobwindsor** [comment]
@gabsie to test on staging
