### ISSUE TITLE
Do not allow download if importing is in progress

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#645]
related to ebi-ait/dcp-ingest-central#600 

**Step/s to replicate:**
Upload a spreadsheet to create big submission (~800 metadata) - this may take long

**Actual Behavior:**
The user is not able to see linking progress.
The user is able to download a spreadsheet even when linking hasn't finished yet

**Expected behaviour:**
The user should see that linking is in progress
The user should not be able to download a spreadsheet yet

**Comment by yusra-haider** [comment]
@aaclan-ebi working on this

**Comment by aaclan-ebi** [comment]
Hi @ami-day  would you be able to do some QA on the UI changes on this ticket?

The changes are listed here and it also includes some screenshots:
https://github.com/ebi-ait/ingest-ui/pull/161#issue-1140339986

I also have a test spreadsheet I can send on slack which you can use for testing.

Thanks!

**Comment by ami-day** [comment]
Tested this, it is working as expected.
