### ISSUE TITLE
Submission stuck in pending, not reporting errors

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/dcp-ingest-central#646]
**Describe the bug**
Uploading a submission to the staging environment results in it being stuck in pending, and not loading the submission 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the staging environment
2. Upload the attached test spreadsheet 
3. See error

**Expected behaviour**
The spreadsheet should generate a new submission that moves from the pending state to the draft and then validating state 

**Screenshots / Logs**
![Screenshot 2022-02-08 at 13.14.25.png](https://images.zenhubusercontent.com/5fd74f67b86eb46030b3f4e3/b8e525b0-368c-4ca0-8a78-642d3f399289)![image (1).png](https://images.zenhubusercontent.com/5fd74f67b86eb46030b3f4e3/9b025472-565d-4d2e-9dec-1fa78ced1ae6)

**Links**
> If applicable, link to relevant docs or Slack conversations.

**Environment**
- [x] prod
- [x] staging
- [ ] dev

**Browser**
- [x] Chrome
- [ ] Safari
- [ ] IE
- [ ] Other (please specify)

**Comment by Wkt8** [comment]
[https://app.zenhub.com/files/299258791/3affa936-f3f7-43ea-81ef-dcd45b2ce833/download](https://app.zenhub.com/files/299258791/3affa936-f3f7-43ea-81ef-dcd45b2ce833/download)

This is the example spreadsheet which was causing errors.

**Comment by aaclan-ebi** [comment]
Thanks @Wkt8  for sending the screenshot of console logs! it's very helpful! 

This is a bug introduced by ebi-ait/dcp-ingest-central#600 , the contentLastUpdated endpoint of the submission is failing on an empty submission.

**Comment by aaclan-ebi** [comment]
PR for review: https://github.com/ebi-ait/ingest-core/pull/114

**Comment by MightyAx** [comment]
Merge to master, deploy to staging, ask a wrangler (ami?) for user testing

**Comment by jacobwindsor** [comment]
merged to master
