### ISSUE TITLE
Getting Internal Server Error on GEO Accessions

### ISSUE THREAD

**Issue by yusra-haider** [ebi-ait/dcp-ingest-central#647]
As reported on slack by the wranglers, there's a `500 Internal Server Error` being thrown when these GEO accessions are used: 

`GSE173682
 GSE131928
 GSE181346
 GSE174792
 GSE186368
GSE189770`

An example screenshot, as seen on dev environment, for the accession GSE189770

![image.png](https://images.zenhubusercontent.com/5fa15836bb6093b67034928a/c4871566-4dcd-401c-aae0-9e791b773490)

We need to investigate:

- why this error is being thrown
- get an estimate on the number of geo accessions the script fails against 
- we also need to improve the error messages being returned by the script

**Comment by ami-day** [comment]
@yusra-haider picking this up

**Comment by amnonkhen** [comment]
@yusra-haider what does the user see in this case?
Is this ticket about improving the experience of the user when the GEO script has an error, or about improving the script to that it is more robust?
Also, please add the important details about the problem to the ticket. It is inconvenient and inefficient to have to go to slack to understand what this is about.

**Comment by yusra-haider** [comment]
@amnonkhen I've updated the ticket

**Comment by gabsie** [comment]
@jacobwindsor has taken this for now, while waiting for his other tasks.

**Comment by idazucchi** [comment]
Probably due to changes in the PubMed api. Can be solved by using different library or   using GSE accessions

**Comment by amnonkhen** [comment]
Consider using [Entrez API](https://www.ncbi.nlm.nih.gov/geo/info/geo_paccess.html) to get data about accessions:
1) [find ids by accession using esearch](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=gds&term=GSE155468)
2) [find relevant doc using esummary](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=gds&id=304704937)
3) [use FTP to download data])(https://ftp.ncbi.nlm.nih.gov/geo/series/GSE155nnn/GSE155468/)

Consider using [decorest](https://pypi.org/project/decorest/) to quickly write python clients for web apis.

**Comment by jacobwindsor** [comment]
@amnonkhen Im not sure that this approach aproach will work because of changes in the Entrez API I believe. Your approach is the exact same one that `pysradb` is using and is failing with. If you look at your example, the SRP accessions are not listed in the esummary.

I'll have a look because maybe it's possible with a few more changes than I'd hoped for

**Comment by jacobwindsor** [comment]
I have investigated a lot and believe something has happened with Entrez API to stop SRP accessions being in the `extrerelations`.

Here is an easy example for [GSE155468](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE155468):
- The SRP project should be SRP274475
- The [current GEO page](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE155468) for it shows no SRP accessions
- If you go back in time by looking at what Google has indexed, the SRP accession is there 

![image.png](https://images.zenhubusercontent.com/5f8d5ed6657f5d56f6792bec/aa79cee7-562c-4a75-89c2-6b441d62adcf)

The `extrerelations` is what `pysradb` is looking for. So, although that library is error prone, it is not at fault here. @amnonkhen your suggestion uses the same approach as `pysradb` and won't work. 

Does anyone know where I should file a bug report for this?

**Comment by gabsie** [comment]
Amnon and @jacobwindsor will discuss this additionally.

**Comment by ESapenaVentura** [comment]
Options:
- Email NCBI about the ENTREZ API's bug
- Change the way we get the SRP accessions (Very convoluted, but works)

**Comment by gabsie** [comment]
NCBI have fixed the issue.

**Comment by prabh-t** [comment]
Amnon to organise a catchup on this.

**Comment by jacobwindsor** [comment]
- GSE173682
- GSE181346
- GSE186368

Will still not work since they do not have corresponding SRA accessions.

However, I believe GSE189770 should work since there is [this SRA project](https://trace.ncbi.nlm.nih.gov/Traces/sra/?study=SRP348406). Moving this back into backlog
