### ISSUE TITLE
GEO spreadsheet has staging schema urls

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#650]
**Steps to replicate:**
1. Go to the new project page
2. Enter GEO accession
3. The project will be created and the user will be redirected to the project's page
4. In the Experiment Info tab, click the download spreadsheet button
5. Save the file

**Actual Behavior:**
Excel file has "Schemas" tab and schema URL are staging URLs

**Expected Behavior:**
Excel file has no "Schemas" tab so that importer will get the latest schemas from Ingest API

Note:
The Geo library is using an hca template spreadsheet which are using staging schema URLs

related to feature ebi-ait/dcp-ingest-central#628

**Comment by yusra-haider** [comment]
as discussed with @aaclan-ebi , the schemas tab in the spreadsheet template has been removed.

PR raised here: https://github.com/ebi-ait/geo_to_hca/pull/33

this change needs to be pushed to PyPI, once merged

**Comment by aaclan-ebi** [comment]
PR merged but I couldn't publish to pypi yet. The shared hca dev user `ebi-hca-ingest` should be added as maintainer of https://pypi.org/project/geo-to-hca/ , moving to waiting pipeline for now

**Comment by idazucchi** [comment]
Alegria will release to pypi today

**Comment by gabsie** [comment]
This would be attended after the other tasks on exporting.

**Comment by aaclan-ebi** [comment]
geo-to-hca has been upgraded to 1.0.6 , and I've updated broker in dev and (master)staging to use the new version, however, due to the issue reported in https://github.com/ebi-ait/dcp-ingest-central/issues/647#issuecomment-1054457873 , I am not able to verify if the issue in this ticket is fixed. Putting this to waiting for now.

**Comment by Wkt8** [comment]
@aaclan-ebi to create a ticket for the issue which is blocking this ticket (separate from 647)

**Comment by aaclan-ebi** [comment]
Verified expected behaviour. Tested with `GSE161255`.  Promoted this ticket to prod today.
