### ISSUE TITLE
Set memory limits on deployments

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#651]
If we set memory limits on our deployments, pods will gracefully be terminated and restarted without downtime when they exceed the limit. This will help our problems with the slowness of core when memory usage gets unnecessarily high. Fair warning that we still need to investigate why memory usage gets so high.

See https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

**Comment by amnonkhen** [comment]
Good idea +1

**Comment by jacobwindsor** [comment]
Writing notes: clusters are running with two nodes using `t3a.large` for each node which have 8GB of memory between them

**Comment by MightyAx** [comment]
https://github.com/ebi-ait/ingest-kube-deployment/pull/45

**Comment by jacobwindsor** [comment]
I'm going to wait until Thursday to deploy this to prod so that any complications will have time to highlight in staging or dev
