### ISSUE TITLE
Add a new SS2 dataset without accessions to be able to use it for direct archiving

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#654]
The current SS2 dataset is not suitable for testing the direct archiving as it contains invalid accessions for biomaterials, project and files.
It is located here: https://github.com/HumanCellAtlas/metadata-schema/blob/master/infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx

I had a discussion with @ESapenaVentura and I am going to replicate the same dataset and remove the accessions from it and place it next to the original one with a different name. I am going to reuse it in the direct archiving integration test.

Tasks to do:
- [x] Create the new dataset and commit it to the metadata-schema repository
- [x] Refactor the direct archiving integration test and reuse the newly created dataset in the test.

**Comment by ipediez** [comment]
PR's have been merged, part of the integration tests
