### ISSUE TITLE
Can not submit a submission as Submit tab is empty after graph validation

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#656]
After a successful graph validation when the user clicks on the `Submit` tab the page is empty. It is not possible to submit the submission.

Steps to reproduce:
1. Upload a valid new submission
2. Go to `Validate` tab and click on `Validate Submission` button
3. Wait for validation
4. When the submission's status changed to `Graph Valid` go to the `Submit` tab

Expected behaviour:
The `Submit` tab displaying the various option how to/where to submit the submission.

Actual behaviour:
Only a `What's next?` text appears on the sreen.

**Comment by ke4** [comment]
This is blocking me to generate test data for direct archiving.

**Comment by ipediez** [comment]
@ke4 and @aaclan-ebi to investigate this afternoon

**Comment by jacobwindsor** [comment]
@ke4  to verify whether this is a problem

**Comment by prabh-t** [comment]
Alegria to try to reproduce issue.

**Comment by jacobwindsor** [comment]
I think this is not happening anymore. I just created an SS2 submission here https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=bb969a26-d198-4bf1-8aa3-2fae40c8441c&project=22887fde-1011-4378-ae26-fa9f4e447b03
