### ISSUE TITLE
Ingest UI: Delete single metadata entity

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#659]
As a data submitter,...
I can delete metadata from a submission,ission
to correct any issues with my submission

### Status
UI change to add delete button, and minor fixups from #689
- [x] Ingest UI: https://github.com/ebi-ait/ingest-ui/pull/167 **Staging**

Core change to properly unlink entities when they are deleted (prevent crashes loading those entities) and sending delete requests to the state tracker:
- [x] Ingest Core: https://github.com/ebi-ait/ingest-core/pull/119 **Staging**

State tracker endpoint to delete internal representation of core changes
- [x] Ingest State Tracker: https://github.com/ebi-ait/ingest-state-tracking/pull/12  **Staging**

### Technical complexity
- Notify state tracker of document delete
  - At the moment there is the `DOCUMENT_PROCESSED` event - this might be able to be reused and might "just work"
  - Proobably need to create a `DOCUMENT_DELETED` event and a subsequent action
- Core: Getting the links for a metadata document that contains a link to a removed metadata document will cause an internal server error, so first:
    - remove protocol from any process.protocols
    - remove process from any biomaterial.inputToProcesses
    - remove process from any biomaterial derivedByProcesses
    - remove process from any file.inputToProcesses
    - remove process from any file.derivedByProcesses
    - remove process from any process.chainedProcesses

Initial UI Implementation _highlighted in yellow_:
![Screenshot 2022-03-23 at 11.31.37.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/83260b05-79a4-400b-8354-551c3f542743)

**Comment by ofanobilbao** [comment]
Once all ready @MightyAx will move to In Code Review

**Comment by MightyAx** [comment]
UI change to add delete button, and minor fixups from #689
Ingest UI: https://github.com/ebi-ait/ingest-ui/pull/167

Core change to properly unlink entities when they are deleted (prevent crashes loading those entities) and sending delete requests to the state tracker:
Ingest Core: https://github.com/ebi-ait/ingest-core/pull/121

State tracker endpoint to delete internal representation of core changes
Ingest State Tracker: https://github.com/ebi-ait/ingest-state-tracking/pull/12

**Comment by Wkt8** [comment]
Code review for the three above is required from devs.

**Comment by jacobwindsor** [comment]
This is now in staging and ready for testing if @ami-day has time

**Comment by MightyAx** [comment]
This is now ready for testing on Staging.
Since the deployment issue's meant Ami didn't get a chance to start any testing, does it makes sense for @Wkt8 to test this as the wrangler on Dev this sprint?

**Comment by MightyAx** [comment]
@ESapenaVentura, as the backup wrangler on dev and the person who originally tested the additions in #689 can you check that the fix-ups that were released with this address the issues you raised.
-  Missing word in New type - concreteType has been **added** successfully
- Don't show in protocol add menu: type/protocol/x.x.x/protocol

Thanks

**Comment by gabsie** [comment]
Write up a test plan with different scenarios and @Wkt8 can go over the scenarios with the dev @MightyAx

**Comment by MightyAx** [comment]
Miro board with testing scenario's and outcomes:
https://miro.com/app/board/uXjVO_fYG-o=

**Comment by ESapenaVentura** [comment]
I am a bit confused here, sorry, am I supposed to test more things or just that the fixes were applied?

**Comment by MightyAx** [comment]
@ESapenaVentura I was given the impression that the Dev Team process mean you *should* test the two things I resolved that you raised. But I will be the first to admit I don't have a clear picture of the nuance of that process right now. I don't *need* you to test them since I think the problems you raised and my fixes for them are fairly self-explanatory.
- Missing word in New type - concreteType has been **added** successfully
- Don't show in protocol add menu: type/protocol/x.x.x/protocol

If on the other-hand you are available to help Wei and I with the user testing of additions/deletions then I don't think either of us would reject the help. Especially because my time is being taken away from it quite a lot.

**Comment by MightyAx** [comment]
@MightyAx will take on the User testing identified here: https://miro.com/app/board/uXjVO_fYG-o=

**Comment by ami-day** [comment]
@MightyAx says he should make progress on this today.

**Comment by aaclan-ebi** [comment]
I think there's an issue with deleting a project 
```
curl -X DELETE -H "Authorization: Bearer $TOKEN" https://api.ingest.dev.archive.data.humancellatlas.org/projects/6254586b71704f5dda5f3ec2
```
logs:
```
ingest-core-679d8bc486-s78rs ingest-core 2022-04-11 16:37:39.803 ERROR 6 --- [o-8080-exec-542] o.h.i.c.web.GlobalStateExceptionHandler  : Runtime exception encountered on DELETE request to resource https://api.ingest.dev.archive.data.humancellatlas.org/projects/6254586b71704f5dda5f3ec2
ingest-core-679d8bc486-s78rs ingest-core
ingest-core-679d8bc486-s78rs ingest-core java.lang.RuntimeException: The metadata document should have a link to a submission envelope.
ingest-core-679d8bc486-s78rs ingest-core 	at org.humancellatlas.ingest.messaging.MessageRouter.routeStateTrackingDeleteMessageFor(MessageRouter.java:85) ~[classes!/:na]
ingest-core-679d8bc486-s78rs ingest-core 	at org.humancellatlas.ingest.core.service.strategy.impl.ProjectCrudStrategy.removeLinksToDocument(ProjectCrudStrategy.java:64) ~[classes!/:na]
ingest-core-679d8bc486-s78rs ingest-core 	at org.humancellatlas.ingest.core.service.strategy.impl.ProjectCrudStrategy.deleteDocument(ProjectCrudStrategy.java:94) ~[classes!/:na]
ingest-core-679d8bc486-s78rs ingest-core 	at org.humancellatlas.ingest.core.service.strategy.impl.ProjectCrudStrategy.deleteDocument(ProjectCrudStrategy.java:21) ~[classes!/:na]
ingest-core-679d8bc486-s78rs ingest-core 	at org.humancellatlas.ingest.core.service.MetadataCrudService.deleteDocument(MetadataCrudService.java:72) ~[classes!/:na]
ingest-core-679d8bc486-s78rs ingest-core 	at org.humancellatlas.ingest.project.ProjectService.lambda$delete$3(ProjectService.java:155) ~[classes!/:na]
ingest-core-679d8bc486-s78rs ingest-core 	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
ingest-core-679d8bc486-s78rs ingest-core 	at org.humancellatlas.ingest.project.ProjectService.delete(ProjectService.java:154) ~[classes!/:na]
ingest-core-679d8bc486-s78rs ingest-core 	at org.humancellatlas.ingest.project.web.ProjectController.delete(ProjectController.java:196) ~[classes!/:na]
```

**Comment by aaclan-ebi** [comment]
@ESapenaVentura will assist @MightyAx with testing.

**Comment by ESapenaVentura** [comment]
We still need some user testing - Not blocking at the moment
