### ISSUE TITLE
Additional labels per project: 'To follow up', 'SCEA', 'CellxGene', 'Needs update'

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#663]
As a wrangler
I would like to mark a project with a label on occasions like:

- I have seen a pre-print for a project, but there is still no data
- I have emailed a contributor, requested actions, but they have been slow in responding, and I don't want to forget about this
- I deem this project suitable for CellxGene/SCEA

Acceptance criteria
============
Given I go to ingest backoffice
When I view the project dashboard, in the table
- I can see the projects tagged as suitable for CellxGene or SCEA
- I can see all projects that need a follow up or an an update
- I can filter the projects using a labels filter

The specific options should be:

Follow up
Needs update
SCEA
cellxgene
Archive

**Comment by gabsie** [comment]
Hey @ipediez, @ESapenaVentura 
I wish to introduce these labels, which are supposed to be stored at project level, to remind the actions needed to be done for wrangling. (so they identify wrangler workflows)

Do these make sense to you?
We will also eventually include them as filters, but not as part of this ticket

Thanks!
Gabs

**Comment by yusra-haider** [comment]
Added the field for Wrangling Labels to project admin tab, and added filter for the field
PRs ready for review:
https://github.com/ebi-ait/ingest-ui/pull/175
https://github.com/ebi-ait/ingest-core/pull/134


Field in Admin tab:
![image.png](https://images.zenhubusercontent.com/5fa15836bb6093b67034928a/cb302eb2-d055-4662-a7c0-5b854b4ba624)

Wrangling Labels added as a column to project table:
![image.png](https://images.zenhubusercontent.com/5fa15836bb6093b67034928a/2e861b58-689a-4040-8dcc-c846922e536d)

Filter for wrangling label:
![image.png](https://images.zenhubusercontent.com/5fa15836bb6093b67034928a/a8635ba9-345b-4d1f-94e4-248b4c3af1b9)

**Comment by ESapenaVentura** [comment]
@yusra-haider and @gabsie had a catchup - Small changes needed, but should be available for testing today

**Comment by gabsie** [comment]
check with Yusra if this is ready, today

**Comment by yusra-haider** [comment]
deployed to dev env

**Comment by yusra-haider** [comment]
deployed to staging and ready for testing

**Comment by gabsie** [comment]
HI, @yusra-haider - I am good for this to be put on prod, whenever possible.
Actually, @yusra-haider - I think the new labels are breaking the table (making it wider), I think we should reconsider how the table behaves and those labels should fall onto a new line etc?
The labels should also have spaces after the commas

**Comment by idazucchi** [comment]
yusra is deploying this!
