### ISSUE TITLE
Additional project field - visualisation portals, to appear both in backoffice and Catalogue

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#670]
As a Data contributor/wrangler, 
I would like to add the link to my project in a supported Analysis Portal (e.g. Cellxgene/SCEA/UCSC browser), 
so that other scientists can view my data in the visualisation tool

**Acceptance Criteria**
- [x] Wrangler/Contributor can specify a link to an analysis portal (through supplementary links)
- [ ] Only supported portals are shown in the catalogue
- [ ] catalogue can be filtered by the analysis portal
- [ ] catalogue allow navigating to the analysis portal

**To move to a separate ticket (and sprint)**
- [ ] create a new field for this on Project (core)
- [ ] regex to only allow support portals (core)
- [ ] UI can be filtered by the analysis portal (UI)

**Comment by MightyAx** [comment]
Just an idea: I believe if the cxgene link is added as an accession it will be displayed in project catalogue (but perhaps this requires a HCA metadata version change)

**Comment by gabsie** [comment]
please refer to [409](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/409)

**Comment by gabsie** [comment]
please refer to [409](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/409)

**Comment by amnonkhen** [comment]
I created [a wireframe](https://miro.com/app/board/uXjVO79yOL0=/)

**Comment by MightyAx** [comment]
The recommendation here is to store links to Cellxgene / SCEA / UCSC in the project metadata schema

`project.supplementary_links`
> External link(s) pointing to code, supplementary data files, or analysis files associated with the project which will not be uploaded.
> example: `https://github.com/czbiohub/tabula-muris; http://celltag.org/`

**The suggested change is to highlight supported URLs in the project catalogue.**

@gabs / @ESapenaVentura Please can I have examples of the following urls, so that I can determine how we detect them:
1. Cellxgene
2. SCEA
3. UCSC

**Comment by gabsie** [comment]
Hi, @MightyAx 

So for UCSC browser links: 
https://cells.ucsc.edu/?ds=fetal-thymus
https://cells.ucsc.edu/?ds=lifespan-nasal-atlas 
CellxGene
https://cellxgene.cziscience.com/collections/0434a9d4-85fd-4554-b8e3-cf6c582bb2fa
https://cellxgene.cziscience.com/collections/6f6d381a-7701-4781-935c-db10d30de293

SCEA:
https://www.ebi.ac.uk/gxa/sc/experiments/E-CURD-98/results/tsne
https://www.ebi.ac.uk/gxa/sc/experiments/E-MTAB-11011/results/tsne

**Comment by ESapenaVentura** [comment]
>SCEA:
> https://www.ebi.ac.uk/gxa/sc/experiments/E-CURD-98/results/tsne
> https://www.ebi.ac.uk/gxa/sc/experiments/E-MTAB-11011/results/tsne

Just adding to this, that for the regex, don't always expect the "tsne" part at the end. It won't always end like that!

**Comment by MightyAx** [comment]
My current plan is to consider any supplementary link that contains:
`cellxgene.cziscience.com/collections` as a **cellxgene** link 
`ebi.ac.uk/gxa/sc/experiments` as a **Single Cell Expression Atlas** link
`cells.ucsc.edu` as a **UCSC Cell Browser** link

We can do more regex manipulation to figure out:

-  the accession (SCEA)
- The uuid (cellxgene)
- the dataset collection name (UCSC)

But then we should probably be validating the data on input and storing it separately also.
If that's in scope for this sprint it's a much bigger task.

Also, any opinions on the use of Logos versus the following text?
**cellxgene** / **Single Cell Expression Atlas** / **UCSC Cell Browser**
If you would like Logo's please provide them.

**Comment by ipediez** [comment]
@gabsie and @ESapenaVentura to take a look and give feedback

**Comment by MightyAx** [comment]
Current progress showing filtering and output for SCEA.
The code also works for cellxgene and UCSC but no prod data features those in supplementary links.

It seems like we Will need some regex after all, to display the accessions.

![Screenshot 2022-04-22 at 11.05.55.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/31d14a71-4b02-4984-91ae-a11153b89703)

**My big question then is how to display cellxgene since they are massive UUIDs and this cell of the table is already massively overflowing, perhaps that's where to bring in the logo.**

To help with the overflow I'll just use "SCEA" rather than "Single Cell Expression Atlas"

**Comment by MightyAx** [comment]
Implemented accession regex
![Screenshot 2022-04-22 at 13.11.30.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/d861f554-978d-45a8-8be8-797965761c24)

The accession cell is getting very full for some records.

**Comment by MightyAx** [comment]
added external link signifier and started using this formatting everywhere (just ENA so far)
![Screenshot 2022-04-22 at 16.23.25.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/20359c3a-9897-4565-8202-6817769e5b24)

**Comment by prabh-t** [comment]
Alexie - Feature complete but some refactoring remaining.

**Comment by MightyAx** [comment]
The list-of-links component has been complete, awaiting re-review
![Screenshot 2022-04-25 at 11.45.46.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/32f285cf-3249-4950-b4c0-6dda0323d70c)

**Comment by MightyAx** [comment]
Deployment in the EBI Web Dev Environment [Failed](https://gitlab.ebi.ac.uk/ebiwd/html-sites/ebi.ac.uk.humancellatlas.project-catalogue/-/jobs/823770#L50), but I don't know how to follow this up!

**Comment by MightyAx** [comment]
The test step that is failing (because yarn is not installed) was added by @jacobwindsor's recent cleanup, removing it for now.

**Comment by MightyAx** [comment]
Deployment Successful, ready for user testing:
https://wwwdev.ebi.ac.uk/humancellatlas/project-catalogue/

**Comment by MightyAx** [comment]
Known Issue: TSV generation shows [Object object] instead of accession.
Will fix tomorrow.

**Comment by ESapenaVentura** [comment]
> Also, any opinions on the use of Logos versus the following text?
cellxgene / Single Cell Expression Atlas / UCSC Cell Browser
If you would like Logo's please provide them.

I think it's fine with the names for now. Adding the logos would require a lot more work (we would need to contact each of the institutions for their logos etc)

>My big question then is how to display cellxgene since they are massive UUIDs and this cell of the table is already massively overflowing, perhaps that's where to bring in the logo.

I think for now we just need to stick with the UUID, cellxgene have no open APIs where we could query a short identifier for the project

I tried to download the TSV for the project that I added the SCEA/cellxgene/UCSC cell browser accessions to test and the resulting TSV had no headers/entries for those accessions, I assume this is the error you comment above or is it different?

Other than that, I've been testing around and adding a couple of accessions to projects and it works great!

**Comment by gabsie** [comment]
@gabsie to check as well.

**Comment by MightyAx** [comment]
Project Catalogue in wwwdev not being deployed to production.
Operations ticket to track with EBI Gitlab Team: https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/788

**Comment by MightyAx** [comment]
Project Catalogue deployment to [Prod](https://www.ebi.ac.uk/humancellatlas/project-catalogue/) successful!

**Comment by gabsie** [comment]
Hey Alexie, this works great when I tried the different links. Small edit you might have to do with regards to your formula for getting the cell browser links. I have seen in the sheet that their links can sometimes be:

https://gut-cell-atlas.cells.ucsc.edu
https://covid19-influenza-response.cells.ucsc.edu

so maybe you also have to consider links that end in ... cells.ucsc.edu, not only start with that (I can see this displaying fine: https://cells.ucsc.edu/?ds=adultPancreas)

I have now entered details for 4 projects, you can see them by filtering by cellxgene portal

Gabs

**Comment by MightyAx** [comment]
![image](https://user-images.githubusercontent.com/13031259/167645372-5f0cfa0a-cdd4-4cca-a6d3-086e41a4be81.png)
Change in review

**Comment by MightyAx** [comment]
Ready for review on dev: https://wwwdev.ebi.ac.uk/humancellatlas/project-catalogue/
can release to prod when you approve.

**Comment by ESapenaVentura** [comment]
Second component to allow for a bit more links in staging yet - But ready to be released

@gabsie to take a look

**Comment by gabsie** [comment]
This has been checked and is OK!

**Comment by MightyAx** [comment]
Deployed to [PROD](https://www.ebi.ac.uk/humancellatlas/project-catalogue/)
