### ISSUE TITLE
Ability to view file to file linkings in the UI

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#673]
As a user
I want to view and update the file to file linkings in the UI
so that I can verify if they are correct and fix any errors

Given a spreadsheet where the sequencing file is linked to an analysis file
When I view the process in the UI
Then I should see that process's input files, protocols and output files and modify them

This is needed for ticket: ebi-ait/hca-ebi-dev-team#470

**Comment by idazucchi** [comment]
@yusra-haider to review this
