### ISSUE TITLE
Ability to see the updates in the metadata relationships on the DCP portal

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#680]
As a data submitter, I want to see the changes in metadata relationships I entered in ingest on the DCP portal.

**Acceptance criteria:**
1. Given 2 donors and cell suspension and cell suspension input is donor 1
When the user changes the linking so that: cell suspension input to donor 2
Then the changes will be submitted to the staging area upon export

-----

2. Given 2 cell suspensions and 6 files, when cell suspension 1 is linked to 6 files
When the user adds a new process and changes the linking so that: cell suspension 1 linked to file 1,2,3 & cell suspension 2 linked to file 4,5,6
Then the changes will be submitted to the staging area upon export

3. Given 2 donors and cell suspension and cell suspension input is donor 1
When the user adds a new protocol and links the protocol to the process connecting cell suspension and donor 1   
Then the changes will be submitted to the staging area upon export

**Out of scope:**
Given 2 cell suspensions and 6 files, when cell suspension 1 is linked to the first 3 files and cell suspension 2 is linked to the next 3 files
When the user changes the process linking cell suspension 2 to 3 files so that the 3 files will now link to 3 files of cell suspension 1
Then the changes will be submitted to DCP

or any other use cases which the following pattern applies

biomaterial -> process -> files

can’t be changed to

biomaterial -> process -> biomaterial
file -> process -> file

**Comment by aaclan-ebi** [comment]
@gabsie I've updated the acceptance criteria. This falls to the update scenario 5, 6, 7 in this doc: https://docs.google.com/document/d/1nTZDW9xQhgZfM6jQkBbK2O68CRvALPiJ8F-noiEvxTA/edit#

5. Modifying links between metadata (Updating a subgraph) with no new entities
6. Adding a metadata 
7. Modifying links between metadata (Updating a subgraph) with entities added

Ida's dataset actually needs both scenarios 5 & 6 & 7
https://docs.google.com/document/d/1eoPUxQb1-rh0mW-ku5fnCa6Oghm9KDSr3Nf5UC5jKoc/edit

We could split this ticket further so that there's 1 user story for 5 and 1 user story for 6 and 7 (which always go together). I believe it's achievable to complete both this sprint.

**Comment by gabsie** [comment]
HI, @aaclan-ebi - this sounds great!
Let's briefly chat about this at standup. I think we can split them if we think that there's a possibility only one gets done this sprint.

**Comment by ke4** [comment]
@aaclan-ebi is going to start the implementation today.

**Comment by gabsie** [comment]
This is ongoing. @aaclan-ebi has communicated with DCP components on using delta staging areas. Design document is [here](https://docs.google.com/document/d/1nTZDW9xQhgZfM6jQkBbK2O68CRvALPiJ8F-noiEvxTA/edit#)

**Comment by aaclan-ebi** [comment]
slack thread conversation with DCP components https://embl-ebi-ait.slack.com/archives/C01360XN04S/p1646068873354109

**Comment by aaclan-ebi** [comment]
@gabsie @Wkt8 @amnonkhen I'd like to scope out the support for the scenario that when a process will become a non-assay
e.g.
biomaterial -> process -> files
can’t be changed to
biomaterial -> process -> biomaterial
file -> process -> file

@ESapenaVentura thinks this is fine. @gabsie pls also confirm if this is alright with you.

**Comment by ESapenaVentura** [comment]
Deploying it to staging - Should be ready for testing soon

@aaclan-ebi to tag

**Comment by aaclan-ebi** [comment]
Hi @Wkt8 , for acceptance criteria 2 & 3, you would need the ability to add single metadata to a project.

We should be able to do it via API. I added the script in this branch to easily create metadata via Ingest API https://github.com/ebi-ait/hca-ebi-dev-team/tree/dcp-680-add-metadata-script/scripts/add_metadata

The ability to add metadata via UI is in ticket ebi-ait/dcp-ingest-central#689 .

**Comment by Wkt8** [comment]
Running the test here for acceptance criteria 1) 
https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=664a3b08-d755-47cd-8c6f-9bee8f81ea55

Test:
1. Upload spreadsheet to create a project via submission
2. Sync data files to the S3 bucket via hca-util
3. Export
4. Make linking changes between inputs to the biomaterial:
Previously:
AP1 --> AP1_spcimen, AP2 --> AP2_specimen
Changed:
AP2 --> AP1_specimen, AP1 --> AP2_specimen
5. Export again with the 'metadata only' tag
6. Check links.json in the staging area

**Comment by Wkt8** [comment]
@aaclan-ebi I have completed steps 1-5 but when I try and look for the links.json files for the relevant processes in the project i can't find them in `(gs://broad-dsp-monster-hca-dev-ebi-staging/staging/b55abecc-245f-472b-b9f9-3f9f34917125/links/)` I can see 10 links.json (5 sets of 2 files, corresponding to the initial export and update) but there are 5 more processes missing.

**Comment by ofanobilbao** [comment]
It meets acceptance criteria 1 but not 2 or 3. Wei is in the process of testing this

**Comment by idazucchi** [comment]
@ipediez or @idazucchi to test this today

**Comment by Wkt8** [comment]
Imaging test data here: https://docs.google.com/spreadsheets/d/1ZfsX5py6TOH7N-er_iT0kg2_CZqp5BWT/edit?usp=sharing&ouid=114069941208994528669&rtpof=true&sd=true

hca-util area here: a0124126-fdc0-4c27-b292-65e9d6175873

**Comment by aaclan-ebi** [comment]
**Steps to test:**
1. Create a spreadsheet to contain your test data according to the acceptance criteria
you could base it on this small test spreadsheet, which contains donor -> cell suspension -> 2 files. https://github.com/HumanCellAtlas/metadata-schema/blob/master/infrastructure_testing_files/current/dcp_integration_test_metadata_1_SS2_bundle.xlsx
2. Upload test spreadsheet to via Ingest UI.
3. Using `hca-util` cli, create test hca-util upload area and upload test files. Sync the files to the submission upload area.
Enrique pointed me to this test script to create dummy fastq's https://github.com/ebi-ait/hca-ebi-wrangler-central/blob/master/src/get_dummy_fastq.py (You could also just generate 1 and just copy and rename them locally.
Ingest doesn't do paired fastq validation yet so this works for testing)
4. Validate graph and submit the submission
5. Check the links in the Terra staging area. You must install and set up your `gsutil` in your terminal first (See instructions for setting up gsutil here: https://ebi-ait.github.io/hca-ebi-dev-team/admin_setup/Setting-up-access-to-Terra-staging-area.html#setting-up-access-to-terra-staging-area, you just need to install and login, our EBI email should be part of the DCP group which have access to the buckets )
staging: `gs://broad-dsp-monster-hca-dev-ebi-staging/staging/<project-uuid>/links/`
6. Do the update scenarios described in the acceptance criteria. You can do these via the UI.
7. If you have to create additional metadata, you could use the script here, follow the README for instructions how to use the script: 
https://github.com/ebi-ait/hca-ebi-dev-team/tree/dcp-680-add-metadata-script/scripts/add_metadata
9. Validate graph and Submit the submission again
10. Verify that linking updates were reflected in the links.json files.
- list links.json files in staging area for a projects
```
gsutil ls -l gs://broad-dsp-monster-hca-dev-ebi-staging/staging/<project-uuid>/links/
```
- check the content of a json file
```
gsutil cat gs://broad-dsp-monster-hca-dev-ebi-staging/staging/<project-uuid>/links/<filename>.json | jq
```

**Comment by idazucchi** [comment]
Running the test here for acceptance criteria 2)
https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=cbebc6f5-c36b-4f89-a2bb-ddb022e98b57

Test:
1. Upload spreadsheet to create a project via submission
2. Sync data files to the S3 bucket via hca-util
3. Export
4. Add process using [this script](https://github.com/ebi-ait/hca-ebi-dev-team/tree/dcp-680-add-metadata-script/scripts/add_metadata)
5. Make linking changes to the new and old process:
Previously:
`Analysis_1`: cell_ID_1 --> analysis_file1, analysis_file2, analysis_file3, analysis_file4, analysis_file5, analysis_file6
Changed:
`Analysis_1`: cell_ID_1 --> analysis_file1, analysis_file2, analysis_file3
`Analysis_2`: cell_ID_1 --> analysis_file4, analysis_file5, analysis_file6
5. Export again with the 'metadata only' tag
6. Check links.json in the staging area 

- [x] the links.json are ok, acceptance criteria 2 is met

**Comment by ipediez** [comment]
Test for acceptance criteria 3)
https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=4c43d4b7-ad94-435f-8de8-8cb6ad0aa23c

Test:

1. Upload spreadsheet to create a project via submission
2. Sync data files to the S3 bucket via hca-util
3. Export
4. Make linking changes between inputs to the biomaterial:
   
   Previously:
   
   specimen_ID_1--> cell_ID_1, dissociation_protocol_1
   
   Changed:
   
   specimen_ID_1--> cell_ID_1, dissociation_protocol_1, enrichment_protocol_1
5. Export again with the 'metadata only' tag
6. Check links.json in the staging area

- [x] Acceptance criteria 3 is met

**Comment by aaclan-ebi** [comment]
Many thanks, @idazucchi and @ipediez ! Promoting this to prod now.

**Comment by aaclan-ebi** [comment]
Forgot to thanks @Wkt8 as well!

**Comment by aaclan-ebi** [comment]
Promoted to prod now.
