### ISSUE TITLE
Add back "no publication or citation missing" in the project catalogue

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#683]
At some point, this feature was removed so that projects without publications don't show.

See [ops-598](https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-wrangler-central/598)

**Comment by jacobwindsor** [comment]
Done in https://github.com/ebi-ait/projects-index/pull/81

**Comment by gabsie** [comment]
So we can introduce a filter for the projects for publications, so wranglers can go and amend.
