### ISSUE TITLE
Steps to submit a suitable dataset to Cellxgene

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#693]
As a data wrangler, I would like to now all necessary steps to submit a project to CellxGene, so that I can start wrangling.

Acceptance criteria:
Given a project is suitable for CellxGene (ticket),
When I follow the steps below, 
I can prepare all necessary files to submit to CellxGene.

**Comment by Wkt8** [comment]
Document here: Steps to be further detailed. https://docs.google.com/document/d/1UVGIllybmEI46x22NSDpMNRywT3c8hcGrcw6opiHdbg/edit#

**Comment by ESapenaVentura** [comment]
@gabsie to review, the document is ready for someone to follow. A wrangler may also be needed to review, TBD.

**Comment by gabsie** [comment]
This document is fine by me. However, it mostly needs to serve other wranglers so that they can do cellxgene wrangling as well.
