### ISSUE TITLE
Validate file metadata before data file upload

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/dcp-ingest-central#7]
## User Story

As a wrangler I would like to be able to upload and validate metadata prior to uploading and validating data files, this is because most issues are in the metadata and validation is quick. The whole process is substantially slower if I have to do it with the data files too and there is an issue with the metadata. 

Change the order of submission process.
Upload spreadsheet first and validate metadata prior to uploading the data files.
status should reflect the multiple "valid/invalid" states.

Define flow of submission flow
Define status flow, one valid status to describe valid metadata and files. Remains in draft unless metadata fails then becomes invalid. 
Pop up/ communicate to the user somehow that the metadata has been validated.

## Acceptance Criteria
Metadata can be uploaded and validated without files being present
User knows when metadata has passed or failed validation

**Comment by rays22** [comment]
* As part of the test plan of [Impact 1 - Update metadata and data for a project](https://docs.google.com/spreadsheets/d/1sf_PnPRufEPUeqkADhewJGJsYsb00CBwymKKPFB_VHI/) I did  functional tests:
    - [x] Validate file metadata before data file upload: all tests PASS.

The test `xlsx` and `fastq.gz` sequence files I used for testing can be found in gdrive folder [impact1 test files (xlsx spreadsheets)](https://drive.google.com/drive/folders/1d1YTB2PKXbL9C4CY83e8LZBq72i6Hxv0)

**Comment by aaclan-ebi** [comment]
Thanks for testing this @rays22 ! The ingest integration tests are also now passing for this. We'll promote this to prod on monday.
