### ISSUE TITLE
ENA creates a new BioSamples when direct archiving a biomaterial

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#703]
When we send a biomaterial with direct archiving into the ENA archive it creates a new BioSamples as we are not sending the already created BioSamples accession in the `sample XML` request.

**Acceptance criteria:**
The created ENA sample should not create a new sample in BioSamples, but linked to the already created BioSamples.

**Comment by MightyAx** [comment]
Rumour from Tony "We don't have to send samples to ENA, we can just reference BioSamples".
**Confirmed by the Documentation!**

**Comment by ke4** [comment]
In this ticket: [Remove ENA sample submission from direct archiving](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/705) I removed the sample submission to ENA. Therefore, we don't need to fix this issue.
I am going to move this ticket to Done.
