### ISSUE TITLE
Linking to previous entities doesn't work in spreadsheet import

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#712]
This happened to Ida's dataset ebi-ait/hca-ebi-wrangler-central#699

**Steps to replicate:**
1. Create 2 spreadsheets.

  spreadsheet 1 should contains:
  > donor 1 ->  specimen 1 (linked via collection protocol 1)
  > specimen 1 -> cell suspension  1(linked via dissoc protocol 1 and enrichment protocol 1) 
  > cell suspension 1 -> 2 files (linked via sequencing protocol 1, lib prep protocol 1)

  spreadsheet 2 contains:
  > specimen 2 linked to donor 1 via collection protocol 1

2. Upload the first spreadsheet, upload files, validate the graph and submit it to HCA.
3. Upload the second spreadsheet, upload files and validate the graph.

**Actual Behavior:**
Graph validation will have errors because there are orphan entities
The process is linked to the specimen but has no input biomaterial nor protocol

**Expected Behavior:**
Graph validation should succeed. There should be no orphan entities.
The specimen 2 should be linked to the donor and the linking process is linked to protocol 1 in Ingest DB.

**Comment by jacobwindsor** [comment]
Devs to review

**Comment by aaclan-ebi** [comment]
Fix is in staging.

**Comment by aaclan-ebi** [comment]
Not sure if we need wrangler testing, i've verified the fix myself. We have a dataset waiting for this fix in prod. cc @ami-day 

I would need to deploy the broker to prod and that contains other changes from different tickets.

**Comment by aaclan-ebi** [comment]
Promoted to prod.

**Comment by Wkt8** [comment]
Moved back into 'In Code Review' as there's still an issue with specimen - donor linking in bulk.

**Comment by aaclan-ebi** [comment]
Deployed fix in staging, @idazucchi pls test, thanks Ida!

**Comment by aaclan-ebi** [comment]
@idazucchi found another issue, but we couldn't verify if the scenario was ever supported.

It's not possible to link a row to an existing entity and new entity of the same concrete type

**Steps to replicate:**
1. Create 2 spreadsheets.

  spreadsheet 1 should contains:
  > donor 1 ->  specimen 1 (linked via collection protocol 1)
  > specimen 1 -> cell suspension  1(linked via dissoc protocol 1 and enrichment protocol 1) 
  > cell suspension 1 -> 2 files (linked via sequencing protocol 1, lib prep protocol 1)

  spreadsheet 2 contains:
  > new donor 2
  > specimen 2 linked to donor 1  and donor 2 via collection protocol 1


2. Upload the first spreadsheet, upload files, validate graph and submit to HCA.
3. Upload the second spreadsheet, upload files and validate the graph.


**Actual Behavior:**
The specimen is linked to donor 1 only

**Expected Behavior:**
The specimen 2 should be linked to donor 1  and donor 2 and the linking process should be linked collection protocol 1 in Ingest database

I'll create a different ticket for this. This issue could be treated as bug/enhancement but priority is low as it's not needed in any dataset. There is also a workaround to this via the UI.
