### ISSUE TITLE
Elixir -> Life SCience Login migration

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#714]
Elixir AAi is to be retired on 11.4.2022
https://lifescience-ri.eu/ls-login/elixir-migration-news.html

ingest would need to adapt its login flow.

- [x] impact assessment session
- [x] dev task breakdown
   - [ ] change elixir to LSL icons

**Comment by jacobwindsor** [comment]
Blocked by #689 deployment
