### ISSUE TITLE
A submission guide section with information for end contributors

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#717]
- [ ] As a potential data contributor, I would like to find an area of the Contribute website which will guide me in the process of submission to HCA.

**Acceptance Criteria / Definition of Done**

* Given I find or am directed to the HCA Ingest website
* When I visit the Submission Guide section
* Then I can find answers to my questions on data types and formats, and steps.

Tasks:

- [x] Design: decide where the guide lives
- [ ] Propose content design
- [ ] Propose design options which fit the content
- [x] Dev discussion on implementation and updates
- [x] Implementation

**Comment by gabsie** [comment]
First version of a design (still have to see about the right VF components), but can work as a prototype first. The sizing of the page is also not right yet

![Sprint 6 April - Project tab - Submission guide.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/9f91a914-4fcb-4fd7-bd98-ed3989291c5e)

![Sprint 6 April - Project tab - Submission guide 2.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/e14ca9cb-2a39-4379-8474-a20da2274a83)

**Comment by gabsie** [comment]
Hey @jacobwindsor - as a start, please consider these two pages as placeholders for 2 pages from the Submission guide:
https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/dataset_suitability_SOP.html
https://ebi-ait.github.io/hca-ebi-wrangler-central/SOPs/GDPR_Guidelines.html

These two pages will fall under the category of Data requirements, from the first version of the suggested design above. I will have time in the afternoon to chat through this :) Please consider also having a diagram in one of the pages, the Data Policy one will probably have the GDPR diagram in a similar format.

I will later change the copy to be contributor-focused and not wrangler focused, but the overall size and contents should be okay for you to get started.

**Comment by idazucchi** [comment]
finishing off page layout, the pages will render markdown documents

**Comment by yusra-haider** [comment]
code implementation done by @jacobwindsor. Waiting on content from @gabsie

**Comment by jacobwindsor** [comment]
https://github.com/ebi-ait/ingest-ui/pull/173

**Comment by ESapenaVentura** [comment]
@gabsie has a starter page - Working on this today

**Comment by ESapenaVentura** [comment]
Set up deadline for Friday 28th

**Comment by gabsie** [comment]
@ofanobilbao I am starting here, and we can continue working together here
https://docs.google.com/document/d/1eIAsRIUmUtJaPgTMuFuHjMGCm3fhg0oefLfYeElZM-M/edit?usp=sharing 
I am also doing a visualisation also in Miro

**Comment by idazucchi** [comment]
gabs to send the first page for review today

**Comment by gabsie** [comment]
https://docs.google.com/document/d/1eIAsRIUmUtJaPgTMuFuHjMGCm3fhg0oefLfYeElZM-M/edit?usp=sharing

**Comment by Wkt8** [comment]
@idazucchi and @Wkt8 to review this document. Oihane has reviewed.

**Comment by gabsie** [comment]
@amnonkhen - can you please look at the code etc using the example text from the doc? I will arrive on campus and continue catching up.

**Comment by amnonkhen** [comment]
@gabsie Here is what it looks like. What do you think?
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/46721860-5f95-4398-8164-38dcbfb60a78)

**Comment by MightyAx** [comment]
@Gabs to make minor visual changes.

**Comment by gabsie** [comment]
Hey Amnon
In the file, I changed the subsections to have shorter names:
https://docs.google.com/document/d/1eIAsRIUmUtJaPgTMuFuHjMGCm3fhg0oefLfYeElZM-M/edit?usp=sharing

**Comment by MightyAx** [comment]
submission guide has been deployed to [dev](http://dev.contribute.data.humancellatlas.org) for testing

**Comment by ESapenaVentura** [comment]
I have a couple of comments:
- Is there any way for the TOC on the left to follow the screen? if I scroll down, I would like to still see the table
- Can we change the font a bit? I don't know how to make it better, but right now the font looks very sharp and clumped.
- I would re-factor the content a bit:
   - Moving the "contribution checklist" to the top, with links to each of the different sections
   - I would put the first paragraph (`The Human Cell Atlas Data Coordination Platform supports scientists in their atlas-building efforts by providing easy access to cellular-resolution data generated by the research community.`) Directly below the Data requirements title.
   - I would add bulleted lists to other parts

I can create a PR for the content changes, let me know!

**Comment by ofanobilbao** [comment]
This is now live in Dev. @gabsie will review the content and edit it. Amnon showed her how to be able to edit going forward

**Comment by Wkt8** [comment]
Gabs to continue editing and then to create a PR for merging into prod / master. Alexie and Enrique to support if necessary.

**Comment by MightyAx** [comment]
deploying to staging

**Comment by MightyAx** [comment]
@gabsie 
- [x] to post the minor edit required

@MightyAx / @amnonkhen 
- [ ] to Commit / PR / merge to production

**Comment by gabsie** [comment]
This is ready for Prod as far as I am concerned

**Comment by idazucchi** [comment]
alexie will push this to prod today

**Comment by MightyAx** [comment]
- [x] put it on the main branch so it is
deployed to staging and tested there
- [x] check it in staging manually
- [x] promote to prod.
