### ISSUE TITLE
Unable to download spreadsheet from ingest UI using GEO accession

### ISSUE THREAD

**Issue by brittneydwick** [ebi-ait/dcp-ingest-central#723]
Hi there, 

I tried to download a spreadsheet for GSE176509, project UUID 5ae10405-795e-42e5-85de-3c3154f9c526 and got the following error:
![Screen Shot 2022-03-22 at 10 26 17 AM](https://user-images.githubusercontent.com/72572505/159539858-88b04dfc-fe8b-41db-8856-907eb135d338.png)

Any ideas what to do?

**Comment by ESapenaVentura** [comment]
Moved to dcp-ingest-central and added the bug label, as well as moving it to the sprint backlog

**Comment by gabsie** [comment]
fixed yesterday and there's a PR.

**Comment by brittneydwick** [comment]
Thank you, everyone!

**Comment by jacobwindsor** [comment]
Fixed by fixes in #707 - waiting for user testing. @brittneydwick please note we found more issues but they are specific to large projects so shouldn't affect everything

**Comment by ipediez** [comment]
@jacobwindsor to add @yusra-haider to the discussion
