### ISSUE TITLE
Data file archiving failed in dev env without meaningful error message

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#725]
I followed these steps to be able to archive a dataset with metadata:

1. Upload a spreadsheet from here: https://docs.google.com/spreadsheets/d/1L6FfWzYfJX8u_ge0w_u13obrAEZJy50d/edit?usp=sharing&ouid=103883794928474636291&rtpof=true&sd=true
2. Upload data files (mock files) with hca-util from here: s3://hca-util-upload-area/8387594c-342d-43b0-b6f2-4d391af605aa/
3. After all files became valid do graph validation
4. Go to Submit tab and submit to EBI archives (1st checkbox should be checked)
5. Follow the instruction to upload the data files to ENA. Instructions are here: https://github.com/ebi-ait/ingest-archiver/blob/dev/README_for_direct_archiver.md
6. After I triggered data file upload based on the above instructions I got a successful message to trigger the file upload:
```
curl -X POST https://archiver.ingest.dev.archive.data.humancellatlas.org/archiveSubmissions/data -H 'Content-Type: application/json' -H "Api-Key:$ARCHIVER_API_KEY" -d '{"sub_uuid": "4b621165-7670-4e60-9f12-9de84753c7b3"}'
{"message":"Data archiving request triggered successfully"}
```
7. I tried to get the status of the data file upload, but I got a 500 error:
```
curl -X GET  https://archiver.ingest.dev.archive.data.humancellatlas.org/archiveSubmissions/data/4b621165-7670-4e60-9f12-9de84753c7b3 -H "Api-Key:$ARCHIVER_API_KEY"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

When I checked the logs in the pod it is not really gave me anything more:
```
$kubectl logs ingest-data-archiver-57ccf8dd4f-fs6gd
 2022-03-08 09:20:25,247  - ingest-data-archiver - INFO in main.py:34 <module>(): Ingest data archiver listening...
 2022-03-24 17:15:31,178  - data.archiver.listener - INFO in listener.py:56 _data_archiver_message_handler(): Data archiving request failed: {'sub_uuid': '4b621165-7670-4e60-9f12-9de84753c7b3'}
```

**Comment by ipediez** [comment]
@ke4 and @prabh-t to have a discussion today about this

**Comment by Wkt8** [comment]
Prabhat can now archive one of the data files successfully. Further checks are required. Prabhat and Karoly to continue working on this.
