### ISSUE TITLE
Avoid redundant metadata validation on linking changes

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#736]
**Background:**
We added a change  https://github.com/ebi-ait/ingest-core/pull/101 is causing a lot of validation messages in the queue and also causing linking during importing to be very slow. This change is to set back the metadata to draft for every linking change so that the submission will go back to Draft and let the user revalidate the graph.

**The issue with that change:**

If a process is linked 3 times,  to file, to protocol and to the biomaterial, the process metadata JSON will be validated 3 times as well when its JSON hasn't even changed. This is causing 2 redundant validation. And if there are 70k+ linking, this is going to do 70k * no. of entities (let's say 2-3) draft events to go to the validation queue. These are a lot of messages which go to the metadata validation queue and validator and lots of requests to the core and state tracker for the validating and valid state transitions.

The following submission took 10hrs~ to finish linking:
```
{
"expectedBiomaterials": 2086,
"expectedProcesses": 7237,
"expectedFiles": 6397,
"expectedProtocols": 36,
"expectedProjects": 1,
"actualLinks": 76295,
"expectedLinks": 76295,
"totalCount": 15757,
"submissionDate": "2022-03-30T11:45:22.610Z",
"updateDate": "2022-03-30T21:56:53.867Z",
...
"_links": {
"self": {
"href": "https://api.ingest.archive.data.humancellatlas.org/submissionManifests/624442d2b06b223527d3df68"
}
...
```

Diagram showing metadata redundant validation
```mermaid
sequenceDiagram

  participant Broker
  participant Core
  participant State as State Tracker
  participant Validator
  

  Broker-->>Core: creates metadata 1
  Core-->>Core: creates metadata with initial validationState DRAFT
  Core-->>State: sends message that there is new metadata in DRAFT

  Core-->>Validator: sends message for metadata 1
  Validator-->Core: sets metadata 1 validationState to VALIDATING
  Core-->>State: sends a message that a metadata 1 is set to VALIDATING

  Validator-->>Validator: validates metadata 1 json against json schema and ontology api
  Validator-->Core: sets metadata 1 validationState as VALID or INVALID + validation error
  Core-->>State: sends a message that a metadata 1 is set to VALID/INVALID

  State-->>State: checks if submission should be set to DRAFT/VALIDATING/VALID/INVALID
  State-->>Core: sets submission state to DRAFT/VALIDATING/VALID/INVALID <br/> PUT /commitValidating or <br/> PUT /commitValid ...

  Broker-->>Core: links metadata 1 to metadata 2
  Core-->>Core: sets both to DRAFT
  Core-->>Validator: sends message for metadata 1 and metadata 2
  
  Validator-->>Validator: validates metadata 1 json against json schema and ontology api
  Validator-->Core: sets metadata 1 validationState as VALID or INVALID + validation error
  Core-->>State: sends a message that a metadata 1 is set to VALID/INVALID

  State-->>State: checks if submission should be set to DRAFT/VALIDATING/VALID/INVALID
  State-->>Core: sets submission state to DRAFT/VALIDATING/VALID/INVALID <br/> PUT /commitValidating or <br/> PUT /commitValid ...


  Validator-->>Validator: validates metadata 2 json against json schema and ontology api
  Validator-->Core: sets metadata 2 validationState as VALID or INVALID + validation error
  Core-->>State: sends a message that a metadata 2 is set to VALID/INVALID

  State-->>State: checks if submission should be set to DRAFT/VALIDATING/VALID/INVALID
  State-->>Core: sets submission state to DRAFT/VALIDATING/VALID/INVALID <br/> PUT /commitValidating or <br/> PUT /commitValid ...
```

**Solution:**
Set the metadata back to draft iff the submission state is Graph Valid

**Comment by Wkt8** [comment]
Testing is failing but uncertain if this is due to issues with State Tracker or with issues with the code. Alegria and Jacob to pair on this.

**Comment by aaclan-ebi** [comment]
This will actually fix https://github.com/ebi-ait/dcp-ingest-central/issues/633 because it will no longer set the metadata entity to Draft if its submission is not Graph Valid. The first submission will always be in Exported (or state after Submitted).

**Comment by jacobwindsor** [comment]
This is now in staging and ready for testing if @ami-day has time

**Comment by gabsie** [comment]
relates to [633](https://github.com/ebi-ait/dcp-ingest-central/issues/633)

**Comment by aaclan-ebi** [comment]
Tested in dev and it took only 46 minutes to import 70k links compared to ~5hrs before

submission manifest:
```
"submissionDate": "2022-04-01T12:06:09.416Z",
"updateDate": "2022-04-01T12:52:00.703Z",
```

**Comment by Wkt8** [comment]
@aaclan-ebi does this still need a wrangler?

**Comment by aaclan-ebi** [comment]
No, this one doesn't need a wrangler, since this is a non-functional change.  But it's linked to the [dcp-633](https://github.com/ebi-ait/dcp-ingest-central/issues/633) that one needs wrangler testing. They have the same fix so they're kind of tied together and I've put them on the same pipeline.
