### ISSUE TITLE
Cannot link to existing and new entity of same domain type in a spreadsheet at the same time

### ISSUE THREAD

**Issue by aaclan-ebi** [ebi-ait/dcp-ingest-central#740]
Scoped out from ebi-ait/dcp-ingest-central#712

**Steps to replicate:**
1. Create 2 spreadsheets.

  spreadsheet 1 should contains:
  > donor 1 ->  specimen 1 (linked via collection protocol 1)
  > specimen 1 -> cell suspension  1(linked via dissoc protocol 1 and enrichment protocol 1) 
  > cell suspension 1 -> 2 files (linked via sequencing protocol 1, lib prep protocol 1)

  spreadsheet 2 contains:
  > new donor 2
  > specimen 2 linked to donor 1  and donor 2 via collection protocol 1

2. Upload the first spreadsheet, upload files, validate graph and submit to HCA.
3. Upload the second spreadsheet, upload files and validate the graph.

**Actual Behavior:**
The specimen is linked to donor 1 only

**Expected Behavior:**
The specimen 2 should be linked to donor 1  and donor 2 and the linking process should be linked to collection protocol 1 in Ingest database

Workaround: Do linking via UI

**Comment by aaclan-ebi** [comment]
This is now in staging, @idazucchi would you be able to verify this in staging? Thanks!

**Comment by idazucchi** [comment]
I tested this with submission ticket280_test_case2 in staging 
In one process I can link:
- existing and new biomaterials
- existing and new protocols

 the fix is working correctly!
