### ISSUE TITLE
Fix memory usage not shown for containers

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#741]
Memory usage per container is not showing in `kubectl`. Need to investigate why and fix

**Comment by MightyAx** [comment]
https://github.com/ebi-ait/ingest-kube-deployment/pull/45

**Comment by jacobwindsor** [comment]
I'm going to wait until Thursday to deploy this to prod so that any complications will have time to highlight in staging or dev
