### ISSUE TITLE
Metadata valid/invalid status

### ISSUE THREAD

**Issue by clairerye** [ebi-ait/dcp-ingest-central#75]
## User Story
As a wrangler I want to understand if metadata is valid or not so that I can either correct it or proceed with file upload.

## Acceptance Criteria
User can instantly see that if the metadata is valid or not before the files have been uploaded.
User can see where any errors are and can be linked directly to see them so they can understand what the error is
filter for file metadata to separate invalid file metadata from missing files

**Comment by aaclan-ebi** [comment]
Tasks:
1. (new ticket) [Core] Create an endpoint to return metadata based on validation error type
- not sure how easy/difficult is this
1. (new ticket) [Validator] Add error type in the validation report
1. (new ticket)[UI] Display error count/summary according to the mockup
- @gabsie, could you post the mock up here (it's okie if it's not final yet)
- i'm not sure if we need more endpoints for this, i think we can use the existing endpoints to get the entities (and the count) by validation state
1. (new ticket) [UI] Filter metadata by error type
- the changes might be overlapping with the first UI task, not sure if a new ticket is needed, 2 people can just coordinate the changes in 1 branch

**Comment by prabh-t** [comment]
Has the acceptance criteria changed based on what was discussed during our meeting? @gabsie can you please add the mockups to the ticket? I don't think this requires changes to the validator or core, it may be just representational changes in the UI, but I can't remember what we finally decided or if we're waiting for more input from Gabs.

**Comment by aaclan-ebi** [comment]
Notes:

Example file metadata with different error types
1. file metadata schema validation error: https://api.ingest.staging.archive.data.humancellatlas.org/files/5fb3dcb8f423490510b8633b
2. data file validation error: https://api.ingest.staging.archive.data.humancellatlas.org/files/5fb4abfaf423490510b86380
3. file is not uploaded: https://api.ingest.staging.archive.data.humancellatlas.org/files/5fb3dcb8f423490510b8633c

we might be able to reuse the generic search endpoint for files (`files/query`)


e.g. to query file metadata list with file metadata schema validation errors:
```
POST https://api.ingest.staging.archive.data.humancellatlas.org/files/query?operator=AND

[
{
	"field": "validationState",
	"operator": "IS",
	"value": "INVALID"  // or Invalid?
},
{
	"field": "cloudUrl",
	"operator": "IS",
	"value": null // not sure if this will work
}, {
	"field": "submissionEnvelope.id",
	"operator": "IS",
	"value": "5fb4abf1f423490510b86379"
}]

```

**Comment by aaclan-ebi** [comment]
Ignore the criteria above. It wouldn't work, cloudUrl is also null for file metadata documents without data files uploaded yet. 🤔

**Comment by gabsie** [comment]
Hi, do you need these in another ticket?
here you go: https://app.zenhub.com/workspace/o/ebi-ait/dcp-ingest-central/issues/91

Gabs

**Comment by yusra-haider** [comment]
Discussion document for API side: https://docs.google.com/document/d/1UlBWc1zqEGAMS1HnbRdNzmXmsH7Tt9-EHPaujcnwvxs/edit?ts=5fbbc669#

**Comment by gabsie** [comment]
cc @ESapenaVentura : maybe place all your comments according to the test plan here, Enrique:

Gabs!

**Comment by aaclan-ebi** [comment]
looks like we have a bug in the validator/file validation , there's no error type for data file errors


https://contribute.data.humancellatlas.org/submissions/detail?uuid=f13d6ad4-69d8-48fb-82b5-dc1f8933e8f3


![Screenshot 2020-12-08 at 10.56.10.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/b21141d7-d904-44f9-a321-5aa99cc879b9)


https://api.ingest.archive.data.humancellatlas.org/files/5fcf5110cb48a221817bfecd

```
{
	"dcpVersion": "2020-12-08T10:10:24.898Z",
	"accession": null,
	"validationState": "Invalid",
	"validationErrors": [{
		"user_friendly_message": "ERROR: Error in file /data/f13d6ad4-69d8-48fb-82b5-dc1f8933e8f3/SRR10433203_2.fastq.gz: line 19140: sequence and quality don't have the same length 98!=34"
	}],
	"isUpdate": false,
	"fileName": "SRR10433203_2.fastq.gz",
	"cloudUrl": "s3://org-hca-data-archive-upload-prod/f13d6ad4-69d8-48fb-82b5-dc1f8933e8f3/SRR10433203_2.fastq.gz",
	"checksums": {
		"sha1": "06815f757e89fae8fac216e34c3f079153a6b3c2",
		"sha256": "137967d15b8dfd255d0781c70da6c49811cf862f06ce2a8dff64848891b1bf63",
		"crc32c": "9f56553e",
		"s3_etag": "6920cd3b487728943e43db704ee4205d"
	},
	"validationJob": {
		"validationId": "bdb229d9-7309-41c7-9213-16555c78b510",
		"checksums": {
			"sha1": "06815f757e89fae8fac216e34c3f079153a6b3c2",
			"sha256": "137967d15b8dfd255d0781c70da6c49811cf862f06ce2a8dff64848891b1bf63",
			"crc32c": "9f56553e",
			"s3_etag": "6920cd3b487728943e43db704ee4205d"
		},
		"jobCompleted": true,
		"validationReport": {
			"validationState": "Invalid",
			"validationErrors": [{
				"user_friendly_message": "ERROR: Error in file /data/f13d6ad4-69d8-48fb-82b5-dc1f8933e8f3/SRR10433203_2.fastq.gz: line 19140: sequence and quality don't have the same length 98!=34"
			}]
		}
	},
	"validationId": null,
	"dataFileUuid": "b3c77c78-55cd-43f8-bc1c-8c0f19061279",
	"size": 327680,
	"fileContentType": "application/gzip; dcp-type=data"
}
```

Validation errors should have error type attributes

![Screenshot 2020-12-08 at 10.59.07.png](https://images.zenhubusercontent.com/5b042c754b5806bc2bd426e2/fa054160-23ee-4d0c-9ee7-a0d86962c103)
