### ISSUE TITLE
When adding a new metadata to a submission it should also be added to the submission's project.

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/dcp-ingest-central#750]
Bug found in the UI where the supplementary link between metadata and project is not being added correctly when posting new metadata.
**This previously worked** but reveals the solution should really be in core rather than the UI:

when Posting to sue/id/biomaterials the biomaterial is created and added to the submission envelope, it should also be added to the project if the submission envelope has one.

**Comment by ESapenaVentura** [comment]
PRs to be reviewed - @aaclan-ebi if you could take a look. it would be great

**Comment by MightyAx** [comment]
Merged to master with 752, deploy to ingest ui failed over the weekend but has been re-deployed to staging now.

**Comment by gabsie** [comment]
Alexie will continue testing on this
