### ISSUE TITLE
Block users from editing or deleting metadata but not adding when in METADATA_VALIDATING

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#752]
At the moment after #730, core does not block requests to patch, post, or delete to metadata endpoints when a submission is in METADATA_VALIDATING. This is because the spreadsheet importing needs to update the submission while it is still in METADATA_VALIDATING.

To circumvent this, in #730 and [this commit](https://github.com/ebi-ait/ingest-ui/commit/0938ce1bee35443f9eb5f965b0e4e36964e3c4e6), the UI is blocked during METADATA_VALIDATING. This is not foolproof though, so we should block in core too.

We can block PATCH and DELETE but not POST and the importer will not be affected.

**task**
- [x] use new `CheckAllowed` annotation on PATCH and DELETE endpoints for metadata entities and use a rule for checking if submission is in METADATA_VALIDATING. Maybe refactor the `isEditable` function on SubmissionEnvelope into `isEditable` and `canAddTo`
- [x] check if any other endpoints need this new guard

**Comment by jacobwindsor** [comment]
https://github.com/ebi-ait/ingest-core/pull/126
https://github.com/ebi-ait/ingest-ui/pull/171

**Comment by gabsie** [comment]
Hopefully today will be in production as well
