### ISSUE TITLE
Add a new resource to ingest core to track archiving jobs

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#755]
We need a new resource in ingest-core to be able to track archiving process as it could be a long running process. It has to communicate with 3 different EBI archiving service, so it could take some time to send all metadata that belongs to a submission.

The new resource name: `archiveJob`

It contains the following fields:
- uuid
- submissionUuid
- datetimeStarted
- datetimeReturned
- overallStatus (enum: `Pending`, `Running`, `Failed`, `Completed`)
- result
```
    "project": {
        "biostudies_accession": "S-BSST827",
        "ena_project_accession": "ERP137556",
        "entity_type": "projects",
        "info": "BioStudies from HCA projects",
        "is_update": false,
        "uuid": "4ee563ab-625b-4b01-82c1-1db9832a1921"
    },
    "samples": {
        "entities": [
            {
                "biosamples_accession": "SAMEA9288570",
                "entity_type": "biomaterials",
                "is_update": false,
                "uuid": "535f8cce-77f2-48ae-aee7-7861568005fb"
            },
            {
                "biosamples_accession": "SAMEA9288571",
                "entity_type": "biomaterials",
                "is_update": false,
                "uuid": "4997a36f-8fa3-425f-92c2-26d1a591e712"
            }
        ],
        "info": "Biosamples from HCA biomaterials"
    }
```

We should be able to create this resource with a POST REST call like this:

Request:

```
POST /archiveJobs
```

with payload:

```
{
    "submissionUuid": "1234"
}
```

Successful response:

```
HTTP 200
{
    "submissionUuid": "1234",
    "createdDate": "2022-04-22T17:19:44.805693Z",
    "overallStatus": "Pending"
}
```

**Comment by prabh-t** [comment]
- added datetime fields
- removed redundant field
- discussed that there is no need to have an overall status as this can be determined by inspecting the result content and this will avoid possible inconsistency between the two fields. 
- submission envelope needs to have reference to archiveJobs entities `submissionEnvelope/<uuid>/archiveJobs` and the other direction (archiveJob to have a reference to submission uuid)

**Comment by ipediez** [comment]
@ke4 please add as a dependency the corresponding tickets. Thanks!

**Comment by prabh-t** [comment]
@ke4 to deploy to prod.
