### ISSUE TITLE
Update ingest archiver to save (POST) archiving result to new ingest entity 

### ISSUE THREAD

**Issue by prabh-t** [ebi-ait/dcp-ingest-central#760]
Currently the user waits for the archive result / output in the console when the archiving request is triggered.
This should now 
- return a "Archiving triggered... check status at ENDPOINT"
- the archiving process runs in the background and instead of printing to the console, save the output to the new ingest entity

**Comment by Wkt8** [comment]
Code refactoring in progress.

**Comment by MightyAx** [comment]
PR for Happy Path done.
WIP in progress for unhappy path.

@MightyAx to look at code review
