### ISSUE TITLE
File descriptor not being filled when exporting

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/dcp-ingest-central#764]
**Describe the bug**
Jeff Korte (Broad Institute) reported some [Release 16](https://docs.google.com/spreadsheets/d/1xApi-qay1H9ef2JQAmPNXH63Xy-0cNYBN4wBaq-YC3U/edit#gid=398656126) validation errors, 7 out of 8 with the following description:

> Malformed descriptor files. File_id should be type string and is None instead. This is a required field, per the JSON schema

This is a field filled automatically by Ingest when exporting. All the errors come from EBI and UCSC datasets, the two teams using ingest.
| institute | email | uuid | terra | spreadsheet |
|---------|------|-----|---|----|
|UCSC |  raschwar@ucsc.edu	|`2253ae59-4cc5-4bd2-b44e-ecb6d3fd7646`
|EBI |  ipediez@ebi.ac.uk	|`c16a754f-5da3-46ed-8c1e-6426af2ef625` |[terra staging area](https://console.cloud.google.com/storage/browser/broad-dsp-monster-hca-prod-ebi-storage/prod/c16a754f-5da3-46ed-8c1e-6426af2ef625;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false) |[spreadsheet](https://docs.google.com/spreadsheets/d/17BkRG8Jk105ipcISsELZL5CAkxsJ7tiG/edit#gid=1694118826)|
|EBI |  ami@ebi.ac.uk|	`f4d011ce-d1f5-48a4-ab61-ae14176e3a6e`|
|EBI |  ami@ebi.ac.uk|	`0b299140-25b5-4861-a69f-7651ff3f46cf`|
|EBI |  ami@ebi.ac.uk|	`94e4ee09-9b4b-410a-84dc-a751ad36d0df`|
|UCSC |  wisulliv@ucsc.edu	|`daa371e8-1ec3-43ef-924f-896d901eab6f`|
|UCSC|  wisulliv@ucsc.edu|	`cfece4d2-f18d-44ad-a46a-42bbcb5cb3b7`|

Coding Tasks:
- [x] validation of generated file descriptor in _ingest-exporter_ using the schema
- [x] validation of create/update file endpoint in _ingest-core_ - see [docs](https://reflectoring.io/bean-validation-with-spring-boot/)
- [x] print file details to log  after creation/update in order to see how real data behaves and understand how the dataFileUuid is being set/changed.
- [x] fix setting the `dataFileUuid` for new File documents
- [x] update the missing dataFileUuid fields in ingest uuid
- [ ] re-export release 16 datasets - see ebi-ait/hca-ebi-wrangler-central#783

**Comment by amnonkhen** [comment]
Some findings:
1. exporter gets a null `dataFileUuid` from core
2. exporter does not validate the generated _file_descriptor_ json files according to the schema. According to the [schema](https://schema.humancellatlas.org/system/2.0.0/file_descriptor) the field file_id is a mandatory string
3. in the prod DB: ~380k files with dataFileUuid ~16k without

Open questions:
1. Is this validation by the Data Importer new? [waiting on Jeff Korte for answers](https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1651163416629819?thread_ts=1650938033.125249&cid=C9XD6L0AD)
2. Which projects do the files with null dataFileUuid belong to?

<details>
  <summary>Mongo Query used to find which projects have files with null <code>dataFileUuid</code></summary>
  
 ```javascript
db.file.aggregate([
    {$match: { "dataFileUuid": null }},
    {$group: { _id: "$project"}},
    {$addFields: {"project_fk": 
                {$arrayElemAt: [{ $objectToArray: "$_id" },1]}
            }},
         {
    $addFields: {
        "project_fk": "$project_fk.v"
    }
    },
     {
    $lookup: {
        from: "project",
        localField: "project_fk",
        foreignField: "_id",
        as: "project"
    }},
    {$unwind:'$project'},
    {$project:{
        dcpVersion:'$project.dcpVersion',
        short_name: '$project.content.project_core.project_short_name',
        wranglingState: '$project.wranglingState',
        primaryWrangler:  { "$toObjectId": "$project.primaryWrangler" },
        uuid: '$project.uuid.uuid',
    }}, 
     {
    $lookup: {
        from: "account",
        localField: "primaryWrangler",
        foreignField: "_id",
        as: "wrangler"
    }},
])
```
</details>

**Comment by prabh-t** [comment]
@amnonkhen and @prabh-t did some investigations yesterday. During export, we do not validate the file (json) we generate. To discuss after standup.

**Comment by Wkt8** [comment]
Amnon will be meeting with @MightyAx and @jacobwindsor to discuss.

**Comment by Wkt8** [comment]
Divide into two tasks:
- workaround to fix the 'file_id' string @ESapenaVentura and @amnonkhen 
- investigation of why this was caused and how to stop it from happening

**Comment by MightyAx** [comment]
@amnonkhen,  @jacobwindsor & @prabh-t to collaborate and look at this today

**Comment by idazucchi** [comment]
culprit commit found, tests added.
The submission might need to be uploaded again - amnon is looking for a workaround

**Comment by amnonkhen** [comment]
@amnonkhen, @jacobwindsor & @prabh-t have found the problem, and coded the fix. Next steps are to update ingest DB with the missing `dataFileUuid`s and re-export. ETA Mon 9/5

**Comment by yusra-haider** [comment]
integration tests are failing for something unrelated to the ticket change. @jacobwindsor is taking a look

Wrangler help needed for re-exporting. @ipediez and @ESapenaVentura to help which we will track under ops ticket: ebi-ait/hca-ebi-wrangler-central#783

**Comment by MightyAx** [comment]
- [x] PUT https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/6256fcf90d00514fc6979a85/commitGraphValidEvent

**Comment by amnonkhen** [comment]
We need to facilitate re-exporting the file descriptors. 
Options:
1. delete the corrupt file descriptors and re-export
2. update the dcpVersion field of the corrupt file documents and re-export

Option 1 seems simplest.

**Comment by ESapenaVentura** [comment]
Doing some research, re-exporting is the issue now. The development is done now.
See ops ticket ebi-ait/hca-ebi-wrangler-central#783
