### ISSUE TITLE
Avoid duplications of projects in ingest by having multiple ways of creating a project 

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#767]
As a data wrangler, I want to avoid creating multiple versions of a project by going directly through Submissions and uploading a spreadsheet, while a Project might already exist in Ingest backoffice. 

### Temporary Acceptance criteria - disable "Upload New Submission" button:
Given a Project already exists in backoffice
When I want to upload a spreadsheet with metadata
I can only do that for an existing project

### Longer term Acceptance Criteria - update if duplicate
needs discussion and prioritisation.
see #809

**Comment by gabsie** [comment]
Make this ticket a bit more specific @gabsie

**Comment by ofanobilbao** [comment]
ebi-ait/dcp-ingest-central#808 would need to be addressed as part of this ticket

**Comment by ESapenaVentura** [comment]
@ke4 to review, @amnonkhen to paste URL to PR

**Comment by amnonkhen** [comment]
See [PR 177](https://github.com/ebi-ait/ingest-ui/pull/177)

**Comment by idazucchi** [comment]
Karoy approved the PR, waiting to release when the devs are back after the release

**Comment by idazucchi** [comment]
@MightyAx will take a look and merge

**Comment by Wkt8** [comment]
Has been pushed to staging. @Wkt8 to verify!

**Comment by Wkt8** [comment]
I'm happy with this! Can't see any ways to generate a full project only from a spreadsheet submission.

**Comment by amnonkhen** [comment]
@MightyAx to push to prod

**Comment by MightyAx** [comment]
Deployed to Production, will show at DCP demo later
