### ISSUE TITLE
Metadata Validator Errors can be listed against the wrong Metadada

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/dcp-ingest-central#768]
Please see this project on staging:
https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=39ac4216-7e5f-400f-a461-4497fd6e9582&project=003dd66d-5d2c-46f8-ac7c-32a06d403501

![image.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/c0200e92-5aaa-4258-9956-e889d36e4adf)

**Comment by jacobwindsor** [comment]
@idazucchi I don't see these errors anymore? Was the issue solved?

**Comment by jacobwindsor** [comment]
@idazucchi I don't see these errors anymore? Was the issue solved?

**Comment by idazucchi** [comment]
@jacobwindsor the issue with errors about the donors are resolved, the other is still standing.
I uploaded again the same spreadsheet in prod and the cell line raised again an error:
- the message errror is displayed correctly
- the error message is not related to the cell_line field, it's about official_hca_publication instead
- the error disappears if I trigger validation again by editing the description

**Comment by gabsie** [comment]
@idazucchi will check once again to see if this is resolved.

**Comment by idazucchi** [comment]
I've modified the spreadsheet to add `cell_line.publication.official_hca_publication` and uploaded it in a new [project](https://staging.contribute.data.humancellatlas.org/projects/detail?uuid=3478672b-6e5c-4d81-af0f-d8462b5213c6) 
The publication error is gone and this ticket can be closed
