### ISSUE TITLE
Add additional metadata/data

### ISSUE THREAD

**Issue by ofanobilbao** [ebi-ait/dcp-ingest-central#78]
## User Story
As a wrangler I want to add additional metadata entities and fields to an existing project that is in the DCP so that I can add additional experimental data to the project

## Examples
Adding a new contact to an existing project
Adding a new donor, specimen, protocols, processes and files (Hugo Dataset is a good example)

## Acceptance Criteria
Addition of any new metadata entities and fields can be made, validated and propagated to Ingest and then exported to the GCP staging area
Unchanged data files are not exported as part of updates (as this requires ongoing storage and excess egress costs etc) (Expected from #77)
Additional files are validated and exported to the GCP staging area (expected from #77)

**Comment by clairerye** [comment]
This should work - we need to create the test plan and test this

**Comment by clairerye** [comment]
This was used to successfully add additional metadata to the Laurenti project for the DCP2 feb release - https://data.humancellatlas.org/explore/projects/455b46e6-d8ea-4611-861e-de720a562ada?catalog=dcp3 compared to https://data.humancellatlas.org/explore/projects/455b46e6-d8ea-4611-861e-de720a562ada?catalog=dcp2
