### ISSUE TITLE
[Archiving test] Some processes are not getting a insdc_experiment_accession

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/dcp-ingest-central#780]
**Describe the bug**
After archiving, the archived processes should have both an SRR accession and an INSDC experiment accession. Nevertheless, some of them do not have the INDSC experiment accession. All of the processes with the accession have 1 sequencing protocol and 1 library preparation protocol. In contrast, all the processes where the accession is not present have 1 sequencing protocol and 2 library preparation protocols. This might be related to the issue. If not, it might be good to know what is causing some processes to have an INSDC experiment and others not. 

**Steps to reproduce**
Follow the steps for direct archiving: https://github.com/ebi-ait/ingest-archiver/blob/dev/README_for_direct_archiver.md

**Expected behavior**
All the processes with SRR accession should have an INSDC experiment accession. 

**Screenshots / Logs**
![Screenshot 2022-05-16 at 11.43.16.png](https://images.zenhubusercontent.com/615accc6c862be97b5e524a4/df834738-ea90-4808-9a7d-91c10daf12da)

The processes SRR11614691 and SRR11614692 are linked to the same library preparation and sequencing protocols. Process SRR11614692 has an extra library preparation protocol. 

**Links**
https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=04a71fe7-cb3c-482d-a1a9-0024a71e5ceb

**Environment**
- [ ] prod
- [x] staging
- [ ] dev

**Browser**
- [x] Chrome
- [ ] Safari
- [ ] IE
- [ ] Other (please specify)

**Comment by prabh-t** [comment]
This process seems to have 2 lib preparation protocols and we do not know how to translate/map an assay process with 2 such protocols into an ENA experiment. That is why the experiment XML for this assay process is being skipped but not the run XML, the latter doesn't require fields from the lib prep protocol(s).

```
 $ kubectl logs ingest-archiver-8449f4dd6-cv26w | sed -n '11713,11800p'
 2022-05-16 10:16:32,770  - hca.assay - INFO in assay.py:81 __get_submission_assays(): 22/33 Checking SRR11614692
 2022-05-16 10:16:32,794  - hca.assay - INFO in assay.py:89 __get_submission_assays(): 1 sequencing and 2 library preparation protocols found.
```

@ke4 @ipediez @ESapenaVentura

**Comment by ipediez** [comment]
A discussion needs to take place with @ipediez and @ESapenaVentura , @prabh-t to schedule the meeting

**Comment by prabh-t** [comment]
PR https://github.com/ebi-ait/ingest-archiver/pull/91

**Comment by ipediez** [comment]
GitLab runner is not working properly for our integration tests. @ke4 to reach out for technical assistance

**Comment by yusra-haider** [comment]
@ke4 to check if GitLab is working now so he can proceed with deployment

**Comment by ESapenaVentura** [comment]
TBpromoted to prod. Waiting on maintenance from GL.

Can try to manually promote while GL is not working properly
