### ISSUE TITLE
Unable to import a spreadsheet 

### ISSUE THREAD

**Issue by ipediez** [ebi-ait/dcp-ingest-central#784]
**Describe the bug**
Will Sullivan (UCSC) reported at 23:28 that they were unable to import spreadsheets in ingest. [This is the slack conversation](https://embl-ebi-ait.slack.com/archives/C02K08WJQF6/p1653604122841889): 

> Yeah so I’m guessing ingest is down because we currently can import a spreadsheet or export the ones you’ve kicked getting the two things below every time I try

I'll add the screenshots sent by Will to the end of the ticket

I've tried to import the test spreadsheet for archiving [to a test project](https://contribute.data.humancellatlas.org/projects/detail?uuid=9bec82c8-ec5c-420c-9eb4-75b39b316f13) and I'm currently getting the same error as him:

> HttpErrorResponse: Http failure response for https://ingest.archive.data.humancellatlas.org/api_upload: 0 Unknown Error

**Screenshots / Logs**
![Error when uploading a spreadsheet](https://images.zenhubusercontent.com/615accc6c862be97b5e524a4/5a2febc8-169d-44a1-807c-81472350408d)

**Environment**
- [x] prod
- [ ] staging
- [ ] dev

**Comment by amnonkhen** [comment]
@jacobwindsor verified it is back to working using a test spreadsheet. 
@amnonkhen [notified UCSC](https://embl-ebi-ait.slack.com/archives/C9XD6L0AD/p1653662889755279?thread_ts=1653660656.937849&cid=C9XD6L0AD).

**Comment by Wkt8** [comment]
Karoly worked on this together with Jacob.
