### ISSUE TITLE
Register integration environment on LS AII

### ISSUE THREAD

**Issue by jacobwindsor** [ebi-ait/dcp-ingest-central#791]
https://lifescience-ri.eu/ls-login/relying-parties/how-to-register-and-integrate-a-relying-party-to-ls-login.html

**Comment by prabh-t** [comment]
I have added the following Redirect URIs in the Perun LifeScience Login Service provider registration page (https://spreg-legacy.aai.elixir-czech.org/spreg/auth) for HCA Ingest client (ID e2041c2d-9449-4468-856e-e84711cebd21)

```
https://integration.contribute.data.humancellatlas.org/aai-callback
http://integration.contribute.data.humancellatlas.org/aai-callback
https://ui.ingest.integration.archive.data.humancellatlas.org/aai-callback
```
The change has not been applied straight away but a request (see below) has been created.

```
Request #581
Status of request:hourglass_emptyWaiting for approval
Action:Update service
Edited on: 31/05/2022
Requested by: Prabhat Totoo (#49264)

https://spreg-legacy.aai.elixir-czech.org/spreg/auth/requests/detail/581
```

We need to check when this is approved and then we should be able to log into the Ingest UI on the new integration environment without the following error:
```
Error invalid_grant
There was an error processing your request.

Invalid redirect: https://integration.contribute.data.humancellatlas.org/aai-callback does not match one of the registered values.
```

**Comment by prabh-t** [comment]
Moving this to waiting. Someone needs to check if/when this change has been applied and test login in integration env.

**Comment by ke4** [comment]
I checked and I could log in to the UI of our integration environment. I also added the `WRANGLER` role to my account.
