### ISSUE TITLE
Get a list of projects which are Submitted but Catalogue=no

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#792]
As a stakeholder, I want to get a list of projects which are Submitted but Catalogue=no, so that we can review and get them updated to show in the Catalog.

**Comment by MightyAx** [comment]
Code change ready for Review

**Comment by MightyAx** [comment]
Actually I missed a part of the ticket (submitted projects) so back into dev

**Comment by MightyAx** [comment]
Ingest Core and Ingest UI tickets now in review.

**Comment by gabsie** [comment]
Let's check this separately with Alexie and we see what's next.

**Comment by amnonkhen** [comment]
@MightyAx to present to @gabsie & @ofanobilbao this morning.
@amnonkhen to code review

**Comment by MightyAx** [comment]
@MightyAx alexie to check gittlab deployment and confirm staging release.

**Comment by MightyAx** [comment]
dev / staging release successful.
(It's worth noting that the Gitlab jobs needing to be restarted multiple times.)

**Comment by MightyAx** [comment]
Screenshot from [staging](https://staging.contribute.data.humancellatlas.org/projects/all):

![Screenshot 2022-07-04 at 12.15.31.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/a18d2846-e9dd-4653-8204-caabad80b59c)

**Comment by ofanobilbao** [comment]
@MightyAx to move it to Prod
