### ISSUE TITLE
sequence_file descriptor files are missing values for the “content_type” and “size” properties

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/dcp-ingest-central#793]
**Describe the bug**
sequence_file descriptor files are missing values for the `content_type` and `size` properties for the files in project [88ec040b-8705-4f77-8f41-f81e57632f7d](https://contribute.data.humancellatlas.org/projects/detail?uuid=88ec040b-8705-4f77-8f41-f81e57632f7d&tab=upload)

I believe these values are automatically generated by Ingest. Is there a way we can check / add these values? 

# links:
- [ingest ui](https://contribute.data.humancellatlas.org/projects/detail?uuid=88ec040b-8705-4f77-8f41-f81e57632f7d&tab=upload)
- s3 upload area - not found (maybe it was deleted)
- [terra staging area](https://console.cloud.google.com/storage/browser/broad-dsp-monster-hca-prod-ebi-storage/prod/88ec040b-8705-4f77-8f41-f81e57632f7d)
- dataset ticket ebi-ait/hca-ebi-wrangler-central#672
# Background: 
This project was originally exported by lattice in Release 12. Not sure how it made it past validation then. In Release 14 we updated it as part of the 'Updates Release', see ticket [here](https://app.zenhub.com/workspaces/dataset-wrangling-status-5f994cb88e0805001759d2e9/issues/ebi-ait/hca-ebi-wrangler-central/334), and now Jeff has reported that the sequence_files are missing values for 'content_type' and 'size'. It has not been made part of the release. 

# Plan

- [x] acuire files
- [x] write a script to update files in db
- [ ] re-export

**Comment by amnonkhen** [comment]
The only time ingest validates the file size and metadata type is when the file descriptor json file is created. We should consider validating it during metadata validation.

**Comment by amnonkhen** [comment]
@amnonkhen to organise a discussion about dcp1 projects export and problems (missing metadata attributes).

**Comment by ofanobilbao** [comment]
There was a meeting yesterday with the wranglers on this, and there is a plan, that is recorded on the Operations ticket

**Comment by ESapenaVentura** [comment]
@ESapenaVentura to link PR for filling out DCP1 file metadata

**Comment by ESapenaVentura** [comment]
PR ebi-ait/hca-ebi-dev-team#508

**Comment by ESapenaVentura** [comment]
Pushed changes:
- Improved query from azul (Now filters on file_source, to avoid DCP/1, DCP/2 analysis team files)
- Deals with pagination in azul
- Now has a progress bar when patching (Can take a very long time for projects with thousands of files)

**Comment by MightyAx** [comment]
still waiting for a fix I recommended.

**Comment by MightyAx** [comment]
I've approved
@amnonkhen will need to approve that their requested changes have been addressed

**Comment by ESapenaVentura** [comment]
@amnonkhen when you have time please review

**Comment by ofanobilbao** [comment]
@ESapenaVentura tested it again yesterday with the Immune Census. It worked fine

**Comment by ofanobilbao** [comment]
@amnonkhen to review today

**Comment by ESapenaVentura** [comment]
@ESapenaVentura to review the comments, fix, and ask re-review

**Comment by MightyAx** [comment]
Amnon has recommended changes, Enrique is working on them now.
