### ISSUE TITLE
Investigate why datasets are stuck in exporting

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#795]
**Description of the problem**
In the last few days the same issue has happened repeatedly when exporting a project:
The project status remains stuck in `Exporting` but the staging area contains the newly generated JSON files
**see Yusra's comment on ticket #121**
 
**Datasets affected**
- ticket #666 - [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=425c2759-db66-4c93-a358-a562c069b1f1)  - `425c2759-db66-4c93-a358-a562c069b1f1`
- ticket #121 - [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=005d611a-14d5-4fbf-846e-571a1f874f70) - `005d611a-14d5-4fbf-846e-571a1f874f70`
- ticket #766   - [ingest](https://contribute.data.humancellatlas.org/projects/detail?uuid=074a9f88-729a-455d-bca5-0ce80edf0cea) - `074a9f88-729a-455d-bca5-0ce80edf0cea`

**Acceptance criteria**
- [ ] find the cause of the issue
- [ ] fix the issue so that the project status is updated correctly

**Comment by ke4** [comment]
I create a new submission in `dev` environment for the dataset in [ticket#666](https://github.com/ebi-ait/hca-ebi-wrangler-central/issues/666):
- https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=11758ef8-a0b2-41c4-b971-bae347bb5cd7&project=d6ebcdb2-6e14-46f6-8009-3749d3947ccb

**Comment by ke4** [comment]
As the original spreadsheet attached to the ticket contained a couple of errors Ida helped me to fix it.
Here is the fixed spreadsheet I used to create the submission: [GSE192740_v1_ontologies_666_pheno-schema-fix3.xlsx](https://app.zenhub.com/files/299258791/ea630aa4-6241-40e4-81b2-428cb3e18bef/download)

**Comment by ke4** [comment]
The hca util upload area for the files: [data files](s3://hca-util-upload-area/46a00d3b-1e19-4137-8533-6e4adf6fdbe1/)

**Comment by ke4** [comment]
Files have been uploaded and now they are validating.

**Comment by ke4** [comment]
Some jobs failed in checksum calculation (1) and file validation (2). I cloned all of them which resulted in restarting the jobs.
All of them succeeded now.

**Comment by ke4** [comment]
Here are the remaining actions with this submission:
- [x] graph validate
- [x] export metadata and data
- [ ] check the logs

**Comment by ke4** [comment]
Looking at the protocols I just realized that the graph validation is going to fail as 1 protocol is not linked.
And it just happened.
![Screenshot 2022-06-13 at 16.58.23.png](https://images.zenhubusercontent.com/5f2957fd448645a503a32777/470a146f-5129-46fb-8a9b-ffc5de2e8024)
I probably need @idazucchi 's help to fix this. I think the original and this submission also differ in protocol names, but that might not be an issue.

**Comment by ke4** [comment]
@idazucchi fixed the issue by deleting the protocol because it wasn't in the final exported protocol and restarted the graph validation.

**Comment by ke4** [comment]
Here is the new updated spreadsheet: [https://app.zenhub.com/files/299258791/82c77da3-41d1-42a6-a525-ed532c31d7b9/download](https://app.zenhub.com/files/299258791/82c77da3-41d1-42a6-a525-ed532c31d7b9/download)

**Comment by ke4** [comment]
The graph validation has succeed. I am triggered the exporting of the submission on the UI and monitoring the logs.

**Comment by ke4** [comment]
The submission status is now `Exported`.

**Comment by gabsie** [comment]
Quickly check what the next suggested experiment here should be. Communicate with @MightyAx as well

**Comment by ke4** [comment]
I checked on AWS Batch for the failed jobs, but I could not find anything that was related to this submission. 😢

**Comment by MightyAx** [comment]
Prototype complete for Exporting Errors being "Dead Lettered"

**Comment by ofanobilbao** [comment]
@MightyAx to build this into the ingest exporter code today

**Comment by MightyAx** [comment]
Ready for PR

**Comment by ofanobilbao** [comment]
@amnonkhen reviewing this morning. Will probably be pushed to Production. @ke4 to review the PR as well

**Comment by MightyAx** [comment]
Deployed to staging with Queue Configuration changes.

**Comment by MightyAx** [comment]
My deploy to staging ebi-ait/ingest-exporter#37 was originally flawed and I created fixes ebi-ait/ingest-exporter#39 which fixed the terra experiment queue and ebi-ait/ingest-exporter#40 which fixed the assay manifest queue, acording to testing on dev.

The fixes are now being deployed to staging.

**Comment by MightyAx** [comment]
The Dead letter queues have been deployed to production

**Comment by MightyAx** [comment]
While investigating a large export I was slowly scaling the exporter and got as high as 20 exporter pods... which made ingest-core hit it’s maximum memory and crash,

As part of evaluating impact for this ticket I can happily report that the messages that failed were moved to the error queue as expected, and I moved them back onto the main queue.

Also, scaling the exporter down to 10 after this killed some exporter pods, but the messages they were processing were put back on the main queue automatically since they are not acknowledged till the end of the process now.
