### ISSUE TITLE
Metadata csvs per project, for consumers

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#796]
Hey Amnon

I have chosen a project from ingest which we can use to produce metadata csv examples for. 

https://contribute.data.humancellatlas.org/projects/detail?uuid=957261f7-2bd6-4358-a6ed-24ee080d5cfc

and this project

[Kuppe's dataset](https://contribute.data.humancellatlas.org/projects/detail?uuid=e9f36305-d857-44a3-93f0-df4e6007dc97)

Can we please produce the necessary metadata files which we suggest to provide for data consumers?
It has got sequencing and imaging technologies in it. 

Thanks. Please attach them here afterwards.

Gabby

**Comment by amnonkhen** [comment]
see ebi-ait/hca-ebi-wrangler-central#826
