### ISSUE TITLE
integration tests not running due to gitlab runner problem

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#797]
See this [pipeline](https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/pipelines/288789).
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/5c05b787-64f9-4c96-b9ad-99eec207503b)

There is a related [helpdesk ticket](https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=591417).

# Acceptance Criteria

- [ ] integration tests are being run by gitlab after push to git
- [ ] documentation updated
- [ ] setup scripts of runner updated

**Comment by ofanobilbao** [comment]
Might need help from @ke4 or @MightyAx

**Comment by amnonkhen** [comment]
With @MightyAx's advice the faulty EBI Gitlab runner ([1349](https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/runners/1349), clicking this would result in a "not found" error) was dissociated from the integration tests project.
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/6090e6ff-c08c-41ff-826c-9a1e782e1826)

After restarting the failed [pipeline](https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/pipelines/288789), our own private runner ([2292](https://gitlab.ebi.ac.uk/groups/hca/-/runners/2292)) was chosen for all jobs, and they are running the integration tests.

Although the runner is running the integration test jobs, they are still failing.
Some of them appear has if they succeeded but have a python error message related to memory management in the logs:
```
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
The other jobs are failing due to timeout.
Both these issues can have their own tickets.

**Comment by amnonkhen** [comment]
A new [push](https://github.com/ebi-ait/ingest-graph-validator/pull/74) by @ESapenaVentura resulted in a failed [pipeline](https://gitlab.ebi.ac.uk/hca/ingest-graph-validator/-/pipelines/289220) with "no permissions" error in the integration tests phase.
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/6ce57627-f3fc-4c97-b405-000b0adb3db0)

I am investigating whether this is related.

**Comment by amnonkhen** [comment]
@amnonkhen re-triggered the job and it is running ok.

**Comment by idazucchi** [comment]
Amnon will look into this today - it could be a permission problem
