### ISSUE TITLE
automation for HCA ontology release

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#800]
see new script [deploy_ontology.sh](https://github.com/ebi-ait/ingest-kube-deployment/blob/master/infra/scripts/deploy_ontology.sh)

[updated SOP](https://github.com/ebi-ait/hca-ebi-dev-team/blob/master/docs/operations_tasks/HCAO-release.md)

- [x] review by another dev - done by Alexie
- [x] test for the July release (pending HCAO release)

**Comment by amnonkhen** [comment]
@MightyAx to review.

**Comment by MightyAx** [comment]
Can you please explain what this block of code is doing:
```
DEPLOYMENT_STAGE=dev
ONTOLOGY_VERSION=
GITLAB_URL=https://gitlab.ebi.ac.uk
while getopts e:v: flag
do
    case "${flag}" in
        e) DEPLOYMENT_STAGE=${OPTARG};;
        v) ONTOLOGY_VERSION=${OPTARG};;
        g) GITLAB_TOKEN=${OPTARG};;
    esac
done
```

can you explain what the `-i.bak` is doing in the following:
```
sed -i.bak \
  "s/ONTOLOGY_REF=.*/ONTOLOGY_REF=${ONTOLOGY_VERSION}/" \
  ../config/environment_${DEPLOYMENT_STAGE}
```
I gather the whole thing is doing a find and replace

**Comment by ofanobilbao** [comment]
@amnonkhen and @MightyAx to go through this together

**Comment by amnonkhen** [comment]
@MightyAx here are the answers to your questions

- getopts - read command line args. If none is given it uses the default values before the getopts statement
- -i.bak - back up th input file of sed
- the sed command replaces the ontology version number in the environment file

**Comment by ESapenaVentura** [comment]
TBU on the next ontology release!

**Comment by MightyAx** [comment]
Ticket for next Ontology Release
GitHub: ebi-ait/hca-ebi-dev-team#494
ZenHub: https://app.zenhub.com/workspaces/operations-5fa2d8f2df78bb000f7fb2b5/issues/ebi-ait/hca-ebi-dev-team/494
