### ISSUE TITLE
Ingest client fixes for reducing callbacks to ingest-core from ingest-exporter

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/dcp-ingest-central#804]
- [x] Cache calls to ingest
    - using [requests-cache](https://pypi.org/project/requests-cache/)
- [x] Specify higher number of items to return from lists in ingest.
    - ingest-core lists include a Pageable that defaults to 20 items, but can be specified to a higher number.
    - ingest-client does not extend this option to its consumers (such as ingest exporter)

**Comment by MightyAx** [comment]
@MightyAx to fix GitLab running unit tests issue

**Comment by MightyAx** [comment]
After some issues with gitlab the integration tests and unit tests are running for ingest-client on PRs, (and hopefully merges will run the tests and then deployments).

The Integration and unit tests needed some fixes which are on PR:
https://github.com/ebi-ait/ingest-client/pull/55

Which requires review.

**Comment by Wkt8** [comment]
@ke4 and / or @amnonkhen to review

**Comment by MightyAx** [comment]
Deployed to PyPi!
https://gitlab.ebi.ac.uk/hca/ingest-client/-/pipelines/312221
https://pypi.org/project/hca-ingest/

**Comment by gabsie** [comment]
Awesome.
