### ISSUE TITLE
sra rest api used in importing from geo is broken

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#805]
**Describe the bug**
"import from geo" script uses the following endpoint:

```
http://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?save=efetch&db=sra&rettype=runinfo&term={srp_accession}
```
passing an SRP accession and get a csv output as a response.

(see [code](https://github.com/ebi-ait/geo_to_hca/blob/fe2fc6120f85f49c562e435c33c4421d7f4ecf33/geo_to_hca/utils/sra_utils.py#L59))

When I call this endpoint now, however, I am getting a **400** error with the following message:

I emailed sra@ncbi.nlm.nih.gov on 4/7. No response yet.

```
400 Bad Request. Both list of IDs and query_key are empty
```

**To Reproduce**
Steps to reproduce the behaviour:
1. hit the endpoint
2. notice the 400 response

**Expected behaviour**
response should be a csv

**Screenshots / Logs**
n/a

**Links**
n/a

**Environment**
- [x] prod
- [x] staging
- [x] dev

**Browser**
n/a

**Comment by amnonkhen** [comment]
No response from the sra people.

**Comment by ESapenaVentura** [comment]
@ESapenaVentura  and @amnonkhen to meet about this

**Comment by amnonkhen** [comment]
@ESapenaVentura and @amnonkhen found the proper way to trigger the entrez api.
So of the calls require a 2 phase sequence:
1. first to get and "env" (sort of a session)
2. 2nd to to the actual search
see [entrez docs](https://www.ncbi.nlm.nih.gov/books/NBK25500/#chapter1.Searching_a_Database)

**Comment by gabsie** [comment]
Is this now resolved?

**Comment by willrockout** [comment]
@amnonkhen @ESapenaVentura want to check in on this in relation to my ticket that Alexie tagged above
