### ISSUE TITLE
Ensure ingest-ui uses supported version of node.

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/dcp-ingest-central#810]
As discovered in ticket [#767](https://github.com/ebi-ait/ingest-ui/pull/177#pullrequestreview-1050682323), the version of node used throughout the ingest UI project is different in development, testing and production scenarios.

What's worse is that the version of node used in production is End-Of-Life and no longer supported.

It's hard to just change one part of ingest UI platform since the versions of **Angular**, **Node**, **TypeScript** and **RxJS** are tightly coupled with each-other, as described by [this table](https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3).

Acceptance Criteria:

- [x] Use a consistent version of Angular, node,  Typescript and RxJs across development, testing and production roles.
- [x] Ensure that the versions of these products are supported by upgrading the version of node used in production scenarios to 14.

**Comment by Wkt8** [comment]
Alexie to timebox to 1 hour and then move on to something else as not incredibly high priority. Close to done.

**Comment by MightyAx** [comment]
Timebox slightly flexed but [Ingest UI PR #179](https://github.com/ebi-ait/ingest-ui/pull/179) is now ready for review.

**Comment by Wkt8** [comment]
Amnon to review.

**Comment by gabsie** [comment]
New ticket to address Amnon's review is needed.
