### ISSUE TITLE
creating a process in the ui renders the project un-exportable

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#813]
While investigating dataset stuck in export ticket ebi-ait/hca-ebi-wrangler-central#869 @MightyAx and @amnonkhen found the following bug:

Creating a new process or biomaterial via the UI creates the relevant entity but does not properly connect it to the project entity, because it does not add it to the `projects` attribute.

During export the contents of the `projects` attributes is read, but processes that were created in the UI it is empty. This results in a failure to export, which is evident by an error message of `"index out of range error"` in the exporter log.

**Comment by MightyAx** [comment]
ready for review: https://github.com/ebi-ait/ingest-core/pull/138

**Comment by ke4** [comment]
@MightyAx retest it in staging

**Comment by MightyAx** [comment]
### Pre-fix test case

- Projects list for Process created from the UI is **blank**: [processes/62ea957ed9314d329d7b8bd2/projects](https://api.ingest.staging.archive.data.humancellatlas.org/browser/index.html#https://api.ingest.staging.archive.data.humancellatlas.org/processes/62ea957ed9314d329d7b8bd2/projects)
- This submission is **stuck in exporting**: [10df2518-7ea6-40dd-9ee9-0d0cf33c4acc](https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=10df2518-7ea6-40dd-9ee9-0d0cf33c4acc&project=00addbff-3499-4d2f-bb5a-7547e6a87ef1)
- With only **4 of 5** entities successful: [exportJobs/62ea9682d9314d329d7b8bd3/entities](https://api.ingest.staging.archive.data.humancellatlas.org/browser/index.html#https://api.ingest.staging.archive.data.humancellatlas.org/exportJobs/62ea9682d9314d329d7b8bd3/entities)


### Post-fix test case
- Projects list for Process created from the UI is **populated**: [processes/62f0daa1e5248105fb1b031b/projects](https://api.ingest.staging.archive.data.humancellatlas.org/browser/index.html#https://api.ingest.staging.archive.data.humancellatlas.org/processes/62f0daa1e5248105fb1b031b/projects)
- This submission is **exported**: [6b4c1345-c97f-46d6-8664-1e23277ace64](https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=6b4c1345-c97f-46d6-8664-1e23277ace64&project=4e44eb37-bd95-4773-bb5c-cf59ab2e38cf)
- With **5 of 5** entities exported successfully: [exportJobs/62f0dd33e5248105fb1b0609/entities](https://api.ingest.staging.archive.data.humancellatlas.org/browser/index.html#https://api.ingest.staging.archive.data.humancellatlas.org/exportJobs/62f0dd33e5248105fb1b0609/entities)
