### ISSUE TITLE
Resolving Exporter Timeouts

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/dcp-ingest-central#815]
### Issues

When a project is being exported, the files need to be transferred from ingest to terra. There are two issues with our current implementation that cause a lot of operational work that are related and could be solved at the same time.

Firstly, when the exporter is transferring these files, it will fill up the export queue with jobs that are waiting for the transfer to finish, **this will prevent any other export activity from being progressed.**
*AKA: project can't be exported because it is stuck behind something else that is exporting*

Secondly, if the *primary* export job exceeds it's timeout of 6 hours. All of the other (hundred or thousands) of jobs dependant on it can never complete, so will simply wait for 6 hours to fail. (Exacerbating the first issue) Meaning that a failed job can not be restarted, without manual intervention.
*AKA: project timed-out while exporting and now needs manual intervention before I can re-start the export*

[Current implementation](https://miro.com/app/board/uXjVOg56gQU=/?moveToWidget=3458764530921383340&cot=14)

### Acceptance Criteria
- An export job that sends data files does not block the export queue
- No exporter pods are consumed waiting for data files to be transferred

### Redesigns
We have two possible redesigns:
[The first](https://miro.com/app/board/uXjVOg56gQU=/?moveToWidget=3458764530921493680&cot=14) makes two new queues, once for creating datafile sync jobs, and the other for polling their progress, and then triggering the current metadata file sync once the polling shows the transfer is successful.

[The second](https://miro.com/app/board/uXjVOg56gQU=/?moveToWidget=3458764530921493747&cot=14) uses a new queue for creating the upload job but then uses the google cloud to callback to ingest to report its success, triggering the current implementation of metadata synchronisation.

**Comment by MightyAx** [comment]
@amnon please review:
https://github.com/ebi-ait/ingest-core/pull/140
https://github.com/ebi-ait/ingest-client/pull/57

**Comment by MightyAx** [comment]
Nathan from the broad has asked for authorisation for our service account to be given "Pub/Sub Editor” as this would allow us to “Modify topics and subscriptions" and "publish and consume messages”

Once our setup is working the service accounts could be downgraded to "Pub/Sub Publisher" and "Pub/Sub Subscriber" which would be sufficient once development is complete.

**Comment by idazucchi** [comment]
waiting for Amnon's review

**Comment by MightyAx** [comment]
I ran this on production in advance to configure the subscription topic
This would have been done the first time the new exporter was run on the production environment but I wanted to ensure it was functional

``` thing.py

from exporter.terra.submission.responder import TerraTransferResponder
responder = TerraTransferResponder(None, 'mystical-slate-284720', 'broad-dsp-monster-hca.staging-transfer-notifications.ebi', 'mystical-slate-284720.json')
2022-09-16 13:55:24,869 - exporter.terra.submission.responder - INFO - Subscription Created: projects/mystical-slate-284720/subscriptions/broad-dsp-monster-hca.staging-transfer-notifications.ebi
```

**Comment by MightyAx** [comment]
On staging, awaiting user testing.

**Comment by MightyAx** [comment]
First Test Successful
[Submission](https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=40cb05cf-7ae1-4543-8aa0-11e5c5f832c6&project=41185446-7fc0-4e9e-9fb6-bb93ca37907b)
[Export Job](https://api.ingest.staging.archive.data.humancellatlas.org/browser/index.html#https://api.ingest.staging.archive.data.humancellatlas.org/exportJobs/6324910179c78d5fd8f79e1e)

Transfer Job:
```
Polling for latest operation name...done.                                                                                                                                                              
Operation name: transferJobs-6324910179c78d5fd8f79e1e-1663340811985967
Parent job: 6324910179c78d5fd8f79e1e
Start time: 2022-09-16T15:06:52.024870199Z
SUCCESS | 100% (75.9GiB of 75.9GiB) | Skipped: 0B | Errors: 0 : 0 /
End time: 2022-09-16T16:13:18.868852785Z
```
## Of Note
The Submission was still in the **Submitted** Status while the **data** was exporting, don't know why that is.
The submission went to **exporting** when the metadata was exporting, and to Exported when it was finished.
Probably something worth fixing but it does not block the release.

**Comment by MightyAx** [comment]
@amnonkhen wanted to test at least one more export
Once his testing is complete:
This [ingest-core pipeline](https://gitlab.ebi.ac.uk/hca/ingest-core/-/pipelines/322400) and this [ingest-exporter pipeline](https://gitlab.ebi.ac.uk/hca/ingest-exporter/-/pipelines/322398) can be released to production.

**Comment by gabsie** [comment]
Continue testing today to push to prod eventually.

**Comment by MightyAx** [comment]
wrote a document on how to confirm that the file transfer is working and monitor it:
https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/stuck-submissions-submitted.html

**Comment by MightyAx** [comment]
Confirmed both test projects have been exported, and viewed the files exported to terra.
[Ingest Project](https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=f4ab9570-bded-41af-a709-6a75f3a60cfa&project=b09ced5b-99ff-442e-8f06-89848b2893a8)
[Terra Staging Area](https://console.cloud.google.com/storage/browser/broad-dsp-monster-hca-dev-ebi-staging/staging/b09ced5b-99ff-442e-8f06-89848b2893a8/data)
