### ISSUE TITLE
Archiving - Project conversion to BioStudies failed

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#819]
When I create the project / submission in the new way (create an empty project first then add a submission and update the project afterwards) and don't add publications to the project the archiving will fail.

**Comment by ke4** [comment]
PR: https://github.com/ebi-ait/ingest-archiver/pull/92

**Comment by MightyAx** [comment]
@MightyAx will review today

**Comment by Wkt8** [comment]
Tested in staging - hopefully moving to production today.
