### ISSUE TITLE
GEO-TO-HCA tool error - "could not find sra accession"

### ISSUE THREAD

**Issue by willrockout** [ebi-ait/dcp-ingest-central#827]
**Description of the task:**

The geo-to-hca tool has stopped working for most GSEs this happens for both the spreadsheet downloads on ingest and the command line. When creating a project, you get the below error even when it is not a super-series.
<img width="1307" alt="Screen Shot 2022-08-04 at 10 59 51 AM" src="https://user-images.githubusercontent.com/19597324/182919090-a7288fe0-63c9-4af6-9fda-fb2ecb1d1662.png">

Then when you try to download a spreadsheet in a created project, you get the below error:
<img width="1315" alt="Screen Shot 2022-08-04 at 11 00 36 AM" src="https://user-images.githubusercontent.com/19597324/182919204-d1fe72c8-1abd-430f-9643-b51469c52d17.png">

I've listed below so examples of GSE having these problems:

- GSE205642
- GSE156456
- GSE202210
- GSE195719
- GSE202601

**Acceptance criteria for the task:**

**Comment by MightyAx** [comment]
Maybe another instance of: ebi-ait/dcp-ingest-central#805

**Comment by MightyAx** [comment]
Amnon to use same fix from SRA.

**Comment by amnonkhen** [comment]
There seem to be 2 problems here:

- GSE156456 - a duplicate of ebi-ait/dcp-ingest-central#805

The following accessions which all give the error:
```
Error creating spreadsheet for accession GSE202601. Could not find SRA accession; is it a GEO super-series? If yes, please re-try with a sub-series accession
```
- GSE205642
- GSE202210
- GSE195719
- GSE202601

**Comment by willrockout** [comment]
Interesting because in the second list none are superseries and all have data in sra.

**Comment by amnonkhen** [comment]
@willrockout the "super series" error message is an incorrect error message, I will issue a fix for it. 

I am trying to figure out the difference between the accessions that work, e.g. GSE156456,  and the 4 that result in the error, e.g. GSE202210. 

Currently I see that the call to *esummary* tool for the 4 erroneous ones has a response that has no `extrelations` attribute, while the ones that work do have an entry of relation type `SRA`.

Verifying this with the Wrangling team, I discovered with the help of @ami-day that some Geo accessions do not have a study associated with them directly. As a work around, I suggest the following:
1. go to the [geo web portal for the accession](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE202210)
1. follow [one of the samples](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM6106340)
1. follow the [SRA experiment link, `SRX...`](https://www.ncbi.nlm.nih.gov/sra?term=SRX15155472) 
1. find the SRA study link `SRP...` - [SRP373617](https://trace.ncbi.nlm.nih.gov/Traces/sra?study=SRP373617)
1. use that with the gro to hca tool

As a quick fix, I have added this information to the error message in the ui.

We will add this automation to our back log and implement it according to our priorities. I will update you as we have an ETA.

**Comment by willrockout** [comment]
Ok, this works for the command line tool but for the UI I can't get the SRP study accession to work for creating a new project or downloading a spreadsheet from an already created project. This is the UUID `505a3492-2f46-411d-afff-359c24431462` for the one I tried to use the SRP.

**Comment by amnonkhen** [comment]
@willrockout, the [project uuid you specified](https://contribute.data.humancellatlas.org/projects/detail?uuid=505a3492-2f46-411d-afff-359c24431462) is associated with the GSE202210 Geo accession.
Currently ingest UI does not let you generate a spreadsheet from a Geo accession for which a project already exists.
Would you please explain what you are trying to achieve?

**Comment by willrockout** [comment]
@amnonkhen I'm trying to test this because I've never been able to get the SRP accession to work through the UI. I see now the srp will download a spreadsheet in the project creation page now which is wasn't doing yesterday. I was also trying tot test adding an SRP to a project and generating a spreadsheet for it. Do I have to delete the GSE to it will default to the SRP?

**Comment by gabsie** [comment]
@amnonkhen needs a chat with somebody to explain the required feature etc, maybe arrange to chat to @ami-day

**Comment by amnonkhen** [comment]
@willrockout it seems a few issues are being mixed here.
Let me put them in order:

1) There was a bug in the SRA Tools API that the geo-to-hca tool is using. This is fixed.
2) There are Geo accessions to which an SRA Study (with an SRP accession) is not directly linked. The script used to not support these kind of projects (this scenario had not been foreseen). The tool now supports it by finding the Study accession through the Geo->Sample->Experiment->Study path.
3) The error message in scenario 2 used to be misleading and incorrectly mentioning "super series". This has been fixed.
4) Ingest UI does not presently allow running the geo-to-hca tool for accessions for which a project already exists in ingest. If you wish to re-generate a spreadsheet for such an accession, please use the HTTP API:

```shell
export ACCESSION=GSE156456
curl -X POST "https://ingest.archive.data.humancellatlas.org/spreadsheet-from-accession?accession=${ACCESSION}" --output ${ACCESSION}.xlsx
```

Implementing this in the UI will get into the backlog and prioritised. See #833

**Comment by amnonkhen** [comment]
need code review from @MightyAx & @Mil-m before closing

**Comment by willrockout** [comment]
@amnonkhen cool that makes more sense

**Comment by amnonkhen** [comment]
Thanks @willrockout, please let me know how the HTTP API usage is going.

**Comment by willrockout** [comment]
@amnonkhen I will give the API a try on another note trying to create a new project for *GSE192721* I'm now getting the below error that seems like we've hit the API too many times. Thoughts?
<img width="1311" alt="Screen Shot 2022-08-23 at 2 34 58 PM" src="https://user-images.githubusercontent.com/19597324/186272171-c7fd9a56-b676-4844-9cbd-4617ce20c993.png">

**Comment by amnonkhen** [comment]
@willrockout sorry about the "too many hits". I have introduced throttling for the requests, but evidently have missed some of them. Fix to come ASAP. See #838

**Comment by willrockout** [comment]
Thanks, @amnonkhen outside the UI the command line tool works now

**Comment by willrockout** [comment]
@amnonkhen So seems we are getting a new error with the command line tool as well as in the UI. This GSE162122 is throwing the below error:
<img width="1190" alt="Screen Shot 2022-09-09 at 9 49 00 AM" src="https://user-images.githubusercontent.com/19597324/189400917-47d41704-6c97-4372-b06b-3cff4838ffa6.png">

This is thrown for both GSE and SRP

**Comment by amnonkhen** [comment]
Thanks @willrockout for reporting this problem.
We will look into it.

**Comment by pnejad** [comment]
@amnonkhen any updates you can share with us?

**Comment by amnonkhen** [comment]
@pnejad this problem was not related to this ticket.
I created ebi-ait/dcp-ingest-central#855 for it and [notified](https://github.com/ebi-ait/dcp-ingest-central/issues/855#issuecomment-1252179139) @willrockout  about it.
The problem was with the dataset. The tool's problem in this case was an unclear error message, for which I will issue a fix next week.
When there is a problem in the geo_to_hca tool it usuallt manifests itself with an error message to the user, however, there is a multitude of reason for the problems:
- bugs
- unclear error message
- external db problems

It helps that each problem has its own ticket, rather than added at the bottom of an existing, possibly unrelated ticket. This it can be discussed, investigated, reported and closed independently. I hope this is not too much bureaucracy. If you have any idea to make this smoother, I would love to hear.

For this specific ticket, I was not aware you needed an update as well.

**Comment by willrockout** [comment]
Yeah, that's my bad I figured it was related and I was out of town so I couldn't update Parisa.
