### ISSUE TITLE
Exporter using caching ingest-client

### ISSUE THREAD

**Issue by MightyAx** [ebi-ait/dcp-ingest-central#828]
- [ ] Performance tests
    - [x] Choose good example project (possibly from [Testing Spreadsheets](https://drive.google.com/drive/folders/1dKZ5bscfej7U_rjJNt0DUBi0B8r58FFo?usp=sharing))
    - [x] Performance Test export of project using existing client  
    - [x] Change Exporter to use new client 
    - [x] Performance Test export of project using new client    

Demoable:
A project being exported - for the same project export (a test at current position), it made much less calls, and took xxxx of time.

**Comment by MightyAx** [comment]
# Baseline Test on Staging:
Testing [Submission](https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=d3e2e3be-f0dd-4146-9453-94d8d6f46e4a&project=2160edb1-41f6-4315-9a6f-f34db410bac1): 

### First Log message:
```
2022-08-19 11:22:21
"log":"2022-08-19 10:22:21,698 - exporter.terra.terra_listener - INFO
submission_uuid:d3e2e3be-f0dd-4146-9453-94d8d6f46e4a
export_job_id:62ff645606f1711fccbdffcb
Received experiment message for process 3e85409a-53e5-4d0d-bec0-c1b426158152
(index 0 for submission d3e2e3be-f0dd-4146-9453-94d8d6f46e4a)
total: 487
```

### Last Log Message:
```
2022-08-19 12:47:27	
{"log":"2022-08-19 11:47:27,263 - exporter.terra.terra_listener - INFO - submission_uuid:d3e2e3be-f0dd-4146-9453-94d8d6f46e4a - export_job_id:62ff645606f1711fccbdffcb - Acknowledging export experiment message: ExperimentMessage(process_id='62fe4f0a06f1711fccbdf434', process_uuid='eeeebd41-ba9c-4104-a46b-c7e7f1ec3180', submission_uuid='d3e2e3be-f0dd-4146-9453-94d8d6f46e4a', experiment_index=486, total=487, job_id='62ff645606f1711fccbdffcb')\n","stream":"stderr","time":"2022-08-19T11:47:27.263280203Z"}
```

### 85 Minutes
### Rabbit MQ Graph:
![Screenshot 2022-08-19 at 12.34.33.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/13f78e11-1abb-48ab-9db1-d4bbb4768a45)
### Log messages per minute:
notice the big gaps as it gets data from ingest
[![Screenshot 2022-08-19 at 13.14.27.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/d5bff29f-bd30-4134-8031-1d77bb6efd4d)](https://monitoring.ingest.staging.archive.data.humancellatlas.org/goto/MZvUUCi4k)

### Metadata Files exported
```
➜ gsutil ls -r "gs://broad-dsp-monster-hca-dev-ebi-staging/staging/2160edb1-41f6-4315-9a6f-f34db410bac1/metadata/" | grep -v /: | cut -d/ -f7 | sed -r '/^\s*$/d' | uniq -c | sort -k2,2
  79 analysis_file
  14 analysis_protocol
 408 cell_suspension
   3 collection_protocol
   9 donor_organism
   1 enrichment_protocol
   5 library_preparation_protocol
 904 process
   1 project
 816 sequence_file
   3 sequencing_protocol
   9 specimen_from_organism
```

### Objects Deleted:
```
gsutil -m rm -r "gs://broad-dsp-monster-hca-dev-ebi-staging/staging/2160edb1-41f6-4315-9a6f-f34db410bac1"
[3.4k/3.4k objects] 100% Done 177.10 objects/s
```

**Comment by MightyAx** [comment]
# Caching version on Staging

### First log message:
```
2022-08-19 15:34:47	
{"log":"2022-08-19 14:34:47,843 - exporter.terra.terra_listener - INFO - submission_uuid:d3e2e3be-f0dd-4146-9453-94d8d6f46e4a - export_job_id:62ff9f8106f1711fccbe08eb - Received experiment message for process 3e85409a-53e5-4d0d-bec0-c1b426158152 (index 0 for submission d3e2e3be-f0dd-4146-9453-94d8d6f46e4a)\n","stream":"stderr","time":"2022-08-19T14:34:47.843887362Z"}
```

### Last log message:
```
2022-08-19 16:43:07	
{"log":"2022-08-19 15:43:07,609 - exporter.terra.terra_listener - INFO - submission_uuid:d3e2e3be-f0dd-4146-9453-94d8d6f46e4a - export_job_id:62ff9f8106f1711fccbe08eb - Acknowledging export experiment message: ExperimentMessage(process_id='62fe4f0a06f1711fccbdf433', process_uuid='ca5d1338-50ab-4a55-b06e-9a86425442d3', submission_uuid='d3e2e3be-f0dd-4146-9453-94d8d6f46e4a', experiment_index=485, total=487, job_id='62ff9f8106f1711fccbe08eb')\n","stream":"stderr","time":"2022-08-19T15:43:07.610134621Z"}
```
### 69 minutes
### Rabbit MQ Graph
![Screenshot 2022-08-19 at 16.47.29.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/91bc2de9-8355-465f-a578-48fb8cbc4218)
### Log Messages per minute
no gaps!
[![Screenshot 2022-08-19 at 16.51.11.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/d7e2e450-24f1-42bb-8e75-4c3681a106f7)](https://monitoring.ingest.staging.archive.data.humancellatlas.org/goto/FNJGnqiVk)
### Metadata Files exported
```
➜ gsutil ls -r "gs://broad-dsp-monster-hca-dev-ebi-staging/staging/2160edb1-41f6-4315-9a6f-f34db410bac1/metadata/" | grep -v /: | cut -d/ -f7 | sed -r '/^\s*$/d' | uniq -c | sort -k2,2
  79 analysis_file
  14 analysis_protocol
 408 cell_suspension
   3 collection_protocol
   9 donor_organism
   1 enrichment_protocol
   5 library_preparation_protocol
 904 process
   1 project
 816 sequence_file
   3 sequencing_protocol
   9 specimen_from_organism
```

### Deletion of Objects
```
➜ gsutil -m rm -r "gs://broad-dsp-monster-hca-dev-ebi-staging/staging/2160edb1-41f6-4315-9a6f-f34db410bac1"
[3.6k/3.6k objects] 100% Done 176.43 objects/s
```

**Comment by MightyAx** [comment]
@amnonkhen With the above metrics, 85 minutes with the old exporter and 69 with the caching exporter do you agree that we can deploy this to production?

**Comment by amnonkhen** [comment]
Thanks @MightyAx.
85m -> 69m is a good improvement.
If we run the same project again does the 69m figure stay consistent?
If so, we can deploy to prod.

**Comment by MightyAx** [comment]
# Second Cached Test

## First Log Message
```
2022-08-23 11:13:09	
{"log":"2022-08-23 10:13:08,957 - exporter.terra.terra_listener - INFO - submission_uuid:n/a - export_job_id:n/a - Message received: {\"exportJobId\":\"6304a82e06f1711fccbe1fa7\",\"documentId\":\"62fe4ef406f1711fccbdf24e\",\"documentUuid\":\"3e85409a-53e5-4d0d-bec0-c1b426158152\",\"callbackLink\":\"/processes/62fe4ef406f1711fccbdf24e\",\"documentType\":\"process\",\"envelopeId\":\"62fe4e6706f1711fccbdeb66\",\"envelopeUuid\":\"d3e2e3be-f0dd-4146-9453-94d8d6f46e4a\",\"projectId\":\"62fe4e5606f1711fccbdeb63\",\"projectUuid\":\"2160edb1-41f6-4315-9a6f-f34db410bac1\",\"index\":0,\"total\":487,\"context\":null}\n","stream":"stderr","time":"2022-08-23T10:13:08.958507092Z"}
```

**Comment by MightyAx** [comment]
The export was notionally 72 minutes but two of the exports timed out because the metadata (despite being present on terra) cannot be verified. This didn't happen during the last export and I'm not certain if it says anything about the software or my change.

```
{"log":"google.api_core.exceptions.GatewayTimeout: 504 PATCH https://storage.googleapis.com/storage/v1/b/broad-dsp-monster-hca-dev-ebi-staging/o/staging%2F2160edb1-41f6-4315-9a6f-f34db410bac1%2Fdescriptors%2Fsequence_file%2Fb83cfcf1-80d9-4a5d-a1a3-2eb05c6747cc_2022-08-18T14%3A37%3A23.524000Z.json?generation=1661250717096282\u0026projection=full\u0026prettyPrint=false: \n","stream":"stderr","time":"2022-08-23T10:32:07.216520415Z"}
```
Initial Graph
https://monitoring.ingest.staging.archive.data.humancellatlas.org/goto/GCOaDdZ4z

Rejected Export Experiments:
https://monitoring.ingest.staging.archive.data.humancellatlas.org/goto/jvU1DOW4k

Manually marked [this file](https://storage.cloud.google.com/broad-dsp-monster-hca-dev-ebi-staging/staging/2160edb1-41f6-4315-9a6f-f34db410bac1/metadata/process/6f55d32d-5058-4f5f-a275-780d1acf8cfa_2022-08-23T10%3A13%3A02.033000Z.json) as export_complete: True
(Something I occasionally have had to do on production so feels irrelevant to this change)
The submission is now exported.

**Comment by MightyAx** [comment]
@amnonkhen thoughts?

**Comment by gabsie** [comment]
OK then, if this is a step forward, let's get this up on prod and keep an eye on prod how this performs. Other changes depend on it. Let's get this rolling! @MightyAx
