### ISSUE TITLE
deployment of ingest-broker on dev fails

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#831]
See for example the [following gitlab job](https://gitlab.ebi.ac.uk/hca/ingest-broker/-/jobs/970917).

Running the deployment command locally with debug messages enabled shows that the broker fails to start:

```
ready.go:277: [debug] Deployment is not ready: dev-environment/ingest-broker. 0 out of 1 expected pods are ready
upgrade.go:431: [debug] warning: Upgrade "ingest-broker" failed: timed out waiting for the condition
```

needs more investigation.

**Comment by amnonkhen** [comment]
Looking at the [k8s admin console](https://github.com/ebi-ait/ingest-kube-deployment#how-to-access-dashboard), I noticed errors in the [broker's pod](http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/service/dev-environment/ingest-broker-service?namespace=dev-environment):

```
container "ingest-broker" in pod "ingest-broker-755fc4664d-9kg88" is waiting to start: trying and failing to pull image

```

**Comment by amnonkhen** [comment]
After I ran the deployment locally it ran successfully.

```shell
# from ingest-kube-deployment
source config/environment_dev
cd apps
make deploy-app-ingest-broker image=quay.io/ebi-ait/ingest-broker:dev-f7ee0304-22-08-2022.1661160088
```
Not sure why this is happening.

**Comment by MightyAx** [comment]
Possibly a gitlab issue.
