### ISSUE TITLE
Create a project programmatically with minimum information

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#839]
As part of the epic to create programmatic submissions in ingest, the first step is to ensure that we are able to create a project in ingest with minimum information.

Alongside all the tickets related to #834, there will be documentation in the form of a readme.md and a python notebook, explaining how to create/check/submit programmatically in ingest.

Both documents will reside, at least for now, here: https://github.com/ebi-ait/hca-ebi-dev-team/tree/feature/dcp-834-programmatic-submissions/scripts/programmatic_submissions

### Acceptance criteria
- [x] A project entity with minimum information is created in ingest staging programmatically
- [x] The steps to produce a project are delineated in the python notebook
- [x] Exhaustive documentation is written on how to generate a project entity, what information goes in, and everything needed to understand this
- [x] (if needed) Extra code is implemented in the [ingest-client](https://github.com/ebi-ait/ingest-client/tree/4fbe2828a373184683c6954e4d9bf290cbe309bb) library and reviewed.

**Comment by ESapenaVentura** [comment]
Up to today:
- A project has been created successfully, with its content fully filled; missing the extra bits of the information on the project page that are not part of the metadata schema
- Currently writing documentation
- Changes have been pushed: https://github.com/ebi-ait/hca-ebi-dev-team/blob/feature/dcp-834-programmatic-submissions/scripts/programmatic_submissions/programmatic_submissions.ipynb

**Comment by ESapenaVentura** [comment]
Created ticket to add a useful feature for users to the ingest-client library: #844

**Comment by amnonkhen** [comment]
Are you aware of the [/projects/search/findByUser](https://api.ingest.archive.data.humancellatlas.org/browser/index.html#https://api.ingest.archive.data.humancellatlas.org/projects/search/findByUser) endpoint?
Or the other [search](https://api.ingest.archive.data.humancellatlas.org/browser/index.html#https://api.ingest.archive.data.humancellatlas.org/projects/search) endpoints?

**Comment by ESapenaVentura** [comment]
I have answered in the ticket with more detail but tl;dr, what I want to do is add a wrapper around those endpoints in our `IngestApi` object https://github.com/ebi-ait/ingest-client/blob/4fbe2828a373184683c6954e4d9bf290cbe309bb/hca_ingest/api/ingestapi.py

**Comment by ESapenaVentura** [comment]
a new feature is going to be ready soon - @ESapenaVentura to create PR and tag @MightyAx

**Comment by MightyAx** [comment]
@idazucchi to start with testing the notebook. Documentation pending.
@ESapenaVentura to link to notebook

**Comment by ESapenaVentura** [comment]
PR with the Notebook here: https://github.com/ebi-ait/hca-ebi-dev-team/pull/502

**Comment by idazucchi** [comment]
new repo for programmatic submissions
enrique is working on a repo readme

**Comment by ESapenaVentura** [comment]
Repository: https://github.com/ebi-ait/ingest-programmatic-submissions
GH page: https://ebi-ait.github.io/ingest-programmatic-submissions/

**Comment by ESapenaVentura** [comment]
The documentation has been written: everything that anyone needs to access the docs.+ notebooks is here https://ebi-ait.github.io/ingest-programmatic-submissions/

Waiting impatiently on review! This has taken forever

**Comment by MightyAx** [comment]
@MightyAx (and other volunteers) to review.

**Comment by MightyAx** [comment]
@ESapenaVentura I've made a PR with my review recommendations.
ebi-ait/ingest-programmatic-submissions#1

**Comment by MightyAx** [comment]
I think you have made an excellent easy to read summary of the system, the ethos behind the system, what problems it solves, an even pointer's to why certain decisions were made.

I think this is an excellent primer to our team across many topics and I'll be recommending reading and playing with this to our new starters before we throw them anything else.

GREAT JOB!

**Comment by idazucchi** [comment]
@Wkt8 and @idazucchi to review

**Comment by ESapenaVentura** [comment]
@ESapenaVentura to review today

**Comment by ESapenaVentura** [comment]
Reviewed the PR, I agree with mostly everything but I left a small comment

**Comment by Wkt8** [comment]
Alexie to look into the 'no: toc' to see if there is an alternate method.

**Comment by MightyAx** [comment]
I managed to *finally* get ruby installed, and Jekyll, will test out GH pages tomorrow.

**Comment by ofanobilbao** [comment]
Milena was testing this on Friday. Alexie to test today

**Comment by MightyAx** [comment]
@MightyAx to add back in the `{no-toc}` elements

**Comment by MightyAx** [comment]
- [x] Added back the `no-toc` elements
- [x] Remove Output folder from GitHub
- [x] update gitignore using gitignore.io
- [x] update local config file, reference correct GitHub repo

@ESapenaVentura please review.
![Screenshot 2022-12-13 at 16.33.31.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/afdd9f1a-0981-44ca-a213-7b36792946bc)

**Comment by MightyAx** [comment]
@ESapenaVentura to review

**Comment by ESapenaVentura** [comment]
reviewed PR and tested locally - LGTM! 

Moving ticket to done
