### ISSUE TITLE
Add "get_project_by_user_id" to ingest-client API object

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#844]

**Comment by amnonkhen** [comment]
Are you aware of the [/projects/search/findByUser](https://api.ingest.archive.data.humancellatlas.org/browser/index.html#https://api.ingest.archive.data.humancellatlas.org/projects/search/findByUser) endpoint?
Or the other [search](https://api.ingest.archive.data.humancellatlas.org/browser/index.html#https://api.ingest.archive.data.humancellatlas.org/projects/search) endpoints?

**Comment by ESapenaVentura** [comment]
Yep! but our `IngestApi` object wraps around the API endpoints and shows user-friendly functions (e.g. `IngestApi.get_project_by_id()`)

I would like to add a function that wraps around that endpoint as well (e.g. `IngestApi.get_project_by_user_id()`), because I can see how a programmatic user would like to not have to remember by heart/in a document the UUID of all their projects!

**Comment by ESapenaVentura** [comment]
PR has been created, reviewed by @MightyAx and @amnonkhen and merged to master: https://github.com/ebi-ait/ingest-client/pull/56

I have just tested the library's new function in pipy test environment:
```
pip install -i https://test.pypi.org/simple/ hca-ingest==2.2.0
```

```python
from hca_ingest.api.ingestapi import IngestApi
api = IngestApi('https://api.ingest.staging.archive.data.humancellatlas.org')
token = "Bearer {staging_token}"
api.set_token(token)
proj = api.get_user_projects()
projects = []
for p in proj:
    projects.append(p)
```

And works as expected! returns an iterator (from function get_all) and retrieves all my projects

**Comment by ESapenaVentura** [comment]
going to deploy to master, v2.2.0
