### ISSUE TITLE
Set status to Submitted when exporting finishes successfully

### ISSUE THREAD

**Issue by Mil-m** [ebi-ait/dcp-ingest-central#850]
scenario 2 - set the status to Submitted when exporting finishes successfully
- test
- code

integration tests
- add an integration test

**Comment by MightyAx** [comment]
@MightyAx  to review

**Comment by MightyAx** [comment]
ready to merge

**Comment by MightyAx** [comment]
On staging, awaiting user testing.

**Comment by MightyAx** [comment]
Once testing is complete:
This [ingest-core pipeline](https://gitlab.ebi.ac.uk/hca/ingest-core/-/pipelines/322400) and this [ingest-exporter pipeline](https://gitlab.ebi.ac.uk/hca/ingest-exporter/-/pipelines/322398) can be released to production.

**Comment by amnonkhen** [comment]
Two problems after a test on staging by @gabsie & @amnonkhen :

- [ ] project status box in admin area is empty
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/65ba5f00-cdf2-4af8-b1d1-404db43a0322)


- [ ] in the history list the entry "In progress -> Submitted" is shown as None
![image.png](https://images.zenhubusercontent.com/600ed297091d3ea152b83c2d/9f87aaae-76ed-4eda-b0c7-f2592065e602)

**Comment by ESapenaVentura** [comment]
@amnonkhen found solution, created a PR

Ned review, tagged @MightyAx and @Mil-m

**Comment by MightyAx** [comment]
approved.
