### ISSUE TITLE
redirect when not logged in goes to home

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#851]
following a link to a project when not logged it sends you to logging screen but does not take you back to project after logging in.

# reproduce
1. make sure you are logged out of ingest
1. click a project or submission link
1. you will notice the "error checking access" message
1. click "Log in" and follow the login process
1. once login is finished you will be redirected to the home page rather than the original project or submission you intended to

# Acceptance Criteria
- [x] Redirect works on all pages:
  - [x] `/projects/all`
  - [x] `/projects`
  - [x] `/submissions/list`
  - [x] `/projects/detail?uuid=xyz`
  - [x] `/submissions/detail?uuid=xyz`
  - [x] `/submissions/detail?uuid=xyz&project=uvw`
- [x] Automated test

**Comment by amnonkhen** [comment]
@gabsie or Wranglers the fix is deployed to dev, please test to approve before I roll into prod.

**Comment by idazucchi** [comment]
Testing in prod:
- [x] Redirect works on all pages:
  - [x] https://dev.contribute.data.humancellatlas.org/projects/all
  - [x] https://dev.contribute.data.humancellatlas.org/projects
  - [x] https://dev.contribute.data.humancellatlas.org/submissions/list
  - [x] https://dev.contribute.data.humancellatlas.org/projects/detail?uuid=73e8f512-0b6a-4b9c-b6ca-364c1ff6596d
  - [x] https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=ae5379bd-d731-403c-b380-8466340b06c3
  - [x] https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=ae5379bd-d731-403c-b380-8466340b06c3&project=5fd76bca-3d78-4fde-bce5-1099ac4a0d76

**Comment by amnonkhen** [comment]
deployed to prod
