### ISSUE TITLE
pressing enter on search field empties it and looses search term

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#852]
# Steps to reproduce
1. Go to [All Projects](https://contribute.data.humancellatlas.org/projects/all)
1. Type a search term in the search box **without** pressing _Enter_
1. notice the project list being filtered
1. press _Enter_
1. search box is emptied
1. all project are shown

Steps 5, 6 are the bug. 

# Expected result:
1. After typing Enter project list should remain filtered

**Comment by Wkt8** [comment]
@amnonkhen should this ticket be assigned to you? If so, please update.

**Comment by MightyAx** [comment]
PR ready for Review.

- [x] @MightyAx to review.

**Comment by ESapenaVentura** [comment]
@ofanobilbao did some user testing and feature is now in prod
