### ISSUE TITLE
integration test failing on staging & prod

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#853]
Looking at the staging pipeline , I notice 3 failures:
- **test_ingest_to_terra** - [pipeline](https://gitlab.ebi.ac.uk/hca/ingest-integration-tests/-/jobs/990102) - [api](https://api.ingest.staging.archive.data.humancellatlas.org/submissionEnvelopes/6318675d925813602e497940) [ui](https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=05fd5d04-30da-40b2-9145-eb3ef856c184)
    - fails while waiting for validation,
    - in UI the state is Metadata Valid
- **test_ingest_to_upload** - [pipeline](url) [api](https://api.ingest.staging.archive.data.humancellatlas.org/submissionEnvelopes/6318675a925813602e49793e) [ui](https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=ba9c4303-2541-453d-9b5c-dfce0dd53768)
    - fails while waiting for validation
    - in UI - metadata invalid due to a missing file: SRR3562314_2.fast
- **archiving**
    - Is timing out, rather than failing due to an expected error (Biosamples being down)
    - this is an issue we should investigate.

Possible related ticket: #321.
Projects there mention there a similar phenomenon of a file having a validation problem in the same test scenario **test_ingest_to_upload**. The actual invalid file out of the 2 in the submission is inconsistent.

**Comment by MightyAx** [comment]
For the direct archiving case I can see that it took 2 hours for the dev system to validate files
https://monitoring.ingest.dev.archive.data.humancellatlas.org/goto/WaiMOXM4z
```
2022-09-08 20:02:01	
{"log":"File document at http://172.20.37.89:80/files/631a3c2338d60e45d754af59 is already validating, ignoring...\n","stream":"stdout","time":"2022-09-08T19:02:01.102098966Z"}
2022-09-08 20:02:03	
{"log":"Document at http://172.20.37.89:80/files/631a3c2338d60e45d754af59 not eligible for validation, ignoring..\n","stream":"stdout","time":"2022-09-08T19:02:03.207712082Z"}
2022-09-08 20:02:03	
{"log":"Document at http://172.20.37.89:80/files/631a3c2338d60e45d754af59 not eligible for validation, ignoring..\n","stream":"stdout","time":"2022-09-08T19:02:03.293484664Z"}
2022-09-08 21:55:58	
{"log":"Posting a valid report for document http://172.20.37.89/files/631a3c2338d60e45d754af59\n","stream":"stdout","time":"2022-09-08T20:55:57.984281454Z"}
```

**Comment by MightyAx** [comment]
I re-ran just the 1one of the three failing tests again by itself, and the was batch job to validate the files hadn't even started by the time the integration test timed out:
![Screenshot 2022-09-12 at 15.33.45.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/aba6e114-f63b-4b2b-a0d5-ba355b639d64)

Finally they were run almost an hour after they were added, and only took 5 seconds:
![9636b06f-bac8-4b6c-923b-341541185e5d.png](https://images.zenhubusercontent.com/5d4053c054f6346037c2ef53/db6baae0-c4bc-4a0f-842a-c31836683eb3)

I can not figure out how to increase how often the batch job is evaluated.

**Comment by ESapenaVentura** [comment]
@MightyAx will try to get the tests on staging and prod to pass

**Comment by MightyAx** [comment]
it seems by retrying at the correct time you can bypass the AWS batch issue

**Comment by MightyAx** [comment]
dev tests are currently failing due to a PR that has not yet been merged.
staging tests have passed.
prod tests have passed
