### ISSUE TITLE
Prep for eLwazi DS-I Africa Datathon (FAIR Workshop) 

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/dcp-ingest-central#863]
Wei is going to the eLwazi DS-I Africa with Isuru to give a workshop on FAIR data and Open Data Science Platforms (ODSP). Prep work required for the following: 

- [x] Skeleton of workshop created
- [x] workshop presented to FAIR experts (Nick Juty and Ibrahim)
- [x] Time spent studying Fuqi's handover document
- [x] Reviewing key FAIR data and DSM (Dataset Maturity) concepts to communicate
- [x] Improve and iterative feedback on workshop

**Comment by ESapenaVentura** [comment]
Already met with experts to prepare the workshop

Meeting again next week there's going to be a demo of the workshop
