### ISSUE TITLE
Error in ingest: exceeding maximum limit on number of rows in spreadsheet 

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/dcp-ingest-central#869]
Error in ingest trying to import a spreadsheet exceeding the maximum number of rows (cell suspensions). We need to increase the limit. The number of rows is 76,000, and currently the limit is 50,000. It might be worth increasing the limit to 100,000 or more just to prevent this potentially happening in future.

Link to project in ingest: https://contribute.data.humancellatlas.org/submissions/detail?uuid=12a87cab-9c56-497b-901b-357b1b7c13d1&project=6936da41-3692-46bb-bca1-cd0f507991e9

Link to an old ticket (Feb 2021) when this was solved for a limit of 50,000: https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/177 (It needs to be increased further)

**Comment by gabsie** [comment]
@amnonkhen and @ESapenaVentura to discuss solution.

**Comment by ESapenaVentura** [comment]
Discussing with @idazucchi about data modelling this evening - May not need this feature

**Comment by ESapenaVentura** [comment]
@ESapenaVentura to move this to closed once Updated with the tickets about graph-validation work
