### ISSUE TITLE
Validation error when editing a Project - Contributor institute is mandatory?

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#880]
To reproduce:
==========

- Create a new project or open up an existing one, edit some Project details like name, short name, species, etc
- Try and save, errors pop up about Institute, for every Contributor

Next steps:

- investigate how often we actually have Contributor institute
- make the Institute non-mandatory (why didn't it actually raise the error when creating?)

@ESapenaVentura, can you please advise only if you know anything about this? (specifically about the last two questions)

Thanks
Gabby

**Comment by ESapenaVentura** [comment]
Instution is a mandatory field when loading the ["contact.json" module](https://github.com/HumanCellAtlas/metadata-schema/blob/master/json_schema/module/project/contact.json#L7)

**Comment by ESapenaVentura** [comment]
> investigate how often we actually have Contributor institute

Most times, it's actually more likely that the contributor will have **multiple** institutes

> why didn't it actually raise the error when creating?

The project was probably not raised because the "ignore validation errors" checkbox was ticked on project creation

**Comment by gabsie** [comment]
Thanks, Enrique - will close for now :)
