### ISSUE TITLE
CellxGene Interoperability Meetings

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/dcp-ingest-central#882]
Wei is going to meetings with Elizabeth Kiernan and Kaylee Matthews and other organisations to try and determine how well / easily they can use the cellxgene-wrangled matrices that we are pushing from the HCA.

**Comment by ESapenaVentura** [comment]
Done now 

Meetings with SCEA, SCP, Cell Browser with feedback (Will come up in the demos)
