### ISSUE TITLE
Metadata spreadsheets for all published DCP projects

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#885]
# Warning Zenhub is no longer showing the latest comments for this ticket
### Prepare
- [x] Create an operational script to create a file listing Project & Submission UUIDs  in ingest:
    - All projects except:
        - Those that do not exists in terra
        - Those that contain multiple submissions 
        - Those where the submission is not in the status Graph Valid or Higher
    - Implemented here: ebi-ait/hca-ebi-dev-team#519

### Operate
- [ ] Create an operational script to export spreadsheets given a file of project and submission uuids
    - Bypasses any need for status changes and exports the spreadsheets
    - We can run the task Operationally
    - We can run it in the EC2
    - Output errors and successes to files for easy reporting

### Report
- [ ] Send import team list of projects that now have spreadsheet data / metadata.

**Comment by MightyAx** [comment]
### Prepare Results
#### Azul Projects: 291
#### With One Submission: 278

#### Projects by status 
  - Metadata invalid: 3
  - Metadata valid: 111
  - Graph invalid: 2
  - Graph valid: 1
  - Submitted: 1
  - Archived: 1
  - Exported: 112
  - Complete: 45

#### Graph valid or higher: 160
##### If we also include Metadata valid: 271

**Comment by MightyAx** [comment]
@amnonkhen @gabsie I think we should also export these 111 `Metadata valid` submissions.

Perhaps with the mitigation of "skip if we fail to generate the spreadsheet".

Do you concur?

**Comment by MightyAx** [comment]
MightyAxCheck for project/supplementary file schema version

**Comment by MightyAx** [comment]
For consideration: Import Form?

**Comment by ESapenaVentura** [comment]
@ESapenaVentura to ping @MightyAx for testing

**Comment by MightyAx** [comment]
First version is to re-export all spreadsheets generated since the end of R23, before the end of R23 so that terra will ingest these new versions:
```
submission_uuid:51945966-78ff-4d20-890f-457cf986a2d3 project_uuid:12f32054-8f18-4dae-8959-bfce7e3108e7
submission_uuid:baf35d2a-5afd-4eca-a38c-6ea8bbefb9ec project_uuid:cd9d6360-ce38-4321-97df-f13c79e3cb84
submission_uuid:0948a727-228f-4cfc-857e-6243c6aed08d project_uuid:2043c65a-1cf8-4828-a656-9e247d4e64f1
submission_uuid:5f7fa8b1-f35b-4a2d-b385-c2a686acbc9c project_uuid:3ce9ae94-c469-419a-9637-5d138a4e642f
submission_uuid:d78adee7-e3d1-46bc-bca4-7822181bd8af project_uuid:cbd2911f-252b-4428-abde-69e270aefdfc
submission_uuid:670faf2b-cfb8-411a-8400-91168cdd139c project_uuid:957261f7-2bd6-4358-a6ed-24ee080d5cfc
submission_uuid:639d3383-47a6-4436-985e-4eedd8ee46bb project_uuid:5f607e50-ba22-4598-b1e9-f3d9d7a35dcc
submission_uuid:fcf7da86-018e-4cc1-a2f1-7a23648223b7 project_uuid:6e60a555-fd95-4aa2-8e29-3ec2ef01a580
submission_uuid:85b5d566-bb78-4bed-89e6-2f44e7b6bd48 project_uuid:5b328561-4a97-40ac-b7ad-6a90fc59d374
submission_uuid:fbd97e6f-625d-4e61-8cc9-50f2c82f2c5a project_uuid:e88714c2-2e78-49da-8146-5a60b50628b4
submission_uuid:fc4feb0b-3749-49b5-b15b-0a9dc1dd6e2f project_uuid:e57dc176-ab98-446b-90c2-89e0842152fd
submission_uuid:3da6718d-aeb4-4376-acd3-6ee24994e2a0 project_uuid:77dedd59-1376-4887-9bca-dc42b56d5b7a
```

**Comment by MightyAx** [comment]
Before the end of R24 we have an opportunity to regenerate all spreadsheets created since the end of R23, ensuring they have the latest format, these are:
```
submission_uuid:51945966-78ff-4d20-890f-457cf986a2d3 project_uuid:12f32054-8f18-4dae-8959-bfce7e3108e7
submission_uuid:baf35d2a-5afd-4eca-a38c-6ea8bbefb9ec project_uuid:cd9d6360-ce38-4321-97df-f13c79e3cb84
submission_uuid:0948a727-228f-4cfc-857e-6243c6aed08d project_uuid:2043c65a-1cf8-4828-a656-9e247d4e64f1
submission_uuid:5f7fa8b1-f35b-4a2d-b385-c2a686acbc9c project_uuid:3ce9ae94-c469-419a-9637-5d138a4e642f
submission_uuid:d78adee7-e3d1-46bc-bca4-7822181bd8af project_uuid:cbd2911f-252b-4428-abde-69e270aefdfc
submission_uuid:670faf2b-cfb8-411a-8400-91168cdd139c project_uuid:957261f7-2bd6-4358-a6ed-24ee080d5cfc
submission_uuid:639d3383-47a6-4436-985e-4eedd8ee46bb project_uuid:5f607e50-ba22-4598-b1e9-f3d9d7a35dcc
submission_uuid:fcf7da86-018e-4cc1-a2f1-7a23648223b7 project_uuid:6e60a555-fd95-4aa2-8e29-3ec2ef01a580
submission_uuid:85b5d566-bb78-4bed-89e6-2f44e7b6bd48 project_uuid:5b328561-4a97-40ac-b7ad-6a90fc59d374
submission_uuid:fbd97e6f-625d-4e61-8cc9-50f2c82f2c5a project_uuid:e88714c2-2e78-49da-8146-5a60b50628b4
submission_uuid:fc4feb0b-3749-49b5-b15b-0a9dc1dd6e2f project_uuid:e57dc176-ab98-446b-90c2-89e0842152fd
submission_uuid:3da6718d-aeb4-4376-acd3-6ee24994e2a0 project_uuid:77dedd59-1376-4887-9bca-dc42b56d5b7a
```

**Comment by MightyAx** [comment]
Before the end of R24 we have an opportunity to regenerate the spreadsheets for all projects exported since the end of R23 with the new formatting.
These are:
```
submission_uuid:51945966-78ff-4d20-890f-457cf986a2d3 project_uuid:12f32054-8f18-4dae-8959-bfce7e3108e7
submission_uuid:baf35d2a-5afd-4eca-a38c-6ea8bbefb9ec project_uuid:cd9d6360-ce38-4321-97df-f13c79e3cb84
submission_uuid:0948a727-228f-4cfc-857e-6243c6aed08d project_uuid:2043c65a-1cf8-4828-a656-9e247d4e64f1
submission_uuid:5f7fa8b1-f35b-4a2d-b385-c2a686acbc9c project_uuid:3ce9ae94-c469-419a-9637-5d138a4e642f
submission_uuid:d78adee7-e3d1-46bc-bca4-7822181bd8af project_uuid:cbd2911f-252b-4428-abde-69e270aefdfc
submission_uuid:670faf2b-cfb8-411a-8400-91168cdd139c project_uuid:957261f7-2bd6-4358-a6ed-24ee080d5cfc
submission_uuid:639d3383-47a6-4436-985e-4eedd8ee46bb project_uuid:5f607e50-ba22-4598-b1e9-f3d9d7a35dcc
submission_uuid:fcf7da86-018e-4cc1-a2f1-7a23648223b7 project_uuid:6e60a555-fd95-4aa2-8e29-3ec2ef01a580
submission_uuid:85b5d566-bb78-4bed-89e6-2f44e7b6bd48 project_uuid:5b328561-4a97-40ac-b7ad-6a90fc59d374
submission_uuid:fbd97e6f-625d-4e61-8cc9-50f2c82f2c5a project_uuid:e88714c2-2e78-49da-8146-5a60b50628b4
submission_uuid:fc4feb0b-3749-49b5-b15b-0a9dc1dd6e2f project_uuid:e57dc176-ab98-446b-90c2-89e0842152fd
submission_uuid:3da6718d-aeb4-4376-acd3-6ee24994e2a0 project_uuid:77dedd59-1376-4887-9bca-dc42b56d5b7a
```

**Comment by MightyAx** [comment]
Of note during consolidation, it was noted that these two projects were listed on the import form and have never had a spreadsheet generated:

1. [KidneyOrganoidsBioprinting](https://contribute.data.humancellatlas.org/projects/detail?uuid=8787c238-89ef-4636-a57d-3167e8b54a80&tab=upload) (graph invalid)
2. [HematopoieticImmuneCellAtlas](https://contribute.data.humancellatlas.org/projects/detail?uuid=cc95ff89-2e68-4a08-a234-480eca21ce79&tab=upload)  (Seems like a release 23 project that got stuck in submitted and was never investigated)

I would not recommend adding these to the list.

**Comment by MightyAx** [comment]
The 12 R24 projects that were exported before the release of the new formatting have been updated to the new formatting.
[log attached export_R24 2023_01_30 16_30.txt](https://github.com/ebi-ait/dcp-ingest-central/files/10539475/export_R24.2023_01_30.16_30.txt)

**Comment by Wkt8** [comment]
Release 24 projects have had spreadsheets exported (@idazucchi to check final project)

**Comment by MightyAx** [comment]
I think, for any of the projects that are `Metadata Valid`/ `Graph Valid` we should probably proceed with the export using the standard ingest systems, since there is a change in metadata that hasn't been exported yet (specifically project schema version) should be reflected on Terra alongside the spreadsheet export. Otherwise the spreadsheet would reference one schema version, while the metadata in terra would reference a different version.

For `Exported` / `Completed` where there hasn't been change we can continue with the original plan of Export the spreadsheet and supporting files without changing anything else.

**Comment by arschat** [comment]
We need to evaluate the situation on how we are going to proceed. @MightyAx @amnonkhen @ESapenaVentura

**Comment by gabsie** [comment]
@amnonkhen will follow up on this.

**Comment by amnonkhen** [comment]
test comment

**Comment by amnonkhen** [comment]
I prepared the list of projects to export: [projects.csv](https://github.com/ebi-ait/dcp-ingest-central/files/10768298/projects.csv)
These are projects that are:
- with project status: 'Published in DCP', 'Submitted', 'In progress'
- found in Azul
- submission status: 'Exported', 'Complete'
 Other submissions statuses such as Metadata valid or Graph valid are excluded now. When the work on the is finished they will be exported and a spreadsheet will be part of this export.

Export log: [export_160_old_projects-2023_02_17.txt](https://github.com/ebi-ait/dcp-ingest-central/files/10771138/export_160_old_projects-2023_02_17.txt)

**Comment by gabsie** [comment]
Hey @amnonkhen - I randomly spot-checked at least 7 projects from your list of exports. The first one from these 7 shows not as 'Exported' in ingest, but 'Exporting'. I won't go into every single one of them, but maybe it's good to check if there are others which are problematic. 
Is it a right summary that you now  - after checking they have all successfully exported, need to notify Mary Wons and Nate that we have 161 new projects coming, they have been submitted, fill out import forms for them?

Thank you.
