### ISSUE TITLE
New users can't register in ingest

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#890]
**Describe the bug**
When trying to register a new user into the UI, the link provided by the "register" button leads to a broken URL

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://contribute.data.humancellatlas.org/home
2. Try to register as a new user by clicking on "Log in" and then "Register" on the new page
3. Wait forever

**Expected behaviour**
It should lead you to a register page, where the user would be able to register with a federated account into LS RII.

Funnily enough, if you try to log in and are not registered, the redirection from the log in to the registration works fine.

**Environment**
- [x] prod
- [ ] staging
- [ ] dev

**Browser**
- [x] Chrome
- [ ] Safari
- [ ] IE
- [ ] Other (please specify)

**Comment by amnonkhen** [comment]
I looked in [the LS/AAI website](https://elixir-europe.org/platforms/compute/aai) and found the support details. I contacted them on email and slack (Dominik Frantisek Bucik, Mikael Linden) and got the following response:

> Dear Amnon,
after the migration to the LS AAI the registration link has changed. If you wish to use exactly the same procedure, just use this link instead:
https://signup.aai.lifescience-ri.eu/fed/registrar/?vo=lifescience&targetnew=https%3A%2F%2F[…]%252Fwww.elixir-europe.org%252Fregistration-successful

Currently ingest-ui uses the following "perun" url for this:
```
https://perun.elixir-czech.cz/registrar/?vo=elixir&targetexisting=https://www.elixir-europe.org/alreadyregistered&targetnew=https://www.elixir-europe.org/registration-successful
```
so according to the response from LS Support, we would need to change it.

**Comment by gabsie** [comment]
Already fixed.
