### ISSUE TITLE
Discussion with Ana from Human Blood Atlas

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/dcp-ingest-central#891]
Wei to meet with Ana from Human Blood Atlas to discuss
- their plan for submitting to HCA
- our pathway for hca - to - cellxgene pipeline work
- potential for collaboration and support 

Agenda + Notes: https://docs.google.com/document/d/1bKphpEjtzerkSENjEzUPKLtnfyKnMaAWvMvXNm-N7bw/edit#

**Comment by Wkt8** [comment]
Good meeting, with lots of engagement from Ana. See notes in the link above for full details.

Short version: they were interested in our tools to combine metadata from hca and cellxgene to get more comprehensive metadata to create an integrated blood atlas. Meeting to be set up in January.

**Comment by gabsie** [comment]
Thank you for stepping in, Wei! We have been chatting to Anna's colleague here as well --

**Comment by Wkt8** [comment]
Meeting this Thursday (today)

**Comment by amnonkhen** [comment]
UCSC Wranglers are taking over the Blood network.
Can be closed.
