### ISSUE TITLE
Revisions in the UI to show metadata errors (for now in Submissions)

### ISSUE THREAD

**Issue by gabsie** [ebi-ait/dcp-ingest-central#91]
Hi, 

Posting these up for discussion tomorrow.

Gabs![8.2 Submission valid.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/a9b63f83-87da-4bf3-a617-04053724fb3f)![8.2 Submission - numbers in tabs.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/4aa5949d-3cc6-4213-a4b7-053bac42875e)![8.2 Submission - texts.png](https://images.zenhubusercontent.com/5b18f77c348b7966b4345c29/76329e55-2f9c-422f-85f1-767ae4e3ca73)

We can review after standup.

**Comment by gabsie** [comment]
Hi, @jacobwindsor 

1. When there are no errors, I suppose none of the lines will show (the ones showing the summary?)
It's just the label of the project will be Draft, or Valid or Validating, correct?
And only when validation has happened, then is when we show errors summary?
see this one is Validating - you will know the errors after this process has happened, right? 
https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=a3dbb8fe-6a0d-4ca7-a043-4ea1a88b7e01

What about submitted? I think I am not clear whether any report is due for that state.. 

2. When there are errors only in one of the entities, let's only show that line, for example here:
https://dev.contribute.data.humancellatlas.org/submissions/detail?uuid=58e464fd-304a-4997-814a-2edb80cc73a4

let's only show the line where there are errors, i.e. in Data files

I think we can afterwards also tell Enrique to test this

Gabs

**Comment by gabsie** [comment]
One more thing I noticed, @jacobwindsor 

https://staging.contribute.data.humancellatlas.org/submissions/detail?id=5fbf7dbdd274853a811c1931

this one says that I have one error in Biomaterials
However, I am currently in Data files  - and when I click on the Biomaterials link - it doesn't take me to that tab.
Let me know if you can't reproduce

Gabs

**Comment by jacobwindsor** [comment]
Okay, let's remember it and see if someone else finds how to reproduce!

**Comment by jacobwindsor** [comment]
https://github.com/ebi-ait/ingest-ui/pull/73
https://github.com/ebi-ait/ingest-ui/pull/72

**Comment by jacobwindsor** [comment]
The two tasks for this are now in prod:
https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/93
