### ISSUE TITLE
project grouping & filtering by biological network

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#911]
As a **system operator/data manager**
I would like to **assign to and search by the biological network** to which the project belongs. Each project can be assigned to more than a single network.
So that the **progress and coverage on the different network could be observed**.

Acceptance Criteria:
- [x] netwrok names added to form - see https://www.humancellatlas.org/biological-networks/
- [ ] project-network mapping document added/licked to ticket 
- [x] projects assigned to networks in ingest
- search capabilities
   - [x] find project that belong to a network
   - [ ] find project that do not belong to any network
- [ ] wrangler/Gabby approve ui

**Comment by amnonkhen** [comment]
plan:
~phase 1: implement as label~ UPDATE: we'll go straight to phase 2
phase 2: add a dedicated search field

data update: assign each project the relevant network

**Comment by gabsie** [comment]
Please let's have a separate field, I do not want to have this as a label in the same group as the current labels. They serve very different purposes.
Let's discuss when I'm back.

**Comment by amnonkhen** [comment]
Tasks for @Mil-m:
- [x] set up ingest-ui on intellij ide by following instructions on readme and run locally connecting to core on dev
- [x] make a sequence diagram documenting how filtering works, from the browser as for into the backend as possible

```mermaid
sequenceDiagram
    
    User -->> UI: click search form
    UI -->> AllProjectsComponent: onFilter($event)
    AllProjectsComponent -->> ProjectDataSource: setQueryData()
    ProjectDataSource --> core : /projects/filter
    core --> ProjectController: filterProjects()
    ProjectController -->> ProjectService: filterProjects()
    ProjectService --> ProjectQueryBuilder: buildProjectsQuery()
    ProjectService -->> mongo: query for projects
```

- [x] design how project network is maintained in the DB
- [x] add necessary code in core
- [x] run core locally in connected to dev db
- [x] update the new projectNetwork field on dev db using rest calls to the local core
- [x] test the /filter endpoint with the new search attribute
- [x] add a new search field to the form
- [x] run ui locally connected to local core
- [x] test modified search form
- [x] PR Review and deployment to dev
- [ ] prepare a script to update the bionetwork association for each project. Review by Amnon - see #929 
- [ ] Gabby & Wrangler review on dev
- [ ] merge to master & validate on staging
- [ ] deploy to prod
- [ ] run the script

**Comment by ESapenaVentura** [comment]
Mongo restore command did not work - @Mil-m  to look into it

**Comment by gabsie** [comment]
Hi, @amnonkhen and @Mil-m - you can get the Bionetwork names from this page on the Human Cell Atlas:
https://www.humancellatlas.org/biological-networks/ 

Thanks, 
Gabby

**Comment by anu-shiva** [comment]
Comments in the PR to be addressed

**Comment by gabsie** [comment]
This is to be tested today  by @gabsie and @ofanobilbao - in dev.

**Comment by ofanobilbao** [comment]
Just tested this in Dev. Development is missing from the BioNetworks list

**Comment by gabsie** [comment]
To follow up from yesterday's chat with Amnon, both Blood and Development need to be added to the dropdown options.
