### ISSUE TITLE
Data portal showing biological network groupings

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/dcp-ingest-central#912]
Use case 1: 
As a data consumer 
I want to be able to see what projects (and if my project is) are listed under a biological network in the data portal. 
This requires some methods of grouping or tagging projects together. Linked to #911

Acceptance Criteria: 
- [x] Obtain community feedback about the method of grouping projects in the data portal linked to #860
- [ ] Obtain feedback from Malte and Fabian Theis's labs about grouping projects in the data portal 
- [x] Metadata schema updates discussed with the wranglers
- [x] Metadata schema updates prioritised and pushed through 
- [ ] There is a method in the data portal to show projects grouped together

**Comment by Wkt8** [comment]
As per a conversation with Gabs, based on a meeting with the DCP, there is now a requirement to create metadata-schema changes for 
a) representing a project as 'The Atlas Project', the project which has integrated a number of different datasets and analysed them together, and which tissue it is 
b) representing a project as a subsidiary project which is part of 'The Atlas Project', and which tissue it is

Additionally we need to think about how to wrangle the 'integrated main project' in terms of donors, technology, etc.

**Comment by Wkt8** [comment]
Document here: https://docs.google.com/document/d/1N3dJA5dQuJcY5pxhT2pNgwZptKfdH3BSsqZSnWD0nUo/edit# 

We need an internal meeting

**Comment by Wkt8** [comment]
Internal meeting concluded - now having meetings with scientists (Pablo, Ana-Maria) and Dave 

@gabsie please see the slightly cleaned up version here: https://docs.google.com/document/d/1N3dJA5dQuJcY5pxhT2pNgwZptKfdH3BSsqZSnWD0nUo/edit#

**Comment by Wkt8** [comment]
Meeting on Friday with Hannifa Lab.

**Comment by Wkt8** [comment]
Metadata schema update here: https://github.com/HumanCellAtlas/metadata-schema/pull/1518

**Comment by idazucchi** [comment]
PR has been merged

remaining tasks:
- data portal: display new fields
- [ ] check which atlas we are exporting for June
- [ ] update projects for the atlas

**Comment by Wkt8** [comment]
This can now be closed because the data portal is not using the metadata schema to show biological network groupings.
