### ISSUE TITLE
large dataset crashes spreadsheet generation

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#926]
See @idazucchi 's project:
- submission `251bf9c5-a5e5-4da6-b2ad-93bac7d47eb4`

The failure happens when trying to call the `linkingMap` link on the submission.

Code in ingest client: 
[hca_ingest.downloader.data_collector.DataCollector.__get_linking_map](https://github.com/ebi-ait/ingest-client/blob/0f205ad415566e1243758cf8a477c56a81aa2d89/hca_ingest/downloader/data_collector.py#L43)

The failure is in ingest core.
The code that builds the response is inefficient and repeatedly calls mongo queries.
 Steps:
- [x] recreate the problem locally - running local ingest-core, local mongo with prod data
- [x] design a solution - use mongo aggregation framework
- [x] test locally on many big projects
- [ ] continue regular release procedure.

**Comment by Mil-m** [comment]
Need a call with @amnonkhen 
@idazucchi support me with the large spreadsheets

**Comment by Wkt8** [comment]
Requires testing locally - expect lower capacity due to days off for conferences next week.

**Comment by amnonkhen** [comment]
I modified the `linkingMap` endpoint in the [SubmissionLinkMapController](https://github.com/ebi-ait/ingest-core/blob/0e9d90c108641327918069b1019ac50549f7bfca/src/main/java/org/humancellatlas/ingest/submission/web/SubmissionLinkMapController.java) class.
It is now implemented with 5 mongo queries that use [mongo's aggregation operations](https://www.mongodb.com/docs/manual/aggregation/#aggregation-operations).

It improved the time of `linkingMap` from not even completing after 30 minutes or crashing ingest to less then a minute.

**I tested the feature extensively manually:**

- running it on many submissions taken from the prod db, running with a local ingest-core and mongo
- comparing results with the old implementation, using http://play.jd-tool.io/ website
- I am now disabling this test with the intention to get back to it.

Here are a few spreadsheet I created locally from production projects. I need a Wrangler's help in verifying they are ok:

- [ ] [0948a727-228f-4cfc-857e-6243c6aed08d.xlsx](https://github.com/ebi-ait/dcp-ingest-central/files/11116959/0948a727-228f-4cfc-857e-6243c6aed08d.xlsx)
- [ ] [4756b97c-3666-4ff0-9c48-611dc06b7740.xlsx](https://github.com/ebi-ait/dcp-ingest-central/files/11116960/4756b97c-3666-4ff0-9c48-611dc06b7740.xlsx)
- [ ] [c81f7d54-a27f-4212-a6df-88dde947f7cc.xlsx](https://github.com/ebi-ait/dcp-ingest-central/files/11116961/c81f7d54-a27f-4212-a6df-88dde947f7cc.xlsx)

**Comment by amnonkhen** [comment]
I installed in prod today, but testing export of submission [`251bf9c5-a5e5-4da6-b2ad-93bac7d47eb4`](https://contribute.data.humancellatlas.org/submissions/detail?uuid=251bf9c5-a5e5-4da6-b2ad-93bac7d47eb4&project=a4f154f8-5cc9-40b5-b8d7-af90afce8a8f) seems to crash the exporter without any message visible in the logs in grafana.
Inspecting the exporter pods in k8s shows they suffer  memory exhaustion:

```
kubectl describe pod ingest-exporter-8c6bd77-swv4v
      Reason:       OOMKilled
```

Investigative actions:
- [x] *PASSED* - run local ingest client connected to local api connected to prod db
- [x] *PASSED* - run [linkingMap](https://api.ingest.archive.data.humancellatlas.org/submissionEnvelopes/63ece9995cd8d87e76ebb1b5/linkingMap.json) endpint on prod api
- [x] *PASSED* - run local exporter connected to prod api 
- [x] *DONE* - find pod crash reason - OOOMKilled (out of memory)
- [x] *PASSED* test [increased memory allocation ](https://github.com/ebi-ait/ingest-kube-deployment/commit/3c9e720c825c3389093f4f6471d56625bb7e5e86)

**Comment by amnonkhen** [comment]
Memory issue encountered. Dealt with. 
MelanocyteDevelopment exported in prod. @idazucchi has a dataset ready for export.
