### ISSUE TITLE
update project-network association in ingest

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#929]
See [Project to network association list](https://docs.google.com/spreadsheets/d/129T_QsKKCqJmPiwuK9qLl7uxASUplI84At6ewu2vwLA/edit#gid=1357076043)

Initially do just: Blood, Kidney, Gut & Retina

This is related to #911

Will be done manually by Oihane.

Tasks:
- [ ] ~write the script~
- [ ] ~review and rehearse on dev~
- [ ] ~run on prod~

**Comment by amnonkhen** [comment]
Script outline:
1. for each row
1.1. If the project is in ingest (see "in ingest?) column - *add* the network to the existing networks list. add to a list of updated projects.
1.2 if project is not in ingest - add to list of not updated projects.

**Comment by amnonkhen** [comment]
automation canceled.
Will be done by Oihane.

**Comment by Mil-m** [comment]
https://github.com/ebi-ait/ingest-ui/pull/192

**Comment by ofanobilbao** [comment]
Blood:
https://contribute.data.humancellatlas.org/projects/detail?uuid=ae62bb31-55ca-4127-b0fb-b1771a604645&tab=project - Can't add label as submission is in exporting state

AIDA_pilot project not in Ingest (Lattice dataset) so I have not added the label

Rest done

**Comment by ofanobilbao** [comment]
Kidney:
https://contribute.data.humancellatlas.org/projects/detail?uuid=97fca723-d9e9-4263-9f67-335416086f47&tab=project - Can't add label as submission is in Graph validating state

I am having to fix several missing fields on the Project Tab, specially data access and organism

**Comment by ofanobilbao** [comment]
Kidney Done now

**Comment by ofanobilbao** [comment]
Gut added

**Comment by ofanobilbao** [comment]
Retina added as Eye

**Comment by ofanobilbao** [comment]
@amnonkhen I don't know if the two projects I link in my comments are the ones stuck from R25. If you could look into them that would be great. Then this ticket we would be able to close

**Comment by ofanobilbao** [comment]
@gabsie we are not labelling Lung, Development, Immune and Skin yet? I thought Skin was "official" list and "development" as well, and we worked on them in the past. Please, confirm as I have finished with the other Bionetwork labels

**Comment by gabsie** [comment]
@gabsie - reply here with the update on New network list for Brain.

**Comment by Wkt8** [comment]
There are some projects in graph-validating that don't have project associations in Ingest.

**Comment by amnonkhen** [comment]
Now that graph validation is fixed, these datasets can be updated.

**Comment by amnonkhen** [comment]
Closing - not currently a priority.
