### ISSUE TITLE
Exporter: Overwriting a file does not contemplate for multiple instances

### ISSUE THREAD

**Issue by ESapenaVentura** [ebi-ait/dcp-ingest-central#934]
PR ebi-ait/ingest-exporter#57

**Context**
Lately, we've been seeing exporter errors where smaller datasets fail due to a googleapis PATCH operation failing (See log for example).

I have noticed that 2 weeks ago, a change was made in the exporter to allow for overwrite of file descriptor and metadata of the spreadsheet.

This change makes it so that every metadata file and descriptor is written in overwrite mode, which I think may be causing this error (Multiple instances overwriting at the same time)

**Description of the issue**

When exporting, some datasets are getting the following errors:

```
"2023-03-24 17:05:52,467 - TerraExperimentExporter - ERROR - submission_uuid:cb989b6e-bab9-432c-895d-ea8d2aa1ebab - export_job_id:641dd84dc99baf0c6c9eeafb - project_uuid:c5b475f2-76b3-4a8e-8465-f3b69828fec3 - process_uuid:1a6b4e97-b6b3-4b04-a17f-3a14dad1dd1e - index:4/10 - Rejecting message: {\"exportJobId\":\"641dd84dc99baf0c6c9eeafb\",\"documentId\":\"64183e2572536c7f2bdc223a\",\"documentUuid\":\"1a6b4e97-b6b3-4b04-a17f-3a14dad1dd1e\",\"callbackLink\":\"/processes/64183e2572536c7f2bdc223a\",\"documentType\":\"process\",\"envelopeId\":\"64183e1e72536c7f2bdc2204\",\"envelopeUuid\":\"cb989b6e-bab9-432c-895d-ea8d2aa1ebab\",\"projectId\":\"636a6ba633904466861ed54a\",\"projectUuid\":\"c5b475f2-76b3-4a8e-8465-f3b69828fec3\",\"index\":4,\"total\":10,\"context\":null} due to error: 404 PATCH https://storage.googleapis.com/storage/v1/b/broad-dsp-monster-hca-prod-ebi-storage/o/prod%2Fc5b475f2-76b3-4a8e-8465-f3b69828fec3%2Fmetadata%2Flibrary_preparation_protocol%2F043020d5-4adf-493e-8860-5454895f7247_2023-03-20T11%3A06%3A11.613000Z.json?generation=1679677552101561&projection=full&prettyPrint=false: The specified key does not exist.\n"
```
(more information on this graphana query: https://monitoring.ingest.archive.data.humancellatlas.org/explore?orgId=1&left=%5B%221679673600000%22,%221679684399000%22,%22Loki%22,%7B%22expr%22:%22%7Bapp%3D%5C%22ingest-exporter%5C%22%7D%20%7C~%20%5C%221a6b4e97-b6b3-4b04-a17f-3a14dad1dd1e%5C%22%22%7D%5D)

**Possible cause**

After some very light investigation, I think the issue with the "overwrite" function calls the upload function without setting a proper pre-condition to check if other exporter instances are uploading the file, thus not checking for the "PreconditionFailed" error, and rather than polling to wait for metadata file transfer, several instances are intervening with each other and causing errors.

Up to now, this wasn't an issue because metadata files that are shared amongst exportJobs were always written and not overwritten.

More information on the lines of code here: https://github.com/ebi-ait/ingest-exporter/blob/484243f80893875f6e0d6853887f5adb09bfc9d4/exporter/terra/gcs/storage.py#L25-L48

**Comment by ESapenaVentura** [comment]
I have been able to replicate the bug and fix it! so the intuition of where the problem was is correct.

**To replicate the bug**
- Clone the [ingest-exporter](https://github.com/ebi-ait/ingest-exporter) repository
- Download `reexport_metadata.py` script from branch https://github.com/ebi-ait/ingest-exporter/tree/bug/dcp934-handle-multithread-overwriting and run from root
   ```
   python reexport_metadata.py d0e49709-adff-4177-b01c-d6f384228730 5
   ```
   This will try to re-export the metadata for the submission with that UUID, where we originally observed the error, with 5 threads.

The error is a bit difficult to observe, as it's hidden in a sea of logs, but you should be able to observe some 404 errors.

**To solve the bug**
- Checkout to bugfix branch: https://github.com/ebi-ait/ingest-exporter/tree/bug/dcp934-handle-multithread-overwriting (or `git checkout dcp934-handle-multithread-overwriting`)
- Run the script as above
- There should be no error, however I noticed in one of the runtimes a file got stuck in assert_file_completion

**(Further proof) To test the bug**
- If you run the script above without the changes to the gcs/storage.py module (As in the first example) but with only 1 thread, the bug will not appear


**Next steps**
- [x] Create a PR (Create a test?)
- [ ] Have it reviewed and merged it to dev
- [ ] Test with a full export in dev
- [ ] Ensure this change does not affect the previous commit (To ensure Descriptors are overwritten)

**Comment by amnonkhen** [comment]
I believe we should solve this problem differently. Only overwrite the spreadsheet related metadata file. See my comments to the PR.

**Comment by idazucchi** [comment]
this is in production!

**Comment by gabsie** [comment]
should this be closed, cc @amnonkhen
