### ISSUE TITLE
linkingMap endpoint unit test fails due to unsupported function in in-memory mongo

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#936]
In the scalability fix for the linkingMap endpoint we are using the aggregation framework.
We specifically use the `$toString` aggragation operator, which is not supported by the flapdoodle in-=mempry mongo we use for the unit tests.
See dcp-926 ebi-ait/dcp-ingest-central#926

I tested the feature extensively manually:
- running it on many submissions taken from the prod db, running with a local ingest-core and mongo
- comparing results with the old implementation, using http://play.jd-tool.io/ website
I am now disabling this test with the intention to get back to it.

Possible fixes:
- upgrade flapdoodle - maybe a newer version supports $toString
- use a real mongo db instance (maybe dev) in the test. Note - in this case it needs a separate db, so that it does not delete the entire dev db.

**Comment by idazucchi** [comment]
deployed in dev and tested, it's much faster than the old version

will be deployed in production today! 
Once this is in prod we can try to export all the datasets left from R26

**Comment by Wkt8** [comment]
Memory issue encountered. Dealt with. MelanocyteDevelopment exported in prod. @idazucchi has a dataset ready for export.
