### ISSUE TITLE
show hca_bionetworks in catalogue

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/dcp-ingest-central#954]
Acceptance:
- [x] show hca_bionetworks column in project catalogue
- [x] show bio networks filter
- [ ] filter values:
   - [x]  each network
   - [ ]  any
   - [ ]  not in a network
- [x] update network assignment
   - [x] write script to update a single project by uuid and network
   - [x] review
   - [ ] run for all projects (see spreadsheet below)

**Comment by gabsie** [comment]
For the population of Networks, Amnon you can use the [information from the spreadsheet](https://docs.google.com/spreadsheets/d/129T_QsKKCqJmPiwuK9qLl7uxASUplI84At6ewu2vwLA/edit#gid=1084845810). The projects are available with their UUIDs.

@amnonkhen , I think it's better for you to enter your plan of tasks here below:

**Comment by gabsie** [comment]
These are ready to assign:

- [x] Blood V1.0  - these are Immune Network, Blood atlas, V 1.0
- [x] Kidney V1.0 - these are Kidney Network, Kidney atlas, V 1.0
- [x] Gut V1.0 - these are Gut Network, Gut atlas, V 1.0
- [x] Retina V1.0 - these are Eye Network, Retina atlas, V 1.0
- [x] Lung V1.0 - these are Lung Network, Lung atlas, V 1.0

Let me know if questions!

**Comment by amnonkhen** [comment]
@gabsie I am assuming I can know which project is an atlas project by the existence of the word "atlas" in its name. Would this be correct?

**Comment by amnonkhen** [comment]
All requested 5 networks updated.
I added 2 columns to each bionetwork worksheet with the update status and failure comments.

There were 7 errors in total:
- blood
  - [`b11acd8b-25cd-453e-a654-f7af80713ce9`](https://contribute.data.humancellatlas.org/projects/detail?uuid=b11acd8b-25cd-453e-a654-f7af80713ce9): project was invalid 
    - 12/7 - done
  - [`9dd2d2a5-d8d3-4e61-a7f7-6ad82fbae14`](https://contribute.data.humancellatlas.org/projects/detail?uuid=9dd2d2a5-d8d3-4e61-a7f7-6ad82fbae14): project missing in ingest
- kidney
  - [`e4b2e4d9-2b9b-46cf-b0e0-bb23ff28030a`](https://contribute.data.humancellatlas.org/projects/detail?uuid=e4b2e4d9-2b9b-46cf-b0e0-bb23ff28030a): lattice project, also project metadata invalid, missing institution
  - [`c5b475f2-76b3-4a8e-8465-f3b69828fec3`](https://contribute.data.humancellatlas.org/projects/detail?uuid=c5b475f2-76b3-4a8e-8465-f3b69828fec3): error running update script. Needs investigation. Related to ebi-ait/hca-ebi-wrangler-central#1105
    - 12/7 - fails with http 403 after updating submission to Graph Valid
- lung
  - [`453d7ee2-319f-496c-9862-99d397870b63`](https://contribute.data.humancellatlas.org/projects/detail?uuid=453d7ee2-319f-496c-9862-99d397870b63): error during script running. needs investigation
    - 12/7 - done
  - [`d8d2419a-ea4b-49fa-8cae-e87d597d2031`](https://contribute.data.humancellatlas.org/projects/detail?uuid=d8d2419a-ea4b-49fa-8cae-e87d597d2031): no atlas version field in spreadsheet
  - [`2c4647ba-c814-4158-8ea9-6889930e4dfe`](https://contribute.data.humancellatlas.org/projects/detail?uuid=2c4647ba-c814-4158-8ea9-6889930e4dfe): no atlas version field in spreadsheet

**Comment by amnonkhen** [comment]
@ofanobilbao & @amnonkhen investigated the errors and discrepancies.
Decisions:
- [x] invalid projects - ignore validation step
  - done - 12/7
- [x] error projects - probably need a status change to allow project modification
    - 12/7 - one error, one success, see comment above

**Comment by ofanobilbao** [comment]
[https://app.zenhub.com/files/299258791/9844af89-807f-4ae7-9f02-ed21563a416e/download](https://app.zenhub.com/files/299258791/9844af89-807f-4ae7-9f02-ed21563a416e/download)

Going through the catalog today I found more discrepancies. I exported excel file for every network and datasets with DCP location. I identified a few issues/errors.

Summarising: For Kidney (I will upload here the highlighted spreadsheet) there is one Lattice dataset, with broken link to DCP (as other Lattice projects). And 4 datasets that are not kidney but Gut (they also display fine in Gut).

As for Lung, there are 2 missing projects (I've made the relevant comments on the Bionetworks spreadsheet)

**Comment by gabsie** [comment]
@amnonkhen @gabsie take a look at the above see if it's still relevant

**Comment by amnonkhen** [comment]
updates according to Oihane's comment:
- `fae72d89-4ac4-4aab-9b93-574775e168d4` - change to Lung
- `73769e0a-5fcd-41f4-9083-41ae08bfa4c1` - change to Gut
- `83f5188e-3bf7-4956-9544-cea4f8997756` - change to Gut
- `e4b2e4d9-2b9b-46cf-b0e0-bb23ff28030a` - changed to Kidney, project does not validate
- `fde199d2-a841-4ed1-aa65-b9e0af8969b1` - change to Gut

**Comment by amnonkhen** [comment]
@ofanobilbao can we move this to "done"?

**Comment by ofanobilbao** [comment]
Moving to Done, considering you did the changes and it should in theory now be ok

**Comment by arschat** [comment]
Script to update is included in this [PR](https://github.com/ebi-ait/hca-ebi-dev-team/pull/530) (since link to `dcp-954 update bionetworks #530` above is invalid)
