### ISSUE TITLE
Unable to log in to ingest staging using my EBI log-in

### ISSUE THREAD

**Issue by ami-day** [ebi-ait/dcp-ingest-central#97]
I have been testing the project registration and project view pages in ingest staging using both my EBI email and then subsequently, a new email I created to do testing as a contributor (I registered with ELIXIR). I made sure this new email was not associated with my EBI email, so that I would not be recognised as a wrangler.

Initially when logged in with my EBI email the project view pages seemed to be working ok and I was able to register a new project. However, after I had logged in using a new email as a contributor, and then tried to log back in using my EBI email to do more testing as a 'wrangler', I was unable to sign in. It recognised me as having logged in using the new 'contributor' email address I created, even though I had logged in via the new email using a different internet browser (Safari instead of Google Chrome as usual). I am now unable to choose to log in using a different email address (i.e. my EBI email).

I am assigning myself to this ticket as I am doing the testing.

**Comment by clairerye** [comment]
Logged this with Elixir, this seems to be an issue when the user doesn't confirm the global logout, but then there is not an easy way to do this after the fact.
