### ISSUE TITLE
hca-util sync'ed files still missing in ingest

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/dcp-ingest-central#988]
**Describe the bug**
After using hca-util to sync the files to the ingest s3 bucket the files' status remains missing in ingest, despite the files being present in the ingest s3 bucket.
This is problem persists after deleting the submission, reuploading the spreadsheet and syncing the files again.
Affected projects: potentially all new project
examples: 
- [DendriticCellActivationHCM](https://contribute.data.humancellatlas.org/projects/detail?uuid=e1fda217-7ee1-4c1a-adfa-648279dafac6) - ebi-ait/hca-ebi-wrangler-central#1227 
- EndStageHeartFailureSimonson - ebi-ait/hca-ebi-wrangler-central#1225

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://contribute.data.humancellatlas.org/projects/all
2. Select one project and upload a spreadsheet - [example](https://docs.google.com/spreadsheets/d/1Pu1Ck7YatLb6rWL-bX8EvIzKnTQint22/edit?usp=drive_link&ouid=113452802627011629126&rtpof=true&sd=true)
3. Upload files with hca-util sync - example uuid `fa6518af-997d-4c4a-9936-e3e83f97d926`
```shell
hca-util select fa6518af-997d-4c4a-9936-e3e83f97d926
hca-util sync s3://org-hca-data-archive-upload-prod/9fd083a0-d72d-4425-a391-f3b7a9795a3b/
```
4. Files are transferred succesfully
5. See error - the files are still missing in the submission

**Expected behaviour**
I expect the files to be recognised by ingest and validation to start

**Environment**
- [x] prod
- [x] staging - test [here](https://staging.contribute.data.humancellatlas.org/submissions/detail?uuid=feb78d3d-6204-499d-82cb-369f8a7f1bf3&project=90df3eb6-bffa-4959-9422-ff77810c27ea) with same project as above
- [ ] dev

**Browser**
- [ ] Chrome
- [ ] Safari
- [ ] IE
- [x] Firefox

**Comment by amnonkhen** [comment]
Trying to follow [dev troubleshooting sop](https://ebi-ait.github.io/hca-ebi-dev-team/operations_tasks/stuck-submissions-validation.html).


**Checking a [file](https://api.ingest.archive.data.humancellatlas.org/files/65ae4989165f1474c1f36cf7) from [DendriticCellActivationHCM](https://contribute.data.humancellatlas.org/projects/detail?uuid=e1fda217-7ee1-4c1a-adfa-648279dafac6)**
- name: `Human_5171_counts_0_1_HHJTNDSXY_S1_L003_I1.fastq.gz`
- validation attributs:
``` json
  "validationState": "Invalid",
  "validationErrors": [
    {
      "errorType": "FILE_NOT_UPLOADED",
      "message": "File cloudUrl property not set.",
      "userFriendlyMessage": "File not uploaded."
    }
  ],
  "validationJob": null,
  "uuid": "13049760-f249-4888-93c6-a08f966ebea6"
  "dataFileUuid": "97356ca4-c9c9-4217-b8ed-7c48e36f243c"
``` 
- It is not clear why the validationJob is `null`.

**Comment by amnonkhen** [comment]
**Step 2.  [validation job logs](https://us-east-1.console.aws.amazon.com/batch/home?region=us-east-1#jobs/ec2/detail/47074c9b-0d7f-405c-abb2-ca62c2c8416c) in aws**
nothing here

**Comment by amnonkhen** [comment]
**Step 3.  [file in s3](https://s3.console.aws.amazon.com/s3/object/org-hca-data-archive-upload-prod?region=us-east-1&bucketType=general&prefix=9fd083a0-d72d-4425-a391-f3b7a9795a3b/Human_5171_counts_0_1_HHJTNDSXY_S1_L003_I1.fastq.gz)**
file is there, nothing evident

**Comment by amnonkhen** [comment]
**Step 4. lambda function logs - filtering for the file**
[dcp-upload-csum-prod](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fdcp-upload-csum-prod/log-events$3FfilterPattern$3DHuman_5171_counts_0_1_HHJTNDSXY_S1_L003_I1$26start$3D1705536000000$26end$3D1705622399000). I found errors sending notifications to ingest about fie validation status:
```
2024-01-18T17:44:10+0000 INFO 
upload.common.ingest_notifier failed to send notification d47ab7e8-69b7-4a59-8741-b50653ebd87b with payload
```
```json
 
{
'upload_area_id': '8e330a2f-25c1-4bb7-95a0-0fc4e602b0bd', 
'name': 'Human_5171_counts_0_1_HHJTNDSXY_S1_L003_I1.fastq.gz',
 'size': 894113556, 
'content_type': 'binary/octet-stream; dcp-type=data',
 'url': 's3://org-hca-data-archive-upload-prod/8e330a2f-25c1-4bb7-95a0-0fc4e602b0bd/Human_5171_counts_0_1_HHJTNDSXY_S1_L003_I1.fastq.gz', 
'checksums': {
   'sha1': 'e6353f4c2aa830d3d58cc3278d4d10465ea20f08', 
   'crc32c': '824be187', 
   'sha256': '2b46f29fdd0e1894d9c333755061c1d6e2dc34290d16d044ff6ee5df00144fa3', 
   's3_etag': 'cfdda042513ef5106a9cf273a4e57380-14'
 }, 
'last_modified': '2024-01-18T17:44:05+00:00'
} 
```
```
and error Expecting value: line 1 column 1 (char 0)
```

This is **probably not the issue**, as a bit further down the log, at 024-01-18T17:44:41.087+00:00, it shows that the notification succeeded.
```
[INFO]	2024-01-18T17:44:41.87Z	7b41a1e8-92e3-5879-947f-ffcbf775ef3a	Notified Ingest: file_info={
'upload_area_id': '8e330a2f-25c1-4bb7-95a0-0fc4e602b0bd', 
'name': 'Human_5171_counts_0_1_HHJTNDSXY_S1_L003_I1.fastq.gz', 
'size': 894113556,
 'content_type': 'binary/octet-stream; dcp-type=data', 
'url': 's3://org-hca-data-archive-upload-prod/8e330a2f-25c1-4bb7-95a0-0fc4e602b0bd/Human_5171_counts_0_1_HHJTNDSXY_S1_L003_I1.fastq.gz', 
'checksums': {
   'sha1': 'e6353f4c2aa830d3d58cc3278d4d10465ea20f08', 
   'crc32c': '824be187', 
   'sha256': '2b46f29fdd0e1894d9c333755061c1d6e2dc34290d16d044ff6ee5df00144fa3', 
   's3_etag': 'cfdda042513ef5106a9cf273a4e57380-14'},
 'last_modified': '2024-01-18T17:44:05+00:00'}, 
status=d47ab7e8-69b7-4a59-8741-b50653ebd87b
```

**Comment by amnonkhen** [comment]
**Step 5: suspicious error messages in the logs**

Looking in the logs of ingest-core in Grafana I noticed errors related to the service account `ingest-service-gcp-svc-acc@ingest-service-301110.iam.gserviceaccount.com`.

```
java.lang.RuntimeException: com.auth0.jwk.SigningKeyNotFoundException: Cannot obtain jwks from url 
https://www.googleapis.com/service_accounts/v1/jwk/ingest-service-gcp-svc-acc@ingest-service-301110.iam.gserviceaccount.com
```

Hitting the [url mentioned in the error message](https://www.googleapis.com/service_accounts/v1/jwk/ingest-service-gcp-svc-acc@ingest-service-301110.iam.gserviceaccount.com) resulted in an HTTP 404 error message:
```json
{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND"
  }
}
```

Investigating in the [GCP console](https://console.cloud.google.com/), I noticed the project ingest-service-301110 was shut down & marked for deletion. I was able to restore it, and that fixed the problematic url, which now is back to return the public keys.

The next steps are:
1. re-sync the upload areas & verify whether this solved the file validation problem.
   - [x] DendriticCellActivationHCM 
   - [x] EndStageHeartFailureSimonson
2. Check with cloud consultants why I did not receive a notification about the deletion of the GPC project. For this end I created [incident INC0015024](https://embl.service-now.com/esc?id=ticket&table=incident&sys_id=1a6ab6731bf37510733585e4464bcb67) in Service Now.

**Comment by amnonkhen** [comment]
It was indeed the deleted GCP project ingest-service-301110 that caused this mess.
The workaround for any affected projects is to re-sync the upload area so that validation is re-triggered.
The 2 projects mentioned in this ticket are Metadata Valid currently.
