### ISSUE TITLE
Add a DUOs id to a HCA project - backoffice UI

### ISSUE THREAD

**Issue by idazucchi** [ebi-ait/dcp-ingest-central#999]
As a data wrangler/submitter, I would like to be able to enter the DUOS id in for a managed access project so it's permanently recorded and easy to see.

The DUOS id field should be a text box in the project tab. 
To avoid entering an id for open access projects it would be nice if the field only appeared or was active when `data_use_restriction = GRU` or `GRU-NCU`.

** Acceptance Criteria / Definition of Done **
- [ ] field is available in project page

**Comment by KociOrges** [comment]
The link to the PR that implements the task can be found [here](https://github.com/ebi-ait/ingest-ui/tree/feature/dcp-999_add_duos_id). Things done in this PR:
- Added DUOS code and DUOS id fields from the Project metadata schema into ingest backoffice
- Implemented conditional logic for DUOS id based on selection for data use restriction
- Implemented validation logic for the added fields, where DUOS id are validated against a given pattern
- Added functionality to selectively ignore schema examples for DUO codes, ensuring the default option is set to blank

I have addressed the review comments and am currently finalising the test cases. A new PR will be submitted shortly thereafter, and a version should become available on a testing environment.

**Comment by KociOrges** [comment]
Have created a new PR with the following changes. The PR has been reviewed and accepted by Amnon. Next step is to have this version deployed in a testing environment for further evaluation by the team:

- Refactored code by separating logic into more granular methods
- Utilised schema-based labels and helper texts for DUOS ID field
- Included test cases to cover the new functionality described above
- Included additional test case into `metadata-form.spec.ts` to validate presence/absence of specific fields based on different schema versions

**Comment by idazucchi** [comment]
I've done a little testing now that this feature is in staging
- Upload spreadsheet and update project info - adds data_use_restriction and DUOS id
- Can add data_use_restriction and DUOS id from the ui
The problem happens here:
- Tested changing between different data_use_restriction to see how the DUOS id field behaves. Project is invalid when changing data_use_restriction from MA to NRES
Steps
1. Set the data_use_restriction to GRU and fill in DUOS id
1. Save
1. Delete DUOS id
1. Change data_use_restriction to NRES - DUOS id field disappears
1. Save
1. Check submission, see error - `* should match pattern "^DUOS-\d{6}$" at .duos_id`
The project is still invalid, we need to remove the field from the project when we change to NRES

**Comment by KociOrges** [comment]
A new version of the ingest-ui has been deployed to the `staging` area to address the issue mentioned above. The following changes have been made in this version:
- Reset `duosIdControl` when `data_use_restriction` is NRES.
- Update validation logic for `duosIdControl` to include both pattern and custom validators.
- Remove `FormGroup` usage and refactor to use `MetadataForm` directly.
- Modify and update test cases to align with refactored component structure.
